### ISSUE TITLE
Refuses to list shortcut with lots of dots in it's name

### ISSUE THREAD

**Issue by herrenP** [oliverschwendener/ueli#1002]
I added a shortcut called "S.T.A.L.K.E.R - G.A.M.M.A" on my desktop. Ueli never lists this if I search using "Stalker" or "gamma". Not even if I raise the fuzziness from the default 0.5 to 1.0. It somehow manages to list just about any other shortcut that is nowhere close to the search phrase. I've also tried increments between 0.5 and 1.0. It does list it if I add the dots in the search phrase while using the default fuzziness.

I've reindexed multiple times.

I haven't really fiddled with dots anymore than this. So, not sure how many dots is an issue or not. Anyway, I feel like it should be able to list this item before shortcuts which has no similarity at all at some point of fuzziness.

**Comment by oliverschwendener** [comment]
After some testing it looks like the issue starts to occur after 4 dots. Ueli uses [fuse.js](https://www.fusejs.io/) to filter search results based on your search term. I'm afraid I don't know how I could solve this without introducing weird side effects. I'll close this as "wont' fix".
