### ISSUE TITLE
Alternatives to dropping Firefox bookmarks support?

### ISSUE THREAD

**Issue by oscardianno** [oliverschwendener/ueli#1005]
Hello :)

I was reading through the newest release changelog ([8.24.0](https://github.com/oliverschwendener/ueli/releases/tag/v8.24.0)), where I noticed the breaking change "_Removed support for Firefox bookmarks due to sqlite and pnpm implications_", and after reading the commits, I was able to see that the problem is caused by a pnpm's issue with the sqlite3 dependencies, which causes the build to fail when running `pnpm package` to build the installer.
However, `npm run package` worked just fine, so I wanted to propose:

Is it possible that we use _npm_ instead of _pnpm_ (while the pnpm's team solves the issue) instead of completely dropping the feature?

Perhaps, there's something else that I'm missing?
Otherwise, I'd drop a PR if needed, please let me know ^^

---
The issue is already documented in the pnpm's repo, and there's a workaround available, though perhaps not so convenient:
> > open `pnpm.cjs` file, replace `#!/usr/bin/env node` with `#!node`,from [electron-userland/electron-builder#6933 (comment)](https://github.com/electron-userland/electron-builder/issues/6933#issuecomment-1213438889)

> this can be fixed in my windows by edit 'AppData\Roaming\npm\node_modules\pnpm\bin\pnpm.cjs', but how to let other users auto fix this, all users need change like this?

_Originally posted by @AiHaibara in https://github.com/pnpm/pnpm/issues/5638#issuecomment-1336832024_

**Comment by oliverschwendener** [comment]
I just added support for Firefox bookmarks back for ueli v9. If you want to try it out you can download the latest alpha version here: https://github.com/oliverschwendener/ueli/releases
