### ISSUE TITLE
Can't use ueli while terminal is open

### ISSUE THREAD

**Issue by kristus123** [oliverschwendener/ueli#1007]
i made a workflow that does a simple ping

https://i.gyazo.com/89f3e3eb863062e9ed32dc48af8ddc83.mp4

But ueli is locked until i manually close the terminal

a workaround for this is to append `& exit` at the end to make it close the terminal

**Comment by kristus123** [comment]
btw. ueli is amazing!!!!

**Comment by kristus123** [comment]
@oliverschwendener 

https://github.com/oliverschwendener/ueli/commit/54d57f8e3d94b08cbbe7de43451f625620e38c26

this was a fix that makes it so i can open multiple cmd windows without having it make ueli hang indefinitely

**Comment by kristus123** [comment]
i am no js expert, so i just made it quick and dirty*

**Comment by kristus123** [comment]
i have no idea how i can test this using powershell etc so i can't know if this is a bug with all the other windows terminals

**Comment by oliverschwendener** [comment]
Is this still an issue with the latest beta release of v9? https://github.com/oliverschwendener/ueli/releases
If so, feel free to reopen.
