### ISSUE TITLE
[Feature request] Calculator Conversions 

### ISSUE THREAD

**Issue by AndersJpg** [oliverschwendener/ueli#101]
possible to make the calculator work like the windows one that can do Conversions on the go :)?

**Comment by oliverschwendener** [comment]
![image](https://user-images.githubusercontent.com/15727229/51807375-492a9400-2286-11e9-8dae-c2fcb906aef3.png)

Like this?

**Comment by AndersJpg** [comment]
just like that do need currency conversion :D

**Comment by oliverschwendener** [comment]
In the upcoming version I added a currency converter plugin and it can be used like this:

![image](https://user-images.githubusercontent.com/15727229/56474327-d4c45300-6478-11e9-8163-2cd3d30f75d5.png)

It uses https://exchangeratesapi.io/ API to get the current exchange rates.
