### ISSUE TITLE
SQLite node error

### ISSUE THREAD

**Issue by SniperAtWork** [oliverschwendener/ueli#1015]
Hi!

I recently encountered this error message after a Clean Windows Install.
The most interesting is that Ueli has worked for a few days after I installed, but somewhat "messed up".
I tried to figure it out how to solve this kind of error, by the previous issues, but none of worked.
However this "ENOENT Javascirpt error" is somewhat different than I found because this errors refers a sqlite module.

![error](https://github.com/oliverschwendener/ueli/assets/834706/2e410877-3926-449d-9d60-c62c52da51a7)

Could you please assist how to fix that?
Thank you in advance!

**Comment by oliverschwendener** [comment]
Does this still occur with the latest beta version of v9? https://github.com/oliverschwendener/ueli/releases

**Comment by oliverschwendener** [comment]
If it's still an issue, feel free to reopen.

**Comment by SniperAtWork** [comment]
Issue has been resolved by reinstalling Windows!
