### ISSUE TITLE
Can't find local files (MacOS)

### ISSUE THREAD

**Issue by GiaRed** [oliverschwendener/ueli#1019]
I've tried searching for local files by simply typing for the file name and nothing shows up, when I use md?, I get a "An Error Occured" error

Checking the log, this is the error that I get

`2023-06-25T17:39:43.302Z error: 2023-06-25 13:39:43.283 mdfind[5462:54401] [UserQueryParser] Loading keywords and predicates for locale "en_CA"
2023-06-25 13:39:43.283 mdfind[5462:54401] [UserQueryParser] Loading keywords and predicates for locale "en"`

**Comment by GiaRed** [comment]
I noticed that the ueli will find the folders in the folder path designated in the "Simple File Search" function but it won't look for any files deeper than that first folder

**Comment by GiaRed** [comment]
Doing a deep re-index solved the issue for me.

**Comment by malwikl** [comment]
Same Issue here, how did you do a deep re-index?
