### ISSUE TITLE
Behind proxy?

### ISSUE THREAD

**Issue by summershrimp** [oliverschwendener/ueli#102]
Hi, my company's network needs a proxy to access internet. How can i set a proxy for this?

**Comment by oliverschwendener** [comment]
Ueli does not need any internet connection, so I guess you won't have to set up a proxy for it. Auto updating might not work though.

**Comment by generic-user** [comment]
If ueli does not require on active connection then how do you use online mode --> alt + s ?
![image](https://user-images.githubusercontent.com/1516035/52332535-30934a00-29fb-11e9-941c-04048dac5cab.png)

**Comment by oliverschwendener** [comment]
You are not using the original version of ueli but @khanhas' fork: https://github.com/khanhas/ueli. Contact him for help.
