### ISSUE TITLE
Unable to find/open Operating System Settings (MacOS)

### ISSUE THREAD

**Issue by GiaRed** [oliverschwendener/ueli#1020]
When I try to look for a system setting, none of the settings show up. Applications show up but not the system settings.
I've enabled the Operating System Settings plugin but nothing changes.

![Screenshot 2023-06-25 at 1 48 23 PM](https://github.com/oliverschwendener/ueli/assets/67559058/50c9687a-9392-4470-8dcf-1792b9550323)
![Screenshot 2023-06-25 at 1 48 09 PM](https://github.com/oliverschwendener/ueli/assets/67559058/039524c7-14a7-4962-8e23-16f833a330a2)

**Comment by oliverschwendener** [comment]
Can someone check if this is still an issue with the latest v9 release? https://github.com/oliverschwendener/ueli/releases
If so, feel free to reopen.
