### ISSUE TITLE
question

### ISSUE THREAD

**Issue by kristus123** [oliverschwendener/ueli#1027]
![image](https://github.com/oliverschwendener/ueli/assets/23336150/744b6268-f3cd-4190-94bf-cfd366f8eeea)

When i edit the file, the changes are not applied until i restart ueli or perform an action inside the settings gui.

Is there a way for ueli to 'update itself' when changes are made to the file ?

**Comment by oliverschwendener** [comment]
Currently, this is not possible. Ueli won't detect changes done to the settings file.

**Comment by kristus123** [comment]
if i were to try to implement this feature myself, do you know which files i should have a look at ?

**Comment by oliverschwendener** [comment]
I would start with looking at the code in `src\main\Core\SettingsManager`.
