### ISSUE TITLE
Potential memory leak

### ISSUE THREAD

**Issue by thatKaran** [oliverschwendener/ueli#103]
Found Ueli consuming over 1GB of my RAM today. Running on Windows 7 Enterprise. No major customization. See attached screenshot and config.

**Ueli Info:**
ueli: 7.2.1
Electron: 2.0.8
Chrome: 61.0.3163.100
Node: 8.9.3
V8: 6.1.534.41
Index size: 299

> **[ueli.config.json.txt](https://github.com/oliverschwendener/ueli/files/2807336/ueli.config.json.txt)**

![image](https://user-images.githubusercontent.com/4639664/51903786-0d591100-23e3-11e9-9f9f-10a9beee319d.png)

**System Info:**
OS Name	Microsoft Windows 7 Enterprise
Version	6.1.7601 Service Pack 1 Build 7601
System Model	HP EliteDesk 800 G1 SFF
System Type	x64-based PC
Processor	Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz, 3601 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date	Hewlett-Packard L01 v02.65, 7/13/2015
Locale	United States
Total Physical Memory	15.9 GB
Graphics:
[1]	AMD Radeon(TM) HD 8490
[2]	Intel(R) HD Graphics 4600

**Comment by oliverschwendener** [comment]
How much memory does it consume when you quit and restart ueli?

**Comment by thatKaran** [comment]
> How much memory does it consume when you quit and restart ueli?
Between 50 to 100 MB.

Also, got this error today. Might be related --

![image](https://user-images.githubusercontent.com/4639664/51964709-56fe3600-248d-11e9-9721-8168aca3f023.png)

**Comment by oliverschwendener** [comment]
Ok then it really might be a memory leak, I will look into this. Thanks for your feedback!

**Comment by oliverschwendener** [comment]
@thatKaran Can you check if this issue still occurs with the newest version [v8.0.0](https://github.com/oliverschwendener/ueli/releases/v8.0.0)?

**Comment by oliverschwendener** [comment]
Closing this issue now because it seems to be fixed.
