### ISSUE TITLE
[Bug] Application Search plugin not working except for Safari.app

### ISSUE THREAD

**Issue by ddogfoodd** [oliverschwendener/ueli#1030]
Ueli version: 8.24.0
OS version: macOS Ventura 13.5

I am using the default settings for the Application Search plugin. No applications are shown in search except Safari.app which is pretty weird as all other Applications are in the same directory. I tried to refresh the index, reload ueli and a few times which didn't solve the issue.

I have found a workaround by adding `/Applications` path to the Simple folder search plugin. This way the Applications can be found as expected with only the icons not working which is not too much of a drawback.

Still, I wanted to report this in case anyone has an idea on why this behavior occurs.
I also checked the debug log which doesn't show any errors when enabling the Application Search plugin or when editing the paths there.

**Comment by oliverschwendener** [comment]
Can someone check if this is still an issue with the latest v9 release? https://github.com/oliverschwendener/ueli/releases
If so, feel free to reopen.
