### ISSUE TITLE
Ueli does not work when VSCode is running

### ISSUE THREAD

**Issue by dm413** [oliverschwendener/ueli#1037]
I'm running Win 10 pro, Ueli ver 8.24.0

If I am running VSCode, Ueli does not work. Alt-space brings up the Ueli text entry box, but keystrokes don't appear in the box. It's as if something else is grabbing all the keystrokes. When VSCode is not running, Ueli works fine. I have tried running VSCode with all extensions disabled, and get the same behavior. 

I'm guessing this doesn't happen to everybody, because others would have reported it by now and you probably would have noticed it yourself! Any ideas for what might be going on or how I might debug it further?

Thanks,

**Comment by tkohlmeier** [comment]
Maybe a VS Code keyboard shortcut is interfering? Have you tried resetting VS Code settings completely?

**Comment by dm413** [comment]
Unfortunately this has turned out to be intermittent. It will work fine for a while, and then suddenly Ueli won't work until I exit VSCode. I haven't figured out a reproducible trigger for it. I'll keep track of it and see if I can figure out what causes it to happen, but for now I don't think there is much you can do. Thanks,

**Comment by dasuppan** [comment]
I am having the same experience: Once I start vscode via the ueli bar (I have a shortcut "vscode" there) the bar does not take any keystrokes, the input field does not even show a cursor. After restarting ueli it works again. Sometimes when I then try to start vscode it will work just fine, even after vscode has opened. When I close vscode and run it once again the error occurs again. I am running on Windows 11.

**Comment by oliverschwendener** [comment]
@dasuppan I guess you have created a shortcut to launch the "code" CLI command right? That would explain the behavior, as the command line shortcut has a limitation as it waits for the program to exit. In your case, ueli waits until vscode exists. I suggest creating a shortcut that opens the executable file via file path.

**Comment by dasuppan** [comment]
Thanks! That resolved the issue. 👍

**Comment by oliverschwendener** [comment]
@dm413 I guess you have the same issue?
