### ISSUE TITLE
google search with hash sign does not work

### ISSUE THREAD

**Issue by GitBiker** [oliverschwendener/ueli#104]
the command 
g?c# stack 

searches for "c" only and not for "c# stack" as expected.

**Comment by oliverschwendener** [comment]
I added the option `Encode search term` so the search term will be URL encoded.

If this option is enabled `g?c#` should lead to `https://google.com/search?q=c%23`.
If this option is disabled `g?c#` should lead to `https://google.com/search?q=c#`

![image](https://user-images.githubusercontent.com/15727229/51966846-f57a9f00-246d-11e9-8c27-34665cead7a2.png)
