### ISSUE TITLE
QUESTION: Can I write my own extensions?

### ISSUE THREAD

**Issue by burntorangejedi** [oliverschwendener/ueli#1040]
This isn't an issue, per se, but a question.
I'd like to be able to write my own extensions to UELI to do some company-specific actions. I could fork the repo and just make updates, but I wondered if this supports the idea of a plug-in model where I could provide something (script, dll, etc.) to my deployments and get our private toolset shared to the team.

**Comment by oliverschwendener** [comment]
Currently, this is not possible.

**Comment by MrModest** [comment]
Do you have plans to add support for this in future?
