### ISSUE TITLE
show last command(s)

### ISSUE THREAD

**Issue by GitBiker** [oliverschwendener/ueli#105]
It would be nice to have the last command (select all) in ueli. It happens quite often that I just want to do the same thing a few times but just a little different. Editing the last command is much easier (wox, alfred) than typing everything all over again.

**Comment by khanhas** [comment]
![image](https://user-images.githubusercontent.com/26436809/52039091-2dfda400-2566-11e9-8c37-f95494061612.png)

**Comment by oliverschwendener** [comment]
https://github.com/oliverschwendener/ueli#keyboard-shortcuts

**Comment by GitBiker** [comment]
Thank you!
