### ISSUE TITLE
Question: Workflows > commandline tooling > how auto close terminals

### ISSUE THREAD

**Issue by konradsikorski** [oliverschwendener/ueli#1050]
Hi, 

I am using windows 11. I have a workflow like this:
1. comandline: path to exe file with parameters
2. comandline: path to exe with parameters
3. file path: to exe file

After executing the worflow three terminals will start and all programs from these tasks are executing properly. My problem is that i have every time close these three terminals. How to automatically close them or even better never show them?

I am using Windows terminal.

**Comment by kristus123** [comment]
i add `& exit` at the end of the command, that will make the terminals close.

**Comment by konradsikorski** [comment]
@kristus123 doesn't work for me :( do you use it for "command line"? for this command
> explorer.exe shell:appsFolder\Microsoft.Todos_8wekyb3d8bbwe!App

 i am receiving error like this:

> At line:1 char:66
> ... xplorer.exe shell:appsFolder\Microsoft.Todos_8wekyb3d8bbwe!App & exit
>                                                                     ~
> The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quot
ation marks ("&") to pass it as part of a string.

**Comment by kristus123** [comment]
https://chat.openai.com/share/511999b4-1ba9-4ede-b61f-8ee2b81cca14

you can try using ;

**Comment by kristus123** [comment]
also, i am curious. how do you use microsoft todo with ueli? 
I am a big fan of microsoft todo

**Comment by konradsikorski** [comment]
I use the Microsoft To Do every day. Basically I start my day with To Do. I want to achieve something very simple. Every day morning I use workflow workflow "Day" to start 3 apps. Looks simple but it's ridiculously complicated. I have in the workflow one task for each app and it works but after all i have 3 terminals open. So I end up with a cmd script which is run by euli workflow but this way I can write any 'workflow' in script and I do not need the euli at all.

So for anyone who has this problem. This was my workflow
![image](https://github.com/oliverschwendener/ueli/assets/5046330/8ae030f4-5690-4aab-85cd-40cf38c8be3b)

this is how i solve it now by running a script

![image](https://github.com/oliverschwendener/ueli/assets/5046330/92275760-0d69-45ee-a1b3-6dbdc473e73d)

and the cmd file:

> explorer.exe shell:appsFolder\Microsoft.Todos_8wekyb3d8bbwe!App
> 
> C:\Users\...\AAA.exe
> 
> start "" "C:\Program Files\...\BBB.EXE"

**Comment by oliverschwendener** [comment]
Thanks for the detailed description. Ueli has an issue that it waits for the commandline program to exit, so that's why the UI is frozen until you close the terminals. I will see that this issue will be fixed with v9 which is currently in an alpha state. I'll keep you posted here.

**Comment by oliverschwendener** [comment]
Can someone check if this is still an issue with the latest beta version? https://github.com/oliverschwendener/ueli/releases
If so, feel free to reopen this issue.
