### ISSUE TITLE
[Bug] Typing "sign" results in one very strange suggestion

### ISSUE THREAD

**Issue by sashaweiss** [oliverschwendener/ueli#1051]
Hi! Thanks again for `ueli` – I use it every day and love it. Found a strange, not-super-high-priority issue.

When I type in "sig", I see results that make sense, e.g., "Signal", "Siri". When I type in "sign", however, I'm presented with a single suggestion:

```js
function ye(e,t){return arguments.length===oe&&I(e)&&$(t)?ee.apply(this,arguments):arguments.length===se&&R(e)&&W(t)?te.apply(this,arguments):arguments.length===ce&&L(e)&&Z(t)?ne.apply(this,arguments):arguments.length===ue&&U(e)&&Y(t)?re.apply(this,arguments):arguments.length===le&&z(e)&&J(t)?ie.apply(this,arguments):arguments.length===pe&&q(e)&&X(t)?ae.apply(this,arguments):ge.apply(this,arguments)}
```

which seems very wrong. It seems like somehow the suggestion is...reading code? I'm not entirely sure what's going on, nor have I demangled the code snippet to see what it might pertain to, but was surprised both that it showed up and that all the other options (e.g., "Signal") disappeared.

<img width="606" alt="image" src="https://github.com/oliverschwendener/ueli/assets/9013117/60ebe6d3-240b-4cc6-a904-01aea6256273">

Please let me know if I can provide any additional details!

**Comment by oliverschwendener** [comment]
I guess this is due to the calculator plugin that falsely detects this to be a valid input for it. I suggest disabling the calculator plugin in the settings.

**Comment by sashaweiss** [comment]
That worked great - thanks for the quick reply!
