### ISSUE TITLE
Chocolately package for 8.25.0

### ISSUE THREAD

**Issue by gtjamesa** [oliverschwendener/ueli#1052]
Any chance you could update it?

**Comment by oliverschwendener** [comment]
I'm sorry, but the chocolatey packages are currently not being updated. I suggest using the [Windows Package Manager](https://github.com/microsoft/winget-cli).

**Comment by gtjamesa** [comment]
No problem. I've switched to Linux since opening this issue and I'm running ueli from #1029 successfully. I'll see what I can do to help bring it into `main` :)
