### ISSUE TITLE
Multiple plugins not working - not showing any results

### ISSUE THREAD

**Issue by CMIanis** [oliverschwendener/ueli#1055]
Basically, I only get results from calculations, apps and that's it. For the rest of the plugins, I get nothing, as you can see in the screen captures:
![2023 11 17 493](https://github.com/oliverschwendener/ueli/assets/95960096/68669849-16fb-4acd-b912-9e5d282cbd33)
Translate is a Bookmark i have in Chrome
![2023 11 17 494](https://github.com/oliverschwendener/ueli/assets/95960096/72c0c530-88ac-408c-8c1f-48c804a69151)
![2023 11 17 495](https://github.com/oliverschwendener/ueli/assets/95960096/1dcaa780-8770-45f9-90a8-19e4a3d349cb)
![2023 11 17 496](https://github.com/oliverschwendener/ueli/assets/95960096/ccf03254-19bb-41f2-937c-6bfd2273099a)
![2023 11 17 497](https://github.com/oliverschwendener/ueli/assets/95960096/46ba7c2c-0511-4415-9d5c-cd19132821cf)

**Comment by oliverschwendener** [comment]
Did you enable the plugins in the settings?

**Comment by CMIanis** [comment]
![2023 11 19 498](https://github.com/oliverschwendener/ueli/assets/95960096/37269114-0b86-4297-bda0-98f922de20a1)
I think so, please tell me if I need to do anything else

**Comment by oliverschwendener** [comment]
Are you using the latest version?

**Comment by CMIanis** [comment]
![2023 11 20 499](https://github.com/oliverschwendener/ueli/assets/95960096/b75d1ff6-f937-4791-9428-4caaf394ec48)

**Comment by cmdbea** [comment]
same thing here, instead i get an error saying to hit enter to open debug log
![image](https://github.com/oliverschwendener/ueli/assets/85807123/9bcb91d3-b687-43cf-9338-15c0e0e4049d)

**Comment by Sobanim** [comment]
> same thing here, instead i get an error saying to hit enter to open debug log ![image](https://private-user-images.githubusercontent.com/85807123/304861591-9bcb91d3-b687-43cf-9338-15c0e0e4049d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2OTAwMzYsIm5iZiI6MTcxMDY4OTczNiwicGF0aCI6Ii84NTgwNzEyMy8zMDQ4NjE1OTEtOWJjYjkxZDMtYjY4Ny00M2NmLTkzMzgtMTVjMGUwZTQwNDlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDE1MzUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmMDJhYTBkYWE3MzU2NWEzMDNkMDE0M2I5YjM0NmRhOGI2ZDljZmZmZjZlNTA2NjczMGY4ODI1MTk3MjJjYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._1JlQxQAnK84-L-Zd58qjZi9qFPO7aJUsnY1JLgj8eE)

It doesn't work because the api for the currency converter applet has changed.
https://github.com/fawazahmed0/currency-api/?tab=readme-ov-file#this-repository-is-migrated-to-httpsgithubcomfawazahmed0exchange-api

**Comment by oliverschwendener** [comment]
Closing this as ueli v8 will be discontinued together with some of these plugins.

Can someone check if this is still an issue with the latest v9 release? https://github.com/oliverschwendener/ueli/releases
If so, feel free to open separate issues for each extension that is not working, thanks.
