### ISSUE TITLE
[Problem] Regarding Japanese input in the Mac version

### ISSUE THREAD

**Issue by darktribe** [oliverschwendener/ueli#1056]
If you are using Japanese input on the Mac version, the text will be executed the moment you confirm the character.For example, when you enter "g?keyword", the moment you confirm the keyword, the search engine screen will be displayed and the keyword will not be reflected. yeah. You cannot enter multiple keywords because they are executed the moment they are confirmed. Is there any possible reason?

**Comment by oliverschwendener** [comment]
Can someone check if this is still an issue with the latest v9 release? https://github.com/oliverschwendener/ueli/releases
If so, feel free to reopen.
