### ISSUE TITLE
bug: Incorrect Tray Icon Color in Light Theme on Windows

### ISSUE THREAD

**Issue by aqyuki** [oliverschwendener/ueli#1058]
## Description:
When launching Ueli on Windows, the tray icon appears to have an unintended color when the system is set to the light theme. Ideally, the tray icon should be black when the Windows theme is set to light, but it currently appears in white. This makes it challenging to locate the icon as it blends with the background color of the tray.

## Steps to Reproduce:

1. Set Windows theme to light.
2. Launch Ueli.
3. Observe the color of the tray icon in the system tray.

## Expected Behavior:
The tray icon should be black to provide better visibility and contrast against the light background of the system tray.

## Actual Behavior:
The tray icon appears in white, making it difficult to distinguish against the light system tray background.

## Additional Information:

Operating System: Windows
Ueli Version: 8.27.0

## Screenshot:

![ueli_tasktrai](https://github.com/oliverschwendener/ueli/assets/117277631/7b5b4356-a85b-4343-91ab-1fb4ca2c2c59)

## Note:
This issue impacts usability, especially for users who prefer the light theme on Windows.

**Comment by aqyuki** [comment]
The icons displayed during the light theme of windows are drawn in white, on a white background, so this should probably be changed.

[This file](https://raw.githubusercontent.com/oliverschwendener/ueli/main/img/icons/win/icon-transparent.ico)

**Comment by oliverschwendener** [comment]
This issue will be solved in v9.
