### ISSUE TITLE
Request for design Improvement

### ISSUE THREAD

**Issue by Vijay-CodeBase** [oliverschwendener/ueli#1059]
I been using this app for long time.
I want to Ask for few Designs improvement. 
- Addition of Border - color
- addition of shadow
- roundness in the overall design

![Screenshot 2024-01-07 144504](https://github.com/oliverschwendener/ueli/assets/68197394/f7110f67-7ebe-4314-b6f1-08cfee9588fa)

-something like this could be great

Because When I use the white background and white theme in this app, I can feel the Search lunch which make it unpleasant. 

-- Add Thank you this wonderful app after trying all this I can tell this by far simple and fast, less clutter

**Comment by oliverschwendener** [comment]
I'm currently working on version 9 and this is how the UI will look:

Dark appearance:
![image](https://github.com/oliverschwendener/ueli/assets/15727229/39d7c3d4-d3b0-4a50-8603-c0ad1296cd5b)

Light appearance:
![image](https://github.com/oliverschwendener/ueli/assets/15727229/a621b6fc-7261-4c03-b09d-65c43d981c07)

What do you think?

**Comment by Vijay-CodeBase** [comment]
It looks great 🤩. Will there be availability of customization???

**Comment by oliverschwendener** [comment]
Nothing that doesn't work with the FluentUI components. Here is a screenshot from the appearance settings.

<img width="978" alt="image" src="https://github.com/oliverschwendener/ueli/assets/15727229/6895a8c8-b88c-438e-a145-3ef6eb737c30">
