### ISSUE TITLE
[Feature Request] Windows Context Menu

### ISSUE THREAD

**Issue by TuRDMaN** [oliverschwendener/ueli#106]
Hi, I've been using Find and Run Robot for a while, and I'd really like to switch to Ueli.

However, there is one feature of FaRR that is not in Ueli that is kind of a dealbreaker for me.

From the results list, it would be great if there was a way to activate the Windows Context Menu for a certain item. (ie: searching for a .bat file, then open the context menu to choose either run, edit, etc.)

**Comment by oliverschwendener** [comment]
Will look into this as soon as possible!
