### ISSUE TITLE
[Bug]Unexpected motion when typing

### ISSUE THREAD

**Issue by Sentixxx** [oliverschwendener/ueli#1061]
# Description
The typing window moves up-left on one of my monitors whenever I type or delete a character.After it meets the left border, it moves up. However, its behavior varies on my other screens, where it only slightly moves to the left and then stops. For a clearer illustration of the issue, I've uploaded a video.

# Extra info
system:Windows 11 22H2
ueli version: 8.27.0

# Video
https://github.com/oliverschwendener/ueli/assets/37214256/e0ea905b-48cb-409f-97e2-67cfdfcbd806
https://github.com/oliverschwendener/ueli/assets/37214256/a1458ad6-528a-4118-8c16-a148e09c8fec

**Comment by oliverschwendener** [comment]
Do you have custom scaling enabled in the Windows settings?

**Comment by Sentixxx** [comment]
> Do you have custom scaling enabled in the Windows settings?

just use 150% recommended for 4k resolution

**Comment by Vijay-CodeBase** [comment]
Ok

**Comment by Sentixxx** [comment]
i set the scale to 100% , the window's moving mode changed, as the second video shows. It seems that it depends on the scaling.

**Comment by carlitorendon** [comment]
I wonder if it has to do with the fact that main language is not based on roman Latin characters

**Comment by oliverschwendener** [comment]
Can someone check if this is still an issue in the version 9.0.0-alpha.7? https://github.com/oliverschwendener/ueli/releases/tag/v9.0.0-alpha.7

**Comment by Sentixxx** [comment]
> Can someone check if this is still an issue in the version 9.0.0-alpha.7? https://github.com/oliverschwendener/ueli/releases/tag/v9.0.0-alpha.7

it's ok

**Comment by oliverschwendener** [comment]
Then I'll mark this as resolved. Thanks for checking!
