### ISSUE TITLE
[Docs] Workflow examples/ideas

### ISSUE THREAD

**Issue by bbkane** [oliverschwendener/ueli#1067]
Hello! I'm trying to learn to use ueli's "Workflow" plugin. I feel like it's powerful, but I don't know how to use it or what it's good for. 

The only mention in the [website](https://ueli.app/#/features) is 
![image](https://github.com/oliverschwendener/ueli/assets/6081085/d6efeb6f-b384-4f19-97e7-6985f1a9fa92)
 which doesn't explain much.

Is there a tutorial anywhere I could follow?

**Comment by oliverschwendener** [comment]
Unfortunatley there is no tutorial or documentation about this. Yes, it's a shortcut to run multiple things at once. You can open files, apps, urls or invoke cli commands. Currently there is no way to pass arguments.
