### ISSUE TITLE
[Feature Request] Show Full Paths

### ISSUE THREAD

**Issue by TuRDMaN** [oliverschwendener/ueli#107]
One feature that I'd like to see in Ueli is the option to show full paths to all the results. And also an option to show the path on all results, without having to highlight them in the list first.

**Comment by oliverschwendener** [comment]
Good idea! Will look into this as soon as possible.

**Comment by oliverschwendener** [comment]
I added the option the option `Show description on all search results`:

![image](https://user-images.githubusercontent.com/15727229/52395460-8ffe6200-2aae-11e9-9e12-cd427ffe062f.png)

When enabled, it will show the description on all search results without having to highlight them:

![image](https://user-images.githubusercontent.com/15727229/52395495-b0c6b780-2aae-11e9-88e8-9c308c825a95.png)

If disabled it will show only the description on the highlighted search result:

![image](https://user-images.githubusercontent.com/15727229/52395530-df449280-2aae-11e9-8f71-98bc6213ab35.png)
