### ISSUE TITLE
The currency converter stopped working

### ISSUE THREAD

**Issue by Karen-Kirakosyan** [oliverschwendener/ueli#1072]
Hello, the currency converter stopped working. It is said on this page that the repository will be closed: https://github.com/fawazahmed0/currency-api/

Here is the version of the app:

ueli - 8.28.0
Electron - 28.1.3
Node - 18.18.2
V8 - 12.0.267.14-electron.0

![image](https://github.com/oliverschwendener/ueli/assets/40933038/4a8bb677-6b4e-40c3-938a-3d6c4602fe14)

**Comment by oliverschwendener** [comment]
This should be fixed with v9, a fix was just merged: https://github.com/oliverschwendener/ueli/pull/1071

**Comment by Karen-Kirakosyan** [comment]
Can you say when the version 9 will be released?
And also thanks for your effort, i really like ueli.

**Comment by oliverschwendener** [comment]
You can already try out the alpha version here: https://github.com/oliverschwendener/ueli/releases

There are some major things outstanding, but I guess an official release could be realistic in a few weeks.
