### ISSUE TITLE
Writing '#' as the first character in search causes an error 

### ISSUE THREAD

**Issue by TheBluKnight** [oliverschwendener/ueli#108]
Tried to test if the app supports hex color search by writing '#' followed by the color number but instead I got this after I press '#'.
 ![2019-02-08 17_08_30-clipboard](https://user-images.githubusercontent.com/38782877/52480348-d9d96c00-2bc4-11e9-966b-562f2f8cc737.png)

**Comment by oliverschwendener** [comment]
Fixing this as soon as possible!

**Comment by oliverschwendener** [comment]
Released a new version with a fix: https://github.com/oliverschwendener/ueli/releases

**Comment by BhanuKiiran** [comment]
I am not able to install the app on Win 10 PC, I am getting the following error as per the pic
kindly help

![UELI Error](https://user-images.githubusercontent.com/49202357/55414286-75b1a380-5588-11e9-9714-7b962f44110c.JPG)

**Comment by oliverschwendener** [comment]
@TheBluKnight Look here: #134
