### ISSUE TITLE
Currency converter has not been working

### ISSUE THREAD

**Issue by accs4me** [oliverschwendener/ueli#1083]
Hello, the currency converter has not been working for a month and gives an error (2024-04-09T14:41:26.843Z error: Unable to get exchange rate. AxiosError: Request failed with status code 404). reinstalling the program did not help. how can this be fixed?

**Comment by oliverschwendener** [comment]
This will be fixed with version 9, which I hope to release soon.

You can already download the alpha version [here](https://github.com/oliverschwendener/ueli/releases) if you can't wait or if you're interested to test it.

**Comment by accs4me** [comment]
Understood, I wish you good luck
