### ISSUE TITLE
Currency converter gives error

### ISSUE THREAD

**Issue by stefrogovskyi** [oliverschwendener/ueli#1084]
A source on gituhb is saying: 

![image](https://github.com/oliverschwendener/ueli/assets/167094700/984ee997-c4ed-4830-97d0-888bb9adce26)

Is it possible to reconnect it?

**Comment by oliverschwendener** [comment]
This will be fixed in ueli v9. If you can't wait for its official release, or if you want to try it out you can download the alpha version here: https://github.com/oliverschwendener/ueli/releases
