### ISSUE TITLE
Super / Windows key doesn't work

### ISSUE THREAD

**Issue by Omricon** [oliverschwendener/ueli#1086]
### Version
[9.0.0-alpha.11](https://github.com/oliverschwendener/ueli/releases/tag/v9.0.0-alpha.11)

### Note
Great app! Keep up the good work.

### Issue
Windows / Super key with modifier doesn't work.
For example: Super+Space doesn't trigger where Alt+Space would.

**Comment by oliverschwendener** [comment]
See this conversation: https://github.com/oliverschwendener/ueli/issues/454#issuecomment-907609417
