### ISSUE TITLE
[Bug] Allow (non-http) URLs and .url file extensions in workflow

### ISSUE THREAD

**Issue by mahoromax** [oliverschwendener/ueli#1088]
I just tried to add a steam game along with what I use when I play this game to a workflow, but it turns out I couldn't find a direct way to add it:
Steam creates .url files as shortcuts that have a url like `steam://rungameid/230410`
I could neither manage to add that URL as URL in the workflow steps nor could I just give the file path of the .url file as file path.

Most that I could manage was adding this url file path as command line tool - which brings up (or for some doesnt) the cmd window which might stay open (don't want to look up old issues, but I'm sure there are more than one)

**Comment by oliverschwendener** [comment]
Can someone check if this is still an issue with the latest v9 release? https://github.com/oliverschwendener/ueli/releases

You can add URL shortcuts in the "Shortcuts" extension:
![image](https://github.com/oliverschwendener/ueli/assets/15727229/67c97a55-6dbe-49a2-9b72-50f854f58c8d)

**Comment by oliverschwendener** [comment]
Feel free to reopen this issue if it still occurs.

**Comment by mahoromax** [comment]
Can confirm I can now add shortcuts with steam url with the shortcuts plugin.

But in the beta there is no more "workflows" which is mainly what this issue was about.

**Comment by oliverschwendener** [comment]
Yes, there is no workflow extension yet. As every plugin of ueli v8 needs a rewrite/migration to work in ueli v9 it is not there yet. And this is also why ueli v9 is still in beta. I plan to add it as soon as I have time.
