### ISSUE TITLE
How to create custom commands??

### ISSUE THREAD

**Issue by Fantoom** [oliverschwendener/ueli#109]

**Comment by oliverschwendener** [comment]
Open the settings with <kbd>Ctrl</kbd><kbd>i</kbd> or search for "ueli settings". Go to the section `Custom Commands`, here you can add custom commands by filling out the fields and then press the plus button on the right to save it.

![image](https://user-images.githubusercontent.com/15727229/52941145-6f64c080-3368-11e9-8e3d-e38b27cea3c5.png)

Lets say you often want to execute `ping` with different parameters. Then you can add the following custom command:

![image](https://user-images.githubusercontent.com/15727229/52941324-c9658600-3368-11e9-9905-d8a9100a7b33.png)

Then you can just type in `p` and whatever follows after this will be passed in as an argument:

![image](https://user-images.githubusercontent.com/15727229/52941382-f3b74380-3368-11e9-9281-e65682de183d.png)

**Comment by gianni3212** [comment]
Hey, I just downloaded Ueli but can't seem to find the Custom Commands section.

**Comment by oliverschwendener** [comment]
"Custom commands" are now called "Shortcuts". You can find them in the settings.
