### ISSUE TITLE
[Bug] Beta 4 doesn't launch on Windows 11

### ISSUE THREAD

**Issue by jakubmikita** [oliverschwendener/ueli#1098]
**Describe the bug**
No beta version opens in Windows 11. It clearly thinks about loading because I'm getting a spinner cursor, but don't print out the prompt eventually. Tried opening as an admin but with same effect.

**Environment**
 - OS: Windows 11 x64
 - Version: 9 beta 4

Is there any log I can check? Couldn't find anything in the app folder.

**Comment by oliverschwendener** [comment]
I'm using Windows 11 too and I don't run into this issue. Maybe there is some information in the debug log?

<img width="549" alt="image" src="https://github.com/oliverschwendener/ueli/assets/15727229/6137550a-16a3-417e-a12f-af7c2a01f8e2">

**Comment by jakubmikita** [comment]
I don't even get to that screen 😅 the app just doesn't load at all.

Forgot to mention I have installed the latest stable version of Ueli and it works like a charm.

**Comment by jakubmikita** [comment]
I've checked the Windows event log and couldn't find any information there, unfortunately

**Comment by oliverschwendener** [comment]
What happens if you delete the following folder:

```
%APPDATA%\ueli
```

⚠️ Note that you will loose all settings from ueli v8 with this. If you want to keep those make sure to back up this folder.

**Comment by jakubmikita** [comment]
Hallelujah! That did the trick :)
