### ISSUE TITLE
[Currency Converter] <Not working>

### ISSUE THREAD

**Issue by SebastianSava** [oliverschwendener/ueli#1099]
Hello,

As you can see, the current used repo seems to be migrated to a new one - https://github.com/fawazahmed0/currency-api

![image](https://github.com/oliverschwendener/ueli/assets/67977875/910d419a-dbfd-471e-b026-dabbcfb07670)

**Comment by oliverschwendener** [comment]
This should be solved with ueli v9. You can try the beta here: https://github.com/oliverschwendener/ueli/releases
