### ISSUE TITLE
Generation app icons leads to weird explorer refresh

### ISSUE THREAD

**Issue by vsxed** [oliverschwendener/ueli#110]
Info: 
ueli: 7.2.5
Electron: 2.0.8
Chrome: 61.0.3163.100
Node: 8.9.3
V8: 6.1.534.41
Index size: 422

OS: Windows 10 1809

Everytime (and that's pretty often for that task, i think) the app icons are generated ("Successfully generated all app icons"), exporer seems to be restarting/refreshing, which leads to blinking (quickly dis- and the re-appearing) taskbar icons, while running ueli.

Heres the log from starting ueli via cmd:
(Thats after recording for 3 min whats actually happening with ueli)

![image](https://user-images.githubusercontent.com/1070998/52974936-9bf9f600-33c3-11e9-9b16-a657061eaa79.png)

**Comment by oliverschwendener** [comment]
@vsxed Thank you for your feedback! This is a known issue => #83

**Comment by vsxed** [comment]
Thanks for the fast response.
Unfortunately it's still flashing with disabled native icons feature in the settings

**Comment by oliverschwendener** [comment]
Then I think it's not the app icon generation that causes the flashing. Do you have multiple monitors?

**Comment by vsxed** [comment]
> Do you have multiple monitors?
Single monitor (LG 38UC99-W)

>Then I think it's not the app icon generation that causes the flashing
Was just an assumption, since it flashed everytime a second before the log message appeared

**Comment by oliverschwendener** [comment]
Yes of course, it would have been possible.

**Comment by oliverschwendener** [comment]
Closing this issue because it's a duplicate of #83. If you have more information how to reproduce this bug please comment in #83.
