### ISSUE TITLE
[Feature Request] v9: Indexing indicator

### ISSUE THREAD

**Issue by tkohlmeier** [oliverschwendener/ueli#1103]
**Is your feature request related to a problem? Please describe.**
After starting ueli, it does not show any results until the initial indexing is done. If you enter a search term immediately after the start, you cannot know if you just have to wait or if there really is no result.

**Describe the solution you'd like**
An indicator should be shown while indexing is in progress.

**Comment by oliverschwendener** [comment]
Thanks for reporting. This will be fixed with the next release.
