### ISSUE TITLE
[Feature Request] Clear and concise installation documentation

### ISSUE THREAD

**Issue by KrishnenduDG** [oliverschwendener/ueli#1109]
**Is your feature request related to a problem? Please describe.**
A Clear and concise documentation for the whole installation process.

**Describe the solution you'd like**
1. Installing
2. Configuring the Hot Keys
3. Basic Settings overview

**Describe alternatives you've considered**

**Additional context**

**Comment by oliverschwendener** [comment]
I guess this will work: https://github.com/oliverschwendener/ueli/wiki/Getting-started
