### ISSUE TITLE
[Feature Request] Bring back color converter to v9

### ISSUE THREAD

**Issue by krisu5** [oliverschwendener/ueli#1117]
I personally use it time to time.

**Comment by oliverschwendener** [comment]
The next release will bring the color converter back:

![image](https://github.com/user-attachments/assets/b901398d-422e-4aa7-91b8-0c944b16724d)

You can press enter to copy the selected format to the clipboard.

You have to go to the extension settings and enable the extension:
![image](https://github.com/user-attachments/assets/8023b2b2-401f-4828-8eec-151ba2c0ca5b)

Then you can tweak the color formats you want to see in the search result list:
![image](https://github.com/user-attachments/assets/7b531f0e-d67e-41cf-abff-366e7ab9a9e1)
