### ISSUE TITLE
[Feature Request] Decouple Settings menu from Search menu

### ISSUE THREAD

**Issue by weiw11** [oliverschwendener/ueli#1119]
**Is your feature request related to a problem? Please describe.**
Search menu shares UI with settings menu, meaning if we need to adjust the settings menu to view more content, the search menu becomes hilariously huge.

Another issue is the `Hide On` option also applies to Settings UI.

**Describe the solution you'd like**
Search menu should be decoupled from Settings menu.

**Additional context**
![2024-06-21_13-56-02_firefox](https://github.com/oliverschwendener/ueli/assets/62213594/4ee46fa4-fd5d-4578-92ae-9e70756d633e)

**Comment by oliverschwendener** [comment]
With the next release the settings will be in a separate window, see the attached example screenshot. Thanks for the patience.

![image](https://github.com/user-attachments/assets/e6a79fd2-8a81-4a88-b6c5-c1ead54b5236)

**Comment by oliverschwendener** [comment]
Et voilà: https://github.com/oliverschwendener/ueli/releases/tag/v9.14.0
