### ISSUE TITLE
[Bug] Maximizing Settings Menu Results in Black Background

### ISSUE THREAD

**Issue by weiw11** [oliverschwendener/ueli#1120]
**Describe the bug**
Maximizing settings menu results in black background.

**To Reproduce**
1. Go to settings
2. Double click Settings menu title bar to maximize window
3. UI is now black instead of set theme.
4. User needs to exit and reopen Ueli in order to restore UI.

**Expected behavior**
UI should remain the same after maximizing.

**Screenshots**
![2024-06-21_14-03-29_firefox](https://github.com/oliverschwendener/ueli/assets/62213594/1585527c-b169-4017-b35d-942d3367bac1)

**Environment**
 - OS: Windows
 - Version: 9.0.0

**Comment by oliverschwendener** [comment]
Unfortunately there is nothing I can do because this is an issue in electron: https://github.com/electron/electron/issues/41824

We have to wait until they release a fix for this.

**Comment by weiw11** [comment]
Maybe disable maximize functionality to prevent user from breaking UI until electron issue is resolved?

Also new v9 UI and extension doesn't appear to be as intuitive as v8. Web search for example shows on the bottom of the results and there isn't a way to directly access web search, or any of the extensions for that matter.

I also upgraded from v8.28.0 directly to v9.0.0 so my old Ueli installation was still there. Thankfully the config for v9 uses a different file so I can revert back. I think for now v9 release is a relatively huge downgrade in terms of functionality compared to v8, so I'm probably going to stay on v8 for now.

**Comment by weiw11** [comment]
The previous Web Search also provided a lot more functionality and customization without any development knowledge.

Below are some examples of custom web search I added, which is a lot easier than developing extensions for every single one.

![image](https://github.com/oliverschwendener/ueli/assets/62213594/cafa53c0-4a83-4772-9f5a-addbd0874bbe)

**Comment by oliverschwendener** [comment]
Regarding the black background: can you try to set the Background Material option in the Window settings to "None" and check if this fixes the problem?

**Comment by weiw11** [comment]
Setting it to `None` does not appear to turn the background black, but it still breaks the UI border styling.

After trying to maximize:
![image](https://github.com/oliverschwendener/ueli/assets/62213594/a4e771be-f20c-4826-856f-e6ec9180214b)

Default:
![image](https://github.com/oliverschwendener/ueli/assets/62213594/22a5ec0f-171a-4871-9df2-de1d2c96c6e1)

**Comment by mattfaucher** [comment]
I fixed this on my machine by setting: Windows > Background Appearance > None

**Comment by Alexander-499** [comment]
> I fixed this on my machine by setting: Windows > Background Appearance > None

Yes, then it jsut removes the background appearance entirely (It doesn't apply any background appearance). Then it fixes it because it is default electron behaviour I guess.

**Comment by oliverschwendener** [comment]
As there is nothing I can do at the moment I'll close this issue.
