### ISSUE TITLE
[Bug] Workflow didn't work/save

### ISSUE THREAD

**Issue by Dtrieb** [oliverschwendener/ueli#1121]
**Describe the bug**
If I try to make a Workflow, the path to the Application won't save,

**To Reproduce**
1. Go to 'Workflow'
2. Click on 'New'
3. Add new Action
4. Add new Name
5.  Set Type to File open
6. Set my Path to "C:\Program Files\Push2Run\cmd" 
7. Click on Save
8. See also "0 Aktionen"

![Ueli_2024-06-22_13-18-23](https://github.com/oliverschwendener/ueli/assets/3650284/d5d07a2e-e171-4465-9d0f-b3a053afdd87)

In the "ueli9.settings.json" :
```
        {
            "actions": [],
            "name": "Rot",
            "id": "workflow-10e0cc56-3c3d-4fc2-a465-228ca57c242e"
        }
```

**Screenshots**
![Ueli_2024-06-22_13-22-27](https://github.com/oliverschwendener/ueli/assets/3650284/3adaf8a3-cb7f-4c72-ae23-f0d3d39bfcaf)

**Environment**
 - OS: [Windows10]
 - Version [9.0.0]

**Comment by oliverschwendener** [comment]
You have to click on "Aktion hinzufügen". I guess I need to improve the UI here a bit 😅

**Comment by Dtrieb** [comment]
> You have to click on "Aktion hinzufügen" and then click "Speichern". I guess I need to improve the UI here a bit 😅

Okay works for me, only missing: https://github.com/oliverschwendener/ueli/issues/1126
