### ISSUE TITLE
[Bug] Application Search does not work

### ISSUE THREAD

**Issue by NetBender** [oliverschwendener/ueli#1124]
Application Search does not work. I've upgraded from v8.29.0 (where it worked) to v9 but now it does not find any program. Downgrading to v8.29.0 makes it work again.

**To Reproduce**
0. Have the `Application Search` extension enabled
1. Show Ueli
2. Type the name of an installed program
3. See nothing listed

**Expected behavior**
To have a list of matching shortcuts found in the set folders

**Environment**
 - OS: Windows 
 - Ueli version:  9.0.0

**Comment by zouhair** [comment]
Back to keypirinha for me, too much hassle, I'll go back to it when it's really stable

**Comment by oliverschwendener** [comment]
Can you open the Settings and go to the "Debug" tab to see if there are any logs that might be helpful? If so, can you share the logs?

Note that the settings from v8 are not compatible with v9. This means, if you have custom settings in v8, you need to apply them manually in v9.

**Comment by Ripwords** [comment]
I have the same issue, the "Debug" is complaining about one of my programs installed
```bash
[6/24/2024, 10:13:51 PM][ERROR] Failed to get search result items for extension with id 'ApplicationSearch.Reason: Exception calling "ExtractAssociatedIcon" with "1" argument(s): "C:\ProgramData\Microsoft\Windows\Start 
Menu\Programs\N.I.N.A. - Nighttime Imaging "
At C:\Users\teohj\AppData\Roaming\ueli\PowershellUtility\1b66a04e-4342-4913-a5fa-eb5287bbb60e.ps1:34 char:5
+     $Icon = [System.Drawing.Icon]::ExtractAssociatedIcon($InFilePath)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FileNotFoundException
 
'

```

For reference, here's the [link ](https://nighttime-imaging.eu/) to that application

**Comment by sacp** [comment]
Thanks for the tips. 
I had encountered the issue and went back to 8.9 while following this topic. 

I have unsintalled 8.9 and installed again 9.0. 
Going to the debug as suggested, I have several complaints, mostly about the "-bit" in 32-bit and 64-bit in the path or name. 

`[24/06/2024, 18:40:45][ERROR] Failed to get search result items for extension with id 'ApplicationSearch.Reason: Error: Command failed: powershell -NoProfile -NonInteractive -ExecutionPolicy bypass -File "C:\Users\Sergio\AppData\Roaming\ueli\PowershellUtility\38ce89f6-2930-4558-aea5-b504249ef409.ps1"
At C:\Users\Sergio\AppData\Roaming\ueli\PowershellUtility\38ce89f6-2930-4558-aea5-b504249ef409.ps1:67 char:129
+ ...  Menu\Programs\Administrative Tools\ODBC Data Sources (32-bit).lnk' - ...
+                                                              ~~~~
Unexpected token '-bit' in expression or statement.
At C:\Users\Sergio\AppData\Roaming\ueli\PowershellUtility\38ce89f6-2930-4558-aea5-b504249ef409.ps1:68 char:129
+ ...  Menu\Programs\Administrative Tools\ODBC Data Sources (64-bit).lnk' - ...
+                                                              ~~~~
Unexpected token '-bit' in expression or statement.
At C:\Users\Sergio\AppData\Roaming\ueli\PowershellUtility\38ce89f6-2930-4558-aea5-b504249ef409.ps1:95 char:120
+ ... ows\Start Menu\Programs\CorelDRAW Graphics Suite 2020 (64-bit)\Corel  ...
+                                                              ~~~~
Unexpected token '-bit' in expression or statement.
At C:\Users\Sergio\AppData\Roaming\ueli\PowershellUtility\38ce89f6-2930-4558-aea5-b504249ef409.ps1:95 char:148
+ ... lDRAW Graphics Suite 2020 (64-bit)\Corel CAPTURE 2020 (64-Bit).lnk' - ...
+                                                              ~~~~
Unexpected token '-Bit' in expression or statement.
At C:\Users\Sergio\AppData\Roaming\ueli\PowershellUtility\38ce89f6-2930-4558-aea5-b504249ef409.ps1:96 char:120
+ ... ows\Start Menu\Programs\CorelDRAW Graphics Suite 2020 (64-bit)\Corel  ...
+                                                              ~~~~
Unexpected token '-bit' in expression or statement.
At C:\Users\Sergio\AppData\Roaming\ueli\PowershellUtility\38ce89f6-2930-4558-aea5-b504249ef409.ps1:96 char:153
+ ...  Graphics Suite 2020 (64-bit)\Corel Font Manager 2020 (64-Bit).lnk' - ...
+                                                              ~~~~
Unexpected token '-Bit' in expression or statement.
At C:\Users\Sergio\AppData\Roaming\ueli\PowershellUtility\38ce89f6-2930-4558-aea5-b504249ef409.ps1:97 char:120
+ ... ows\Start Menu\Programs\CorelDRAW Graphics Suite 2020 (64-bit)\Corel  ...
+                                                              ~~~~
Unexpected token '-bit' in expression or statement.
At C:\Users\Sergio\AppData\Roaming\ueli\PowershellUtility\38ce89f6-2930-4558-aea5-b504249ef409.ps1:97 char:152
+ ... W Graphics Suite 2020 (64-bit)\Corel PHOTO-PAINT 2020 (64-Bit).lnk' - ...
+                                                              ~~~~
Unexpected token '-Bit' in expression or statement.
At C:\Users\Sergio\AppData\Roaming\ueli\PowershellUtility\38ce89f6-2930-4558-aea5-b504249ef409.ps1:98 char:120
+ ... ows\Start Menu\Programs\CorelDRAW Graphics Suite 2020 (64-bit)\CorelD ...
+                                                              ~~~~
Unexpected token '-bit' in expression or statement.
At C:\Users\Sergio\AppData\Roaming\ueli\PowershellUtility\38ce89f6-2930-4558-aea5-b504249ef409.ps1:98 char:144
+ ... CorelDRAW Graphics Suite 2020 (64-bit)\CorelDRAW 2020 (64-Bit).lnk' - ...
+                                                              ~~~~
Unexpected token '-Bit' in expression or statement.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken
 
'`

**Comment by NetBender** [comment]
> Can you open the Settings and go to the "Debug" tab to see if there are any logs that might be helpful? If so, can you share the logs?

Here it is
```
[24/6/2024, 21:39:53][ERROR] Failed to get search result items for extension with id 'ApplicationSearch.Reason: Error: Command failed: powershell -NoProfile -NonInteractive -ExecutionPolicy bypass -File "C:\Users\salva\AppData\Roaming\ueli\PowershellUtility\a2df354d-a688-4431-b40c-b570b31fa6d6.ps1"
In C:\Users\salva\AppData\Roaming\ueli\PowershellUtility\a2df354d-a688-4431-b40
c-b570b31fa6d6.ps1:176 car:136
+ ... indows\Start Menu\Programs\JDownloader\JDownloader 2 Update & Rescue. ...
+                                                                 ~
E commerciale (&) non consentita. L'operatore & � riservato per utilizzi 
futuri. Utilizzare "&" per passare la e commerciale come stringa.
In C:\Users\salva\AppData\Roaming\ueli\PowershellUtility\a2df354d-a688-4431-b40
c-b570b31fa6d6.ps1:213 car:234
+ ... FileImageImageGenerator\ecc5b54908db840dea14cb0aa03dca73b0563daa.png'
+                                                                         ~
Carattere di terminazione mancante nella stringa: '.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordEx 
   ception
    + FullyQualifiedErrorId : AmpersandNotAllowed
 
'
```

**Comment by blade2005** [comment]
Here's mine as well as it's a bit diferent from the other pasted logs.

```
[7/10/2024, 10:38:13 AM][ERROR] Failed to get search result items for extension with id 'ApplicationSearch.Reason: Error: Command failed: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive -ExecutionPolicy bypass -File "C:\Users\Stoney\AppData\Roaming\ueli\PowershellUtility\97fb1d79-9a41-4adf-b7c1-5337b8e78b9c.ps1"
At C:\Users\Stoney\AppData\Roaming\ueli\PowershellUtility\97fb1d79-9a41-4adf-b7c1-5337b8e78b9c.ps1:184 char:114
+ ... t\Windows\Start Menu\Programs\Python 3.11\Python 3.11 (64-bit).lnk' - ...
+                                                              ~~~~
Unexpected token '-bit' in expression or statement.
At C:\Users\Stoney\AppData\Roaming\ueli\PowershellUtility\97fb1d79-9a41-4adf-b7c1-5337b8e78b9c.ps1:185 char:122
+ ... s\Start Menu\Programs\Python 3.11\Python 3.11 Manuals (64-bit).lnk' - ...
+                                                              ~~~~
Unexpected token '-bit' in expression or statement.
At C:\Users\Stoney\AppData\Roaming\ueli\PowershellUtility\97fb1d79-9a41-4adf-b7c1-5337b8e78b9c.ps1:186 char:126
+ ... art Menu\Programs\Python 3.11\Python 3.11 Module Docs (64-bit).lnk' - ...
+                                                              ~~~~
Unexpected token '-bit' in expression or statement.
At C:\Users\Stoney\AppData\Roaming\ueli\PowershellUtility\97fb1d79-9a41-4adf-b7c1-5337b8e78b9c.ps1:283 char:131
+ ... t\Windows\Start Menu\Programs\Python 3.10\Python 3.10 (64-bit).lnk' - ...
+                                                              ~~~~
Unexpected token '-bit' in expression or statement.
At C:\Users\Stoney\AppData\Roaming\ueli\PowershellUtility\97fb1d79-9a41-4adf-b7c1-5337b8e78b9c.ps1:284 char:139
+ ... s\Start Menu\Programs\Python 3.10\Python 3.10 Manuals (64-bit).lnk' - ...
+                                                              ~~~~
Unexpected token '-bit' in expression or statement.
At C:\Users\Stoney\AppData\Roaming\ueli\PowershellUtility\97fb1d79-9a41-4adf-b7c1-5337b8e78b9c.ps1:285 char:143
+ ... art Menu\Programs\Python 3.10\Python 3.10 Module Docs (64-bit).lnk' - ...
+                                                              ~~~~
Unexpected token '-bit' in expression or statement.
At C:\Users\Stoney\AppData\Roaming\ueli\PowershellUtility\97fb1d79-9a41-4adf-b7c1-5337b8e78b9c.ps1:313 char:238
+ ... FileImageImageGenerator\f263b3d22f7cd00936f778237376ddd8e78ec8ca.png'
+                                                                         ~
The string is missing the terminator: '.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken
 
'
```

and if i rename all of those to just be `(64)` instead of `(64-bit)` I get these following errors too

```
[7/10/2024, 10:46:03 AM][ERROR] Failed to get search result items for extension with id 'ApplicationSearch.Reason: Error: Command failed: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive -ExecutionPolicy bypass -File "C:\Users\Stoney\AppData\Roaming\ueli\PowershellUtility\53c3640e-cd21-4e23-8d1c-db8bc7991f7a.ps1"
At C:\Users\Stoney\AppData\Roaming\ueli\PowershellUtility\53c3640e-cd21-4e23-8d1c-db8bc7991f7a.ps1:313 char:238
+ ... FileImageImageGenerator\f263b3d22f7cd00936f778237376ddd8e78ec8ca.png'
+                                                                         ~
The string is missing the terminator: '.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString
 
'
```

**Comment by oliverschwendener** [comment]
Thanks for all the logs. I'm still trying to find out what causes the issue.

**Comment by oliverschwendener** [comment]
There is an update available with a fix which potentially fixes this issue. Can someone check?

**Comment by blade2005** [comment]
looks great from me too!

**Comment by NetBender** [comment]
The latest update fixes the issue, thanks!

**Comment by wessamfathi** [comment]
Application Search is still broken for me on 9.4.0. Here are the debug logs:

`[10/09/2024, 11:44:00][ERROR] Failed to get search result items for extension with id 'ApplicationSearch.Reason: RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded'

[10/09/2024, 11:45:17][ERROR] Failed to get search result items for extension with id 'ApplicationSearch.Reason: RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded'

[10/09/2024, 11:45:23][ERROR] Failed to get search result items for extension with id 'ApplicationSearch.Reason: RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded'

[10/09/2024, 11:47:03][ERROR] Failed to get search result items for extension with id 'ApplicationSearch.Reason: RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded'`

After multiple attemps I got it _partially_ working, by playing around with the Search Engine, Rescan interval, and Fuzziness settings. Now I can find some but not all applications. For example, I cannot find any applications installed through Microsoft Store, even though I have _Include Apps from Windows Store_ enabled.

I'm glad to provide more info if it helps you, let me know.

**Comment by oliverschwendener** [comment]
Can you open a separate bug report for this? Thanks
