### ISSUE TITLE
[Feature Request] One button to get the old UI back.

### ISSUE THREAD

**Issue by heikopadelat** [oliverschwendener/ueli#1127]
I did the update to the new version and I'm shocked! What happened to the perfect UI of the 8.x version?
I would like to have a button to be able to switch back to the old look.

For all those who, like me, would like to have the old version back. Here is the DL link:
https://github.com/oliverschwendener/ueli/releases/download/v8.23.2/Ueli-Setup-8.23.2.exe

**Comment by oliverschwendener** [comment]
Here is the link to the latest v8 version:

https://github.com/oliverschwendener/ueli/releases/tag/v8.29.0
