### ISSUE TITLE
[Question] Why is ffmpeg in ueli?

### ISSUE THREAD

**Issue by kristus123** [oliverschwendener/ueli#1128]
![image](https://github.com/oliverschwendener/ueli/assets/23336150/d95cfa77-1ae8-482e-a3df-916cf684ac85)

**Comment by oliverschwendener** [comment]
I don't know why ffmpeg is there but I guess it's a part of electron. Maybe you find more information here: https://stackoverflow.com/questions/66961391/why-is-ffmpeg-bundled-with-my-electron-app
