### ISSUE TITLE
[Feature Request] make settings window bigger by default

### ISSUE THREAD

**Issue by kristus123** [oliverschwendener/ueli#1129]
![image](https://github.com/oliverschwendener/ueli/assets/23336150/63495013-72dd-4a4d-84dd-a91873d8ba9a)

The settings window is quite small. could it be bigger?

**Comment by kristus123** [comment]
what i mean is, can it be opened by default in a bigger window?

**Comment by weiw11** [comment]
This could potentially be resolved if settings was decoupled from search. See https://github.com/oliverschwendener/ueli/issues/1119.

**Comment by oliverschwendener** [comment]
Closing this in favor of #1119
