### ISSUE TITLE
[feature request] Add suffix to web search engines

### ISSUE THREAD

**Issue by LalaGhost** [oliverschwendener/ueli#113]
Hey I wanted to implement a command to search for a synonym on this website:
https://synonyme.woxikon.de/synonyme

But it needs ".php" as a suffix in the url at the end.

This does not work:
https://synonyme.woxikon.de/synonyme/fliegen
This does:
https://synonyme.woxikon.de/synonyme/fliegen.php

"fliegen" is the german word for "to fly".

So adding custom suffix to the urls would be nice.

**Comment by oliverschwendener** [comment]
You don't need to specify a suffix. Try this as the URL for your web search: `https://synonyme.woxikon.de/synonyme/{{query}}.php`

**Comment by LalaGhost** [comment]
Oh, works perfectly! Thanks!
Is this somewhere in the documentation specified?

**Comment by oliverschwendener** [comment]
It's a little hidden but it is here: https://github.com/oliverschwendener/ueli#options => `websearches` => `url`
