### ISSUE TITLE
[Question] About the config file

### ISSUE THREAD

**Issue by kristus123** [oliverschwendener/ueli#1130]
the new config for workflows look like this:

"extension[Workflow].workflows": [
        {
            "actions": [
                {
                    "id": "workflow-action-46f0ff87-ba2d-4bbc-99be-e86d134c0018",
                    "args": {
                        "url": "www.google.com"
                    },
                    "name": "hi",
                    "handlerId": "OpenUrl"
                }
            ],
            "name": "hi",
            "id": "workflow-bc023763-4622-4e73-b612-8d2bca122d28"
        }
    ],

is the 'id' just a random uuid?

i am asking because i want to programatically generated my config

**Comment by oliverschwendener** [comment]
Yes it's a random UUID generated with `crypto.randomUUID()`: https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID.

If you want to generate the config programmatically, just make sure that the id is unique among all the workflows. I also recommend prefixing them with the "workflow" or something similar so that they won't collide with other search result items.

**Comment by kristus123** [comment]
thank you!

**Comment by kristus123** [comment]
would it be possible to do some sort of js config?
e.q you could use js to generate config, and have programmable config generation more built into ueli.

what do you think?

**Comment by oliverschwendener** [comment]
I don't understand what you mean.

**Comment by kristus123** [comment]
this is what i hade done in order to use ueli. i don't think the ui is good, and it is easier to just write code to set up the config

for example:
```py
for repo in repos_list:
    add_url_shortcut(
        name=repo + " - main page",
        url=f"https://github.com/kristus123/{repo}",
        icon="https://github.com/favicon.ico",
        search_prefix="g")

    add_url_shortcut(
        name=repo + " - commits",
        url=f"https://github.com/kristus123/{repo}/commits/master",
        icon="https://github.com/favicon.ico",
        search_prefix="gc")
```

**Comment by kristus123** [comment]
would it be easy to natively support 'programatic config'?
or else, if you would be interested, i could maintain a 'programatic config tool'

**Comment by kristus123** [comment]
yes it does support it, but i have to write a wrapper for it.
which means everyone has to write their own wrapper

**Comment by kristus123** [comment]
if they want to do the same as me

**Comment by oliverschwendener** [comment]
I'm completly fine with that.

**Comment by kristus123** [comment]
and have you removed shortcuts?

how can i create a shortcut for opening a url?

and does 'websearchengines' still exist? that was quite useful:
e.q i could make my own google search thing

**Comment by oliverschwendener** [comment]
With "I'm completly fine with that" I mean that I'm completly fine if everyone (who wants to populate the settings programmatically) has to find their own way how to do it.

> everyone has to write their own wrapper

Not if you make your script available for others.

> would you be interested in collabing

No, unfortunately not

> the only thing i would need from you is to be able to refresh the config without having to restart ueli

I see, this is currently not possible. I'll see what I can do about thi.

**Comment by oliverschwendener** [comment]
> and have you removed shortcuts?

Yes

**Comment by kristus123** [comment]
> > and have you removed shortcuts?
> 
> Yes

aaaaaaw. that is an insanely useful tool.
will it be reintroduced later?

**Comment by oliverschwendener** [comment]
Shortcuts was replaced by Workflows, as they are very similar. The Workflows feature is basically the same, just with the ability to invoke multiple things at once, instead just one thing. With Workflows you can achieve the exact same result as with Shortcuts.

**Comment by kristus123** [comment]
what about search engine?

> and does 'websearchengines' still exist? that was quite useful:
> e.q i could make my own google search thing

**Comment by kristus123** [comment]
> > the only thing i would need from you is to be able to refresh the config without having to restart ueli
> 
> I see, this is currently not possible. I'll see what I can do about this.

if you could make it possible to refresh config without having to restart ueli, i can make my code public.
right now it is super hacky to make it easy for me to change config.
and people who use it will probably not wanna use it because of that

**Comment by kristus123** [comment]
> There is an extension called Web Search, supporting Google and DuckDuckGo, but there is currently no way to add your custom web search.

would it be possible to add that back? that is a super useful feature

**Comment by oliverschwendener** [comment]
Yes it is possible but I won't promise any timeline as this is a project that I work on in my free time.

**Comment by kristus123** [comment]
that's very understandable.
you should have a donation button!

probably many people using your tool in a professional setting

**Comment by oliverschwendener** [comment]
There is ;)

<img width="715" alt="image" src="https://github.com/oliverschwendener/ueli/assets/15727229/00ff5a16-b941-46f3-b844-f9078083a4ef">
