### ISSUE TITLE
[Question] Features removed in 9.0?

### ISSUE THREAD

**Issue by pnw-cascadia** [oliverschwendener/ueli#1131]
Version 9.0.1 seems vastly different than what I've used before.

I just installed Euli on a Win 11 laptop.  It looks very different than what I'm used to and much of the core functionality seems different or removed.  I can no longer use dot commands at all (e.g. .es?) and I can't add or change any web searches.  The ueli.app/#/features page still shows what I used to see.  Do I have a bad install or has there been a major change in the app?

**Comment by oliverschwendener** [comment]
You don't have a bad install ;) Ueli v9 was completly rewritten from the ground up and a lot of features were not ported from v8. The website needs to be updated, it still refers to ueli v8. If you depend on some features that are not available in v9 you can just install the latest v8 version from here: https://github.com/oliverschwendener/ueli/releases/tag/v8.29.0
