### ISSUE TITLE
[Bug] The calculator goes down when the number is too big.

### ISSUE THREAD

**Issue by undecV** [oliverschwendener/ueli#1132]
**Describe the bug**
The calculator goes down when the number is too big.

**To Reproduce**
Example input: `99999999!`
Then, the application loses the response.

**Expected behavior**
Show an exception ~~or give the result~~.

**Screenshots**
![image](https://github.com/oliverschwendener/ueli/assets/22562116/4e04a27b-4cd8-4b74-bedd-b6367b6fabe9)

**Environment**
 - OS: Windows
 - Version 8.29.0, 9.0.0-9.0.1

**Additional context**
Thanks for your attention!

**Comment by oliverschwendener** [comment]
As I don't see an reasonably quick solution to this, I'll mark this with "won't fix".
