### ISSUE TITLE
[Bug] Icons are not shown for links in the `Start Menu` folders.

### ISSUE THREAD

**Issue by undecV** [oliverschwendener/ueli#1133]
**Describe the bug**
Icons are not shown for links in these two default folders.

- `C:\ProgramData\Microsoft\Windows\Start Menu`
- `%APPDATA%\Microsoft\Windows\Start Menu`

But it works fine for custom folders such as `C:\Links` and "Apps from Windows Store".

**To Reproduce**
1. Setting -> Debug -> [Reset]
1. Result in Fig 1.
1. Setting -> Application Search:
   - Delete two default folders listed before.
   - Kept the switch `Include Apps from Windows Store` on.
1. Setting -> Extensions -> Application Search -> [Rescan]
1. Result in Fig 2.
1. Setting -> Application Search: Add a custom folder such as `C:\Links`.
1. Setting -> Extensions -> Application Search -> [Rescan]
1. Result in Fig 3.

**Expected behavior**
The colorful icons will be shown.

**Screenshots**
Fig 1: With the default setting.

- Include Apps from Windows Store: ON
- Folder: `C:\ProgramData\Microsoft\Windows\Start Menu`
- Folder: `%APPDATA%\Microsoft\Windows\Start Menu`
- File Extensions: `lnk`
 
![image](https://github.com/oliverschwendener/ueli/assets/22562116/59d4522c-13fb-411a-a9c3-da716d07af95)

Fig 2: With no folder.

- Include Apps from Windows Store: ON
- File Extensions: `lnk`

![image](https://github.com/oliverschwendener/ueli/assets/22562116/03b95480-fdeb-4ff2-bbaa-cbbd5cafb416)

Fig 3: With custom folders:

- Include Apps from Windows Store: ON
- Folder: `C:\Links`
- File Extensions: `lnk`

![image](https://github.com/oliverschwendener/ueli/assets/22562116/9cd0fa0f-0d50-4d67-aaf8-9ba29676dac1)

**Environment**
 - OS: Windows
 - Version 9.0.0-9.0.1
 - I tried it on both MS Store and Zip versions.

**Additional context**
There is no text in Setting -> Debug -> Logs.
Thanks for your attention!

**Comment by oliverschwendener** [comment]
There is an update available with a fix which potentially fixes this issue. Can you check?

**Comment by oliverschwendener** [comment]
Is there some info in the debug log? Open the settings and to to debug and see if something is in the "Logs".

**Comment by undecV** [comment]
I still can't find any text in Settings -> Debug -> Logs :(
I'm not sure if there are other options or console parameters that could show more logs.

**Comment by Dr-Sparx** [comment]
FWIW, exactly the same problem here with a fresh installation from the v9.0.4 msi installer. No icons for start menu items unless they came from the app store, no debug log info.

**Comment by undecV** [comment]
Good news! Most of the icons are working! However, some icons are still not showing.

**Environment**

- Ueli 9.6.0
- OS: Windows 11 23H2 (22635.4225)
- I only tried the Zip versions.

Fig 1 shows the current situation: some icons are displayed correctly, such as 7-Zip FM and 7-Zip Help (which naturally has a blank icon), while some icons, such as Voicemeeter, are still not showing.
![Fig 1](https://github.com/user-attachments/assets/cf19e874-266e-4f82-86f6-f223cceb3936)

**Comment by undecV** [comment]
I tried to identify the differences between shortcut files.

One scenario I found is that the icon disappears when the file extension is uppercase (.LNK) instead of lowercase (.lnk). As shown in Fig 1:
![Fig 1](https://github.com/user-attachments/assets/d70b2fa0-e13d-4637-b98f-3728c306e45c)

Although Windows forces the file extension of shortcut files to be hidden, it can still be viewed using file properties, as shown in Fig 2:
![Fig 2](https://github.com/user-attachments/assets/ea406217-3080-413f-abfc-0d9222600b58)

**Comment by undecV** [comment]
Another scenario I found is that the icon disappears when the Target and Icon are not the same file. As shown in Fig 1:
![Fig 1](https://github.com/user-attachments/assets/3c937c5c-253d-4236-8120-4d92510ef8aa)

Fig 2 shows the file properties of two files:
The one on the left is the native Discord icon, and the one on the right is the one I created. I used %LOCALAPPDATA% instead of the absolute path to anonymize it.
![Fig 2](https://github.com/user-attachments/assets/5289dc1a-3c0d-49f7-b19e-bdb17ba9d6cd)

I apologize for having only done some preliminary testing so far. I haven't deeply investigated these scenarios, so I'm not sure if this covers all the situations. Right now, I'm deeply buried in my primary work. 🤯

**Comment by oliverschwendener** [comment]
Can you check the latest release? It should include a bug fix which ignores the case of the file extension (`.lnk` / `.LNK`).

**Comment by undecV** [comment]
Congratulations! The new version works as expected. Thank you so much for the fix!

**Comment by undecV** [comment]
I’ve been digging deeper into this issue:

> Another scenario I found is that the icon disappears when the Target and Icon are not the same file.

I discovered that Ueli fetches the icon from the shortcut’s Target rather than from the icon specified by the shortcut itself. This behavior is demonstrated in Fig 1, which shows search results for some shortcuts from the K-Lite Codec Pack:

![Fig 1](https://github.com/user-attachments/assets/c547c3e2-ea11-49f2-adca-e3ac59e06d67)

In this case, the shortcut for `LAV Video (MPC-HC internal)` has a Target pointing to `mpc-hc64.exe`, but its icon is set to `lavvideo.ax`. As you can see, Ueli displays the first icon from `mpc-hc64.exe`. The properties of the shortcut are shown in Fig 2:

![Fig 2](https://github.com/user-attachments/assets/0c402f5c-4c52-414e-942f-ceb656a21d44)

**Environment**

- Ueli 9.6.1
- OS: Windows 11 23H2 (22635.4300)
- I only tested the Zip versions.

**Comment by oliverschwendener** [comment]
I consider the original issue to be resolved. For the icons, please open a separate feature request.
