### ISSUE TITLE
[Bug] The "Currency Conversion" extension does not seem to work

### ISSUE THREAD

**Issue by tsukiongithub** [oliverschwendener/ueli#1134]
**Describe the bug**
The currency convert has been broken for a little while on v8, and seeing it should be fixed in v9 i decided to update. This does not seem to be the case as if i enable the extension, choose the currencies i want in the dropdown from the extension settings and then type "8 eur" as i would with v8 when it was working, i get absolutely no results.

**To Reproduce**
1. Open Ueli settings
2. Click on Extensions
3. Enable "Currency Conversion"
4. Click the rescan button for "Currency Conversion"
5. Go back to the search field and type "8 eur"

**Expected behavior**
Expected to get the inputted currency converted into the other currencies

**Screenshots**
![image](https://github.com/oliverschwendener/ueli/assets/43679101/e59762f9-bb24-49fd-ba7b-6cad21044455)

**Environment**
 - OS: Windows 11 Home
 - Version: 9.0.1

**Comment by undecV** [comment]
You can try entering "1 USD to EUR".

https://github.com/oliverschwendener/ueli/blob/main/src/main/Extensions/CurrencyConversion/CurrencyConversion.ts#L42

**Comment by tsukiongithub** [comment]
> You can try entering "1 USD to EUR".
> 
> https://github.com/oliverschwendener/ueli/blob/main/src/main/Extensions/CurrencyConversion/CurrencyConversion.ts#L42

This does not work either
![image](https://github.com/oliverschwendener/ueli/assets/43679101/6025c2e8-a134-4468-b4b8-4c0c5cc80422)
