### ISSUE TITLE
[Question] about building my own super minimal ueli

### ISSUE THREAD

**Issue by kristus123** [oliverschwendener/ueli#1135]
i have for a long time wanted to help on ueli.

If i were to try and make my own 'super minimal ueli inspired launcher'
what files should i have a look at ?

i know you use electron,
and that opens a window when hitting a hot key

**Comment by oliverschwendener** [comment]
Hey, cool idea! I suggest you look at these files:

The main entry point of the application, responsible for setting up all different parts of the application:
`src/main/index.ts`

The global shortcut module, responsible for catching the hot key:
`src/main/Core/GlobalShortcut/GlobalShortcutModule.ts`

The browser window module, responsible for creating and managing the window:
`src/main/Core/BrowserWindow/BrowserWindowModule.ts`

The application search extension (responsible for searching apps):
`src/main/Extensions/ApplicationSearch/ApplicationSearch.ts`

**Comment by oliverschwendener** [comment]
If you want to build a super minimal version you can also check out how I started this project: https://github.com/oliverschwendener/ueli/tree/v1.0.0/src/js

Back then the source code was much more simple, maybe that's a better starting point.

**Comment by kristus123** [comment]
i tried to set up the v1.0.0 version, but got a lot of errors.
maybe because i am using the latest node version?
