### ISSUE TITLE
Please separate the old and the new ueli (Give us the old version back again)

### ISSUE THREAD

**Issue by a-hl-2003** [oliverschwendener/ueli#1136]
![image](https://github.com/oliverschwendener/ueli/assets/174365387/f54f74ed-851d-4a88-ae2e-68b108efe9b7)
The old version were so responsive with great performance. Also it was better implemented all its features. I still use it on Windows11 instead of the new version and even instead of the PowerToys Version. 
I like the idea of theming it with windows11 style, but will all appreciating that we have towards the new version, maybe some users prefer functionality over style.
Also the old version style was great enough.
Great work btw.

**Comment by oliverschwendener** [comment]
Then just use the latest v8 version ;)

https://github.com/oliverschwendener/ueli/releases/tag/v8.29.0

**Comment by Pardasus** [comment]
My first thought after a new installation was that the programme was broken. I love the programme and can no longer imagine working without it. But the new look is not for me. Thanks for the DL link to the old version.

Would it be conceivable to build in a feature to be able to switch between the old and new look? Something like a theme add-on?

**Comment by oliverschwendener** [comment]
It's a completly separate app, therefore unfortunately no.
