### ISSUE TITLE
[Question] v8 design in v9?

### ISSUE THREAD

**Issue by Brugman** [oliverschwendener/ueli#1139]
Is the minimalist design/look of v8 going to be _close_ to possible in v9 with future updates?

**Comment by oliverschwendener** [comment]
I don't understand your question. Can you elaborate a bit more?

**Comment by Brugman** [comment]
![2024-07-15-00-05-25](https://github.com/user-attachments/assets/f5d990e6-a5ca-47a9-8224-474da794107e)

This is my v8. In v9 we can currently customize the colors but not the borders, margin, padding and visible elements. So I can't style it to look the same. Do you expect that to be possible soon?

**Comment by oliverschwendener** [comment]
No, this is not planned. If you want to have full customization of the UI then you have to stay on v8.
