### ISSUE TITLE
[enhancement] Change the '?' to something different

### ISSUE THREAD

**Issue by LalaGhost** [oliverschwendener/ueli#114]
Is there a way to change the '?' you have to type for Ueli to make use of the web search engines?
Would be a nice feature to have. Maybe the standard is a '?' but you are able to change that?

**Comment by oliverschwendener** [comment]
I am working on a big update, and I am planning to allow more unrestricted prefixes for all kinds of plugins.

**Comment by keekuu** [comment]
I'm pumped for this big update. I think this will resolve my question/help wanted Issue I submitted.

**Comment by oliverschwendener** [comment]
In the upcoming update this is how you can edit/add web search engines.

![image](https://user-images.githubusercontent.com/15727229/56474384-4e5c4100-6479-11e9-98b7-859dfa5f57c6.png)

You can then freely choose a prefix for the web search engine. Hope this solves your problem.
