### ISSUE TITLE
Is it possible to open ueli to search a specific folder?

### ISSUE THREAD

**Issue by AlanEdd** [oliverschwendener/ueli#1140]
Hey there,
I have been looking around all the settings but don't see if this is possible.
Add a workflow to:

1.Type in a tag, say "note"
2.Ueli will only search a custom folder for content, say D:/myfolder/myNotes/

Is it possible to set that up?  something inbetween Workflows and Web search?
Thank you.

**Comment by oliverschwendener** [comment]
Currently, that's not possible. Workflows are meant to launch multiple things at once.
