### ISSUE TITLE
An application with an ' in it's link name totally breaks Ueli

### ISSUE THREAD

**Issue by Roemer** [oliverschwendener/ueli#1141]
**Describe the bug**
I updated from ueli 8 to 9.03 and now everything is broken.
The error I get is:
```
[13.7.2024, 13:26:17][ERROR] Failed to get search result items for extension with id 'ApplicationSearch.Reason: Error: Command failed: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive -ExecutionPolicy bypass -File "C:\Users\redacted\AppData\Roaming\ueli\PowershellUtility\53d6dae3-1680-43f3-8e1e-a1576e73bb88.ps1"
In C:\Users\redacted\AppData\Roaming\ueli\PowershellUtility\53d6dae3-1680-43f3-8e1e-a1576e73bb88.ps1:251 Zeichen:248
+ ... FileImageImageGenerator\a43d34b8da0a3b45eccb819c272566aa8725535d.png'
+                                                                         ~
Die Zeichenfolge hat kein Abschlusszeichen: '.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString
 ```

Having a look at the file, I seed that there are applications with an `'` in the name which obviously breaks the file. They should be escaped.

In my case, it is the intallation of Sysinternals via scoop which leads to this breaking line:
```
Get-Associated-Icon -InFilePath 'C:\Users\redacted\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Scoop Apps\SysInternals\CacheSet - Control the Cache Manager's working set size.lnk' -OutFilePath 'C:\Users\redacted\AppData\Roaming\ueli\FileImageImageGenerator\e03d87fd742663eff5ec9845b8209a3cd19e935c.png'
```

**To Reproduce**
1. Install Sysinternals via scoop: `scoop install extras/sysinternals`
2. Install ueli (via scoop or probably anything else)
3. Ueli is completely broken

**Expected behavior**
Ueli works

**Environment**
 - OS: Windows
 - Version 11

**Comment by oliverschwendener** [comment]
Thanks for all the detailed investigation! The issues reported [here ](https://github.com/oliverschwendener/ueli/issues/1124)might be related.

**Comment by oliverschwendener** [comment]
Can you try the latest release and check if it works?

**Comment by Roemer** [comment]
Yep, works now with 9.0.4, thanks for the fix.
