### ISSUE TITLE
[Bug] Ueli dosen't show settings while going into some of it's menus and also everything search dosent work!

### ISSUE THREAD

**Issue by Reicoler** [oliverschwendener/ueli#1143]
**Describe the bug**
Ueli dosent show settings when going into some sections of the app

**To Reproduce**
Go to some menues in ueli and see the problem 

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/769cf85e-9ee8-4711-afaf-601527ab1e6a)
![image](https://github.com/user-attachments/assets/e7ab8257-7f32-4f5f-a503-bd1f48cabbad)

**Environment**
 - OS: windows
 - Version 9.0.4 

**Additional context**

(es? dosent work either)

**Comment by oliverschwendener** [comment]
This is expected behavior when the extension does not have any settings.
