### ISSUE TITLE
[Help Wanted] Not able to set custom shortcuts

### ISSUE THREAD

**Issue by Gurvak-Singh** [oliverschwendener/ueli#1144]
Tried setting up custom shortcuts in the new Ueli application, but unable to do so as there is no option to do that. I tried getting into settings and find the settings to do that not getting any option for that. Can I please get some assistance in regard to how to setup the custom shortcuts for websites and file paths

**Comment by EidolonForgery** [comment]
+1 to this. The only thing that made UELI work for me was being able to segregate result type with a prefix. I have to switch programs until this is fixed.

**Comment by oliverschwendener** [comment]
Here is an example on how to set up a workflow:

Go to "Settings" and enable the "Workflow" extension:
![Screenshot 2024-07-25 215847](https://github.com/user-attachments/assets/ef8b5e0a-442b-4880-bcb4-50522751114d)

Go to the Workflow extension settings and click on "Create new Workflow"
![Screenshot 2024-07-25 215216](https://github.com/user-attachments/assets/a2d8bf44-3fce-4631-ad13-8ffcfc9fa83f)

Give your workflow a name
![Screenshot 2024-07-25 215922](https://github.com/user-attachments/assets/63d3d4c6-33a5-48ba-a8b5-60359696c1b7)

Click on "New Action" and enter the details of your action. In this example the action opens a file.
![Screenshot 2024-07-25 220019](https://github.com/user-attachments/assets/3d05c281-cba0-4f64-9a16-b9d56e61a6e0)

Click on "Add Action"
![Screenshot 2024-07-25 220024](https://github.com/user-attachments/assets/9348a7f4-9c75-4ecb-a0fd-4bfce6ceea73)

You can add multiple actions. All of them are executed simulatenously when invoking the workflow. When you're done, click on "Save"
![Screenshot 2024-07-25 220105](https://github.com/user-attachments/assets/57128294-04a6-4153-8efd-de7ff943797d)

Your workflow will appear now in the list of workflows
![Screenshot 2024-07-25 220109](https://github.com/user-attachments/assets/6334ec24-3126-4928-ab27-dee1c3846181)

Close the settings and search for the name of your workflow. Press enter to invoke the workflow.
![Screenshot 2024-07-25 220124](https://github.com/user-attachments/assets/2a733880-017d-4124-83dc-026b25fe0f8e)

I hope this helps. If something is not clear I can also make a screen recording. Cheers
