### ISSUE TITLE
[Bug] Unable / unsure how to use Everything Search in V9.0+

### ISSUE THREAD

**Issue by z-chw-rd** [oliverschwendener/ueli#1148]
**Bug description**
I do not see a way to use Everything Search within Ueli since upgrading to V9. I have Ueli's file search pointed at `es.exe`, but I don't see any documentation on how to start a search within Ueli using Everything.

**To Reproduce**

1. Invoke Ueli
2. Open settings with `^` `,`
3. Add path to `es.exe` in File Search tab
4. Go back to primary Ueli window
5. Unsuccessfully attempt to use Everything Search

**Expected behavior**

Invoke Everything Search within Ueli by entering a user-defined prefix

**Screenshots**
![Ueli Everything Search](https://github.com/user-attachments/assets/d46df902-4f76-4c9a-a3cb-0be1f6cd43c8)

**Environment**
 - OS: [Windows 11]
 - Version [e.g. 9.2.0]

**Comment by oliverschwendener** [comment]
Did you try searching for "file search"?

**Comment by z-a-c-hdotcom** [comment]
I tried that just now and yes, it works.

I guess that makes this more a feature request than a bug. I liked how in previous versions of Ueli, I could set up a prefix to invoke Everything, but with version 9+ I need to type out / access file search, then search. 

I think at the very least some documentation that instructs users how to utilize the file search feature is probably necessary; I searched around and wasn't able to find any instructions. 

If you need some help with documentation, I'd be happy to help with putting some stuff together!
