### ISSUE TITLE
[bug] Ueli window is not transparent

### ISSUE THREAD

**Issue by LalaGhost** [oliverschwendener/ueli#115]
These are my settings:
![screenshot_1](https://user-images.githubusercontent.com/43962138/53181824-9afdda00-35f8-11e9-8591-81f9da78cef1.png)

After a restart Ueli still looks like this:
![screenshot_2](https://user-images.githubusercontent.com/43962138/53181823-9a654380-35f8-11e9-955d-2dae7b6b1f59.png)
Should it not be transparent?

ueli: 7.2.2
Electron: 2.0.8
Chrome: 61.0.3163.100
Node: 8.9.3
V8: 6.1.534.41
Index size: 282

**Comment by oliverschwendener** [comment]
Additional to enabling `transparentWindow` you have set a custom user stylesheet and add a transparent background to it.

https://github.com/oliverschwendener/ueli#custom-color-themes

**Comment by LalaGhost** [comment]
But how do I exactly set the transparency?
I get it with adding a custom CSS file but where do I define the transparency?

**Comment by oliverschwendener** [comment]
See: https://github.com/oliverschwendener/ueli/issues/89#issuecomment-453738597

**Comment by LalaGhost** [comment]
Thanks, can be closed! :)
