### ISSUE TITLE
[Feature Request] Re-add hotkeys for extensions e.g. g? weather

### ISSUE THREAD

**Issue by MaximilianMauroner** [oliverschwendener/ueli#1152]
**Is your feature request related to a problem? Please describe.**
This feature existed and now it doesn't exist anymore.

**Describe the solution you'd like**
Re-add the feature

**Describe alternatives you've considered**
So far the only thing that comes close is using a different search engine (the fuzzy one)

**Additional context**
![image](https://github.com/user-attachments/assets/8ff5d7cd-2847-4807-8d52-893e2f995806)

**Comment by oliverschwendener** [comment]
I think this has been resolved by the addition of the Custom Web Search extension, added here: https://github.com/oliverschwendener/ueli/releases/tag/v9.11.0

![image](https://github.com/user-attachments/assets/dc4cc126-bf63-4764-8a41-fab7120a5a1c)
