### ISSUE TITLE
[Bug] locales not loaded

### ISSUE THREAD

**Issue by superuser7777** [oliverschwendener/ueli#1153]
**Describe the bug**
locales not loaded

**To Reproduce**
Status after resetting all settings
English and German only

**Expected behavior**

**Screenshots**
[image](https://i.imgur.com/hQaeOSD.jpeg)

**Environment**
 - OS: Windows 10 Enterprise LTSC
 - Version 21H2 19044.4651

**Additional context**
Thank you, “ueli” is getting better and better!

**Comment by oliverschwendener** [comment]
What's the exact issue? Ueli only supports English and German at the moment.

**Comment by superuser7777** [comment]
I was assuming a multi-language UI.
Isn't locale's country name .pak file for UI?

**Comment by oliverschwendener** [comment]
Sorry, I don't know what .pak files are. As stated above, Ueli currently just supports English (US) and German (Switzerland), so therefore I don't see a bug here. Please open a feature request if you want support for other languages.

**Comment by superuser7777** [comment]
`Ueli-9.3.1-win.zip > locales > (any langname).pak`
Isn't this a language file for the UI?

**Comment by oliverschwendener** [comment]
No. I don't know what the purpose of that file is.
