### ISSUE TITLE
[Bug] Failed to generate a cache for icon extractor

### ISSUE THREAD

**Issue by Zeromax** [oliverschwendener/ueli#1154]
**Describe the bug**
I installed the Appimage on Majaro and after I started the App I see only the Ueli commands.
The following Error appears in the logs:
`[8.8.2024, 20:39:34][ERROR] Failed to generate a cache for icon extractor. Reason: TypeError: {(intermediate value)(intermediate value)}[e] is not a function`

**To Reproduce**
1. Install Manjaro
1. Install the App via Appimage
1. Start the App
2. check the logs

**Expected behavior**
Search result of Apps and later for files and other stuff

**Screenshots**

**Environment**
 - OS: Latest Manjaro Linux 6.6.32-1-MANJARO 1 SMP PREEMPT_DYNAMIC Mon May 27 03:41:25 UTC 2024 x86_64 GNU/Linu

**Additional context**

**Comment by oliverschwendener** [comment]
@ke1v

**Comment by ke1v** [comment]
Looking into it

**Comment by oliverschwendener** [comment]
This should be fixed with v9.3.5
