### ISSUE TITLE
[Bug] V9, Ctrl+Shift+F2 not possible hotkey

### ISSUE THREAD

**Issue by ZatsuneNoMokou** [oliverschwendener/ueli#1156]
Bug similar to #1150 

Previously, control + shift + F2 was possible in V8, and with what is written in electron documentation, it should be possible to do it, is it possible to fix it ?

# Preview

![image](https://github.com/user-attachments/assets/8d434473-8eef-4626-8048-3244930dc747)

**Comment by oliverschwendener** [comment]
This is fixed in v9.3.4

**Comment by ZatsuneNoMokou** [comment]
Thanks
