### ISSUE TITLE
[Feature Request] Add blur effect to transparency 

### ISSUE THREAD

**Issue by jcklpe** [oliverschwendener/ueli#116]
This effect seems to have already been achieved on a fork of this project here: https://github.com/khanhas/ueli#features

Seems worth including. 

This project is looking great though! I'm currently having to split myself between alfred, albert, and Listary and would love if I could move to a more unified cross platform solution.

**Comment by oliverschwendener** [comment]
Currently [electron](https://electronjs.org/docs/api/browser-window) supports vibrancy (blur transparency effect) only for macOS. Taking a screenshot and setting it as a background image to imitate the native transparency blur effect seems like a workaround for me that I don't want to do. Will have to wait until electron supports vibrancy for windows too. Closing this issue for now.

**Comment by jcklpe** [comment]
make sense, thanks! 
👍

**Comment by IRlyLikeBac0n** [comment]
@oliverschwendener Could [this module](https://github.com/levrik/electron-vibrancy-windows) be useful here?

**Comment by oliverschwendener** [comment]
Yes, it may work but I don't want to use any 3rd party libraries to achieve this. As electron already supports the acrylic effect on macOS I'd rather wait until they also add support for this on Windows.

**Comment by voxain** [comment]
Bump? Not sure if electron natively supports this now, but with the release of windows 11, could you check this again?

**Comment by oliverschwendener** [comment]
Still only supported in macOS 🥲
