### ISSUE TITLE
[Help wanted] <Description>

### ISSUE THREAD

**Issue by Gurvak-Singh** [oliverschwendener/ueli#1166]
I am using the older version of ueli which is 8.22.1, and I am wondering if there is a way I can add a shortcut or maybe a workflow that can help open an online search in the browser of my choice.

Like for example if I do a web search in google using ueli the query is g? - and then I can type whatever I want to look up online and the google results will come.

Just like this I am wondering if I can do something maybe in a shortcut or in workflow that will open a browser and the search results come in that browser

**Comment by oliverschwendener** [comment]
Can you please add a meaningful title to this issue?
