### ISSUE TITLE
It is possible to make the input text persistent?

### ISSUE THREAD

**Issue by ifigueroac** [oliverschwendener/ueli#117]
I dont find any option to control this behavior but, It is possible to make the entered text persistent? For example if I type something and close the bar the typed text clears himself but I need that the typed text keeps in bar 

If this is not possible at this moment, then can you consider to add this feature in the future? 

I love ueli!

**Comment by oliverschwendener** [comment]
Thanks for your feedback! This is a good idea, could be an option to enable/disable. Will consider this to add in the next release.

**Comment by alanaasmaa** [comment]
I would like this also.
But when opening ueli second time the text should be selected.

This allows quickly to enter a new cmd or alternatively press enter to trigger last cmd again.

**Comment by oliverschwendener** [comment]
In case you didn't know, there is the possibility to browse through your last inputs with <kbd>Shift</kbd><kbd>Up</kbd> or <kbd>Shift</kbd><kbd>Down</kbd>

**Comment by oliverschwendener** [comment]
This is included in the newest [v8.0.0](https://github.com/oliverschwendener/ueli/releases/v8.0.0) release.
