### ISSUE TITLE
[Bug] Global shortcut does not work on Linux using Wayland

### ISSUE THREAD

**Issue by ke1v** [oliverschwendener/ueli#1170]
**Describe the bug**
Global hotkeys are not available on Linux under GNOME Wayland sessions.

**To Reproduce**
1. Launch ueli on GNOME Wayland
2. Hide ueli window
3. Press hotkey
4. Ueli does not reappear

**Expected behavior**
Ueli should reappear when using the global hotkey

**Environment**
 - OS: [Linux]
 - Version 9.3.2

**Additional context**
This appears to be an upstream bug (https://github.com/electron/electron/issues/38288) in Electron, as Wayland does not provide a way for Electron to register global hotkeys.

**Comment by ke1v** [comment]
I'm proposing a workaround that seems to be popular with other apps, where calling the executable with an argument flag (ie. `ueli --toggle`) will dispatch the same event in the main process (using Electron's `requestSingleInstanceLock`) as pressing the global hotkey. If anyone has a better idea please feel free to suggest them.

**Comment by Neitex** [comment]
+1 to the proposal above. This solution would also enable ueli's usage outside of full desktop environments. For instance, setting `XDG_SESSION_DESKTOP=gnome` makes application search extension work smoothly even with Hyprland Wayland compositor (tested on ueli commit 737655b). So this workaround would make ueli a decent alternative to, for example, ULauncher across various Linux setups, not just within major desktop environments.

**Comment by ke1v** [comment]
> This solution would also enable ueli's usage outside of full desktop environments.

I'm curious as to what you mean by this?

> setting `XDG_SESSION_DESKTOP=gnome` makes application search extension work

BTW this should be fixed in 9.3.5 (although Hyprland may not have working icon support)

**Comment by oliverschwendener** [comment]
The next release contains a fix for this. Just try to launch a second instance of Ueli and it will show and focus the already running app.
