### ISSUE TITLE
[Bug] search bar does not hide when pressing the escape key

### ISSUE THREAD

**Issue by gspinoza** [oliverschwendener/ueli#1174]
**Describe the bug**
The search bar does not hide when pressing esc key

**Expected behavior**
When the esc key is pressed the search bar should close/hide just like the previous version

**Environment**
 - OS: macOS
 - Version 9.3.1 (9.3.1)

**Comment by oliverschwendener** [comment]
See #1151

**Comment by gspinoza** [comment]
> See #1151
Thank you, my apologies for missing this in settings.

**Comment by oliverschwendener** [comment]
No worries. Maybe it makes sense to enable this setting by default. I'll look into it, thanks for reporting!
