### ISSUE TITLE
[Feature Request] Update Custom Theme Lables

### ISSUE THREAD

**Issue by ondrovic** [oliverschwendener/ueli#1177]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/user-attachments/assets/91c84e95-cfb3-45a5-985e-bf96176fb312)
Not sure what the numbers represent

**Describe the solution you'd like**
Like the them settings in v8
![image](https://github.com/user-attachments/assets/9ff7626b-cdc4-4db6-b08d-2a383ae07976)

Clear, understandable labels

**Describe alternatives you've considered**
Manually changing the color until the element I want is the color and moving on

**Additional context**
![image](https://github.com/user-attachments/assets/be35f8a6-181a-4700-a7a1-00ddac98b197)

**Comment by oliverschwendener** [comment]
With Ueli v9 you can't customize colors of separate elements, you can just alter the brand colors of the theme.

The values 10-160 represent color shades that make up the theme, you can find more information here: https://react.fluentui.dev/?path=/docs/concepts-developer-theming--docs#customizing-the-theme
