### ISSUE TITLE
[Feature Request] Update Chocolatey packages

### ISSUE THREAD

**Issue by ZatsuneNoMokou** [oliverschwendener/ueli#1182]
Is it possilbe to update Chocolatey version with at least 9.3.4 ?

**Comment by oliverschwendener** [comment]
As far as I understand the ueli chocolatey package is maintained by other people than me and I don't have any plans to do that myself. As an alternative you can install and update ueli via the `winget` CLI if you want:

```
winget install Ueli -s msstore
```
