### ISSUE TITLE
[Help wanted] Can't import custom theme

### ISSUE THREAD

**Issue by bl4xe** [oliverschwendener/ueli#1186]
I downloaded the Catppuccin Mocha Mauve theme (https://github.com/catppuccin/ueli) and their install instructions are to just import the .json. However, I don't have such an option. Only editing the hex codes, which there is more of in the settings menu than there are in the .json for some reason.

**Screenshots**
![image](https://github.com/user-attachments/assets/bb104ff0-6175-4320-91e7-7f3ce84c8c14)

**Environment**

-   OS: Arch Linux
-   Version: 6.10.8-arch1-1

**Comment by IrishBruse** [comment]
Looks like that theme is for v8

**Comment by oliverschwendener** [comment]
Yes as @IrishBruse said, that theme is not compatible with ueli v9 .
