### ISSUE TITLE
[Feature Request] Restore the Ability to Add Custom Search Engines in Web Search

### ISSUE THREAD

**Issue by Ilya-Green** [oliverschwendener/ueli#1188]
**Is your feature request related to a problem? Please describe.**
In ueli version 9.4.0, I can't find an option to add a new search engine in the Web Search settings. In version 8.26.0, I could add any search engine I wanted, such as YouTube, GitHub, Wikipedia, Google Maps, etc. After updating to the latest version, this functionality seems to be missing.
 
**Describe the solution you'd like**
I would like to have the ability to add custom search engines in the new versions of ueli, just like it was possible in previous versions.

**Comment by oliverschwendener** [comment]
The latest version includes a "Custom Web Search" extension, thanks to @NiewView
