### ISSUE TITLE
[Bug] "Include apps from windows store" does not work

### ISSUE THREAD

**Issue by wessamfathi** [oliverschwendener/ueli#1189]
Application Search is still broken for me on 9.4.0. This could potentially be related to #1124 and/or #1030.

1. Open Ueli (via the global keyboard shortcut or right click on tray icon -> Show)
2. Try to search for any installed application
3. Notice that no applications show up

Debug logs:
I noticed the following debug log message appears every time the scanner re-searches for applications:

```
ERROR] Failed to get search result items for extension with id 'ApplicationSearch.Reason: RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded'
```

Environment:
 - OS: Windows 11
 - Version 9.4.0

Notes:
Sometimes playing around with the settings under the _Search Engine_ section, some of the installed applications start to show, but not all of them, and not all the time.

**Comment by oliverschwendener** [comment]
Thanks for reporting. I have an assumption what the problem could be, I will look into this as soon as possible. Can you share your application search settings?

![image](https://github.com/user-attachments/assets/ff2eea3f-0931-4520-9ee7-48e3be8b5f01)

**Comment by wessamfathi** [comment]
Sure thing, here you go.

Let me know if I can help with anything else.

![image](https://github.com/user-attachments/assets/f733e44a-4305-4a6e-b77b-41d5127d3059)

**Comment by oliverschwendener** [comment]
Can you try turning off the option "include apps from windows store"? Do you get any apps then?

**Comment by wessamfathi** [comment]
That seems to do the trick! I get my apps normally now. Thanks for the help.

It will be great though, if later there will be a fix for the store apps :)

**Comment by oliverschwendener** [comment]
Good to hear! I'll update here when there is an update.

**Comment by wessamfathi** [comment]
Hi again! I just wanted to let you know something that might be useful in your bughunt. I have Ueli 9.8 (MS Store edition) installed on my PC and my laptop, both running Windows 11. On my PC, if I enable _Include apps from Windows Store_, the application search stops working as mentioned before.

However, it appears that it works fine on my laptop. Despite using the same version, Application Search works fine when I include Windows Store apps.

I'm available to send more diagnostic or log files if that helps.

**Comment by oliverschwendener** [comment]
I already have a clue what could be the issue. I assume that the number of apps that you have installed from the MS store is bigger on your PC than your Laptop, is that right?

**Comment by wessamfathi** [comment]
Not by a lot, but yes. About 60+ on laptop vs. 70+ on PC.

**Comment by oliverschwendener** [comment]
I assume that you would experience the same issue on the laptop when adding more apps.

**Comment by wessamfathi** [comment]
I did a little experiment by removing some apps from my PC, so it's less than what I have on my laptop. Then, I enabled _Store Apps_ search on my PC, but it still doesn't work, while it works on the laptop.

Is there a way to clear the search index and/or re-index files somehow, maybe the issue could be resolved with a fresh one?

**Comment by oliverschwendener** [comment]
The index is cleared every time you quit the app and start it again.

**Comment by oliverschwendener** [comment]
Can you try the latest release? https://github.com/oliverschwendener/ueli/releases/tag/v9.9.1

**Comment by wessamfathi** [comment]
This fixes the bug on my PC. Great work, thanks :)
