### ISSUE TITLE
[Help wanted] App not launching at all on macOS

### ISSUE THREAD

**Issue by YousufSSyed** [oliverschwendener/ueli#1190]
**Describe what you're trying to achieve**
I tried running Ueli 9.4.0 from both the Github releases and the website, but when I open the app nothing happens, I just see the icon in the dock and menu bar options.

**To Reproduce**

1. Download Ueli from https://ueli.app/
2. Drag it to Applications folder
3. Open the app
4. nothing happens

**Environment**

-   OS: macOS 15 Beta
-   Version 9.4.0

**Comment by oliverschwendener** [comment]
macOS probably prevents you from opening the app because it's neither signed nor notarized. Can you try right-clicking the app and then choose "Open". Then you should see a warning and have the option to click "Open anyway".

**Comment by oliverschwendener** [comment]
Did you have a look at these issues already?
- #380
- #821

**Comment by YousufSSyed** [comment]
I tried `xattr -dr com.apple.quarantine /Applications/ueli.app/` and `sudo xattr -dr com.apple.quarantine /Applications/ueli.app/` but the same thing happens. Nothing appears under "Privacy & Security" (I never got any message about it being blocked either).

The same thing happens: when I click the dock icon nothing shows up except for stuff in the menu bar.

**Comment by YousufSSyed** [comment]
The issue persists on 9.5.1

**Comment by IrishBruse** [comment]
To run it via the command line you can do something like this not sure of the exact path but `/Application/Ueli/Contents/MacOS//Ueli` something like that anyways tab completition will help get you there and it will display any errors when you go to try and start it up in the terminal it might be related to you being on a beta version of mac also

**Comment by YousufSSyed** [comment]
>  not sure of the exact path but /Application/Ueli/Contents/MacOS/Ueli

The proper path would be `/Applications/Ueli.app/Contents/MacOS/Ueli`. Entering that in and then click the dock icon outputs the following:

```log
2024-09-14 15:02:49.484 Ueli[38639:5075723] +[IMKClient subclass]: chose IMKClient_Modern
2024-09-14 15:02:49.484 Ueli[38639:5075723] +[IMKInputSession subclass]: chose IMKInputSession_Modern
```

**Comment by oliverschwendener** [comment]
@YousufSSyed Are you using an Intel odr Apple M chip?

**Comment by YousufSSyed** [comment]
I'm on an M1 Mac and just tried 9.6.3 (`Ueli-9.6.1-arm64.dmg`) and it still doesn't launch.

**Comment by oliverschwendener** [comment]
Is it possible that some sort of anti-virus is blocking it?

**Comment by YousufSSyed** [comment]
I don't have any AV software on my mac. This is my output of `ls /Applications/ > apps.txt`.

```
1Piece.app
789-Zip.app
Accents.app
'Adobe Photoshop 2024'
'Affinity Designer 2.app'
'Affinity Photo 2.app'
Alacritty.app
'Alfred 5.app'
AltTab.app
Amnesia.app
Amphetamine.app
'Amphetamine Enhancer.app'
'Android Studio.app'
AppleBlox.app
Applite.app
'Audio Hijack.app'
'Automator Open with Neovim.app'
BetterTouchTool.app
BetterZip.app
Bitwarden.app
BrightIntosh.app
Buckets.app
Chatbox.app
ChatGPT.app
CheatEngine74.app
'CleanShot X.app'
ColorSlurp.app
'Command X.app'
Cuber.app
Cursor.app
CursorSense.app
DaisyDisk.app
Dime.app
DockDoor.app
Emacs.app
emochi.app
Espanso.app
FastDMG.app
Figma.app
Firefox.app
'Firefox Nightly.app'
Folders.app
GeekTool.app
'GitHub Desktop.app'
GitKraken.app
'Grammarly Desktop.app'
Hammerspoon.app
Hazel.app
Homerow.app
Hyper.app
'iA Writer.app'
Ice.app
iClip.app
'Icon Preview.app'
IINA.app
Invisibility.app
iTerm.app
JDownloader2.app -> '/Users/yousuf/bin/JDownloader 2'/JDownloader2.app
'Jump Desktop Connect.app'
Karabiner-Elements.app
Karabiner-EventViewer.app
'Keyboard Cowboy.app'
'Keyboard Scroller.app'
KeyLimePie.app
Keymou.app
KeyPad.app
kindaVim.app
kitty.app
krita.app
Kulve.app
LibreWolf.app
LinearMouse.app
'Little Snitch.app'
Logoer.app
Loopback.app
LosslessCut.app
Maccy.app
MacForge.app
MacSploit.app
Mailspring.app
'Microsoft Excel.app'
'Microsoft OneNote.app'
'Microsoft Word.app'
Minecraft.app
'MuMuPlayer Pro.app'
neovide.app
NetNewsWire.app
'NTFS for Mac.app'
Numbers.app
OBS.app
Obsidian.app
Omnivore.app
OpenArtemis.app
OpenMTP.app
Orbital.app
OrbStack.app
Orion.app
'Parallels Desktop.app'
PastePal.app
Pieces.app
'Pieces OS.app'
PinFrame.app
'Pixelmator Pro.app'
Playgrounds.app
Plover.app
ProNotes.app
qbittorrent.app
'QSpace Pro.app'
qView.app
Raycast.app
'Rectangle Pro.app'
Roblox.app
RobloxStudio.app
Rocket.app
Safari.app -> ../System/Cryptexes/App/System/Applications/Safari.app
Scoot.app
Scroll.app
'SF Symbols.app'
Shortcat.app
'SimpleLogin for Safari.app'
Sketch.app
SlimHUD.app
SnippetsLab.app
SoundSource.app
Stats.app
SteerMouse.app
'Sticky Notes.app'
Superkey.app
Swapface.app
'Swift Quit.app'
'Swift Shift.app'
Swish.app
Tabby.app
TablePlus.app
Tabula.app
Tailscale.app
TestFlight.app
TextPal.app
Thunderbird.app
TinkerTool.app
'Tor Browser.app'
Tower.app
Typora.app
Ueli.app
Untitled.app
Unwrap.app
Utilities
UTM.app
Vimac.app
VimMotion.app
'Visual Studio Code.app'
Vivaldi.app
VLC.app
VSCodium.app
Warp.app
WezTerm.app
Whisky.app
Wooshy.app
xbar.app
Yomu.app
'Zen Browser.app'
```

**Comment by oliverschwendener** [comment]
Is the app showing up in the menu bar?

**Comment by YousufSSyed** [comment]
Yeah it shows up, I'll close this now. There's nothing in particular I did.
