### ISSUE TITLE
[Bug] Taskbar tool tip empty on Windows 11

### ISSUE THREAD

**Issue by milnak** [oliverschwendener/ueli#1191]
**Describe the bug**
Taskbar tool tip empty on Windows 11

**To Reproduce**
Run euli.  However over "U" taskbar icon. empty box shown

**Expected behavior**
Should read "Euli" or something.

**Screenshots**
![image](https://github.com/user-attachments/assets/9d24ff62-1616-4e2c-b609-7dc60debc22f)

**Environment**
 - OS: Windows
 - Version 11

**Additional context**

**Comment by oliverschwendener** [comment]
This will be fixed with the next release.
