### ISSUE TITLE
[Help wanted] Web search request not working "An error has occurred"  

### ISSUE THREAD

**Issue by Rick21st** [oliverschwendener/ueli#1192]
after imputing my web search prefix which in this case would be "gg" you can see on the screenshot it recognizes it as a google search. Once I start typing anything else I keep getting a "An error has occurred". I refreshed the index wherever that does and restarted the program and still can't seem to resolve this issue. I just stopped working on me, how can I fix this? I use this program heavy. I didn't mess with the setting or inputs so I'm even more confused why this is happening. This happened last week but it just resolved itself an hour or two later but I want to avoid this being a reoccurring thing. 

**Screenshots**
<img width="463" alt="Screenshot 2024-09-10 181928" src="https://github.com/user-attachments/assets/3eb00564-ff53-4682-a203-3e594f3de58d">
<img width="467" alt="Screenshot 2024-09-10 181951" src="https://github.com/user-attachments/assets/6a7c9a53-5152-4de5-9f5d-f2e766edb05f">

**Environment**

-   OS: [Windows|
-   Version [8.23.1]

I've tried the new version but found this version a lot more cleaner looking and setting easier to customize for some reason

**Comment by oliverschwendener** [comment]
Ueli v8 is discontinued, therefore I'm afraid to tell you that there won't be a patch for this.
