### ISSUE TITLE
[Feature Request] Shortcut for Go back

### ISSUE THREAD

**Issue by popstas** [oliverschwendener/ueli#1195]
There are several screens with a "Go back" button. It would be handy to have a hotkey for this action.

Screens with "Go back":
- Settings
- DeepL

Common hotkeys for the "Go back" action:
- Alt+left / Cmd+left (browser way)
- Esc (intuitive way)

The hardware button "back" is working, although.

**Comment by oliverschwendener** [comment]
With the next release (v9.9.0) you will be able to navigate back with pressing "Escape".
