### ISSUE TITLE
[bug] search subsitution variables for search query urls does not seem to work or isn't documented

### ISSUE THREAD

**Issue by jcklpe** [oliverschwendener/ueli#120]
Are there any syntaxes that can be used for query variables? As in if I want to use googles lucky search I have to as specific query string as a substitution for the parameter I enter into ueli. 

I can't find this anywhere in the documentation

Let's say that the query variable is triggered by the characters "xoxo" then I would have this query in my config files: http://www.google.com/search?q=xoxo&btnI then if I search "go? lucky charms", I would expect it to use the query string: http://www.google.com/search?q=lucky+charms&btnI which then launches the lucky charms cereal website rather than taking me through google since the lucky charms website was the first google search result.

does ueli recognize query substitution variables? If not then please consider this a feature request to support this feature. Appending the search term works for like 75% of search queries but the most powerful search queries use variables, and you can do cool stuff like use different wolfram alpha functionalities straight from ueli with very little set up.

**Comment by jcklpe** [comment]
Also I finally found some info on what the default query variable used by google is. They, and many other people use `/%s?`. This however does not appear to work with ueli so I'm guessing it doesn't have the ability to use query variable substitution right now?

**Comment by oliverschwendener** [comment]
For your web search engine you can add this as URL: `https://www.google.com/search?q={{query}}&btnl`

If you then search for `g?lucky charms` it should result to `https://www.google.com/search?q=lucky+charms&btnl`

Hope this solves your problem

**Comment by jcklpe** [comment]
Awesome thanks! Sorry I missed that!
