### ISSUE TITLE
[Bug] Deepl translater plugin not starting/working

### ISSUE THREAD

**Issue by rocthem** [oliverschwendener/ueli#1209]
**Describe the bug**
Search for “DeepL Translator” and press the Enter key.
But the DeepL Translator window does not open. 
Edge with Google Search opens instead.

**To Reproduce**
1. Alt+Space: Open UELI
2. Type DeepL Translator or "DeepL Translator"
3. Press Return

**Expected behavior**
a window as described here should open:
https://github.com/oliverschwendener/ueli/blob/main/docs/Extensions/DeeplTranslator/README.md

**Screenshots**
![Screenshot 2024-09-16 120501](https://github.com/user-attachments/assets/4951b812-51a5-4d19-a284-1c7d575f5382)
![Screenshot 2024-09-16 120501](https://github.com/user-attachments/assets/6490e86b-8e87-4324-a450-c4d5e8ebf153)

**Environment**
 - OS: Windows 11
 - Version 9.3.4

**Comment by oliverschwendener** [comment]
Are you sure you're using Ueli? This doesn't look like Ueli's UI.

**Comment by rocthem** [comment]
![Screenshot 2024-09-16 142639](https://github.com/user-attachments/assets/701ef06a-bf2c-4021-9a8d-3b70c6d96a3d)

Yes :)

![Screenshot 2024-09-16 143235](https://github.com/user-attachments/assets/62381291-6cb6-42cb-b1fa-a3edaa096abb)

**Comment by oliverschwendener** [comment]
This is definitely not Ueli

![image](https://github.com/user-attachments/assets/4a34bc79-ac9d-426b-8253-6cfdfa4d02fc)

**Comment by oliverschwendener** [comment]
I assume that you have another app (most likely Powertoys Run) running with the same hot key.

**Comment by rocthem** [comment]
oh, that's right.
What a mix-up, I'm sorry
