### ISSUE TITLE
[Feature request] Change/remember position on screen

### ISSUE THREAD

**Issue by enoversum** [oliverschwendener/ueli#122]
It would be super rad if ueli could remember its (altered) position on the screen once you moved it - I like that pretty window to appear lower on the screen, since I am operating a huge 32" screen :) .

**Comment by oliverschwendener** [comment]
Thanks for your feedback, going to look into this as soon as possible!

**Comment by enoversum** [comment]
Danke, Oliver :) !

**Comment by enoversum** [comment]
Thanks for adding this! Works as it should :) . 
Could you let ueli remember its position across bootups? It just happens to reset after a restart, and I believe eben after a wakeup from sleep mode.

**Comment by krizajb** [comment]
How exactly does one move the ueli launcher?

**Comment by krizajb** [comment]
Can confirm that the position isn't saved on application restart.
