### ISSUE TITLE
[Bug] Visual Studio Code extension not working (on Windows)

### ISSUE THREAD

**Issue by milnak** [oliverschwendener/ueli#1220]
**Describe the bug**
Visual Studio Code extension not working (on Windows)

**To Reproduce**

ueli (9.6.0)
extensions > Visual Studio Code. Hit refresh
search for a recent project by name in ueli (see VS Code File > Open Recent)
Not found.

**Expected behavior**
Should be found.

**Screenshots**
![image](https://github.com/user-attachments/assets/ddf986ae-7359-4b5d-8cf7-26f0313f06b1)

![image](https://github.com/user-attachments/assets/3e1f2807-3902-47ba-bb44-6da8b6804966)

![image](https://github.com/user-attachments/assets/3e354260-4826-4da1-81cf-1a74d94d006c)

**Environment**
 - OS: Windows
 - Version 9.6.0

**Additional context**
Nothing shown in debug log.

**Comment by IrishBruse** [comment]
Have you tried chaning the fuzziness 
![image](https://github.com/user-attachments/assets/90bd469e-9426-405c-97e3-8908bef2fdb7)

**Comment by IrishBruse** [comment]
I aso find fuzzysort as the search engine better in most cases

**Comment by milnak** [comment]
fuzzysort didn't help.

**Comment by IrishBruse** [comment]
Whats your prefix set to in the extension settings? 
Are any recents at all showing up?
Is the command in the extension set to `code %s`

**Comment by milnak** [comment]
That was it. prefix is "vscode" and i didnt realize a prefix is required. No other extension in ueli requires a prefix does it?  Is it beneficial to have a prefix here? In my screen shots you can see I was expecting that typing the vscode workspace name would have it show in the list.

If this is by design, feel free to close (and document)!
