### ISSUE TITLE
[Feature Request] unit conversion

### ISSUE THREAD

**Issue by milnak** [oliverschwendener/ueli#1222]
would be nice to have an extension that does unit conversion, e.g.

Prompt: 
`2.5 cm` or `2.5 centimeter`

Result:

```text
0.025 Meter
0.000025 Kilometer
2.5 Centimeter
25 Millimeter
25000 Micrometer
25000000 Nanometer
0.0000155342 Mile
0.0000155342 Yard
0.0820209974 Foot
0.9842519685 Inch
2.642521769E-18 Light Year
```

and selecting Inch (for example) would copy `0.9842519685` to the clipboard.

see [UnitConverters](https://www.unitconverters.net/) for examples.

**Comment by oliverschwendener** [comment]
This is already possible with the Calculator extension

<img width="712" alt="image" src="https://github.com/user-attachments/assets/248ae27c-1f39-48bf-9fda-948accb24c3e">

**Comment by milnak** [comment]
ah, "in" was the key! thanks!
