### ISSUE TITLE
[Bug] <Currency conversion not working when ueli is invoked via shortcut>

### ISSUE THREAD

**Issue by TheMasterOfMadness** [oliverschwendener/ueli#1246]
**Describe the bug**
When I press Alt+Space to invoke ueli, it comes up  and I input a string as shown below that doesn't run any results except a web search
![mIvteQxY81](https://github.com/user-attachments/assets/90a1407b-47f2-4e94-8dc6-6bf1159a5521)

When I open ueli by right clicking application icon and selecting 'Show', firstly the UI seems to be different than my existing settings.
The currency extension seems to be working then.
![jsGX5XVPE5](https://github.com/user-attachments/assets/1e70f91c-fb4a-4109-8749-27d3f5868966)

**Comment by oliverschwendener** [comment]
![image](https://github.com/user-attachments/assets/e6417cc1-7655-448c-b66f-75350dbba000)

I think this is PowerToys Run.

**Comment by oliverschwendener** [comment]
See #1209

**Comment by TheMasterOfMadness** [comment]
Thanks for pointing that out. My bad.
