### ISSUE TITLE
[Bug] Custom Web Search shows as "Custom Seb Search"

### ISSUE THREAD

**Issue by milnak** [oliverschwendener/ueli#1253]
ueli 9.10.0

![image](https://github.com/user-attachments/assets/b2a43203-2355-44fe-838f-4219fde54b26)

**Comment by milnak** [comment]
looks like it's fixed here

https://github.com/oliverschwendener/ueli/commit/7891a71c06413933169ce4b62aae1227b4e02e99

**Comment by oliverschwendener** [comment]
Yes, a fix for this will be included in the next release.
