### ISSUE TITLE
[Bug] Custom Web Search doesn't support similar names

### ISSUE THREAD

**Issue by milnak** [oliverschwendener/ueli#1254]
Custom Web Search.

```text
Name: Google Search
Prefix: g
Url: https://www.google.com/search?q={{query}}

Name: Genius Web Search
Prefix: genius
Url: https://genius.com/search?q={{query}}
```

now open ueli and enter "genius steely dan"

google search will run.

**Comment by NiewView** [comment]
@milnak you can add these to custom settings. Why would it be neccessary to add it to the default?

**Comment by arcticpinecone** [comment]
Can I ask how you add the custom search anyway? From Ueli 9.10, I see the web search extension, and it comes with 2 options. There is nowhere I find to add a new one. I would like to add Kagi search.

**Comment by oliverschwendener** [comment]
The new extension is called "Custom Web Search". You can enable it in the settings:

**Comment by oliverschwendener** [comment]
A fix for this is included in the latest release
