### ISSUE TITLE
>ping 1.1.1.1 -t

### ISSUE THREAD

**Issue by GitBiker** [oliverschwendener/ueli#126]
this ping results in a timeout that keeps running forever.
subsequent cmd calls keep showing "Request timed out."

**Comment by oliverschwendener** [comment]
`-t` Parameter documentation says:

>Specifies that ping continue sending echo Request messages to the destination until interrupted. To interrupt and display statistics, press CTRL+break. To interrupt and quit ping, press CTRL+C.

from https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/ping

**Comment by GitBiker** [comment]
ok, thank you! I did not check the syntax.
I wasn't able to stop ueli.

**Comment by oliverschwendener** [comment]
`-t` makes to commandline program to run forever until you stop it with <kbd>ctrl</kbd><kbd>c</kbd>
