### ISSUE TITLE
[feature request]Hotkey to open folder of selected file

### ISSUE THREAD

**Issue by LalaGhost** [oliverschwendener/ueli#127]
Is there a way to open the directory of the searched file within ueli?
Does this function have a specific key combination? I was only able to open the file itself.
![ueli](https://user-images.githubusercontent.com/43962138/54455805-fab15600-475c-11e9-93df-d03bc3abe654.jpg)

**Comment by oliverschwendener** [comment]
https://github.com/oliverschwendener/ueli/blob/master/README.md#keyboard-shortcuts

<kbd>ctrl</kbd><kbd>o</kbd>
