### ISSUE TITLE
[Feature Request] Refresh function like Ueli 8 wanted

### ISSUE THREAD

**Issue by tomaskall** [oliverschwendener/ueli#1272]
[Feature Request] Refresh function like Ueli 8 wanted.  Simple folder watcher/files was refreshed when i typed "ref" ang got suggestion refresh. 

Now my workaround is via a abt file (feels a little uggly): 

`taskkill /F /IM ueli.exe
@REM taskkill /F /IM "Cross-Platform Keystroke Launcher.exe" /T
@REM taskkill /F /IM "Cross-Platform Keystroke Launcher.exe" /T

@REM timeout 1
@REM start "" /MIN "%LOCALAPPDATA%\Programs\ueli\Ueli.exe"

powershell -Command "Start-Process '%LOCALAPPDATA%\Programs\ueli\Ueli.exe'"

timeout 3
EXIT /B `

**Comment by oliverschwendener** [comment]
The next release will include an option to trigger a rescan from the search results:

![image](https://github.com/user-attachments/assets/4fa90207-8221-40fe-8f2b-ebda6eaf2d3a)
