### ISSUE TITLE
[Help wanted] Search Queries

### ISSUE THREAD

**Issue by christopher-wagner-work** [oliverschwendener/ueli#1277]
**Describe what you're trying to achieve**
In an earlier version of Ueli, the ability to have search queries with websites was supported. 
For example the syntax for the build was https://www.google.com/search?q={{query}}
I do not have a screenshot as I have the more recent version of Ueli so the issue report shows an example. 

I may be overlooking this functionality in the new versions. Im really sorry if so.

**Additional context**
This was working before in an earlier version. See issue report here as an example https://github.com/oliverschwendener/ueli/issues/665

**Comment by oliverschwendener** [comment]
You might want to check out the "Custom Web Search" extension:

![image](https://github.com/user-attachments/assets/3e07c60a-ef0c-4240-b012-d297e3912550)
