### ISSUE TITLE
[Help wanted] Have to click into input box to get focus to type

### ISSUE THREAD

**Issue by paltman** [oliverschwendener/ueli#1288]
When I hit the keyboard shortcut to bring up the UI, I see the input box but it doesn't seem to have focus as when i type nothign appears.  I have to click into the input box before it will register what i type.

**Environment**

-   OS: macOS Sequoia 15.1.1 (24B91)

**Comment by paltman** [comment]
A bit more information.

I have my shortcut key set to Cmd+Space (currently Spotlight isn't working for me and want to use this to replace Spotlight but use the command i'm used to).

If i press Esc, then i'm able to type.  It's like the Spotlight UI is activated as well but just not visible to me and hitting Esc closes that "ghost" UI which activates ueli.

WHen i change shortcut key to Alt+Space it works fine.

So this likely has nothing to do with your app and something to do with my broken Spotlight.

**Comment by oliverschwendener** [comment]
Thanks for the detailed report. I tried to reproduce it on my mac and it seems I can't even use the hotkey if it's already assigned to Spotlight. You can turn off the hotkey cmd+space for spotlight (System Settings => Keyboard => Keyboard shortcuts => Spotlight):

<img width="827" alt="image" src="https://github.com/user-attachments/assets/c9fa3d95-ad01-410c-802b-2652190fedfa">

If you deactivate the hotkey for Spotlight, or assign something else then Cmd+Space seems to work fine with Ueli.

**Comment by paltman** [comment]
Agreed. They worked for me. Thanks! Great tool!

**Comment by paltman** [comment]
https://github.com/sponsors/oliverschwendener?sp=paltman

Appreciate it!

**Comment by oliverschwendener** [comment]
Wow, thanks alot! :)
