### ISSUE TITLE
i'm getting this error, how do i fix this?

### ISSUE THREAD

**Issue by adityasanehi** [oliverschwendener/ueli#129]
I accidentally changed the hotkey to ALT and now I cannot access the app or the settings. I've tried reinstalling multiple times but it still shows a JavaScript Error (cannot register globalhotkey). Any solution to this?

**Comment by adityasanehi** [comment]
![Error 19-03-2019 02_37_48](https://user-images.githubusercontent.com/20219493/54563784-25670d00-49f0-11e9-8c88-4decf4a95880.png)

**Comment by anuragdeshpande** [comment]
I had the same issue, try resetting the shortcuts and special commands.

**Comment by adityasanehi** [comment]
> I had the same issue, try resetting the shortcuts and special commands.

How can I do that? I tried resetting the keyboard settings and it didn't work.

**Comment by oliverschwendener** [comment]
This has nothing to do with shortcuts and custom commands. `alt` is simpliy a invalid hotkey. Alt is a modifier that works only in combination with another key. Here you can read about which hotkeys are available: https://electronjs.org/docs/api/accelerator#available-modifiers.

There are two ways of fixing this:

1. If you see ueli's icon in your windows system tray: click on it => click on "Settings". The settings window should show up. Go to the section "Hotkey" and change it to `alt+space`.

![image](https://user-images.githubusercontent.com/15727229/54589415-de940a00-4a25-11e9-95eb-f8e94897e556.png)

2. Open the config file (`C:\Users\<your username>\.ueli\ueli.config.json`) with a text editor. In that text file search for the section `"hotKey": "alt"`. Change this line to `"hotKey": "alt+space"`. Save and restart ueli and it should work again.

**Comment by adityasanehi** [comment]
Fixed it. I was trying to change the hotkey the other day but it closed on me accidentally leaving 'alt' written under the 'hotkey' section. Thankyou.
