### ISSUE TITLE
[Help wanted] UELI not finding any app

### ISSUE THREAD

**Issue by Razer0123** [oliverschwendener/ueli#1297]
Open an app through Ueli

**To Reproduce**

Just open Eueli and search for an app

**Environment**

Mac OS sequoia 15.2

Is it a bug or am I doing something wrong?

**Comment by oliverschwendener** [comment]
Is this issue resolved?

**Comment by Razer0123** [comment]
> Is this issue resolved?

Hello Olivier,

yes it's solved ,not sure how, but seems like the issue was caused by the Lulu firewall, once I reinstalled it with Lulu disabled it started working

It's a bit confusing because I don't think UELI requires a connection to scan for apps, but was not working before

**Comment by Razer0123** [comment]
> Is this issue resolved?

Reinstalled again on a clean device, same issue, could it be a problem with latest version?

**Comment by oliverschwendener** [comment]
The default mdfind filter works fine on my mac. I don't really understand why it works on some computers and on some you need to change it. Does one of the filters solve the issue for you?

**Comment by Razer0123** [comment]
> The default mdfind filter works fine on my mac. I don't really understand why it works on some computers and on some you need to change it. Does one of the filters solve the issue for you?

The last one on the list seems to work

**Comment by oliverschwendener** [comment]
Then I consider this bug resolved.
