### ISSUE TITLE
App weird behavior (Does not work?)

### ISSUE THREAD

**Issue by raziEiL** [oliverschwendener/ueli#130]
I see the ueli.exe process in Task Manager but there no GUI on desktop. Rebooting and reinstalling does not help. OS: Win 7

**Comment by oliverschwendener** [comment]
Do you see the icon in the system tray?

**Comment by raziEiL** [comment]
Nope

**Comment by oliverschwendener** [comment]
Can you show me the content your config file? You can find this file in `C:\Users\<your username>\.ueli\ueli.config.json`

**Comment by raziEiL** [comment]
Thank you! Problem is solved. I guess I accidentally clicked this checkbox
![notepad++_k95vyHqF1t](https://user-images.githubusercontent.com/2551987/54890871-28b93780-4ecd-11e9-9218-d74b37bf0ecf.png)
