### ISSUE TITLE
[Enhancement] Changing primary desktop dies not changes Ueli's position

### ISSUE THREAD

**Issue by LalaGhost** [oliverschwendener/ueli#131]
I have two screens attached to my PC.
When the left screen is my primary display, Ueli does open on my left screen.
But when I change my primary display to the right one, Ueli does still open on my left screen.
It would be nice if Uelis would open on the primary display as the setting say.

I have checked 'Always show on primary display'.

Info
ueli: 7.2.5
Electron: 2.0.8
Chrome: 61.0.3163.100
Node: 8.9.3
V8: 6.1.534.41
Index size: 293

**Comment by oliverschwendener** [comment]
Did you restart the app after you changed your primary display?

**Comment by LalaGhost** [comment]
Right, kinda makes sense...
No, I did not, after restart it did change it's position....

**Comment by CristianPadilla** [comment]
I have the same issue, "show always on primary display" setting not working

**Comment by TheophileMot** [comment]
Same problem here. I have multiple desktops on my laptop, and often Ueli gets "stranded" on the wrong one. When I hit the keyboard shortcut to open it, the screen slides left or right to reveal the desktop that Ueli is hiding in.
