### ISSUE TITLE
Can't get shortcuts to work

### ISSUE THREAD

**Issue by TobiasDev** [oliverschwendener/ueli#132]
Hello, 

I'm trying to add a shortcut to some software that Ueli can't find, but I can't get it to work. 

  "shortcuts": [
	{
		"name": "Server",
		"executionArgument": "C:\InternalSoftware\start.exe"
    }
  ],

Am I doing something wrong, or how would I go at this?

**Comment by oliverschwendener** [comment]
I recommend using the GUI to add shortcuts. Press <kbd>Ctrl</kbd><kbd>i</kbd> to open up the settings. To to the section shortcuts and fill in the fields. Finally press the + button to save the shortcut.

**Comment by TobiasDev** [comment]
Hmm, I tried doing that, but after doing it, I added the folder path to the ExecutionArgument (I want to open an .exe file), added a name and prefix, but all it does is open a random folder. It does not even open the folder with the .exe file in, it opens a folder. 

I have not added a icon path at all. 

I must be doing something wrong, just not sure what. :(

**Comment by oliverschwendener** [comment]
I think you are in the wrong section. I think you tried to set up a custom command which is something different. You have to scroll all the way down to "Shortcuts" (see screenshot).

![image](https://user-images.githubusercontent.com/15727229/54921413-02fc5480-4f06-11e9-9904-79f80c52df5f.png)

Shortcuts only need a name and a execution argument (in this case the filepath to your file)

**Comment by TobiasDev** [comment]
... Sorry... I was. I don't know why I didn't see that... I was so sure I was in the right place. I'm really sorry!

**Comment by oliverschwendener** [comment]
No problem ;)
