### ISSUE TITLE
[Feature Request] Convert Hex to RGBA/HSL and visa versa

### ISSUE THREAD

**Issue by jcklpe** [oliverschwendener/ueli#133]
This would be a killer feature. Probably one of the things I use in my day to day life. I know some electron based launchers have this feature as a plugin like zazu so maybe there's some logic that can be scraped from there: https://github.com/halvves/zazu-colors

It would also be cool if the output copied to the clipboard and/or in CSS compatible syntax

As always thank you for your fantastic work!

**Comment by oliverschwendener** [comment]
Thank you for your feedback! I will consider this as a possible plugin for the next release.

**Comment by oliverschwendener** [comment]
New feature now available in the [newest](https://github.com/oliverschwendener/ueli/releases/tag/v8.1.0) release.

**Comment by jcklpe** [comment]
@oliverschwendener woo thank you!!! ❤
