### ISSUE TITLE
Help. Issue when naming opening key as "0" BUG

### ISSUE THREAD

**Issue by sneak100** [oliverschwendener/ueli#134]
For Ueli, I renamed the opening key to 0 and it keeps crashing. I re-downloaded and the same pop-up appears Please fix. Kind of like issue #108 but with just the number 0
![ueli](https://user-images.githubusercontent.com/49135381/55299500-10bf4780-53e8-11e9-980f-8a4dba0a2e05.png)

**Comment by oliverschwendener** [comment]
You can't assign `0` as global hotkey. The hotkey should contain a modifier (`alt`, `ctrl`, etc.). For your case it could be for example `alt+0`. Here is a documentation about keycodes and key modifiers: https://electronjs.org/docs/api/accelerator#available-modifiers.
