### ISSUE TITLE
Remote Desktop connection UELI is not working

### ISSUE THREAD

**Issue by chrisonline** [oliverschwendener/ueli#135]
If I connect to my PC with Remote Desktop the Ueli app after hitting the shortcut shows for a millisecond and is disappearing.
Afterwards the shortcut does not show the app anymore.

Only a restart of Ueli does fix the problem.
Needs to be done once after a remote desktop connection. Afterwards all is working fine again.

**Comment by oliverschwendener** [comment]
Does it work if you open ueli via the system tray icon?

**Comment by chrisonline** [comment]
Will try that tomorrow when I am again connecting via Remote Desktop.

**Comment by chrisonline** [comment]
Just tried it and it does also not work if I use the tray icon and select "show".

**Comment by oliverschwendener** [comment]
Can you check if this still occurs in the newest [release](https://github.com/oliverschwendener/ueli/releases)?

**Comment by chrisonline** [comment]
Yes of course. I have just updated it and will try it tomorrow.
Will let you know.

**Comment by chrisonline** [comment]
Sadly it is not solved.
But could this problem be because I have at home 2 monitors and in the office only 1?

I have now enable the setting "Show always on Primary".
I will report back on monday if the problem is still there with this setting.

**Comment by chrisonline** [comment]
Just tested it again.
Does not work :-(

I see for a millisecond the window and afterwards it disappears.
Now if I hit the Key I don't see it again until I restart Ueli.

**Comment by oliverschwendener** [comment]
I'll mark this as won't fix as I don't see how this could be resolved.
