### ISSUE TITLE
Cannot Load Custom CSS File

### ISSUE THREAD

**Issue by moses-bowman** [oliverschwendener/ueli#137]
My portable programs (including `ueli`) are stored in Google Drive under the `Programs` folder. Inside is a folder called `__appdata` which contains two folders: `config` and `data`.

`ueli`'s config is located in:
`..\__appdata\config\ueli\ueli.config.json`
it can be loaded properly, but not the custom `.css` file which is stored in:
`..\__appdata\data\ueli\style.css`

**Comment by oliverschwendener** [comment]
Does it work if you put your stylesheet somewhere else (e.g. on your desktop folder)?

**Comment by moses-bowman** [comment]
@oliverschwendener 

Yes indeed. Originally I had it in a `config` folder along with `ueli.config.json` inside the root directory.

Another thing is that, whenever I try to run `ueli` as administrator using `Listary` or `Quick Access Popup` with this setup, I get this error:
![image](https://user-images.githubusercontent.com/40249465/55964342-1f8ae180-5ca7-11e9-88b9-d6a4224fb84d.png)
The error doesn't appear when I run it as administrator from the `Context Menu` though.
<sup>_Anyway, to stay on topic with the issue posted, I'll just submit a new one for this if need be._</sup>

**Comment by oliverschwendener** [comment]
Why would you need to run it as admin?

**Comment by moses-bowman** [comment]
> Why would you need to run it as admin?

Don't mind this at all. I had a thought that `ueli` wouldn't run when an active window is run as admin, which was pointed out in another app that I'm using.

Anyway, the error shown on the image with my recent comment started popping up during startup ever since I had the `..\__appdata\config\ueli\ueli.config.json` configuration (regardless whether `ueli` is run admin or not). I'll just open another issue for this.

---

:tada: with #142
Will try it out as soon as I can!

**Comment by oliverschwendener** [comment]
Closing this because the original issue has been resolved.
