### ISSUE TITLE
What is the Difference b/w ueli & other search indexers?

### ISSUE THREAD

**Issue by Droyk** [oliverschwendener/ueli#140]
For e.g. khanhas/ueli, Keypirinha, Cerebro, Wox

What's the main difference b/w them?
Is there is any comparison table?

I mean they have almost the same UI providing the same thing, a search indexer to search everything there is.

**Comment by alanaasmaa** [comment]
Frameworks, performance, plugins etc..

You have to test each of them to find best one. 
Currently i'm using Wox. But i'm waiting refactored ueli, then i probably move here.

I'm sure i will start using refactored ueli because:
- Typescript
- Vue
- Plugins

I hope @oliverschwendener will release some pre release soon!!!

**Comment by Droyk** [comment]
>I'm waiting refactored ueli, then I probably move here.

Why not use khanhas/ueli it's more like an updated repo with more features?
or am I missing something? possible to enlighten me?

**Comment by alanaasmaa** [comment]
@Droyk I have tried also this one, but it felt not right. I have no good reason.

**Comment by Droyk** [comment]
>but it felt not right

Possible to elaborate a little?
specifically, what you did not like about it?

**Comment by oliverschwendener** [comment]
They are all kind of similar. Considering features, there are definitely differences, go check by yourself which launcher comes with what kind of feature set.

Here are some differences that come to my mind:

* ueli & khanhas/ueli both use the Electron framework, and this could be a reason **NOT** to use them. Read more [here](https://medium.com/commitlog/electron-is-cancer-b066108e6c32).
* ueli & Cerebro run on Windows & macOs
* keypirinha, khanhas/ueli & Wox only run on Windows
* ueli does not support 3rd party plugins, the others do
* khanhas/ueli does not have any GUI to tweak the settings/configuration (as far as I know)

At the end of the day it depends on your personal taste and your needs.

Does this answer your questions?

**Comment by alanaasmaa** [comment]
The electron IS the reason for me why i like ueli. And plugins are the reason i wait the big upgrade. 

I code mostly JS and i have enough RAM so i would love to make little plugins to make my dev life easy.

Im sure some of them will help others too

**Comment by oliverschwendener** [comment]
> And plugins are the reason i wait the big upgrade.

Then I'm sorry to tell you that there are no plans yet to support plugins. :(

**Comment by alanaasmaa** [comment]
@oliverschwender call them mods and figure something out :)

But srlsy.. why not :(
I have misunderstood something then.

**Comment by oliverschwendener** [comment]
@alanaasmaa Let's have this discussion in #96
