### ISSUE TITLE
[Feature Request] Open Share folders

### ISSUE THREAD

**Issue by bashz0** [oliverschwendener/ueli#145]
I would like to see an option to open share folders. 
I can open normal folders by typing C:\Users\*.
But it would be very handy if we could open share folders aswell, by tying \ \Share\* for example. 

Im not really sure if this is already possible but I couldn't find how to do it.

**Comment by oliverschwendener** [comment]
Hmm.. the first question is: is `\\Share\...` a valid Windows file path?

**Comment by bashz0** [comment]
Yes, for instance I use it in my company to get to a different user their C:\ disk
![afbeelding](https://user-images.githubusercontent.com/17523231/57452807-03a63b80-7265-11e9-8dff-96e30c0b1e2d.png)

This is also used for instance print servers or file sharing locations
![afbeelding](https://user-images.githubusercontent.com/17523231/57452871-2a647200-7265-11e9-9d10-539ebd8c852f.png)

![afbeelding](https://user-images.githubusercontent.com/17523231/57452896-3d774200-7265-11e9-85af-d4571484899f.png)

It would be very handy if I could just type this in ueli to open the shares:
![afbeelding](https://user-images.githubusercontent.com/17523231/57452933-5849b680-7265-11e9-81ad-3676cc43c8a3.png)

**Comment by oliverschwendener** [comment]
Allright, I will look into this as soon as possible!
