### ISSUE TITLE
Cyrillic cmd output is unreadable

### ISSUE THREAD

**Issue by MonstraG** [oliverschwendener/ueli#146]
ueli: 7.2.5
![image](https://user-images.githubusercontent.com/17963791/57828422-e2919d80-77c4-11e9-8edb-011406fda3f2.png)

nuff said.

**Comment by oliverschwendener** [comment]
Duplicate of #40.

This should be fixed with the next release.

**Comment by oliverschwendener** [comment]
This is included in the newest [v8.0.0](https://github.com/oliverschwendener/ueli/releases/v8.0.0) release.
