### ISSUE TITLE
Main process crash when deleted a folder from a desktop

### ISSUE THREAD

**Issue by TheAifam5** [oliverschwendener/ueli#15]
Hey,

i really love your program and I using it every day. I tried to clean up my desktop and I deleted one folder exactly. After when the deletion completed, the ueli crashed. I think, the program was in the middle of scanning apps :)

Here is the crash log.
![image](https://user-images.githubusercontent.com/2192274/39083203-066b6ad4-4561-11e8-8759-ff49808e8988.png)

Regards,
TheAifam5

**Comment by oliverschwendener** [comment]
Hello there, thanks for your feedback! I really apprecitate that. I fixed this issue with a simple try-catch in 90bee07. Since I am still figuring out how to test this case there is no guarantee that this won't happen again. Please reopen this issue if you're still encountering this error.

**Comment by TheAifam5** [comment]
Simple try-catch should be ok than crashing application completely.
