### ISSUE TITLE
Ueli is fullscreen

### ISSUE THREAD

**Issue by pickbreaker** [oliverschwendener/ueli#150]
After the update to Version 7.2.6 ueli is now displaying fullscreen instead of the normal centered search.

**Comment by oliverschwendener** [comment]
I'm on it! Thanks for the feedback!

**Comment by oliverschwendener** [comment]
I just re-released v7.2.6. Can you check if it works properly now? Cheers

**Comment by pickbreaker** [comment]
Yes, works fine. Thanks for your work.

**Comment by asienchris** [comment]
Hey, it is happening again and UELI is opening in full screen instead of normal centered search (ueli 8.10.0 Electron 10.1.2 Node 12.16.3 V8 8.5.210.20-electron.0) thanks for checking / reapiring!
