### ISSUE TITLE
chocolatey doesn't support revisions of the same version

### ISSUE THREAD

**Issue by TimB87** [oliverschwendener/ueli#151]
Hi Oliver,
FYI: I've updated today when you first pushed the new version as a release. Now you seem to have  pushed another release with the same version number, therefor the sha256sum changed.
Choco doesn't support revisions of the same port, so I had to call it version 7.2.6.1. Will push in the next minute or so.. 
Please don't do that stuff in the future, rather bump it up a version. Thanks a lot!

Best regards,
Tim

**Comment by oliverschwendener** [comment]
Ok I see. Next time I'll just make another release, my bad.
