### ISSUE TITLE
Convert Unix path (slashes) to Windows path (backslashes)

### ISSUE THREAD

**Issue by Tobirexy** [oliverschwendener/ueli#153]
I prefer UNIX style paths (e.g. /example/test) instead of Windows style paths (e.g. \example\test). I can type forward slashes a lot faster than backslashes. Most programs support both options nowadays. It would be awesome if you could add an option to convert slashes to backslashes when typing file paths.

![image](https://user-images.githubusercontent.com/6097749/59185810-ab1ed280-8b71-11e9-825f-544e70576040.png)
 
![image](https://user-images.githubusercontent.com/6097749/59185943-005ae400-8b72-11e9-8cb8-299531cbccdf.png)

Thanks!

**Comment by oliverschwendener** [comment]
A fix for this will be included in the next major release.

**Comment by Tobirexy** [comment]
> A fix for this will be included in the next major release.

Awesome 👍 Thanks a lot!

**Comment by oliverschwendener** [comment]
This is included in the newest [v8.0.0](https://github.com/oliverschwendener/ueli/releases/v8.0.0) release.
