### ISSUE TITLE
Crashes on opening

### ISSUE THREAD

**Issue by seba5496** [oliverschwendener/ueli#154]
![Anotación 2019-06-21 140830](https://user-images.githubusercontent.com/47981550/59942595-1f892980-942e-11e9-80b1-3d15b55e2091.png)
I keep having this issue, no clue why.
Please help me :(

**Comment by oliverschwendener** [comment]
Did you modify the settings? If so, can you provide me the content of your settings file (`~/.ueli/ueli.config.json`)?

**Comment by oliverschwendener** [comment]
Probably related to #152

**Comment by oliverschwendener** [comment]
Closing this as a duplicate of #152.
