### ISSUE TITLE
I get this error every time the app starts up. So,I have to restart the app though sometimes while I search I get the same error

### ISSUE THREAD

**Issue by Mahesh-Ironcoder** [oliverschwendener/ueli#156]
![ueli_32Of9lsBnT](https://user-images.githubusercontent.com/51284518/60020695-2a51f180-96ae-11e9-96e6-02556e612a9d.png)

**Comment by Mahesh-Ironcoder** [comment]
please tell me what does it mean?

**Comment by oliverschwendener** [comment]
Did you change the config? If so can you provide the content of your config file (`~/.ueli/ueli.config.json`)?

**Comment by oliverschwendener** [comment]
New version with bugfix released: https://github.com/oliverschwendener/ueli/releases/tag/v7.2.7
