### ISSUE TITLE
Crashes when pressing alt+space in hotkey setting

### ISSUE THREAD

**Issue by SpectralKH** [oliverschwendener/ueli#158]
When you  go into ueli's settings and press alt+space inside the hot key text field, the app will crash. Relaunching the app seems to work a couple times, but eventually it doesn't work at all (menu bar icon shows up, but it's grayed out indefinitely). Had to close euli's processes through Activity Monitor.

Before pressing alt+space, I had deleted the text in the hot key text field so it was empty - Might not have to be empty. Have not tried anything else than alt+space, so there might be other ones that work too.

Deleting `~/.euli` makes the error go away.

OS: macOS

ueli: 7.2.7
Electron: 2.0.18
Chrome: 61.0.3163.100
Node: 8.9.3
V8: 6.1.534.41
Index size: 189

**Comment by SpectralKH** [comment]
Off-topic question: How does euli manage to not have it's menu bar show up (e.g when you're in Chrome and open euli, the menu bar is still Chrome's)? Couldn't figure out how by looking at the source code.

**Comment by nisar22** [comment]
Same for me, How do I change the hotkey since my UELI is not opening. Can someone direct me coz I dont know much of coding n all

**Comment by oliverschwendener** [comment]
First of all: if you want to change the global hotkey in the settings you cannot press the hotkey while being inside the text field. You have to type in the hot key by yourself. Possible hotkeys are documented here: https://github.com/oliverschwendener/ueli#options

### How to reset the global hotkey
#### If you want to preserve your config:

* Open `~/.ueli/ueli.config.json` with a text editor
* Search for the the line which starts with `"hotKey"`
* Replace this line with `"hotKey": "alt+space",`
* Restart ueli

#### Easier way (you will loose your modification of the settings though)

* Quit ueli
* Delete the file `~/.ueli/ueli.config.json`
* Start ueli

**Comment by SpectralKH** [comment]
@oliverschwendener Realized that, but maybe it shouldn't brick the app if you do try pressing the hotkey you want it changed to

**Comment by oliverschwendener** [comment]
@SpectralKH Yes you are right. This will be fixed in the next major release.
