### ISSUE TITLE
Buggy fade in animation when opening

### ISSUE THREAD

**Issue by oliverschwendener** [oliverschwendener/ueli#160]
Original feedback from @neojp

> For some reason it always flickers a lot when I open it, I know it's trying to fade in but it never seems to work well on my machine. An option to avoid the animation and just open would be nice.

**Comment by krizajb** [comment]
If I understand correctly this is only fixed if the `Allow transparent background (Restart required)
` option is disabled?

**Comment by oliverschwendener** [comment]
@krizajb Correct.

**Comment by ianpan870102** [comment]
Seconded. After I disabled "transparent background" for ueli, the flickering problem went away.
