### ISSUE TITLE
Command to put computer to sleep?

### ISSUE THREAD

**Issue by Keagel** [oliverschwendener/ueli#166]
I have noticed there are commands to Shutdown, Lock, Sign out, Restart but not to put the computer to sleep/hibernate. Could you implement that?

Thanks!

**Comment by oliverschwendener** [comment]
This will be included in the next release.

**Comment by oliverschwendener** [comment]
This is included in the newest [v8.0.0](https://github.com/oliverschwendener/ueli/releases/v8.0.0) release.

**Comment by maku** [comment]
@oliverschwendener Is there also a command for "hibernation" (Ruhezustand)

**Comment by oliverschwendener** [comment]
@maku Not at the moment => Create new issue for this please.

**Comment by sashaweiss** [comment]
Is there a way to "Sleep" a Mac as well? I typically use my machine in clamshell mode connected to monitors, and like to sleep it when I walk away (rather than just lock) to preserve power.

Thanks in advance for any advice!
