### ISSUE TITLE
Custom search engine icon too big

### ISSUE THREAD

**Issue by xXKeyleXx** [oliverschwendener/ueli#167]
When I set a custom SVG for a websearch engine and the icon is bigger than the expected size, the icon will be as big as it is defined in the svg options.

![npm](https://user-images.githubusercontent.com/631504/62999803-ceb31180-be6f-11e9-83aa-6f141a2d072a.png)

[ueli.config.json.zip](https://github.com/oliverschwendener/ueli/files/3500141/ueli.config.json.zip)

**Comment by oliverschwendener** [comment]
Thanks for the feedback! This is fixed in [v8.0.1](https://github.com/oliverschwendener/ueli/releases/v8.0.1)
