### ISSUE TITLE
On ueli show random flicker/flash of the launcher

### ISSUE THREAD

**Issue by krizajb** [oliverschwendener/ueli#169]
On ueli show it looks like the launcher is being opened twice. Same happened on the previous version, updated it and the issue persisted. The issue can be reproduced by hotkeys or manually via system tray (show button).
This does not happen on every show.

**Comment by krizajb** [comment]
Sorry, didn't see this bug was already reported [issue-160](https://github.com/oliverschwendener/ueli/issues/160). Closing the issue.

**Comment by ianpan870102** [comment]
I ran into the same issue, but after I disabled "transparent background" for ueli, the flickering problem went away.
