### ISSUE TITLE
[Feature Request] Browse folders with arrow keys

### ISSUE THREAD

**Issue by matthacksteiner** [oliverschwendener/ueli#176]
It would great to use the arrow keys to move around the folder structure.

**Comment by matthacksteiner** [comment]
> You can use the arrow key to move up or down in the search result list. Use tab to autocomplete and jump into the highlighted folder. Does this solve your issue?

Sorry for the late answer. I meant "file system browsing".

For example: I search for documents -> then I hit tab ( or the right arrow key) and see all folders inside of document -> then I can go even further into another folder... To go a up in folder I hit the up arrow key...

**Comment by oliverschwendener** [comment]
A fix for this is included in the latest release.
