### ISSUE TITLE
Error when adding additional folder to "application folders"

### ISSUE THREAD

**Issue by floele-sp** [oliverschwendener/ueli#177]
The following error is displayed when adding a folder to the application folder (Settings --> Application Search --> Add application folder):

{ "code": "EPERM", "errno": -4048, "level": "error", "path": "C:\\Sandbox\\Trunk\\System Volume Information", "service": "user-service", "syscall": "lstat", "timestamp": "2019-08-20T10:46:03.441Z" }

I installed Ueli for the first time on Windows 10 Build 1809. I tried adding different folders and even a folder from a different drive without success.

![grafik](https://user-images.githubusercontent.com/15671468/63341281-28707b80-c349-11e9-9175-a4977800deb1.png)

**Comment by pickbreaker** [comment]
I've got similar issues on directories where the user has insufficient rights. Ueli will stop indexing if a single subfolder or file is inaccessible.

**Comment by AquilaRapax** [comment]
Same here, but with errno : -4058

**Comment by oliverschwendener** [comment]
Is this still an issue in the [newset](https://github.com/oliverschwendener/ueli/releases/latest) version?

**Comment by AquilaRapax** [comment]
No, at least I don't have this issue anymore.

**Comment by oliverschwendener** [comment]
Closing this issue now because it seems to be resolved.
