### ISSUE TITLE
Protocols other than http are not possible in "Web Search"

### ISSUE THREAD

**Issue by TheStruggleForAntiSpaghetti** [oliverschwendener/ueli#178]
In another application, I now have setup searching a query in the Deezer app by using:
deezer://www.deezer.com/search/{query}
 
When trying to configure this url in ueli, I get the error:
"Invalid web search engine"
 
I'd like for this to be possible.

**Comment by oliverschwendener** [comment]
Thanks for your feedback! I'll look into this.
