### ISSUE TITLE
Windows .zip portable version has no settings and shows errors on access

### ISSUE THREAD

**Issue by Spiegel-Leser** [oliverschwendener/ueli#179]
I tried Ueli the first time today with the .zip portable version, 8.1.0., on Win 7 x64. It starts and functions correctly. On entering "setting", it offers "Ueli settings" -> no reaction, and "edit Ueli settings" -> error message. Is this the desired behaviour? Can I edit Web search engines only in the installed version? Or is it a bug?

**Comment by oliverschwendener** [comment]
This is not intended behaviour. I'll look into this as soon as possible! Thanks for your feedback!

**Comment by oliverschwendener** [comment]
@Spiegel-Leser Could not reproduce your issue. Can you tell me where did you unpack the zip? Maybe in a folder where the app does not have enough access rights?

**Comment by Spiegel-Leser** [comment]
My reply wasn't posted, for some reason. So, I also couldn't reproduce it. Please Close this. Thx.
