### ISSUE TITLE
I cant set up the es.exe as when i do it doesnt work and there is no help anywhere else....pls help:(

### ISSUE THREAD

**Issue by ChitDaBoss** [oliverschwendener/ueli#181]
i set it up to the es application in my c drive....users.....chitr.... .ueli.....es.exe and it wont work:(

**Comment by oliverschwendener** [comment]
Is there something in the debug log?

Open settings -> General -> Open debug log

![image](https://user-images.githubusercontent.com/15727229/63753570-9968e380-c8b3-11e9-86c6-0c51d0d3bd75.png)

**Comment by ChitDaBoss** [comment]
oh wait i just figured it out....i forgot to put the es? before searching.....sorry for bothering you :(
