### ISSUE TITLE
Everything search doesn't find any results

### ISSUE THREAD

**Issue by atresnjo** [oliverschwendener/ueli#184]
My attempt:
![grafik](https://user-images.githubusercontent.com/41112852/63922810-b0d7d600-ca45-11e9-9369-68b362086262.png)

Settings: 
![grafik](https://user-images.githubusercontent.com/41112852/63922930-ed0b3680-ca45-11e9-8b6d-6cd92b47355d.png)

Using es.exe from cli:
![grafik](https://user-images.githubusercontent.com/41112852/63923019-14fa9a00-ca46-11e9-965a-f06d94ea10f8.png)

**Comment by oliverschwendener** [comment]
You have to activate the plugin on the top right.

![image](https://user-images.githubusercontent.com/15727229/63927888-e1703d80-ca4e-11e9-958a-9da7d5d80e83.png)

**Comment by atresnjo** [comment]
Jesus. I am sorry for missing the obvious, thank you for the great tool!
