### ISSUE TITLE
Search Window Closes Only After Delay

### ISSUE THREAD

**Issue by sgruetter** [oliverschwendener/ueli#185]
When opening an application, I type the name, see quickly the correct search result, and then hit Enter.

Now 

- the search field gets emptied and, after probably 500 ms,
- the search window gets hidden.

This delay until the the search disappears is a bit annoying. I know, not really a big issue 😄

See in the video: when "sla" disappears, I just hit Enter. A bit later, the entire window gets hidden.

![openafterdelay](https://user-images.githubusercontent.com/30778657/63992330-99532880-caeb-11e9-99a1-d73b6bd95292.gif)

Is there a reason for the delay? Otherwise I offer to look into this, if it's fine with you, @oliverschwendener.

**Comment by oliverschwendener** [comment]
Strangely this seems to appear only on macOS and only after the app is being packaged. When I run the app in development mode, then this delay does not appear.

**Comment by cosimochellini** [comment]
I noticed this problem also on Windows 10

**Comment by natyusha** [comment]
This seems to happen for me when opening most programs on Windows 10 as well.
