### ISSUE TITLE
Feature request: Add local images rather than SVG or color for "Shortcuts"

### ISSUE THREAD

**Issue by TobiasDev** [oliverschwendener/ueli#187]
I love setting up my own shortcuts in Ueli for different Websites I want to quickly reach, or software. However, I would like to add my own PNG image rather than a SVG file (since I can't always get a hold of those). Is that something that could be added? So I could add a local image rather than a SVG, URL or Color?

**Comment by MonstraG** [comment]
I'm able to do that using URL, but entering local absolute address.

**Comment by oliverschwendener** [comment]
You cann add local images like this: select icon type **URL** and then for the url add this:
```
file://<here the file path to your image>
```

For example on macOS:
```
file:///Users/oliverschwendener/Pictures/my-picture.png
```

or on Windows:
```
file:///C:/Users/oliverschwendener/Pictures/my-picture.png
```
