### ISSUE TITLE
Convert temperature

### ISSUE THREAD

**Issue by LalaGhost** [oliverschwendener/ueli#190]
It would be nice to convert from Fahrenheit to Celsius and vice versa.
The question is how you want to do it:
Option 1: "40°F to C°"
Option 2: "40F to C"
Note the degree symbol.
Maybe both?

**Comment by oliverschwendener** [comment]
You can to this already with these units:

**K**: kelvin 
**degC** celsius
**degF**: fahrenheit
**degR**: rankine

for example type in this: `100 degF to degC`
