### ISSUE TITLE
Command for "hibernation"

### ISSUE THREAD

**Issue by maku** [oliverschwendener/ueli#191]
It would be really great if there was a command for hibernation...
Could you implement that?

**Comment by Maltbrew** [comment]
I don't have the Hibernation feature in 8.1.2 unfortunately.

**Comment by maku** [comment]
@Maltbrew - hibernation works for me perfectly fine (win 10)

**Comment by oliverschwendener** [comment]
@Maltbrew Are you on Windows? And which language did you select in ueli?

**Comment by Maltbrew** [comment]
I am yes, on Win 10. I selected English.

**Comment by oliverschwendener** [comment]
Did you turn on the operating system commands plugin?

**Comment by Maltbrew** [comment]
Aah! That's the ticket! 

Thank you!
