### ISSUE TITLE
Everything settings path does not work with whitespace

### ISSUE THREAD

**Issue by GitBiker** [oliverschwendener/ueli#194]
Everything within ueli does not work if the path to es.exe contains a whitespace.

From the log:
2019-09-18T06:20:40.810Z error: Command failed: ""C:\Program Files\ES\es.exe"" -max-results 24 test
'""C:\Program' is not recognized as an internal or external command,
operable program or batch file.

**Comment by oliverschwendener** [comment]
What version of ueli are you running?

**Comment by GitBiker** [comment]
ueli 8.1.2

**Comment by oliverschwendener** [comment]
We had a similar issue here: https://github.com/oliverschwendener/ueli/issues/172

I thought it was fixed, but apparently it is not. Will look into this asap.

**Comment by WonaBee** [comment]
I had the exact same error in the debug log, I fixed it by choosing the es.exe once again (and not inputting the path directly) and clicking the save button.

I believe this had something to do with me importing the config from the previous version and it saving the quotes in the path.

**Comment by GitBiker** [comment]
You're right. It has nothing to do with the whitespace.
The quotes in the path are not allowed (I read in some previous issue that quotes are required).
Selecting the path through the file dialog works.
