### ISSUE TITLE
Prevent window to hide after execution

### ISSUE THREAD

**Issue by gr0undhog** [oliverschwendener/ueli#195]
Hello together, 

nice app!, very useful and of course my new <3 app! it makes things so simple!

is there a way to fix the app on windows desktop instead of closing it after pressing enter? its okay to loose focus and get back with Alt+Space.

thanks # #

**Comment by oliverschwendener** [comment]
Open the settings (`Cmd+,` on macOS or `Ctrl+i` on Windows) and disable the option "Hide window when focus is lost" in the General settings:

![image](https://user-images.githubusercontent.com/15727229/65258356-0c582980-db03-11e9-9264-08c002ec4237.png)

**Comment by gr0undhog** [comment]
Thanks oliver,

setting is disabled but unfortunately the search field hides anyway after pressing enter. is that a bug or am i doing something wrong?

so e.g. opening with shortcut, typing "chrome", pressing enter -> Searchfield hides (closes), Chrome starts

**Comment by oliverschwendener** [comment]
Ok I see your problem now. You want the main window to stay openend after you execute stuff (open programs, etc.), is that correct?

**Comment by gr0undhog** [comment]
> Ok I see your problem now. You want the main window to stay openend after you execute stuff (open programs, etc.), is that correct?

correct

**Comment by oliverschwendener** [comment]
Will look into this asap

**Comment by gr0undhog** [comment]
> Will look into this asap

yery cool, thanks so much
