### ISSUE TITLE
Add web search engine always invalid

### ISSUE THREAD

**Issue by Spiegel-Leser** [oliverschwendener/ueli#196]
I'm not able to add a new search engine. The message is just "invalid", no explanation to what is the problem.

See screenshots
![Invalid](https://user-images.githubusercontent.com/31407409/65305842-60572280-db84-11e9-8add-c921c1847928.png)
![Invalid2](https://user-images.githubusercontent.com/31407409/65305843-60efb900-db84-11e9-988f-f1e51f53bc53.png)

Happens in Ueli 8.1.2 portable on Windows 7 x64.

**Comment by oliverschwendener** [comment]
I see it's a little annoying that there is not a precise error message. I should look into this.

Anyway: you can remove all the double quotes and then it should work.
