### ISSUE TITLE
[feature request] Add dictionary search

### ISSUE THREAD

**Issue by ZackaryNisbet** [oliverschwendener/ueli#200]
Hello! I used to use spotlight everyday on my MacBook Air and since switching over to windows I've been looking for a replacement. Ueli is definitely the best out there, but there's one feature I'm absolutely unable to live without and I would love for it to be added if it isn't already. 
![7Loux7K2Vv](https://user-images.githubusercontent.com/55851584/65711969-0367da80-e064-11e9-991c-37c81ba190e7.png)
Is there anyway Ueli can show me the definition of a word without clicking enter? I often come across words I'm not familiar with and like to quickly define them without changing the window or tab I'm currently on.

**Comment by ZackaryNisbet** [comment]
Just to be more specific with my request, I decided to design something that represents it.
![Ueli Dictionary Search Example](https://user-images.githubusercontent.com/55851584/65713075-5e9acc80-e066-11e9-8089-63c8a1eeae15.png)

Obviously I didn't crop the foreground to fit the design LOL but this is what I mean. I'd like to be able to access Euli's search, get a definition of a word, then quickly deactive it after I see the result. This would be super helpful!

**Comment by oliverschwendener** [comment]
Startet working on a dictionary plugin. This is how it looks like so far:

![image](https://user-images.githubusercontent.com/15727229/66461269-f0e49c80-ea78-11e9-9c9a-d14f24c2289e.png)

Of course the prefix `dict?` can be defined by the user. You can also change this to `define ` if you want to.

**Comment by ZackaryNisbet** [comment]
Thank you! I'm excited to have access to this; when do you think you'll release it?
What service are you using to provide the definitions? Google dictionary?
Lastly, is there any chance you'd be able to format the search results to be organized and provide a view of the full definition? Something similar to how it is on MacOS perhaps:
![usingmacspotlight6-5c61746e46e0fb0001f25082](https://user-images.githubusercontent.com/55851584/66490190-c269c000-ea7e-11e9-8a4e-9950a889cf46.jpg)
Keep me updated; I love this software :)

**Comment by ZackaryNisbet** [comment]
Can't wait to see how this software develops; maybe you'll create the "Alfred" equivalent software for Windows! 
I don't know anything about coding, but I'd be eager to help out in anyway I can. If you ever need someone to test a beta software/plugin I'd be happy to.
Honestly if you manage to add a preview feature, improve the overall organization of search results and have a fully functioning dictionary similar to the one on MacOS, improve the GUI a little, I'd literally pay $50 for that for life lol. I'm sure others would too. Your software could become a staple in people's workflow.

**Comment by oliverschwendener** [comment]
Added in the newest [release](https://github.com/oliverschwendener/ueli/releases).
