### ISSUE TITLE
Change Terminal on Windows

### ISSUE THREAD

**Issue by 4ern** [oliverschwendener/ueli#201]
It would be nice if you could change the terminal, for example to powershell or bash.

**Comment by oliverschwendener** [comment]
I added an option to switch between cmd and Powershell. You can access it in the commandline plugin options:

![image](https://user-images.githubusercontent.com/15727229/71764230-5ebc2b00-2ee5-11ea-899e-7dd431013d4d.png)

**Comment by alanaasmaa** [comment]
It would be create to include Ubuntu(wsl) when installed. or maybe custom shell like Hyper.js

**Comment by firinael** [comment]
I use Hyper.js so having it as a choice of shell is super important to me.
