### ISSUE TITLE
Encoding problems in general

### ISSUE THREAD

**Issue by MonstraG** [oliverschwendener/ueli#203]
I've seen the #175 issue, and I have the same issue, but I'm not using Everything search.
![image](https://user-images.githubusercontent.com/17963791/66182518-dbddc700-e68e-11e9-9f4f-8f5e899e1071.png)

(Actual name of that file is "ASD123фапфщпыдлпфы.exe")

**Comment by cpkio** [comment]
I confirm this behaviour.

**Comment by oliverschwendener** [comment]
Fix should be available in the newest release.
