### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by Tarik02** [oliverschwendener/ueli#204]
Hello. I am going to make my own launcher like ueli and I would be happy to use some styles from ueli. May I use it in order to make themes from ueli compatible with my launcher (of course leaving like to ueli)?

P.S. I am going to release my launcher's source under MIT license.

**Comment by oliverschwendener** [comment]
Sure, no problem! Make sure to reach out to me when you release it, I would be interested to have a look at it ;)

**Comment by Tarik02** [comment]
@oliverschwendener Okay! Thank you and have a good day!
