### ISSUE TITLE
More unity conversions[feature request]

### ISSUE THREAD

**Issue by LalaGhost** [oliverschwendener/ueli#205]
I would like to see more unit conversions, like from ounces to litre and stuff like that.

**Comment by oliverschwendener** [comment]
1. Enable Calculator plugin
2. Type in `100l in floz`
3. Et voilà

**Comment by LalaGhost** [comment]
Did not know that floz existed.

**Comment by oliverschwendener** [comment]
Here is a list of the available units: https://mathjs.org/docs/datatypes/units.html#reference
