### ISSUE TITLE
[WIN] Default Tool for Simple Folder Search

### ISSUE THREAD

**Issue by leik-software** [oliverschwendener/ueli#206]
Hi!
Thank you for this great tool! I am using an alternative file explorer on Windows: Directory Opus. But ueli opens folder with default windows file explorer. Is there a way to change this behaviour?

**Comment by oliverschwendener** [comment]
No currently you can't change this. I'll mark this issue as feature request.

**Comment by chmielciu** [comment]
I just did it cause i am in exactly same situation.
You need to amend 3 files, then bundle and package.
Three files are in src/main/executors:

- src\main\executors\file-path-executor.ts

- src\main\executors\file-path-location-executor.ts

- src\main\executors\url-executor.ts

Just remove implicit call to explorer in windows commands in these files.
The only thing is that, all paths are in quotation so you need to add extra empty parameter, as first thing in quotation will be treated as window title.

Like so: 

![image](https://user-images.githubusercontent.com/11930016/68370812-9ef96a00-013d-11ea-8724-d6dd9b0d6a12.png)

I also added extra regex replace removing filename from path in path-location-executor, where /select was before. 
![image](https://user-images.githubusercontent.com/11930016/68370929-dc5df780-013d-11ea-90cc-4d4f6ad3d920.png)

I did it all literally in 15 mins so it might be good idea to check if there is no better way.
Nevertheless this has been working for me without an issue (so far after 45 mins) ;)

**Comment by oliverschwendener** [comment]
Thanks for your contribution!

1. I think, when we add this we will introduce this bug again: #42. Therefore not sure if this is the right way to do it.
2. If you remove the `/select` the file won't be selected when opening the file location.

**Comment by oliverschwendener** [comment]
@leik-software @chm-dev Is there a way to change the default file browser in the windows settings?

**Comment by Otiel** [comment]
@oliverschwendener Any chance to see this implemented? For those using an alternative Explorer (XYplorer, Directory Opus, Explorer++...), it's not pleasant to use Simple Folder Search which opens results in Windows Explorer.

**Comment by mididev** [comment]
I'd love to see this implemented as well. I've been using Total Commander since I'm 10 years old and never really used Explorer. But I'd like to use Simple Folder Search as it's an incredibly useful tool. An option for an alternative command prompt would be awesome.

For example, to open a specific folder in an already open instance of Total Command, I need to run:

C:\Program Files (x86)\totalcmd\totalcmd.exe /O [foldername]

This would make Simple Folder Search even more powerful.

**Comment by mididev** [comment]
@chm-dev Did you encounter any issues with your approach since you made this addition (4 years ago)?

**Comment by oliverschwendener** [comment]
The progress of the feature request "change default file explorer" will be tracked here: #1069
