### ISSUE TITLE
Issue: Can't search and open Whatsapp Desktop on Windows 10

### ISSUE THREAD

**Issue by eternalcakes** [oliverschwendener/ueli#207]
As noted. All fresh install.

**Comment by oliverschwendener** [comment]
Did you install Whatsapp Desktop with the Microsoft Store?

**Comment by eternalcakes** [comment]
Yep. Uninstalled and installed from Internet now. Resolved and working!

**Comment by oliverschwendener** [comment]
Due to technical reasons ueli is currently not able to search UWP apps (apps installed with the microsoft store).

**Comment by oliverschwendener** [comment]
Proper UWP support is now added in the latest release.
