### ISSUE TITLE
[Feature Request] Filter shortcuts

### ISSUE THREAD

**Issue by KryptonicDragon** [oliverschwendener/ueli#208]
It'd be nice if I could, say, prevent any shortcuts with the word "uninstall" in their title from showing up in search results.

**Comment by oliverschwendener** [comment]
I added the option to filter out items in the search engine options.

1. Open the settings
2. Got o search engine options
3. Add keywords in the blacklist option

![image](https://user-images.githubusercontent.com/15727229/71764243-91662380-2ee5-11ea-9ed5-28847a48086f.png)

**Comment by bee-eater** [comment]
I have tried this feature with the latest version (where can I see the version???? xD)
I added AutoHotkey.exe to the blacklist, still I see a looooot of AutoHotkey results!
