### ISSUE TITLE
QUESTION

### ISSUE THREAD

**Issue by 0ANIMEFREAK0** [oliverschwendener/ueli#209]
### There are 2 things i want to ask

1. is there any mouse interaction option in version 8.2.0
`Because clicking on icon doesn't works scrolling works for me at least
and i can't find a option for mouse interactions on settings `

1. how do use transparent theme on this version 
`i enabled transparent background but how do u use the css file`

**Comment by oliverschwendener** [comment]
1. There is no mouse interaction supported in ueli version 8.x.
2. How to use transparent color themes:
    - Enable "Allow transparent background" in appearance settings
    - Go to color theme settings and add a color with transparency values
        - For example: `rgba(0,0,0,0.5)`
