### ISSUE TITLE
[Help Wanted] Trouble with Everything

### ISSUE THREAD

**Issue by LalaGhost** [oliverschwendener/ueli#211]
> This plugin enables you to use Everything search to find files and folders on your local file system. You have to install "Everything" and the "Everything Command-line Interface" from https://www.voidtools.com/downloads/. After installing both you have to specify the file path to 'es.exe' below.

This is the description of Everything in Ueli.
One small thing: You sometimes use 
' and sometimes ". Is it a mistake or intended? Maybe you want to make it equal.

Second:
Which es.exe should give Ueli the path to?
"*\Everything\es.exe"
or
"\Everything Interface\es.exe"
?

Ueli: 8.2.0
Electron: 5.0.9
Node: 12.0.0
V8: 7.3.492.27-electron.0

**Comment by oliverschwendener** [comment]
You have to point to "es.exe" from the commandline interface: https://www.voidtools.com/support/everything/command_line_interface/
