### ISSUE TITLE
Refreshing indexes

### ISSUE THREAD

**Issue by MetaMmodern** [oliverschwendener/ueli#214]
The program always shows Refreshing indexes and I can't use it when it refreshes. How to reduce the frequency of refreshing?

**Comment by oliverschwendener** [comment]
Search for "Settings" -> Press enter -> In "General" you can find the option "Periodic rescan enabled" which you can disable if you don't want ueli to do a periodic rescan. Additionally you can adjust the value of the rescan interval "Rescan interval (in seconds)":

![image](https://user-images.githubusercontent.com/15727229/69010273-612aeb80-095e-11ea-8865-4035a65946b6.png)
