### ISSUE TITLE
Search Windows settings

### ISSUE THREAD

**Issue by Waleedov** [oliverschwendener/ueli#215]
Is this already a feature? I can't find any results for settings.

![6Ny9xVC 1](https://user-images.githubusercontent.com/48418015/68744045-0b6be180-05f4-11ea-8dad-5cb13854b9c4.png)

**Comment by oliverschwendener** [comment]
Open the Settings with `ctrl+i` and activate the plugin "Operatin system settings".

![image](https://user-images.githubusercontent.com/15727229/69010303-a2230000-095e-11ea-8358-85aff9e2f9e8.png)

Search for "Display":

![image](https://user-images.githubusercontent.com/15727229/69010312-b2d37600-095e-11ea-919c-b41f3137c566.png)

Although there are alot of windows settings missing or with the wrong title. See #97 

I hope this solves your issue?
