### ISSUE TITLE
Powershell process spam

### ISSUE THREAD

**Issue by HVK500** [oliverschwendener/ueli#216]
Seems the powershell process issue has returned - [issue 71](https://github.com/oliverschwendener/ueli/issues/71)
Using version 8.2.0
![image](https://user-images.githubusercontent.com/14907718/69008164-1c985380-0950-11ea-8d94-f7a4ff5843f1.png)

**Comment by oliverschwendener** [comment]
Are you sure that these are running processes?

**Comment by HVK500** [comment]
Yup I took that image from process explorer, I did check task manager as well to be sure. The processes are running. I haven't tried the temp work around with disabling native icons.

**Comment by oliverschwendener** [comment]
I can't see a running powershell process in Windows Task Manager. I can see it coming up when icons are generated and then it quits after a short time (after icon generation is finished).

The powershell process will exit after it's finished.

See here the code:
https://github.com/oliverschwendener/ueli/blob/fe032e339d134e8181b33543fb394dab0f4c8a57/src/main/plugins/application-search-plugin/windows-app-icon-generator.ts#L57

**Comment by HVK500** [comment]
Thanks for the reference, I'll monitor it and see how it goes. Looking at the source it should be terminating, that is quite clear. Its an interesting one. I'll try see if I can cause the issue to occur. I'll feedback if I find anything.

**Comment by HVK500** [comment]
I managed to replicate it again, but not sure how. Did some tinkering and it may be related to this issue [node-powershell#81](https://github.com/rannn505/node-powershell/issues/81)

**Comment by HVK500** [comment]
Only way I've been able to replicate the issue is by waking my PC from sleep... Weirdly. I'm pretty sure it has to do with the issue [node-powershell#81](https://github.com/rannn505/node-powershell/issues/81).

**Comment by oliverschwendener** [comment]
Will close this issue until we know how to reproduce it.
