### ISSUE TITLE
Uninstaller is missing after installation (Windows)

### ISSUE THREAD

**Issue by chongyunxiang** [oliverschwendener/ueli#218]
I was playing around with the reindexing portion and when i changed the reindexing interval from 300s to 0s, Ueli immediately caused the whole computer to throttle due to it constantly reindexing.

I suggest setting a minimum reindexing interval.

I was searching for an uninstaller for Ueli when that happened, but luckily after a few restarts, I managed to set the interval back to 300.

Btw, where is the uninstaller? I'll still be using Ueli because its great.

**Comment by oliverschwendener** [comment]
I agree there should be a minimum interval of 10s or something like that. Will look into this asap.

To uninstall ueli just open "Apps & Features" in the Windows settings and search for "ueli" and select uninstall.

![image](https://user-images.githubusercontent.com/15727229/69010360-4a38c900-095f-11ea-901d-4ad5709d7dfc.png)

**Comment by chongyunxiang** [comment]
Yes, a min of 10s would be better. But anyway, I've felt that deactivating the reindex would be better, since it doesn't auto reindex on its own every X seconds, which will take up ram. Deactivating the intervals would mean it indexes if there are new document updates right?

Btw, I could not find the app to uninstall when I had the interval issue. After its fixed, the app still cant be found.

**Comment by oliverschwendener** [comment]
How did you install the app?

**Comment by chongyunxiang** [comment]
I downloaded the windows installer. Then also installed Everything and the es.exe.

It really is nowhere to be found but its running. I suggest to have an option to uninstall under the general setting in Ueli.

**Comment by oliverschwendener** [comment]
Open Windows Task Manager, go to "Details" find "ueli.exe", right click it and choose "open file location". This should open up the install location of ueli and there you should find an uninstaller. Nevermind, uninstalling ueli won't delete your user settings. The settings are stored in this file: `%APPDATA%\ueli\config.json`. Open this file with nodepad and replace the value of `rescanIntervalInSeconds` to your desire.

**Comment by MetaMmodern** [comment]
> I agree there should be a minimum interval of 10s or something like that. Will look into this asap.
> 
> To uninstall ueli just open "Apps & Features" in the Windows settings and search for "ueli" and select uninstall.
> 
> ![image](https://user-images.githubusercontent.com/15727229/69010360-4a38c900-095f-11ea-901d-4ad5709d7dfc.png)

i think it would be better, if you make smth like autorescan, which works only when ueli is not opened and visible. You've closed my last issue, ok, thanks, that helped me. But it won't update the search results in that case. Maybe you can make it not refresh and rescan when i'm typing or searching smth, cause just before I started writing tis response ueli showed me next
![image](https://user-images.githubusercontent.com/42899786/69013493-4752ce00-0989-11ea-9555-db7f7d0e0985.png)

**Comment by chongyunxiang** [comment]
![Uninstaller Missing](https://user-images.githubusercontent.com/57867863/69019775-02608300-09ed-11ea-8471-960ba0cfce98.png)

This is what I found when I opened the File Location. Maybe you could send me the uninstaller so I could add it into the folder. I'd also suggest having an option to uninstall under the General tab in Ueli, just in case there're other users with missing uninstallers or app.

It would also be good for the reindex not to happen when the search is open. Otherwise it'll interrupt the search experience.

**Comment by oliverschwendener** [comment]
If you don't have an uninstaller in the install location, I guess something went wrong during the installtion. No I won't add an uninstall option in the UI because there is no way to determine how the app was installed in the first place.

I won't change the reindex behaviour either because you can adjust the reindex options to your needs. I use ueli on every day and barley never see the "reindexing" message with the default options of running the reindex every 5min.

Because this thread now mainly is about the uninstaller I renamed this issue and created a new issue for the minimum reindex interval value: #221.

**Comment by oliverschwendener** [comment]
Make sure ueli is not running (if you cant quit ueli via the tray icon with right click => "Quit" then open Windows task manager and kill the process). Try reinstalling ueli in the same location and check again if there is no uninstaller. If there is still no uninstaller, try installing ueli in a different location.

**Comment by chongyunxiang** [comment]
Yes, this works. The uninstaller and the files are now available.
