### ISSUE TITLE
[Question] How did you build your UI?

### ISSUE THREAD

**Issue by LalaGhost** [oliverschwendener/ueli#219]
Hey Oliver,
I would like to know where exactly the file is where the code for the UI is and whether you created it with some program or just by coding? Other stuff like which libraries you used and which langauge I can probably figure myself out
Thanks :)

**Comment by oliverschwendener** [comment]
Ueli is built with [electron](https://electronjs.org/). Technologies used: HTML, CSS, TypeScript using Vue.js. Read [this](https://github.com/oliverschwendener/ueli#development) to start developing ueli. Most of the UI code is found here: https://github.com/oliverschwendener/ueli/tree/master/src/renderer

Does this answer your question?

**Comment by LalaGhost** [comment]
Yes, thanks a lot!
