### ISSUE TITLE
Dictionary's shortcut doesn't work!

### ISSUE THREAD

**Issue by callmehanu** [oliverschwendener/ueli#230]
I don't know why I can launch the dictionay

![image](https://user-images.githubusercontent.com/13230502/69173117-1ed3ec80-0acd-11ea-833a-e263a97f16ee.png)

**Comment by Lukentui** [comment]
Just remove a whitespace.
[Screenshots](https://imgur.com/a/ZPqv1Ui)

**Comment by oliverschwendener** [comment]
Yes, remove the whitespace
