### ISSUE TITLE
Everything plugin not working 

### ISSUE THREAD

**Issue by hdaasari** [oliverschwendener/ueli#233]
![everythingissue](https://user-images.githubusercontent.com/3305401/69519847-02c6c400-0f81-11ea-93c2-f7bff698edd2.gif)

When entering any character after es? I am getting help for command line options

**Comment by oliverschwendener** [comment]
You have to download the everything commandline interface here: https://www.voidtools.com/downloads/

Unpack the ZIP to your desired location. In ueli you have to specify the path to the `es.exe` file that was extracted from the ZIP.

**Comment by hdaasari** [comment]
Yep that works!

Sorry I didn't look at the command line tools interface and downloaded the installer
