### ISSUE TITLE
Right click and open file location

### ISSUE THREAD

**Issue by chongyunxiang** [oliverschwendener/ueli#234]
Is there a way to open the file location? If there isn't, can it be implemented?

**Comment by Lukentui** [comment]
Are you tried to press enter?

**Comment by oliverschwendener** [comment]
Here is the documentation for keyboard shortcuts:
https://github.com/oliverschwendener/ueli#keyboard-shortcuts

Press <kbd>Ctrl</kbd><kbd>o</kbd> on Windows or <kbd>Cmd</kbd><kbd>o</kbd> on macOS to open the file location.
