### ISSUE TITLE
Rescan

### ISSUE THREAD

**Issue by chongyunxiang** [oliverschwendener/ueli#235]
I've turned off periodic scan on ueli.
Installed new softwares for my work, but ueli can't find it until I open up the settings and do the scan myself.

Would it be possible not to have a scan each time a new document or file is available on the computer? The reason I turned off the periodic scan is because I've encountered multiple times, when I bring up Ueli, it suddenly says Re-indexing. Then I wont be able to search until it's done.

I don't think the mac spotlight has this issue and would love to see it in ueli.

Thanks!

**Comment by oliverschwendener** [comment]
Related to #242

**Comment by oliverschwendener** [comment]
This should be solved now with the latest update.
