### ISSUE TITLE
Russian to English translation not working

### ISSUE THREAD

**Issue by areg1998** [oliverschwendener/ueli#238]
![Action 01-12-2019 13-51-06](https://user-images.githubusercontent.com/34375489/69912356-bc220f80-1441-11ea-9b41-a4e5c5a8ed78.gif)

**Comment by oliverschwendener** [comment]
What happens if you just wait a little longer?

**Comment by oliverschwendener** [comment]
Ok, I checked it myself. This seems to be a bug. I'll look into this as soon as possible! Thanks for reporting!

**Comment by oliverschwendener** [comment]
This should be resolved with the DeepL Translator extension in v9. You can try out the beta release here: https://github.com/oliverschwendener/ueli/releases

![image](https://github.com/oliverschwendener/ueli/assets/15727229/2f948153-ce41-4fd3-8239-5f33c4a395f2)
