### ISSUE TITLE
Make use of Vue single file components

### ISSUE THREAD

**Issue by oliverschwendener** [oliverschwendener/ueli#241]
The objective of this task is to move current code from this:

example-component.ts
``` typescript
export const exampleComponent = Vue.extend({
    template: `<div>...</div>`,
});
```

to this:

example-component.vue
``` vue
<template>
    <div>
        ...
    </div>
</template>

export default Vue.extend({
});
```

**Comment by usernamehw** [comment]
If you're using VSCode as a primary editor this change might make working with vue files easier (template part), since extension `vetur` has some features working for SFC, like hover/go to definition/autocomplete. (with `vetur.experimental.templateInterpolationService` enabled).

**Comment by freedsny** [comment]
Create an official youtube channel, for the Ueli app, suo tutorials and updates, if possible also in Spanish, because there aren't many videos on youtube about ueli

**Comment by oliverschwendener** [comment]
Implemented in [beta/ueli-9](https://github.com/oliverschwendener/ueli/tree/beta/ueli-9)
