### ISSUE TITLE
application icons not loading

### ISSUE THREAD

**Issue by sid176** [oliverschwendener/ueli#243]
Application icons are not loading in the search.
![image](https://user-images.githubusercontent.com/11403343/70233690-15ad7580-1785-11ea-82d6-71c326e44d93.png)

Ueli version : 8.4.0
Electron : 5.0.9
Node : 12.0.0
V8 : 7.3.492.27-electron.0

error while refreshing application search : 
{ "level": "error", "name": "PS_CMD_FAIL_ERROR", "service": "user-service", "timestamp": "2019-12-05T12:03:09.110Z" }

debug logs : 
[ueli_logs.txt](https://github.com/oliverschwendener/ueli/files/3926717/ueli_logs.txt)

**Comment by krizajb** [comment]
Can confirm having the same issue after the update.

**Comment by AmrBinBashir** [comment]
same here

**Comment by AmrBinBashir** [comment]
the problem is described [here](https://github.com/oliverschwendener/ueli/issues/202#issuecomment-561682128) but the given solution didn't work for me but I found another solution to make powershell use unicode utf-8:
1- Run `intl.cpl` (which opens the regional settings in Control Panel).
2-Go to `Administrative` tab.
3-Click on `Change system locale..` in the right bottom corner.
4-Check the option called `Beta: Use Unicode UTF-8 for worldwide language support` and press OK
5-Restart Ueli and voilà.

**Comment by krizajb** [comment]
The icons are back with the proposed solution but unfortunately other problems arise not related to the ueli. For example the degrees (°) character is not displayed properly using the rainmeter program.

**Comment by AmrBinBashir** [comment]
@krizajb I didn't think of that, check my answer again, i edited it

**Comment by krizajb** [comment]
@AmrBinBashir Unfortunately it didn't work.

**Comment by AmrBinBashir** [comment]
@krizajb provide ueli logs and open powershell to see if it gives any errors upon launching it, if so paste the error here too.

**Comment by alefnull** [comment]
came to report this same problem, having just started noticing it myself. the described steps worked as intended for me. 👍

**Comment by oliverschwendener** [comment]
I added a fix in the newest version. Can you guys check if it works now?

1. Clear caches first:
![image](https://user-images.githubusercontent.com/15727229/71764210-24eb2480-2ee5-11ea-8882-56231cab10c6.png)

2. Then refresh indices:
![image](https://user-images.githubusercontent.com/15727229/71764215-30d6e680-2ee5-11ea-85b6-a3d494f5ebed.png)

**Comment by krizajb** [comment]
Still nothing, but my case might be an exception since even the above provided solution from @AmrBinBashir didn't work for me. Shall I try reinstalling?

**Comment by AmrBinBashir** [comment]
I can confirm the bug is solved, I reverted the steps i mentioned above and made sure i got the bug before updating to the newest version, after the update everything works fine.

**Comment by krizajb** [comment]
Reinstall didn't help. Let me know what I can do.

**Comment by oliverschwendener** [comment]
@krizajb Delete uelis temp folder `C:\Users\<your-username>\.ueli` and restart the app.

**Comment by krizajb** [comment]
No, this is content of debug.log:
```
2020-01-04T17:37:29.248Z debug: 0/200 app icons already exist
2020-01-04T17:37:29.249Z debug: Started to generate 200 app icons to C:\Users\blazk\.ueli\application-icons
2020-01-04T17:37:31.533Z error: 
      Exception calling "ExtractAssociatedIcon" with "1" argument(s): "Illegal characters in path."
At line:1 char:86908
+ ... leExists) { $icon = [System.Drawing.Icon]::ExtractAssociatedIcon("C:\ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentException
 
Exception calling "Save" with "2" argument(s): "Illegal characters in path."
At line:1 char:87081
+ ... leExists) { $bitmap = $icon.ToBitmap().save("C:\Users\blazk\.ueli\app ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentException
```

**Comment by krizajb** [comment]
I can confirm the latest build (8.5.0) fixed the issue for me.
