### ISSUE TITLE
Unable to start programms cause desktop path needs correction

### ISSUE THREAD

**Issue by Anis108** [oliverschwendener/ueli#245]
Thanks for this helpful application.

I mention this situation in case other people face this and don't understand how to solve it.

Right now the complet ueli program search is blocked on my system 
as long the desktop path is set to:
C:\Users\...\Desktop

On my system the desktop is stored in onedrive.
It worked after editing this manualy to:
C:\Users\...\OneDrive\Desktop

Error message came up after restore default setup:
Get-ChildItem : Der Pfad "C:\Users\...\Desktop" kann nicht gefunden werden, da er nicht vorhanden ist.
 In Zeile:1 Zeichen:186
 + ... Menu' | %{ Get-ChildItem -Path $_ -include *.lnk, *.appref-ms, *.url ...
 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 + CategoryInfo : ObjectNotFound: (C:\Users\...\Desktop:String) [Get-ChildItem], ItemNotFoundException
 + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
 

System: win pro 64bit system Ver. 1909 build 18363.476

ueli 8.4.1
Electron 5.0.9
Node 12.0.0
V8 7.3.492.27-electron.0

**Comment by oliverschwendener** [comment]
I don't think that `C:\Users...\Desktop` is a valid file path?

**Comment by Anis108** [comment]
Thanks for your attention and prompt response.
While entering the message here the path changed:

The standard setup "C:\Users\[my username]\Desktop" didn't work.

**Comment by bentmperez** [comment]
thanks I'm having the same issue

**Comment by oliverschwendener** [comment]
@bentmperez You probably added a very top level directory to the appliaction search settings. You shouldn't do that. You should only add directories that include the shortcut files. For example `C:\ProgramData\Microsoft\Windows\Start Menu\`.

@Anis108 Just open the settings, go to Application Search settings and remove the path `C:\Users\<username\Desktop` and add the correct desktop file path.

**Comment by bentmperez** [comment]
oh thanks that fixed the issue

**Comment by oliverschwendener** [comment]
Closing this issue because it wasn't really a bug.
