### ISSUE TITLE
no "context menu"

### ISSUE THREAD

**Issue by indexofrefraction** [oliverschwendener/ueli#246]
I found no other way to contact you, oliver,
therefore hijacking this for a feature request...

tested ueli on macos and its sleek and fresh !

the thing i really miss (and why i stay with my old launcher) is a context menu
ie. when i find my app or file i dont want to just open it
i also want to be able to reveal/show it in the finder, get info, trash it, etc etc
in quicksilver this is done by mode switch using tab after the item has been found
but could also work by using the text input ..
ie. find textedit by typing "text", then add an action like
"text?r" --> reveal, "text?i" --> info, "text?t" --> trash, etc

**Comment by oliverschwendener** [comment]
You can press `ctrl+o` (on Windows) or `cmd+o` (on macOS) to reveal the file in explorer/finder. Does this resolve your issue?

**Comment by indexofrefraction** [comment]
hey ;)

reveal ist mir tatsächlich mit abstand das wichtigste... 
insofern case closed würde ich sagen.

wirklich nicht schlecht die app, und das mit electron !

wie funktioniert der currency converter? da fehlt eine anleitung in der app
dito bei os commands/settings

gruss

**Comment by oliverschwendener** [comment]
Ok, I'll close this issue for now.

How to use the currency converter: https://github.com/oliverschwendener/ueli#currency-converter
