### ISSUE TITLE
Support for other Chromium browsers

### ISSUE THREAD

**Issue by chrislachance** [oliverschwendener/ueli#248]
Browser bookmarks seems to only detect Chrome on my machine. Using Brave (a Chromium browser) full-time, wasn't sure if Ueli could be extended to find Brave bookmarks also.

**Comment by oliverschwendener** [comment]
Do you know where Brave bookmarks are saved?

**Comment by chrislachance** [comment]
For Mac its '~/Library/Application Support/BraveSoftware/Brave-Browser/**/Bookmarks' I believe its something similar in Windows.

**Comment by chrislachance** [comment]
For Windows its 'C:\Users\USERNAME\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default\Bookmarks'

**Comment by irafaz** [comment]
I'd love to see support for Microsoft's new Edge browser, built with Chromium.

**Comment by oliverschwendener** [comment]
Support for Brave browser is included in the latest release.
