### ISSUE TITLE
Add a small banner to notify the user of an update pending

### ISSUE THREAD

**Issue by cosimochellini** [oliverschwendener/ueli#249]
I think that a useful thing to add is a small banner with something like "update available" that notify the use of a possible update to do.
maybe something positioned in a spot like this
![image](https://user-images.githubusercontent.com/24718181/70848964-175bf500-1e79-11ea-9bdb-015c0652fc0b.png)

**Comment by oliverschwendener** [comment]
As I plan to distribute ueli over the Microsoft Store in the future, this won't be needed.
