### ISSUE TITLE
Feature Request/Bump: Add custom folders to search

### ISSUE THREAD

**Issue by JACooper** [oliverschwendener/ueli#25]
Really impressed with this so far! I saw this in the roadmap "Add option to change folders which are being scanned for programs and files" and wanted to bump it - I have a number of programs (like VS Code) installed in non-default location that ueli can't find, and it would be **awesome** if I could just add that directory to the ones ueli searches in. Platform is Win 10.

**Comment by oliverschwendener** [comment]
Thanks for your feedback! I am working on it, this feature will be in the next release.
