### ISSUE TITLE
I can't search apps installed from Windows Store!

### ISSUE THREAD

**Issue by callmehanu** [oliverschwendener/ueli#251]
Yep, recently I installled Slack and Instagram from Windows Store, but I just realize that when I launch Ueli and star typping I can't find any of these apps.

**Comment by oliverschwendener** [comment]
At the moment it's not possible to search apps installed from the Windows store. See #46 or #38

**Comment by giacomontalti** [comment]
Hi @oliverschwendener, I know that you closed a lot of similar issues, but I notice that no one mention this command:

`explorer.exe shell:::{4234d49b-0245-4df3-B780-3893943456e1}`

That simply open a sort of explorer window with **all** the apps installed (also UWP).

Idk if this can be useful...

**Comment by LoZeno** [comment]
> `explorer.exe shell:::{4234d49b-0245-4df3-B780-3893943456e1}`

It has a more human readable version:
`explorer.exe shell:AppsFolder`

The problem, I think, is that it opens a specific view that belongs to `explorer.exe` and I am not sure it can be parsed programmatically.

**Comment by LoZeno** [comment]
To give a bit more context:
`shell:` commands, which can be run both through explorer.exe and through the `Run` applet in Windows 10, are commands that open specific views in windows 10 shell. You can find a long list of them here:
https://winaero.com/blog/list-of-shell-commands-in-windows-10/
They are not shortcuts to folders, but commands that activate specific UI windows that belong to the OS. So I doubt they can be useful for applications like UELI.

**Comment by oliverschwendener** [comment]
Proper UWP support is now added in the latest release.
