### ISSUE TITLE
UWP apps can't be detected 

### ISSUE THREAD

**Issue by AmrBinBashir** [oliverschwendener/ueli#252]
when i search for spotify i can't find it and other uwp apps that i installed.

**Comment by AmrBinBashir** [comment]
i kinda found a workaround by adding "C:\Program Files\WindowsApps" to Application Search Plugins and make ueli always start as administrator (not sure if this is necessary)
now i can see all of my store installed apps

**Comment by oliverschwendener** [comment]
See #46 and #38

**Comment by AmrBinBashir** [comment]
@oliverschwendener  how about my workaround/solution? i have tested it for a full day with different apps and it's working fine

**Comment by oliverschwendener** [comment]
I think your solution stays a **workaround** as long as it requires admin rights.

**Comment by oliverschwendener** [comment]
Proper UWP support is now added in the latest release.
