### ISSUE TITLE
How did you setup electron with vue.

### ISSUE THREAD

**Issue by AmrBinBashir** [oliverschwendener/ueli#254]
It's sort of a silly question but i would appreciate your answer, how did you setup your project with electron and vue, cause this [repo ](https://github.com/SimulatedGREG/electron-vue)uses node 8 and you are using node 12

**Comment by oliverschwendener** [comment]
There is nothing special to it. I use the latest vue version with webpack to bundle all together.

You can have a look at my electron-typescript-vue quickstart repo: https://github.com/oliverschwendener/electron-typescript-vue-quickstart
