### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by zohozer** [oliverschwendener/ueli#255]
Hi. As a multi-OS user, I am interested on finding a good launcher program that runs on all the three main OS-s (Mac, Windows, Linux) and Ueli seems to be a good candidate, the only downside seems to be the lack of Linux support?

Any chance to see a Linux build for this launcher? How dificult will be to adopt this launcher to the Linux ecosistem? This app it is writen using the Electron framework? If so, I think will be easier to make a Linux port? Thank you.

**Comment by oliverschwendener** [comment]
Thanks for your feedback! There is already a ticket for Linux support, see here: #94
