### ISSUE TITLE
Search window not remembering position when restarted on MacOS

### ISSUE THREAD

**Issue by zohozer** [oliverschwendener/ueli#256]
I just installed Ueli latest release version on my MacOS 10.14.6 and tested a little bit to check how behaves comparing with my LaunchBar6 and I do found some issues and possible feature requests.

When closing and starting again, Ueli seems to don't remember the position of the window. I set the window position to the very top of my screen, but if I do close the app and start again, the search window will be displayed at a lower position that the one I do setup. Seems that it is not remembering between sessions the position of the window.

**Comment by oliverschwendener** [comment]
This is intended. At the moment the app only remembers the window position within the current session. If you quit the app and restart the window will be shown in the center of the screen.
