### ISSUE TITLE
[Feature Request] Clipboard manager

### ISSUE THREAD

**Issue by zohozer** [oliverschwendener/ueli#257]
I am using the LaunchBar6 on MacOS and one of this nice features of this launcher is that has a clipboard manager built-in witch can be accessed with a shortcut and it is very handy.

It is possible to implement such a feature in Ueli?

<img width="646" alt="Screenshot 2020-01-04 at 12 23 03" src="https://user-images.githubusercontent.com/5983791/71764195-4c45ef80-2eed-11ea-9706-067ba46b9267.png">

**Comment by oliverschwendener** [comment]
There is already a ticket for a clipboard manager: #85 
Closing this because it is a duplicate.

**Comment by zohozer** [comment]
> There is already a ticket for a clipboard manager: #85
> Closing this because it is a duplicate.

Actually you closed both tickets. So no open ticket for a Clipboard manager in Ueli? This is a very useful feature. Please add a clipboard manager! Thank you.

**Comment by oliverschwendener** [comment]
Sorry my bad, didn't see that the other one was closed. Openin this as a feature request.

**Comment by oliverschwendener** [comment]
Don't know why I reopened this issue as #85 is still open. Closing this issue because it's a duplicate.
