### ISSUE TITLE
Translucent background option?

### ISSUE THREAD

**Issue by zohozer** [oliverschwendener/ueli#259]
I am trying to change the default theme of the Ueli and I would like to have a translucent background, so to see a little bit the background app through the Ueli launch window. It is possible to add a translucent feature for windows in Ueli?

**Comment by oliverschwendener** [comment]
1. Open settings
2. Go to appearance
3. Toggle the "Allow transparent background" option
4. Go to color theme options and add values with an alpha value, for example: `rgba(0,0,0,0.5)`
5. Restart ueli
6. Et voilà

**Comment by zohozer** [comment]
Thank you for the tip. It is working by changing the colour straight to RGBA format but the option to toggle transparency in Settings/Appearance it is missing.

<img width="1006" alt="Ueli_settings_MacOS_2020-01-04" src="https://user-images.githubusercontent.com/5983791/71767742-018d9d00-2f18-11ea-9b31-b2ae61b28331.png">

**Comment by oliverschwendener** [comment]
Ah you're on macOS. The allow transparent window option is only necessary for Windows.

**Comment by zohozer** [comment]
Ok. It is possible to add a translucent blurry effect? Transparent it is not the best effect IMHO.

**Comment by oliverschwendener** [comment]
At the moment this is not possible because electron does not support the transparent blur effect on Windows. See here: https://www.electronjs.org/docs/api/browser-window under "vibrancy".
