### ISSUE TITLE
Show google search suggestions in websearch plugin

### ISSUE THREAD

**Issue by AmrBinBashir** [oliverschwendener/ueli#265]
Is it possible to have google search suggestions in websearch plugin?

**Comment by oliverschwendener** [comment]
This is not possible at the moment.

**Comment by AmrBinBashir** [comment]
I did some research and there is already two npm modules which might help you when you decide to implement the feature:
https://github.com/eugeneware/suggestion
https://github.com/capablemonkey/google-autocomplete (I highly recommend this one)

**Comment by tmueller** [comment]
Maybe this can be generalized to other search plugins as well. Duckduckgo for instance uses `https://duckduckgo.com/ac/?q=${query}` for querying search suggestions.

**Comment by anoriqq** [comment]
How advanced is this feature?

**Comment by AmrBinBashir** [comment]
I think it is finished but waiting for oliver's approval.

**Comment by oliverschwendener** [comment]
This feature will be included in the next release.

![image](https://user-images.githubusercontent.com/15727229/96371783-d7823000-1163-11eb-8f2b-a31bc8b19f25.png)
