### ISSUE TITLE
Is it possible to prioritize apps to show higher in the list.

### ISSUE THREAD

**Issue by AmrBinBashir** [oliverschwendener/ueli#266]
In Wox, they had an option to called "make topmost in this query", i would like to see this feature but it's fine if it's not possible

**Comment by oliverschwendener** [comment]
Ueli automatically detects which apps you use the most and lists them higher. Is that what you are looking for?

**Comment by AmrBinBashir** [comment]
Yeah I know that,Its cool but would be better if i can just do it manually cause ueli takes sometime to kick in when i have a new app installed. doing it manually would be just accelerate the process.
