### ISSUE TITLE
cannot get application alias item on macos

### ISSUE THREAD

**Issue by zarzen** [oliverschwendener/ueli#268]
Hi,
my emacs was installed through homebrew, which creates an application alias instead of an emacs.app at `/Application` folder. `ueli` cannot get the emacs alias for me. 

emacs installation command: 
```
$ brew tap d12frosted/emacs-plus
$ brew install emacs-plus
$ brew linkapps emacs-plus
```

`ueli` search result screenshot:
<img width="610" alt="Screen Shot 2020-01-20 at 10 04 45" src="https://user-images.githubusercontent.com/1150493/72736793-5bbf6c80-3b6c-11ea-8158-ea5d2bebd872.png">

**Comment by oliverschwendener** [comment]
Can you find the alias with mac's build int Spotlight search?

**Comment by zarzen** [comment]
@oliverschwendener yes, spotlight in MacOS Catalina can. But I think spotlight of Mojave cannot

**Comment by zarzen** [comment]
BTW, ueli cannot find `dictionary app` as well. 
Here is the screenshot:
<img width="610" alt="Screen Shot 2020-01-21 at 15 04 50" src="https://user-images.githubusercontent.com/1150493/72839009-7d4d5080-3c5f-11ea-9485-9cdb8fd9ddc8.png">

**Comment by oliverschwendener** [comment]
@zarzen Can you show me your application search settings?

To open the settings search for "settings" and press enter:

<img width="610" alt="image" src="https://user-images.githubusercontent.com/15727229/72875537-c3a0bf00-3cf4-11ea-8536-b0901f3e2c9f.png">

Then navigate to "Application Search":

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/15727229/72875586-dadfac80-3cf4-11ea-9811-1d09f37ac6d8.png">

**Comment by zarzen** [comment]
<img width="992" alt="Screen Shot 2020-01-22 at 12 53 11" src="https://user-images.githubusercontent.com/1150493/72919837-2b1b3680-3d16-11ea-8d62-9874148db325.png">
@oliverschwendener

**Comment by oliverschwendener** [comment]
@zarzen Try adding `/System/Applications` to the folders.

**Comment by zarzen** [comment]
@olivereisenhut 
Dictionary app issue fixed. While the Emacs-alias issue is still there

**Comment by oliverschwendener** [comment]
@zarzen Do you know where your missing Application is installed?

**Comment by zarzen** [comment]
`/usr/local/Cellar/emacs-plus/`
After adding `/usr/local/Cellar/` it works fine.
