### ISSUE TITLE
[Windowd 10] keystroke blinks

### ISSUE THREAD

**Issue by yratanov** [oliverschwendener/ueli#270]
From time to time keystroke blinks on open. Please see video below.

https://www.dropbox.com/s/trxjnwwcsz2hkbq/wldrWPjkMv.mp4?dl=0

ueli
8.5.0
Electron
5.0.9
Node
12.0.0
V8
7.3.492.27-electron.0

**Comment by oliverschwendener** [comment]
I guess you have the option "Allow transparent background" in the Appearance settings enabled?

**Comment by yratanov** [comment]
@oliverschwendener yes, if I turn it off, blinking doesn't happen.

PS: I also noticed that this setting doesn't change anything (bg is not transparent), or I can't notice it.

**Comment by oliverschwendener** [comment]
Then I consider this as resolved.

In order to get a transparent background you have to activate the option "allow transparent background" and then add a transparent color in the color theme settings.

**Comment by yratanov** [comment]
@oliverschwendener I think it's still a bug, that when "allow transparent background" is enabled, keystroke blinks.

**Comment by oliverschwendener** [comment]
This is a bug in [electron](https://github.com/electron/electron) (only on Windows) and I can't do anything about this. This is why the option to disable a transparent background is there.
