### ISSUE TITLE
Application search not working - help

### ISSUE THREAD

**Issue by alitarraf** [oliverschwendener/ueli#272]
Searching applications is not working, Ueli cant seem to find them for some reasons, although i added the relevant folders. See my screenshots below. I am on a Windows 10 Pro machine.

![ueli](https://user-images.githubusercontent.com/21084320/73000006-e7552980-3e08-11ea-8e4c-e46750ef761d.gif)
![application search](https://user-images.githubusercontent.com/21084320/73000007-e7edc000-3e08-11ea-8ba2-4c2970a05684.PNG)

**Comment by alitarraf** [comment]
After resetting the application folder everything works fine.

**Comment by oliverschwendener** [comment]
You should not add any top level folders like `C:\Program Files (x86)\` to the app folders. Only add folders which contain shortcut files.
