### ISSUE TITLE
[Bug] Command line execution fails to read the "path" element

### ISSUE THREAD

**Issue by anuragdeshpande** [oliverschwendener/ueli#273]
![image](https://user-images.githubusercontent.com/3684197/73003223-7c80ff80-3dc2-11ea-9eeb-54599b52ce76.png)
The command is added to the system path in environment variables. Command works fine in a normal command line window. but fails in ueli folder.

**Comment by oliverschwendener** [comment]
Can you confirm that this is still an issue with the latest version? If so feel free to reopen.
