### ISSUE TITLE
Mac Installation 

### ISSUE THREAD

**Issue by underthecocotree** [oliverschwendener/ueli#274]
Hi,

I seem to have installed ueli on the mac.  I see it running on the activity monitor.  I have tried using `cmd+space` but I still get spotlight.  I tried to disable the shortcut but then nothing happens.

I tried assigning ueli the shortcut of `cmd+space` but no luck either.

Am I missing something?  
Thanks

**Comment by oliverschwendener** [comment]
Can you show me what keyboard shortcut you assigned in your general settings? Click the tray icon and choose "Settings".

<img width="244" alt="image" src="https://user-images.githubusercontent.com/15727229/73008375-baa41080-3e0e-11ea-83e5-e3d07fe0a8ed.png">

![image](https://user-images.githubusercontent.com/15727229/73008330-a06a3280-3e0e-11ea-8895-0a2de1e30e40.png)

**Comment by underthecocotree** [comment]
I never saw the menu bar icon as I got a few.  I disabled the shortcut for spotlight and changed the hotkey to CMD.

Thanks for your help!
