### ISSUE TITLE
Mac system apps missing from results

### ISSUE THREAD

**Issue by underthecocotree** [oliverschwendener/ueli#278]
Hi,

Thanks for this amazing plugin.  I seem to have a problem loading system apps.  They don't come up at the results.  eg Mail.app Calendar.app Calculator.app 

I do get other apps from the /Application folder.  I saw the plugin has different directories listed and the ?Application is in there.

Any ideas?

**Comment by oliverschwendener** [comment]
What version of macOS are you using?

**Comment by underthecocotree** [comment]
Catalina 10.15.2

Is there a way to get debug messages to help out?

**Comment by oliverschwendener** [comment]
Can you show me your application search settings? Search for "Settings" and press enter:

![image](https://user-images.githubusercontent.com/15727229/73720808-20ec3580-4723-11ea-91e2-80f2600c7436.png)

Then on the left side navigate to "Application Search":

![image](https://user-images.githubusercontent.com/15727229/73720850-37928c80-4723-11ea-9cb6-6d550802669e.png)

**Comment by underthecocotree** [comment]
Hey,

I started doing some digging today because it wasn't making any sense.  Short answer in the Application search settings I needed to add `/System/Applications` folder.

I `ls /Applications` and `ls ~/Applications` and the main system apps where missing.  Like the Mail.app, Calendar.app Calculator.app.  I did a spotlight search, found one of the apps and then checked the path.

**Comment by oliverschwendener** [comment]
Alright, so in macOS Catalina 10.15 and newer, system apps are installed in `/System/Applications`. I guess adding this folder to the default app search settings should fix this issue.

**Comment by oliverschwendener** [comment]
Fix should be available in the newest release.
