### ISSUE TITLE
Change/Customise terminal in Mac

### ISSUE THREAD

**Issue by underthecocotree** [oliverschwendener/ueli#279]
Hi,

I noticed that there is a past issue on windows to use Powershell vs CMD.  I went on the setting for a Mac but there is no other option.  I understand that there might be a lot more terminal options for Mac.

Is there a way to customise this?  Perhaps pass directly the path of an alternative terminal?

Thanks

**Comment by Nokeo08** [comment]
A user customizable setting for this would be a nice feature in general. Not just for OSX. It would allow for using things like WSL, Cygwyn, Msys2, on windows.

**Comment by oliverschwendener** [comment]
@underthecocotree iTerm is now supported with the newest release!
@Nokeo08 Please open a separate issue for Windows.
