### ISSUE TITLE
Non-stop errors

### ISSUE THREAD

**Issue by pluckyporcupine** [oliverschwendener/ueli#284]
I have tried both the portable zip and the installer version (both placed in D:\Applications). Whenever I try to add folders in the Application Search menu, I get errors like the following and the folders aren't indexed.

`{ "cmd": "powershell -Command \"& { 'C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs','C:\\Users\\user\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu','C:\\Users\\user\\Desktop','D:\\Applications' | %{ [Console]::OutputEncoding = [Text.UTF8Encoding]::UTF8; Get-ChildItem -Path $_ -include *.lnk, *.appref-ms, *.url, *.exe -Recurse -File | % { $_.FullName } } }\"", "level": "error", "service": "user-service", "timestamp": "2020-02-05T13:48:57.978Z" }`

Whenever I try to run an Everything search, the following happens:
![image](https://user-images.githubusercontent.com/35611215/73848802-c9b79500-47f6-11ea-9a86-026d902b3742.png)

I cannot get Ueli to function.

I am using the latest version from the website on Windows 10 Build 1903. I've even tried running Ueli as admin, but no dice.

**Comment by oliverschwendener** [comment]
What folders are you trying to add?

**Comment by pluckyporcupine** [comment]
Right now, primarily D:\Applications. Both the Everything and Ueli folders are also in there. I've also tried adding D:\Games and E:\Games, but neither has worked.

**Comment by oliverschwendener** [comment]
You shouldn't add top level folders like this. Add only folders that contain shortcut files (.lnk).

**Comment by pluckyporcupine** [comment]
Ah, I must have misunderstood. The default Application File Extensions include .exe and it searched folders on my desktop, so I thought that it worked like that.

Any insight on why Everything search is erroring out?

**Comment by oliverschwendener** [comment]
For that I need more debug information. You can open the debug file via the settings:

![image](https://user-images.githubusercontent.com/15727229/73850750-92fc7180-482c-11ea-9251-498aa80d56b0.png)

**Comment by pluckyporcupine** [comment]
Nevermind. That one was my mistake. I had closed the Everything client, leaving only the service open and it couldn't find it. Thanks for the info on where to find the debug log.

Going to go ahead and close this issue.
