### ISSUE TITLE
Workflow images

### ISSUE THREAD

**Issue by mahoromax** [oliverschwendener/ueli#286]
There seems to be no information on formatting or other requirements of the images that can be used for the workflow and how to set up the code there.

I tried to inlcude URLs from the web and to a local picture via a simple
<img src="https://a.link.to/the/wanted/pic.png">

But both had no effect.

**Comment by oliverschwendener** [comment]
You have 3 options to specify an icon for your workflow:

### 1. SVG icon

Paste in a valid SVG icon code for example like this:

![image](https://user-images.githubusercontent.com/15727229/74110429-e3f1ca00-4b8c-11ea-87ba-38873b836d21.png)

Here is the result:

![image](https://user-images.githubusercontent.com/15727229/74110476-359a5480-4b8d-11ea-9d3b-b98d976bb8e1.png)

If you don't know what an SVG icon is google it.

### 2. Image URL

Paste in a valid public URL to an image, for example like this:

![image](https://user-images.githubusercontent.com/15727229/74110462-21565780-4b8d-11ea-8790-2b8fa94b05fd.png)

Here is the result:

![image](https://user-images.githubusercontent.com/15727229/74110485-45b23400-4b8d-11ea-8981-e1243ca3a6d6.png)

### 3. Color

Paste in a valid color code (HEX, RGB or RGBA), for example like this:

![image](https://user-images.githubusercontent.com/15727229/74110523-9aee4580-4b8d-11ea-8f9f-50e743297d1f.png)

Here is the result:

![image](https://user-images.githubusercontent.com/15727229/74110512-8742df00-4b8d-11ea-9b0e-ef4bafe25212.png)

@mahoromax Does this resolve your issue?

**Comment by mahoromax** [comment]
Hi, that does resolve my problem. I'm a bit ashamed that I didnt find that out myself, I saw sure I tested it without the tag around... but I guess not.
![image](https://user-images.githubusercontent.com/22126466/74115071-a2bde200-4bad-11ea-8726-389c29eda242.png)
This is quite misleading though.

Are there any requirements for the icons? (maximum size, limited formats,...)

**Comment by oliverschwendener** [comment]
No there are no special requirements. The icons/images should be able to be opened with a webbrowser, best image formats are JPG, PNG or SVG.

Yes I agree that the current placeholder `<img src="...">` is misleading, I have to fix this. You only have to provide the URL to the image.

If you want to provide a local file path you have to use the `file:///` prefix. For example if your image file path is `C:\temp\image.png` you have to enter the following:

```
file:///C:\temp\image.png
```

And you dont have to use double quotes around the URL. Icons should be updated instantly without any delay.

**Comment by mahoromax** [comment]
Thank you! That would definitely answer all my questions. Should I close this issue or keep it open for you as a reminer?

**Comment by oliverschwendener** [comment]
I'll close this. But I should probably update the docs on how to create custom icons. Thanks for reporting this issue!
