### ISSUE TITLE
[Bug] search engine blacklist blocks plugins results

### ISSUE THREAD

**Issue by AmrBinBashir** [oliverschwendener/ueli#287]
In my search engine i have blacklisted "uninstall" and now when i try to use command line plugin and execute a command like "choco uninstall ..." so once i type uninstall the search result for command line plugins is removed. I think blacklist should only work on non plugins search results.

**Comment by oliverschwendener** [comment]
Thanks for reporting this issue! A fix for this will be included in the next release.
