### ISSUE TITLE
Issues with Ueli

### ISSUE THREAD

**Issue by kumar007git** [oliverschwendener/ueli#292]
I'm having the following issues, Can someone suggest how to fix?
1. Many plugins are unavailable. There is a red dot next to them and on the right side nothing is showing.

2. Ueli from time to time is showing a pink colored pop up window with a message about powershell. This is very annoying.

Thanks.

**Comment by oliverschwendener** [comment]
1. The red dot is an indicator if the plugin is activated or not. You can activate the plugin by clicking on the plugin on the left side and then activate it with the on/off button on the top right.

![image](https://user-images.githubusercontent.com/15727229/74250633-2df0c200-4ceb-11ea-8aa7-2b3d42d6d23b.png)

2. I assume you modified the application search settings. Can you show me a screenshot of your settings?

![image](https://user-images.githubusercontent.com/15727229/74250756-61335100-4ceb-11ea-952e-6d218c03b2f2.png)

**Comment by kumar007git** [comment]
Thanks.

I think there is a bug in the app. Whenever I add my windows quick launch folder I get the pink pop up window. My quick launch has many shortcuts and executables. Is there a limit on how many Ueli can store in its index databaes or what is causing this error? I can confirm it's not indexing quick launch because after I add that folder to application search, Ueli tried to refresh index then shows me the pink pop up window immediately and when I call up Ueli launcher and I search for a file present only in my quick launch that file is not in the search result which tells me Ueli did not index quick launch folder.

**Comment by oliverschwendener** [comment]
I think this should solve your problem: https://github.com/oliverschwendener/ueli/issues/272#issuecomment-577785567

You can adjust the rescan interval in the general settings:

![image](https://user-images.githubusercontent.com/15727229/74414335-82a65100-4e41-11ea-8788-375404f11625.png)

**Comment by kumar007git** [comment]
This is the error I'm getting whenever Ueli refreshes index. What is going on and how to fix this issue? Thanks!

![ueli error](https://user-images.githubusercontent.com/56237819/74612406-2bb7aa80-50d3-11ea-8e0c-a3a9850a6d4d.jpg)

**Comment by kumar007git** [comment]
> I think this should solve your problem: [#272 (comment)](https://github.com/oliverschwendener/ueli/issues/272#issuecomment-577785567)
> 
> You can adjust the rescan interval in the general settings:
> 
> ![image](https://user-images.githubusercontent.com/15727229/74414463-c9944680-4e41-11ea-9357-4cb1a89d9679.png)

Hi,
Can you let me know how to fix my issue below?
![ueli error](https://user-images.githubusercontent.com/56237819/74681656-f8882080-5191-11ea-9f2a-4fd0d5493672.jpg)

**Comment by oliverschwendener** [comment]
@kumar007git Can you show me your application search settings?

**Comment by kumar007git** [comment]
> @kumar007git Can you show me your application search settings?

Sure, here it is. This is a good app and I want to use it, so please let me know how I can fix this issue.
![ueli application search](https://user-images.githubusercontent.com/56237819/74777765-2fc90100-5268-11ea-8044-a224af684e6f.jpg)

**Comment by oliverschwendener** [comment]
There is no limitation on how many levels deep ueli will look for files. There is a limit though on how many items ueli can index. How many files do you have in your quick launch folder, so I can test it and see if the number of items is causing the problem.

**Comment by kumar007git** [comment]
> There is no limitation on how many levels deep ueli will look for files. There is a limit though on how many items ueli can index. How many files do you have in your quick launch folder, so I can test it and see if the number of items is causing the problem.

I have about 2500 items (shortcuts, exe, url). If you are going to increase the index size, I suggest increasing it a lot.

**Comment by kumar007git** [comment]
Any update on a solution to the issue I'm having with Ueli?

**Comment by oliverschwendener** [comment]
I'm looking into this.

**Comment by kumar007git** [comment]
> I'm looking into this.

Hi Oliver,
Did you fix this issue?

**Comment by oliverschwendener** [comment]
No, not yet

**Comment by kumar007git** [comment]
> No, not yet

Do you have time frame when this fix will be released?

**Comment by oliverschwendener** [comment]
I'll look into this as soon as I have time.

**Comment by oliverschwendener** [comment]
Please check if this is still an issue with the latest beta version: https://github.com/oliverschwendener/ueli/releases. Feel free to open the issue again if it's still happening.

**Comment by Denvermax19** [comment]
After updating the app I mostly use, Ueli stopped indexing it.

I reinstalled the app multiple times and re-scanned the Ueli if it any glitch.

For weeks, i opened the app manually, 
Then one day I found the solution:

Ueli indexes all the apps in the selected folders (default 2 system folders), 
strangely that app is installed in different folder (in which installed apps doesn't exists normally)

So i added that folder path in the Ueli settings, and my favourite app indexed in Ueli..
