### ISSUE TITLE
Application search not working

### ISSUE THREAD

**Issue by kcnightfang** [oliverschwendener/ueli#293]
I just installed Ueli on a Windows 10 computer. I've been kicking the tires, and application search doesn't work. I'm not sure why, I had it completely default, and I tried adding C:\Program Files\ to the index, but that didn't change anything, and I reset it.

A pop-up showed up saying that the file paths didn't exist I think.

**Comment by oliverschwendener** [comment]
I think this should solve your problem: https://github.com/oliverschwendener/ueli/issues/272#issuecomment-577785567

**Comment by kcnightfang** [comment]
It didn't I had reset my search to the stock setup previously, and it's still not working. This is the error message I've been getting.
![Annotation 2020-02-13 080954](https://user-images.githubusercontent.com/3062705/74438588-871a3c00-4e38-11ea-988d-87b3f7c1398e.png)

**Comment by oliverschwendener** [comment]
The error says `C:\Users\Kyle Curia\Desktop` does not exist. Remove it from the application folders and see what happens.

**Comment by kcnightfang** [comment]
That worked! It looked like it was just hanging on that I guess. I have a desktop folder, but I don't think I need to be scraping it as well.
