### ISSUE TITLE
Commandline plugin history

### ISSUE THREAD

**Issue by AmrBinBashir** [oliverschwendener/ueli#297]
whenever a user executes a command with command line plugin, it should be added to a history list and next time the user activates command line plugin instead of showing only one result with current typed command, it should display the commands used before as well, kinda like how windows "run" work.

**Comment by oliverschwendener** [comment]
Did you try <kbd>Shift</kbd><kbd>↑</kbd>?

**Comment by AmrBinBashir** [comment]
@oliverschwendener yes i did but that just cycles through all of my search queries of the whole app not just the command line plugin and while at it, the history array for the whole app shouldn't hold duplicate values, cause some times i use the same search query over and over again and when i try to cycle through them it takes forever to get what i want.
