### ISSUE TITLE
Feature Request: Save previous choices

### ISSUE THREAD

**Issue by TheCell** [oliverschwendener/ueli#30]
Hey guys, great work so far! Started using it for some time now, my biggest issue with ueli to date is that it doesn't save previous choices. An example: When I write tex in windows (windows key then write) it shows programms that have something to do with Tex, like Texmaker, Vertex, Miktex. When I select Texmaker several times it saves that choice and the next time I'm writing tex the system shows Texmaker as nr 1 so I can just use the enter key instead of navigating. Same works for webbrowsers who save ofen used websites when I write t it suggests twitter first.

Would love to see that feature in ueli. Keep it on.

**Comment by oliverschwendener** [comment]
I think you are not using the latest version of ueli. We implemented this feature already in version 4.0.0, see [Release Notes](https://github.com/oliverschwendener/ueli/releases/v4.0.0). Read [this](https://github.com/oliverschwendener/ueli#updater) to check if you are using the latest version.

**Comment by TheCell** [comment]
Just updated now after using the programs and restarting ueli it worked. Nice! thanks a lot and sorry for the hassle.
