### ISSUE TITLE
Unable to remove 'Mail' from search... outlook mail link?

### ISSUE THREAD

**Issue by eternalcakes** [oliverschwendener/ueli#301]
I currently use Mailbird as my email manager and have uninstalled Mail (UWP), which came pre-installed. I have uninstalled it and removed all shortcuts from desktop/start menu/folders. However, it still appears when I search. When selected, it opens this dialogue menu: https://i.imgur.com/cgG6VTU.png   

What/where is this? 

I can't blacklist 'Mail' as it blacklists my mailbird search.

**Comment by oliverschwendener** [comment]
Your Mail app is not installed anymore. Ueli is not really scanning your installed UWP apps, it's just showing a hardcoded predefined list uf UWP apps. As a workaround for now, you can just disable the UWP plugin if you don't have to launch other UWP apps from ueli.

**Comment by oliverschwendener** [comment]
Proper UWP support is now added in the latest release.
