### ISSUE TITLE
If ueli settings is open, launcher defaults to the desktop in which the settings is opened.

### ISSUE THREAD

**Issue by blmhemu** [oliverschwendener/ueli#304]
The new release almost fixes the bug with multiple desktops (spaces). But this issue seems to be an edge case. Now, it shifts to the desktop / space of it's settings (if open).

Sub-issue of #303 persists after the latest fix.

**Comment by oliverschwendener** [comment]
This should be solved with v9, as there will be just one window. You can try out the latest beta release here: https://github.com/oliverschwendener/ueli/releases
