### ISSUE TITLE
Change font

### ISSUE THREAD

**Issue by Jarvvski** [oliverschwendener/ueli#311]
Hey there

Great app! I'm finding it much better than the alternatives, having come to windows from macOS (Alfred)

How hard would it be to enable changing the font used?

**Comment by oliverschwendener** [comment]
A new setting for changing the font is included in the latest release ;)

![image](https://user-images.githubusercontent.com/15727229/76913239-b0eed480-68b6-11ea-9575-2f1e4a001fcd.png)

**Comment by Jarvvski** [comment]
Thank you @oliverschwendener!
