### ISSUE TITLE
[Feature Request] Set prefixes to be followed by space

### ISSUE THREAD

**Issue by Jarvvski** [oliverschwendener/ueli#313]
So if I use the web search prefixes, I think we should specify if there is a space or not before following it

I.e.

I set the duckduckgo prefix to just `d`

Then if I type in `disco` to autocomplete to discord, it will force the duckduckgo search because it starts with `d`

I think it should be just prefix followed by space -> web search

**Comment by oliverschwendener** [comment]
Just add a prefix with a whitespace at the end?

**Comment by Jarvvski** [comment]
That could work as a fix, but won't help users who don't see this issue 😉

**Comment by oliverschwendener** [comment]
So your suggestion is to force users to add a space after the prefix in order to have a match on the web search?

**Comment by Jarvvski** [comment]
Maybe as an option?

I'm just trying to follow what other launchers I've seen do - which to me feels more natural

`g my web search`

vs 

`gmy web search`

**Comment by irafaz** [comment]
I was thinking the exact same thing. Might be because I'm also used to this behavior in other launchers.

I did as you suggest @oliverschwendener and added the space in the prefix itself, but I wouldn't mind this as a toggle in the Web Search settings. I think most of the Ueli users coming from other launchers are used to this behavior.

**Comment by AmrBinBashir** [comment]
I moved to ueli from wox and wox used the prefixes with a whitespace at then end. It feels natural tbh than using `?` so I changed all of my prefixes to work with a whitespace at the end. 

@oliverschwendener I don't think it's necessary to add a separate setting for it. Maybe we can add a hint in the settings that lets people know they are allowed to add `whitespace` with an example or if you have to add a setting for it, i think it should be a keymap presets where you can provide two default presets, one with `?` and the other with `whitespace` and allow users to create their own presets like colortheme but in my opinion, a hint under the prefix field would be enough.

**Comment by xfirf** [comment]
I also just added a space at the end of my keyword to have it working "like in wox". Works perfect. I think a hint to this solution would be enough too.
