### ISSUE TITLE
Scroll item by item instead of current scrolling mechanism.

### ISSUE THREAD

**Issue by AmrBinBashir** [oliverschwendener/ueli#318]
I think it would be better to scroll item by item rather than a whole bunch of them at a time. I can open a pull request with the changes if you want. It's actually pretty simple change.

**Comment by oliverschwendener** [comment]
To be honest I don't agree that this is a better behavior. I will close your PR because I think the current solution is better. If more people support your opinion, we can open the PR later again.

**Comment by AmrBinBashir** [comment]
That sounds reasonable.

**Comment by dmratcliffe** [comment]
I think this would be nice as a setting.
Scroll page vs scroll one by one
