### ISSUE TITLE
Steam Games

### ISSUE THREAD

**Issue by sistematico** [oliverschwendener/ueli#32]
You can add list of Steam Games(library) in ueli?

Thank you..

**Comment by Zaplanincan** [comment]
Hi,
I'm using Pin Steam (from w10 shop) to pin steam games to start menu, then ueli can start games.

**Comment by oliverschwendener** [comment]
@sistematico When you install a game in steam you can create a shortcut in the start menu folder. So ueli should be able to find the game.

![steam-install](https://user-images.githubusercontent.com/15727229/41232737-97388486-6d87-11e8-837e-0003ddf67931.png)

If you already hav installed the game you can create a shortcut on the desktop:

![steam-shortcut](https://user-images.githubusercontent.com/15727229/41234326-1f7c2a7e-6d8c-11e8-9133-91281c6d86a4.png)

**Comment by oliverschwendener** [comment]
@Zaplanincan What do you mean by "default folder to set shortcuts in there"?

**Comment by Zaplanincan** [comment]
Hi,
sorry my bad,  I just realized that I can write my favorites to ueli.count.json and give them hi count.
I don't use desktop shortcuts so I use Pin Steam on W10, for ueli to read *.ink files.

**Comment by oliverschwendener** [comment]
You can [customize](https://github.com/oliverschwendener/ueli#customization) the folders and file extensions ueli should search. I think this should solve your problem.
