### ISSUE TITLE
MacOS High Sierra: Visual Studio Code is not shown 

### ISSUE THREAD

**Issue by zarzen** [oliverschwendener/ueli#322]
Hi there,

ueli is not able to locate the `visual studio code` as shown in following:

<img width="639" alt="Screen Shot 2020-03-31 at 1 02 25 PM" src="https://user-images.githubusercontent.com/1150493/78054326-e502d480-734f-11ea-9126-026f3550fe46.png">

The path which contains `visual studio code` is included in search path:
<img width="659" alt="Screen Shot 2020-03-31 at 1 03 12 PM" src="https://user-images.githubusercontent.com/1150493/78054394-019f0c80-7350-11ea-86a1-8e15731ad3e7.png">

And the application is located at `/Applications`:
```
➜  /Applications ls |grep Visual
Visual Studio Code.app
```

**Comment by oliverschwendener** [comment]
Can you find Visual Studio Code with the normal Spotlight search?

**Comment by zarzen** [comment]
yes
<img width="679" alt="Screen Shot 2020-04-01 at 3 51 48 PM" src="https://user-images.githubusercontent.com/1150493/78180444-c88a9900-7430-11ea-9789-5414cb0ef4d2.png">

BTW, I have tried Alfred4, which has the same issue.

**Comment by zarzen** [comment]
I don't know what happened, but the visual studio code is back.
