### ISSUE TITLE
Ueli not opening anything from everything search with a utf8 character in path or name

### ISSUE THREAD

**Issue by DVark09** [oliverschwendener/ueli#323]
I can't open a lot of my files because my language (Hungarian) has some special letters, and ueli couldn't handle those characters.
Example from log: 
2020-03-31T18:09:47.271Z error: Failed to open: D:\SULI\H�L�ZAT\40_oldalas_segedlet.pdf
Those are letters like á,ó,ű,ő,ú,ü,ö
Everything is working correctly because I can open files that don't have foreign characters in its path or name.
Can this issue be addressed somehow?

**Comment by oliverschwendener** [comment]
Thanks for reporting! I'll close this issue because there is already another issue for this: #203
