### ISSUE TITLE
[Feature Request] Optional rounded window corners

### ISSUE THREAD

**Issue by rmcproductions** [oliverschwendener/ueli#327]
Title says it. Apart from custom CSS, a little slider in the appearance settings to set rounded corners for the window.

**Comment by AmrBinBashir** [comment]
This feature has been added in v8.8.0. This issue can be closed now.

**Comment by oliverschwendener** [comment]
Yes. You can now add rounded corner via the border radius settings in the "Appearance" tab:

![image](https://user-images.githubusercontent.com/15727229/86443547-b65e1680-bd0f-11ea-9d5d-3a0eadde7319.png)

**Comment by vglzng** [comment]
Is there a bug in this function? If i set the 'User input border radius' to 5px for example nothing happens.
Am i doing something wrong?

**Comment by amrbashir** [comment]
It's working fine.
@vglzng can you share a screenshot of your settings ?

**Comment by vglzng** [comment]
Sure

![Screenshot_1](https://user-images.githubusercontent.com/25006085/102605294-5cb6a080-4125-11eb-985f-3d36cbb7bd16.jpg)

**Comment by amrbashir** [comment]
@vglzng that's weird tbh and I can't of think of any reason why it wouldn't work.
Try these steps though: 
1. backup your settings.
2. reset all of the app settings to default.
3. try setting the radius and see if it works. 

If it didn't work try:

4. uninstall the app and delete this folder `C:\Users\<your-user-name>\AppData\Roaming\Ueli`
5. reinstall the latest version of the app.
6. try settings the radius and see if it works.

**Comment by vglzng** [comment]
In the mean time, i installed it on a second laptop. Exactly the same problem. You sure it is not a bug?

This is a clean install, i only found Ueli just yesterday. Really loving it though.

**Comment by amrbashir** [comment]
@vglzng oh yes it is a bug, I just found the problem. You need to enable the transparent background switch. 

![image](https://user-images.githubusercontent.com/48618675/102608149-1a479080-4132-11eb-8274-d39bf78c6743.png)

you can still have opaque background even with this switch on.


Electron doesn't support rounded corners in the `BrowserWindow` object so rounded coreners must be done via css which would require a transparent background.

**Comment by vglzng** [comment]
You are correct. This fixes my issue.

I do see that if i set 'Search results border radius'. Only the left side is rounded. Other than that it works. Thanks for your help.
