### ISSUE TITLE
ueli 8.6.2 not showing the app icon in search result

### ISSUE THREAD

**Issue by divyanshu-sam** [oliverschwendener/ueli#328]
I have tried and install ueli several time but the application in start menu folder and appdata folder is showing in the search result in windows 10 latest update

![1](https://user-images.githubusercontent.com/61079404/78387050-42bb4900-75fc-11ea-8e4a-577c751dccb8.jpg)

![2](https://user-images.githubusercontent.com/61079404/78387059-46e76680-75fc-11ea-82b6-3960a59e4f8c.jpg)
 

Earlier I was using previous version and it was running fine but this version is not showing any of the application installed in my system and from the start menu folder

**Comment by oliverschwendener** [comment]
It's weird that the windows 10 settings are showing up when you search for "chrome". Can you show me your "Search engine" settings? What happens if you disable the "Operating system settings" plugin?

**Comment by divyanshu-sam** [comment]
The issue is that i am not able to see any of the application icon in the search result which is installed in my system.

![3](https://user-images.githubusercontent.com/61079404/78422208-52c63d80-767b-11ea-9ec5-0712dcf93107.jpg)

I have attached the screenshot which you have said. kindly have a look into it.

**Comment by divyanshu-sam** [comment]
Any update on this why this issue is coming in this version

**Comment by oliverschwendener** [comment]
Is there any information in the debug log?

![image](https://user-images.githubusercontent.com/15727229/79020555-6b51be80-7b79-11ea-9d42-000d2db02f82.png)

**Comment by divyanshu-sam** [comment]
![image](https://user-images.githubusercontent.com/61079404/79175623-d7ebe800-7e1b-11ea-9aaf-4387f4e69edc.png)

Only this error is showing in the debug file nothing more error is there

**Comment by oliverschwendener** [comment]
What happens if you disable the browser bookmarks plugin?

![image](https://user-images.githubusercontent.com/15727229/79218697-1fd93200-7e51-11ea-9b91-e80d68987e03.png)

**Comment by eskoONE** [comment]
> 
> 
> What happens if you disable the browser bookmarks plugin?
> 
> ![image](https://user-images.githubusercontent.com/15727229/79218697-1fd93200-7e51-11ea-9b91-e80d68987e03.png)

tried that, didnt help.
