### ISSUE TITLE
multiple entries in windows installed app list

### ISSUE THREAD

**Issue by shaneknysh** [oliverschwendener/ueli#329]
When the app is updated a new entry with the new app version is listed as installed in the windows 10 installed app list.

**Comment by themegaphoenix** [comment]
hello,
could you give us an example?

**Comment by shaneknysh** [comment]
After I updated ueli in the windows 10 installed app list (Windows button -> Settings -> Apps -> Apps & Features. Scroll down to u or search the list for ueli) ueli was listed twice.  Once with the old version number and once with the new version number. 

I am waiting for an update to test to see if it is still happening.

**Comment by themegaphoenix** [comment]
what versions number are showing up?
i am not sure about the updates as i have only started using Ueli recently (in the latest version)

**Comment by shaneknysh** [comment]
I uninstalled and reinstalled so I only have 1 version showing up right now.

**Comment by oliverschwendener** [comment]
I consider this to be resolved.
