### ISSUE TITLE
Feature request: Add support for multiple screens

### ISSUE THREAD

**Issue by jess-sys** [oliverschwendener/ueli#33]
Hey there! Really impressed with this so far! The best alternative to "rofi" for Windows.

What about a dual screen support ? 
With mouse focus retrieval to determine on which screen the bar will display ?

It would be so cool!

**Comment by oliverschwendener** [comment]
Thank you for your feedback! Good idea, I will look into it.

**Comment by oliverschwendener** [comment]
Added support for multiple screens in: 07c3fc770f544e24d8203ff55e8cbc233a02ca00. This will be included in the next release.

**Comment by oliverschwendener** [comment]
[Version 4.7.0](https://github.com/oliverschwendener/ueli/releases/tag/v4.7.0) is released.
