### ISSUE TITLE
[Windows] How to add application search folders correctly?

### ISSUE THREAD

**Issue by ianpan870102** [oliverschwendener/ueli#330]
Thanks for this awesome package, I've been using it as an Alfred replacement for my windows machine.
Is there a way to recursively add a folder to Application Search? For example, quite a few of my apps are installed in `C:\Program Files\`
However, it seems that I have to individually add the subfolders `C:\Program Files\Cmder`, `C:\Program Files\Mailbird`, `C:\Program Files\Typora` etc.

**Comment by themegaphoenix** [comment]
it would be faster to add the shortcuts to the start menu
it would make it faster to index and search and would have less .exe available because those programs have a lot more .exe than the standard

**Comment by oliverschwendener** [comment]
Just add files with shortcuts in it, for example:

- `C:\ProgramData\Microsoft\Windows\Start Menu`
- `C:\Users\<Your username>\AppData\Roaming\Microsoft\Windows\Start Menu`
