### ISSUE TITLE
Add folder type to Shortcuts Plugin

### ISSUE THREAD

**Issue by AmrBinBashir** [oliverschwendener/ueli#338]
I always want to access my user directory but I can't index it using "Simple Folder Search" cause that will add more user directories that I don't want. 

Right now, I can add the folder with the type of file path, but It would be convenient to add Folder type too and A default folder Icon like "Simple Folder Search" Icon.

**Comment by oliverschwendener** [comment]
Why not just change the label from "File path" to "File or folder"?

**Comment by AmrBinBashir** [comment]
There is no default Icon for folder, Which will make the user try to find the svg you use for folders and manually use it.
