### ISSUE TITLE
ueli.config.json settings do not apply

### ISSUE THREAD

**Issue by C4b4nossi** [oliverschwendener/ueli#34]
Hey,

great tool! It seems to not apply my changes of the settings-file. It does not change theme and custom commands are not working.
Win10 Pro 1709

Can I provide any logs for review?

**Comment by oliverschwendener** [comment]
Did you reload ueli after editing the config file? Just type in "Reload ueli".

**Comment by ravarious** [comment]
Same problem, change ueli.config.json (theme and command), make reload (pls write this command in documention), nothing changed.

**Comment by oliverschwendener** [comment]
@ravarious You are right. I Forgot to mention this in documentation.

@HelloKittyCat & @ravarious 
Can you post your config here?

**Comment by C4b4nossi** [comment]
@oliverschwendener - my mistake: forgot a few commas when I added more folders in the config. Works great!
