### ISSUE TITLE
Proper Support for UWP apps

### ISSUE THREAD

**Issue by brukbrhane** [oliverschwendener/ueli#340]
I was hoping it would be possible to properly support displaying UWP apps because I, personally, seem to find them a defining part of my PC. I don't know a lot on what I can do to help but I was hoping [this](https://github.com/Wox-launcher/Wox/issues/198#issuecomment-234382957) comment I had seen on Wox's Github page would provide some support

**Comment by brukbrhane** [comment]
Closing cause there are just so many duplicates. Will request reopening if I find a suitable way to open UWP apps with Node

**Comment by oliverschwendener** [comment]
Actually this is coming in the next release thanks to @tkohlmeier , see this PR: https://github.com/oliverschwendener/ueli/pull/337.

**Comment by xfirf** [comment]
> Actually this is coming in the next release thanks to @tkohlmeier , see this PR: #337.

When will the next release be available? :-)

**Comment by brukbrhane** [comment]
@xfirf not an answer to your question but I've been running the test version after building it. Really easy and quick to do

**Comment by xfirf** [comment]
> @xfirf not an answer to your question but I've been running the test version after building it. Really easy and quick to do

good idea. But unfortenatly I´m getting build errors I´m not able to resolve. So I have to wait for the next release.

**Comment by brukbrhane** [comment]
> Fixed my errors by
Glad to hear it.

**Comment by oliverschwendener** [comment]
> When will the next release be available? :-)
 
@brukbrhane @xfirf  By the end of this week ;)

**Comment by oliverschwendener** [comment]
New release is out now.
