### ISSUE TITLE
Option to open log on error?

### ISSUE THREAD

**Issue by ScottBurfieldMills** [oliverschwendener/ueli#348]
Hi, 

If an error occurs a message is displayed instructing the user to check the log. I am proposing to add the ability for the user to instantly open the log file by pressing ENTER.

Users can open the debug log from within the General settings menu but I feel that it is rather hidden away.

If you're happy with this then I can attempt a PR.

Thanks.

![image](https://user-images.githubusercontent.com/1740387/79680522-a84a3f00-8264-11ea-8083-8bbe06ae2277.png)

![image](https://user-images.githubusercontent.com/1740387/79680500-71742900-8264-11ea-8c63-ecc5b620ba89.png)

**Comment by AmrBinBashir** [comment]
I would like that too.

**Comment by luckymurari** [comment]
+1

**Comment by thelegend09** [comment]
I'd like that too.

**Comment by matbe81** [comment]
+1

**Comment by oliverschwendener** [comment]
Should be fixed with the next version
