### ISSUE TITLE
Navigation pane keeps showing up 

### ISSUE THREAD

**Issue by zen-quo** [oliverschwendener/ueli#350]
Hi, just updated to the new version 8.6.2 on Windows 8.1. When I search for a folder and open it through Ueli it shows up with the navigation pane and even after hiding it, next time I open it, it still shows up. Opening through windows explorer is as usual (no nav. pane).

The normal behavior was that when I use a new way to open a folder (Ueli or any other program), I set up appearance once and it would stay that way. 

Any help is appreciated.

Edit: problem persists through versions 8.6.1 and 8.6.0. I'm unable to install older versions. I think I had 8.5.0.

**Comment by AmrBinBashir** [comment]
Same here. I thought it was only me.

**Comment by oliverschwendener** [comment]
Can someone check if this is still an issue with the latest v9 release? https://github.com/oliverschwendener/ueli/releases
If so, feel free to reopen.
