### ISSUE TITLE
Ueli can't find application

### ISSUE THREAD

**Issue by lelouch162** [oliverschwendener/ueli#352]
Hello, 

When I type something simple as chrome or discord, it cannot find it. Could you please help me with this problem
![Annotation 2020-04-21 211226](https://user-images.githubusercontent.com/50264163/79904400-e1c1ac80-8414-11ea-8189-e8241f62b796.png)

it also says: " Get-ChildItem : Cannot find path 'C:\Users\jeger\Desktop' because it does not exist. At line:1 char:207 + ... ing]::UTF8; Get-ChildItem -Path $_ -include *.lnk, *.appref-ms, *.url ... + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : ObjectNotFound: (C:\Users\pc\Desktop:String) [Get-ChildItem], ItemNotFoundException + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand"

**Comment by oliverschwendener** [comment]
Go into your application search settings and remove the Desktop folder. Then try again.

**Comment by Maltbrew** [comment]
Hey, I'm also getting the same bug. 

Even after removing the Desktop folder.

**Comment by oliverschwendener** [comment]
@Maltbrew Do you have an error message I could look into?

**Comment by Maltbrew** [comment]
@oliverschwendener Sure, where are the logs?

**Comment by Maltbrew** [comment]
@oliverschwendener  I took a screenshot, don't know if it helps. https://bit.ly/357nj1T

**Comment by tkohlmeier** [comment]
@Maltbrew You can find the debug log here:

![grafik](https://user-images.githubusercontent.com/6824291/80303231-2cde1580-87af-11ea-98ab-79bccbaef4e8.png)

And by the way, you can just paste screenshots here.

**Comment by Maltbrew** [comment]
There we are! 

[debug.log](https://github.com/oliverschwendener/ueli/files/4535381/debug.log)

**Comment by tkohlmeier** [comment]
@Maltbrew: Did you add the folder `C:\Program Files (x86)` to the application search plugin? There are PermissionDenied errors for folders like `C:\Program Files (x86)\ASUS\CrashReports`. These errors seem to interrupt the index refreshing process so that no applications are searchable anymore. I will look into this.

Anyway I do not recommend to index folders like `C:\Program Files (x86)` because it is very slow. Instead you should just add links to the start menu.

**Comment by tkohlmeier** [comment]
I created pull request #358 to solve this error.

**Comment by Maltbrew** [comment]
@tkohlmeier 

That fixed it! Cheers!

**Comment by themegaphoenix** [comment]
@lelouch162 are you logged in as Microsoft account?
if you are then the Desktop folder does not exist but rather it is:
C:\Users\Username\Onedrive\Desktop:

**Comment by lelouch162** [comment]
> 
> 
> Go into your application search settings and remove the Desktop folder. Then try again.

Yes it worked, thanks a lot
