### ISSUE TITLE
 FluentUI Support

### ISSUE THREAD

**Issue by megsystem** [oliverschwendener/ueli#356]
GoodMorning, 
I wanted to know if you will add **FluentUI** in the future. Thank you :D

**Comment by dmratcliffe** [comment]
In what capacity would this use fluent ui? My understanding is that fluent is mostly for web / mobile apps?

**Comment by oliverschwendener** [comment]
At the moment there are no plans to implement Fluent UI in this app.

**Comment by anuragdeshpande** [comment]
with 8.8.0 release, there is an alpha slider. you can mimic the Fluent UI look for the most part. May be will help you. This is my setup at the moment

![image](https://user-images.githubusercontent.com/3684197/86601235-4abdb880-bf5e-11ea-9ccf-728076d77f0f.png)

**Comment by oliverschwendener** [comment]
Ueli v9 will use fluentui/react-components, see this example screenshot:

![image](https://github.com/oliverschwendener/ueli/assets/15727229/38d9fde0-2e8e-41de-a11d-48cfeed61d33)
