### ISSUE TITLE
Multiple processes

### ISSUE THREAD

**Issue by kumar007git** [oliverschwendener/ueli#359]
I'm seeing 3 and 4 Ueli processes running in task manager, is that expected behavior or am I launching more than one instance of Ueli?

Also, if I refresh indexes from the tray icon, how can I tell Ueli successfully completing refreshing indexes?

**Comment by oliverschwendener** [comment]
1) Multiple processed running is normal for an [electron](https://electronjs.org) app.
2) There is no notification when the index refresh fails when triggering it from the tray icon. You can check the error logs or just open up the settings window to see if there are any issues while reindexing.
