### ISSUE TITLE
Feature request: Add option to hide tray icon

### ISSUE THREAD

**Issue by xXKeyleXx** [oliverschwendener/ueli#36]
It would be great if I could hide the icon in the tray bar as I don't need it and I like it clean there.

**Comment by oliverschwendener** [comment]
Thank you for your feedback! I will add an option `showTrayIcon` to the [configuration](https://github.com/oliverschwendener/ueli#customization) but keep in mind that (currently) the only way to update ueli is through the tray icon ([see here](https://github.com/oliverschwendener/ueli#updater)).

**Comment by oliverschwendener** [comment]
I'm working on that... this will be included in the next release.

**Comment by oliverschwendener** [comment]
New release is out.
