### ISSUE TITLE
can't find some administrative tools

### ISSUE THREAD

**Issue by kumar007git** [oliverschwendener/ueli#360]
I have shortcuts to administrative tools in my start menu. When I search in Ueli for them, these shortcuts show up in addition to the actual executable from system32 folder. For some of these administrative programs such as dfrgui.exe and compmgmtlauncher, when I select the shortcut link then nothing happens and for defragmenter when I also click on the actual system32 executable then also nothing happens. How can I fix this issue?

Also, for application search I specified only start meu and quick launc, but when I search in Ueli, it pulls the actual executables from the installation folder and for administrative tools it shows executables from system32 folder. Why is Ueli looking in those folders instead of just showing me shortcut links from the folders I specified in application search.
Thanks for your help.

**Comment by oliverschwendener** [comment]
Do you have the simple folder search plugin enabled?

**Comment by kumar007git** [comment]
Yes, I have simple folder search plugin enabled.

**Comment by oliverschwendener** [comment]
Can you show me your application search settings and your simple folder search settings?

**Comment by danielsteiner** [comment]
I've got a similar issue - when I try to look for programms like the MS Terminal (UWP App) or Termius (SSH Client), they simply don't show up and ueli shows me either some system commands (when I search for terminal) or some Apps that contain some of the chars (for example Create Backup USB Key or Groove Music) for Termius.

**Comment by themegaphoenix** [comment]
@danielsteiner have you got the UWP plugin enabled? searching for terminal does show up the Windows Terminal but in second place. What version of Windows are you running?
![image](https://user-images.githubusercontent.com/9766462/81916397-ace7e600-95cb-11ea-9ec3-740e9e5a7c97.png)

**Comment by danielsteiner** [comment]
yep, the UWP Plugin is up and running. I am running 1903 (just realized that I must have somehow skipped 1909 on that machine), Build 18362.778. 

I am about to update to 2004 tough. 

As you can see in my previous comment, when I am looking for "Termius", I get "Groove Music (UWP App)" as fourth result. Because of this, I actually think, that my issue might be a problem with the search itself.

**Comment by oliverschwendener** [comment]
Can someone check if this is still an issue with the latest v9 release? https://github.com/oliverschwendener/ueli/releases
If so, feel free to reopen.
