### ISSUE TITLE
Search window does not fully expand on activation

### ISSUE THREAD

**Issue by jeshuawoon** [oliverschwendener/ueli#363]
So whenever I try to launch ueli using the hotkeys, it wont fully expand. It will only fully show the search bar if i start typing. However if I were to close it right after or press enter to activate a command etc, the issue will pop up again and the bar wont fully display the next time I press the hotkeys.

Surprisingly, if I don't type anything and just close the bar and reopen it, it will now fully show the bar. The bug happens again if I type into the bar though.

Attached a gif to explain:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/35112783/80674791-70a18980-8ae5-11ea-9601-a8ce6ec65750.gif)

Any way to fix this?

**Comment by oliverschwendener** [comment]
Can you show me your appearance settings?

![image](https://user-images.githubusercontent.com/15727229/80725571-8b82f680-8b03-11ea-9629-2ec77fdf8b1a.png)

**Comment by jeshuawoon** [comment]
Here you go.

![image](https://user-images.githubusercontent.com/35112783/80728653-c273ff00-8b39-11ea-9dc5-df8c577a21d7.png)

**Comment by oliverschwendener** [comment]
Try to disable the option "Allow transparent background" if you don't really need it.

**Comment by jeshuawoon** [comment]
@oliverschwendener thanks, seems to have solved the issue.
