### ISSUE TITLE
Feature Request: Show all running windows on all virtual desktops? (ALT+TAB Feature)

### ISSUE THREAD

**Issue by TobiasDev** [oliverschwendener/ueli#364]
Hello!

I was wondering if it would be possible to add something like the alt+tab functionallity to the app. Because I'm a huge user for Virtual Desktops on Windows 10, and I'm usually running quite a lot I would love to see something where I could typ "win" and that gives me a list of all my software. That would make it a lot faster for me than having to alt+tab until I reach the one I want to reach. :)

**Comment by oliverschwendener** [comment]
Maybe similar to #111 ?

**Comment by TobiasDev** [comment]
I thought I searched properly this time to look for similar features... But apperently not. :D Sorry! It is exactly that I'm after. :) 

I'll close this issue since you already have it requested.
