### ISSUE TITLE
Ueli search box not showing/launching

### ISSUE THREAD

**Issue by kumar007git** [oliverschwendener/ueli#365]
now a new issue. ueli was working fine then today suddenly stopped working i.e., the search box is not showing when I press the hotkeys and it is also not showing when I select "show" option from tray icon. How can I fix this issue?

**Comment by oliverschwendener** [comment]
Can you open your settings via the tray icon? Try to reset the general and appearance settings:

![image](https://user-images.githubusercontent.com/15727229/80857691-4fab7680-8c54-11ea-8792-5a67129fb2ff.png)

**Comment by kumar007git** [comment]
I have 8.5.3 and 8.6.2 on teo different computers. I had the issue on both. After  resetting settings, 8.5.3 is working. 8.6.2 worked briefly like 2 times and not it is the same issue.
