### ISSUE TITLE
Updating an app

### ISSUE THREAD

**Issue by Lambada10** [oliverschwendener/ueli#377]
When i'm doing an update through settings it shons me that windows 7 or up is required (i'm running win10)

**Comment by Lambada10** [comment]
Anyone?

**Comment by themegaphoenix** [comment]
any other error messages?

**Comment by oliverschwendener** [comment]
That's weird, what exact version of windows are you running?

**Comment by Lambada10** [comment]
So I have Windows 10 Pro version 2004 build number : 19041.208

**Comment by Lambada10** [comment]
[https://1drv.ms/u/s!AjxQakyYsl3og1Q4qhDs4zIgCJDD]

**Comment by themegaphoenix** [comment]
> So I have Windows 10 Pro version 2004 build number : 19041.208

Thats a Windows Insider build is it not?
Have you tried uninstalling and reinstalling the old version ( an old version is needed as you wont be able to update a new version)

**Comment by Lambada10** [comment]
I had this issue on stable too. (Thats one of the reasons why I joined Insider)

**Comment by weiwang11** [comment]
Might be an electron issue: https://github.com/electron-userland/electron-builder/issues/2420

This is the commit that addresses the issue: https://github.com/electron-userland/electron-builder/commit/d4513087c4514d974865efd6b2f0f4e880491093#diff-7774a046985338a2868cf34e2ab60b08

**Comment by weiwang11** [comment]
Maybe related to this issue: https://github.com/electron-userland/electron-builder/issues/2420

**Comment by mukireus** [comment]
Yesterday I upgraded the Windows 10 version 2004 . I got the same error. I uninstalled Ueli. I cleaned the registry and i installed ueli again. It is working now.

**Comment by oliverschwendener** [comment]
Can someone check if this is still an issue with the latest v9 release? https://github.com/oliverschwendener/ueli/releases
If so, feel free to reopen.
