### ISSUE TITLE
Search on google automaticaly when no result are found

### ISSUE THREAD

**Issue by alexandredp-apptweak** [oliverschwendener/ueli#378]
I switched to ueli from alfred and one thing that I'm missing is you could just type in it your question and if it didn't find anything it would search on google, without type g? or google ofc
thanks!

**Comment by oliverschwendener** [comment]
![image](https://user-images.githubusercontent.com/15727229/81445264-cf67a280-9178-11ea-953e-c5e39b1c413c.png)

**Comment by alexandredp-apptweak** [comment]
thanks!!! and sorry for the inconveniance, is there a documentation for these kind of things ?
