### ISSUE TITLE
Start UWP-Apps on Windows

### ISSUE THREAD

**Issue by lampenlampen** [oliverschwendener/ueli#38]
### Start UWP-Apps with Ueli
It would be nice to start uwp-apps with ueli.

I tried to workaround by creating a shortcut to the app on the destop and ueli shows this shortcut, but an error is thrown by windows that it cannot find a programm to handle this action.

Doubleclicking the shortcut on the desktop is working.

Thanks in Advance

PS: Really great tool. 👍

**Comment by oliverschwendener** [comment]
The problem is that there is no way (at least none which I know of) to get all installed uwp apps. But you can set up a [custom command](https://github.com/oliverschwendener/ueli#custom-commands) to start a UWP app.

For example: I installed the official Instagram app from the Microsoft Store and I set up this custom command:

``` json
{
    "name": "Instagram",
    "executionArgument": "!start instagram:"
}
```

The only thing you have to do is to get the correct start parameter for your UWP app. In my case ist was `instagram:`.

**Comment by lampenlampen** [comment]
I found a way to get all installed app with a PowerShell command.

`Get-AppxPackage`

https://stackoverflow.com/a/37086764/7441041

**Comment by oliverschwendener** [comment]
`start shell:AppsFolder\{PackageFamilyName}!App` doesn't work for me. Does it work for you?

**Comment by lampenlampen** [comment]
I think i tested it with one of the few apps it worked on (Microsoft Photos App). I tested it with others now and it didn't work.

**Comment by oliverschwendener** [comment]
For me only the pre-installed UWP from Windows work like this: `start ms-photos:` or `start ms-settings:`

**Comment by oliverschwendener** [comment]
Thanks for the hint, I didnt know that!

**Comment by lampenlampen** [comment]
Sadly it doesn't help for an automated solution.

**Comment by oliverschwendener** [comment]
I will close this issue, because I have no acceptable solution for this issue.

**Comment by cosimochellini** [comment]
hey, **really important**, find a workaround, to open all UWP-Apps,
1: search on windows (window key + name app)
2. right click on the app icon> add to start
3: drag the app icon to the desktop
4 (optional): move the link to some folder if you prefer not to have such icons on your desktop

**Comment by chrisonline** [comment]
I have used before the launcher "Keypirinha" and they have a plugin to add all Windows UWP apps.
The plugin is open source and also on Github:
https://github.com/ueffel/Keypirinha-WindowsApps

Can you have a look how they do this ?

**Comment by oliverschwendener** [comment]
@chrisonline Thank you for your research! I will have a look into this as soon as possible.

**Comment by TobiasDev** [comment]
Are there any updates on this? I know it is closed, just curios. :)

**Comment by oliverschwendener** [comment]
Not yet. I am working on a rewrite of the core modules to support async code execution. Will look into this as soon I released the the next major update.

**Comment by oliverschwendener** [comment]
Proper UWP support is now added in the latest release.
