### ISSUE TITLE
Feature request: Kill/force quit applications/processes

### ISSUE THREAD

**Issue by johanhelsing** [oliverschwendener/ueli#382]
Killing unresponsive applications requires a lot of clicks on windows, would be useful to be able to do this through ueli. i.e. `kill misbehavingapp`.

**Comment by oliverschwendener** [comment]
Duplicate of #128

**Comment by johanhelsing** [comment]
Ah, sorry (tried searching issues for "kill" and "quit", but nothing showed up).
