### ISSUE TITLE
[Bug] Persistent user input should show previous search results

### ISSUE THREAD

**Issue by Tibi** [oliverschwendener/ueli#385]
Hi Ueli devs!

Coming from other launchers and so far very happy with the switch to Ueli.

Regarding the nice "Persistent user input" feature I would suggest that it should not only keep the last entered text, but also directly show the search results. Even better would be to select the last selected result.

It would make it very easy to try different results to the same query.

Keep up the good work :)
Cheers!
Tibi

![image](https://user-images.githubusercontent.com/50194/82038082-4c2bdc80-96a3-11ea-9cf1-f2e599b93269.png)

**Comment by vivadavid** [comment]
Hi,

I agree with @Tibi that it would be great to have this type of behaviour on the persistent feature. Would it make sense for Ueli to perform the search again, in case there are new results, or just show the results of the previous search?

I haven't used a launcher for quite some time and today I reinstalled Ueli. The latest changes, especially the UWP support, are great!

**Comment by Tibi** [comment]
PowerToys has this too.

**Comment by tomaskall** [comment]
I would pay to get "history" of my old searches.

**Comment by oliverschwendener** [comment]
> I would pay to get "history" of my old searches.

Try pressing <kbd>Shift</kbd>+<kbd>ArrowUp</kbd> or <kbd>Shift</kbd>+<kbd>ArrowDown</kbd> ;)

**Comment by tomaskall** [comment]
> > I would pay to get "history" of my old searches.
> 
> @tomaskall Try pressing Shift+ArrowUp or Shift+ArrowDown ;)

Great, one mer thing I miss from Launcy if i have "Memo_John.txt" and "Memo_Alice.txt" and the one i uses the  most(or the last time) is "Memo_John.txt", i would like UELI to rember the last "choosen" alternative (if you understand me) and suggest that one first, is that possible?

Is there a way to pay/donate for this good product?

(really like i can google directly from UELI, that makes a big

**Comment by oliverschwendener** [comment]
This issue should be solved with the latest beta release of ueli v9. You can try it out here: https://github.com/oliverschwendener/ueli/releases

@tomaskall If you want to support this project financially, you can sponsor me on GitHub here: https://github.com/sponsors/oliverschwendener

**Comment by vivadavid** [comment]
Now when I run Ueli again, I get the previus search results: thanks!

As for the search history, I've enabled it, but the mouse pointer becomes a traffic sign and there are no results to show.

**Comment by oliverschwendener** [comment]
You first have to search and invoke something, before the search history is populated. When you turn off the search history, it will be cleaned.

**Comment by vivadavid** [comment]
> You first have to search and invoke something, before the search history is populated. When you turn off the search history, it will be cleaned.

That's the way I'm trying, but it's not working for me.

**Comment by vivadavid** [comment]
There's now a result on the history, but I've typed "LibreOffice" a few times and it doesn't appear there.

**Comment by oliverschwendener** [comment]
The search term is only saved when you invoke a search result item by hitting enter. Did you try that?

**Comment by vivadavid** [comment]
I've found out what happened: if I hit enter, the result appears on the history. However, if I click on the result with my mouse, it doesn't appear. Could this be fixed, please?

**Comment by oliverschwendener** [comment]
Oh, true. The issue will be fixed with the next version. Thanks for reporting!
