### ISSUE TITLE
PowerShell Commands

### ISSUE THREAD

**Issue by lampenlampen** [oliverschwendener/ueli#39]
### PowerShell Commands

Ability to execute PowerShell commands

**Comment by oliverschwendener** [comment]
You can execute powershell commands like this:

![image](https://user-images.githubusercontent.com/15727229/42051693-fd14c926-7b0c-11e8-9f32-25be3df55f28.png)

![image](https://user-images.githubusercontent.com/15727229/42051711-09a8a0b8-7b0d-11e8-9486-61c4761727a4.png)

**Comment by lampenlampen** [comment]
Is it possible to include a setting in the config-file to set PowerShell as the default console?

Or better: a setting with the path to a console.
This way it is possible to use PowerShell Core.

**Comment by oliverschwendener** [comment]
There is no such thing like a "default console". Ueli does not have an interactive console, you can only see the output of a commandline program.

If you type in `>{some command}` the command is not interpreted by a shell (like cmd or powershell) but by the operating system itself (like the "Run" dialog in Windows). For example if you type in `>ipconfig` and hit enter there is no cmd or powershell involved. Windows directly executes `ipconfig.exe` which is in `C:\Windows\System32\`. When you type in `>powershell {some powershell command}` Windows will execute `powershell.exe` and powershell will interpret your powershell command as an argument.

So I don't really get what kind of behaviour you would like to have?

**Comment by lampenlampen** [comment]
I thought a console is running in the background  and wanted the ability to change this console to another one.

You can close this issue.
