### ISSUE TITLE
Feature request: Add support for mouse interaction

### ISSUE THREAD

**Issue by pb29** [oliverschwendener/ueli#393]
did i miss something or just there's no feature to click on search results?
please make able to click on them to execute!

**Comment by AmrBinBashir** [comment]
I've been thinking about it for a while, I will make a PR to add it when I have the change.

**Comment by vivadavid** [comment]
I created this thread yesterday (https://github.com/oliverschwendener/ueli/issues/399) and now that I see this thread, I think we refer to the same thing. Before I posted, I just searched for the word "mouse" and that's why I didn't find this. Sorry for duplicating requests.

**Comment by kitwit87** [comment]
I would also like this functionality! Thanks!

**Comment by n158** [comment]
This is a killer feature for me. I am a heavy mouse user, so without ability to click on a search result this cool app is worthless to me.

**Comment by Warden20** [comment]
+1

**Comment by underthecocotree** [comment]
@olivereisenhut would that be a click to highlight, double click to execute?  Or a single click and open?

**Comment by oliverschwendener** [comment]
Hover: highlight
Single click: execute
Shift+Click or something similar: open location if possible

**Comment by freedsny** [comment]
PLEASE, Add support to click the result and also to open the file uvication, (Open Path), it is very necessary

**Comment by freedsny** [comment]
> ‎Hover: resaltado‎
> Single click: execute
> Shift+Click or something similar: open location if possible

wonderfull, yes

**Comment by freedsny** [comment]
First of all, thank you very much for such a great application, more and more Alfred stops, but for windows, It would be very useful if they could add options that Alfred or Wox has, such as being able to navigate between folders from there, that is, from the same results without leaving,  **and also the right click function: (copy, paste, cut, execute as an administrator, open location, open selected search with one click),** as it is a bit ugly to have to use the arrow keys or arrow keys on the keyboard.

**Thank you very much for listening, I appreciate your effort.**

----------------------ESPAÑOL-----------
Primero que todo, muchas gracias por tan genial aplicacion, cada vez más se para a Alfred, pero para windows, sería muy útil que pudiesen agregar opciones que tiene Alfred o Wox, tal como poder navegar entre carpetas desde ahi mismo, es decir desde los mismos resultado sin salirse , y también la función de clic derecho: (copiar, pegar, cortar, ejecutar como administrador, abrir ubicación, abrir búsqueda seleccionada con un clic), pues es un poco feo tener que usar las teclas de dirección o flecas del teclado.

Muchas gracias por escuchar, les agradezco su esfuerzo. 
![Captura de pantalla (5)](https://user-images.githubusercontent.com/81711459/113493535-a5605280-94a5-11eb-8c06-de8c8a90a60a.png)

**Comment by freedsny** [comment]
please add support for mouse interaction, Right click, open location, run as administrator,  take ownership, copy, paste. Thanks

**Comment by ForsakenHarmony** [comment]
BTW @freedsny there's no need to add a Spanish translation to your comments / issues, English is more universal and if the owner/maintainer doesn't speak Spanish better than English it just adds noise

**Comment by fourteen-1** [comment]
Any updates to the implementations of this feature? Did the dev ever confirm anything?

**Comment by ForsakenHarmony** [comment]
https://github.com/oliverschwendener/ueli/tree/beta/ueli-9

**Comment by onlytanmoy** [comment]
> Any updates to the implementations of this feature? Did the dev ever confirm anything?

Don't think it is implemented yet, I just checked in the new version of ueli today.

**Comment by ForsakenHarmony** [comment]
@oliverschwendener do you have any ETA for ueli 9?

**Comment by oliverschwendener** [comment]
Not really. As this is a project that I work on only in my free time (which is quite limited at the moment unfortunately 😅) I can't promise anything, sorry!

**Comment by freedsny** [comment]
Thank you for listening to me and answering, I hope and you can reconsider, very respectfully you hear itWell, having support for interaction with the mouse would give it a lot of functionality and I know that to all its fans of this aol they would like to

Gracias por escuchar
________________________________

**Comment by fourteen-1** [comment]
> Any updates to the implementations of this feature? Did the dev ever confirm anything?

More than a year later, still waiting for this feature. Its really easier to click the mouse than to press enter to select a search result.

The mouse can be used to scroll through the results, but why not make it click the results as well? I don't know much about coding, but is it a difficult thing to program?

**Comment by TaylorJKing** [comment]
Pleeeasseee mouse support! This is the best searcher for Windows that I've used so far; but the lack of being able to click on a result is really bad. Thanks

**Comment by oliverschwendener** [comment]
Support for mouse interaction has been added in v9. Check out the alpha releases if you're interested.

**Comment by vivadavid** [comment]
> Support for mouse interaction has been added in v9. Check out the alpha releases if you're interested.

That's great! Thanks!

**Comment by vivadavid** [comment]
Hi, again,

I've just tried version 9.0.0 alpha 5 and I thought the mouse still didn't work, but then I realized you need to double-click on the result you want to open. Would it be possible to open the result with just one click?

Thanks.

**Comment by oliverschwendener** [comment]
I think a single click should select an item.

**Comment by vivadavid** [comment]
When you point to a result, that's already selected: the colour changes anyway. I think it'd be faster to open the result with just one click.

**Comment by oliverschwendener** [comment]
Hovering over the result doesn't select it, it just highlights it. I think the current behavior is the best option, I also checked other applications/UI libraries and most of them do it this way.

I could make it configurable though, so a user can choose what action they want on single click/double click.

**Comment by vivadavid** [comment]
In PowerToys, for example, you single click to open a result. It would be truly appreciated if you could make it configurable.

**Comment by oliverschwendener** [comment]
In Raycast on the other hand you select an item on single click ;)

**Comment by oliverschwendener** [comment]
I'll add this settings later today and release another alpha version, feel free to test it.

![image](https://github.com/oliverschwendener/ueli/assets/15727229/572629ad-e379-44bd-9618-ae7060f3d6b5)

**Comment by vivadavid** [comment]
I will: thanks!

**Comment by BobbySherman** [comment]
This is great! Do you have a timeline on your next release? Will this be included? Thanks! This app is slick!

**Comment by oliverschwendener** [comment]
There is no detailed timeline, but I want to fix/implement some missing things before doing an official v9 release:
- add support for commandline programs in the Shortcuts extension
- add support for workflows in the Shortcuts extension
- add a automatic rescan scheduler
- add more window options for multiple screens

Until then feel free to try out the alpha releases here: https://github.com/oliverschwendener/ueli/releases
