### ISSUE TITLE
commandline plugin pends the execution of the app until shell is closed

### ISSUE THREAD

**Issue by AmrBinBashir** [oliverschwendener/ueli#395]
The command line plugin pends the execution of the app until the shell is closed. What if I want to run 2 different commands in two seprate windows. 

![commandline plugin bug](https://user-images.githubusercontent.com/48618675/82259593-2aa94a00-995c-11ea-8af2-692e672db28c.gif)

I think the issue happens because of this commit 	5a4fbd7c7db8ac43a2b7fd4b5211a14a24480a9d

**Comment by oliverschwendener** [comment]
Maybe we should resolve the execution promise instantly in the commandline plugin and not wait for the actual program to exit.

**Comment by AmrBinBashir** [comment]
Yeah that would work.

**Comment by oliverschwendener** [comment]
Fixed in the newest release.
