### ISSUE TITLE
Receiving "invalid workflow" when trying to create new workflow

### ISSUE THREAD

**Issue by gtjamesa** [oliverschwendener/ueli#398]
I'm not sure when this first started as the last workflow I created was a few months ago, however, I have updated to 8.7.0 and the problem still persists. The screenshot shows the error when trying to add the example CLI command

![](https://i.imgur.com/egmHAE4.png)

**Comment by oliverschwendener** [comment]
You have to press the green + button to add the execution step to the list. I know there should be an indicator that the list is currently empty. This can be improved. Feel free to create a separate issue for this.

**Comment by gtjamesa** [comment]
Well, I feel silly - thanks!

I think an improvement would be when clicking save and there is content in the command textbox, it should apply that to the list before proceeding with the save action

**Comment by altryne** [comment]
agree to the above comment btw, It took me like 10 minutes figuring out why the workflow can't be saved, until I googled my way here. 
The UI should at least suggest to "save" your command
