### ISSUE TITLE
Mouse functionality

### ISSUE THREAD

**Issue by vivadavid** [oliverschwendener/ueli#399]
Hello,

I've noticed that I can't open a search result by double-clicking with the mouse. Even if it makes more sense to use Ueli with your keyboard, in a few occasions I've found myself reaching for the mouse to click on a search result that was in middle of the list.

The only thing I can do with my mouse, as far as I can see, is to scroll up and down though the search results using the mouse wheel or dragging the scrollbar. However, if I click on a particular search result, nothing happens: it won't even get highlighted.

If that's the expected behaviour, I was wondering if you would consider to add mouse support. Thanks!

**Comment by oliverschwendener** [comment]
Closing this due to duplication: #393.
