### ISSUE TITLE
Launching UWP apps installed from the Microsoft Store

### ISSUE THREAD

**Issue by 7automaton** [oliverschwendener/ueli#404]
Hello,

As of right now, Ueli can only launch preinstalled UWP apps, such as the built in Microsoft Edge, Mail and Calendar apps. I'm not able to launch Spotify from Ueli, when installed from the Microsoft Store.

Could we expect to see this functionality at some time?

**Comment by tkohlmeier** [comment]
Since version 8.7.0, ueli should find all installed UWP apps.

**Comment by 7automaton** [comment]
I updated and tried it, and it works well. Thanks guys.
