### ISSUE TITLE
Web Search Engine only replaces {{query}} wilcard first time in url [bug] 

### ISSUE THREAD

**Issue by bastiMQ** [oliverschwendener/ueli#408]
I've created a custom search engine for a Confluence page with the {{query}} wild card used twice.
But only the first {{query}} wildcard will be replaced with my search keyword
e.g.
`https://my-domain.com/confluence/dosearchsite.action?cql=siteSearch+~+"{{query}}"+and+space+%3D+"CUSTOM"&queryString={{query}}`

If I use this search engine with e.g. "Reviews" I'll get the following URL:

`https://my-domain.com/confluence/dosearchsite.action?cql=siteSearch+~+%22Reviews%22+and+space+%3D+%22CUSTOM%22&queryString={{query}}`

Strangely another custom search engine, I created for Google Shopping, also has 2 {{query}} entries and works just fine:
`https://www.google.com/search?tbm=shop&hl=de&biw=&bih=&q={{query}}&oq={{query}}`

![search_engine-bug](https://user-images.githubusercontent.com/3727554/82896980-28944c00-9f57-11ea-9a11-2d50b9b9a05f.png)

**Comment by weiwang11** [comment]
Is searching `g? test` suppose to include the space? Or should we be using `g?test` when searching?

**Comment by bastiMQ** [comment]
> Is searching `g? test` suppose to include the space? Or should we be using `g?test` when searching?

As far as I know due to testing, everything that comes **after** the prefix will be interpreted as the query
So if your prefix is `g?`, you can simply search via   `g?search-term`   but   `g? search-term`   will also work fine. It will just include the space(s) into your query. (the resulting google search will strip your white spaces anyway)
Since I don't like to type question marks on every query, I just used a space inside my prefix. Otherwise I would have to type `gwhats the weather like` which looks uglier to me than typing `g search-term` 
See example image below
![image](https://user-images.githubusercontent.com/3727554/82925034-7c199080-9f7d-11ea-8f01-1ed50cbfc74b.png)

**Comment by weiwang11** [comment]
Oh that's great, I just wanted to make sure since I haven't tested how it works prior to fixing the issue. I was using your settings to check my code but since it didn't show the space, I was really confused why my search urls are coming out differently than the one on your post.

**Comment by oliverschwendener** [comment]
Fix should be available in the newest release.
