### ISSUE TITLE
Cannot open settings

### ISSUE THREAD

**Issue by Lambada10** [oliverschwendener/ueli#409]
![image](https://user-images.githubusercontent.com/62511588/82901653-8a0be900-9f5e-11ea-9d83-9bcdddbed9a7.png)
I can't open settings of ueli. I tried reinstalling but it doesn't help. `Ctrl + i` also don't works.
I am using windows 10 build 19041.264

**Comment by tkohlmeier** [comment]
I don't think this screenshot is from ueli. Do you have PowerToys Run installed? If so, close it and then start ueli again.

**Comment by oliverschwendener** [comment]
Yes, I don't think that you are using ueli.

**Comment by Lambada10** [comment]
Oops.
I thought that is an update.
