### ISSUE TITLE
Activity indicator to make background processes visible

### ISSUE THREAD

**Issue by neikei** [oliverschwendener/ueli#41]
Hi Oliver,

is it possible to integrate something like a progress bar to make a background progress visible?

Use Case: You run a cmd (Windows) or shell (Mac OS) command which doesn't show output directly, because it will collect some data first and you don't know if your entered command started proberly until the output is shown.

Idea example (just a javascript for rotating spinner): http://spin.js.org/

Best regards and thanks for the great project. 👍

**Comment by khanhas** [comment]
Replace SVG of search icon should do, no need a dependency.
I'm using this one for my fork:
```html
<svg viewBox="0 0 32 32">
    <g id="surface1">
        <path d=" M 18.914 31.995 C 17.406 31.984 16.152 30.835 16.013 29.336 C 15.873 27.838 16.895 26.478 18.375 26.191 C 22.267 25.278 25.303 22.238 26.204 18.349 C 26.411 17.313 27.163 16.47 28.169 16.143 C 29.175 15.817 30.28 16.058 31.057 16.774 C 31.835 17.49 32.165 18.569 31.921 19.597 L 31.926 19.597 C 30.54 25.711 25.773 30.495 19.656 31.91 L 19.656 31.905 C 19.41 31.969 19.157 32.001 18.904 32 L 18.914 31.995 Z "/>
        <animateTransform attributeName="transform" type="rotate" from="0 16 16" to="360 16 16" dur="1800ms" repeatCount="indefinite"></animateTransform>
    </g>
</svg>
```
https://streamable.com/0bdfx
Simple and fit UELI style

**Comment by oliverschwendener** [comment]
Thank you for your feedback. I will look into it as soon as possible.

**Comment by oliverschwendener** [comment]
I added a message (in this example `Started "ping" with parameters: "1.1.1.1"`) which indicates that a command line tool has started. Does that satisfy your needs?

![image](https://user-images.githubusercontent.com/15727229/42442304-97c731ce-836a-11e8-8caa-cb122237d9fb.png)

**Comment by neikei** [comment]
Good idea! What does it look like if several parameters are specified?

```bash
# Example with parameters
ping -n 8 -w 20 1.1.1.1
```

**Comment by oliverschwendener** [comment]
![image](https://user-images.githubusercontent.com/15727229/42452917-97cbbd9a-838b-11e8-83b8-95c49e710020.png)

**Comment by oliverschwendener** [comment]
This will be included in the next release.
