### ISSUE TITLE
You can't write anything if RDP session is running

### ISSUE THREAD

**Issue by TheFlighteur** [oliverschwendener/ueli#412]
Hello,
I'm loving this software but when I have an RDP connection, even minimized, I can't write anything in the search field of ueli on my main computer.

Has this issue already been raised or encoutered ?

**Comment by oliverschwendener** [comment]
Maybe related to #135 ?

**Comment by TheFlighteur** [comment]
No it isn't the same bug. 
the shortcut functions properly but I can't write anything in the search bar, I have no blinking cursor and the bug disapears as soon as I close my rdp connections and reappears as soon as I reopen one, everytime.

**Comment by weiwang11** [comment]
Not really, everything should be the default besides file sharing which I don't think affects input.

Do you have some other program interfering with the input?

**Comment by TheFlighteur** [comment]
No, I don't think I have programs that would interfere. I'll check what I have.

**Comment by TheFlighteur** [comment]
Hello, I've checked my computer and I don't have any program that would interfere with the keyboard and the Antivirus isn't registerin ueli as a threat. I don't know what is happening

**Comment by weiwang11** [comment]
Did you change any of the following settings? The values below should be the default values:
![](https://i.imgur.com/qZYIeXi.png)
![](https://i.imgur.com/IoBAsq0.png)

If that still doesn't work, try rebooting your local and remote machine.

**Comment by TheFlighteur** [comment]
Hello,
I haven't seen the bug recently, maybe rebooting my computer worked. For now I'll close the issue until I see it reappear.
