### ISSUE TITLE
ueli search panel rises to the up-left corner of the screen after typing each letter

### ISSUE THREAD

**Issue by samirmmdv** [oliverschwendener/ueli#415]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/66056492/83275741-a7e88080-a1e0-11ea-8266-0524dcbfc78e.gif)
Ueli search panel rises to the up-left corner of the screen after typing each letter. As you can see from here.

**Comment by weiwang11** [comment]
[Known bug](https://github.com/oliverschwendener/ueli#known-bugs) if your windows scaling is set to a custom scaling value.

**Comment by samirmmdv** [comment]
@weiwang11 thanks so much!
