### ISSUE TITLE
crash when doing a google search

### ISSUE THREAD

**Issue by michabbb** [oliverschwendener/ueli#42]
i enter `g?something` :

![13-07-2018-02-39-52](https://user-images.githubusercontent.com/3524595/42692054-9aa50b08-86aa-11e8-93e2-0e002f0bf45e.png)

![13-07-2018-02-40-16](https://user-images.githubusercontent.com/3524595/42692069-a902133a-86aa-11e8-8ee2-c1c437aadaa3.png)

seem like it has something todo with _rights_ .

os: windows 10
browser: chrome

thanks for any help

**Comment by oliverschwendener** [comment]
Where did you install ueli?

**Comment by michabbb** [comment]
the installer saved it to `C:\Program Files\ueli`

**Comment by oliverschwendener** [comment]
What happens if you open Command Prompt and execute the following command?

```
start "" "https://google.com/search?q=test"
```

**Comment by michabbb** [comment]
first i get this:

![13-07-2018-06-12-29](https://user-images.githubusercontent.com/3524595/42701976-4e2d076c-86c8-11e8-995a-bdee2735e2ae.png)

and the cmd shows me: `Zugriff verweigert`

**Comment by michabbb** [comment]
the funny thing is, i remeber the first day of using ueli, it worked. in the meantime i got a windows update and maybe chrome too, i don´t know. so it´s very strange that this stopped working.

**Comment by michabbb** [comment]
yes i have, it looks the same: i use chrome

**Comment by oliverschwendener** [comment]
Ok never mind.

The problem seems to be on operating system level and not in ueli. You should be able to open up a web page from the command line with the command I mentioned before. This is how ueli opens up web pages with your default browser.

**Comment by oliverschwendener** [comment]
What happens if you change your default browser?

**Comment by michabbb** [comment]
when i switch to edge, it´s working. back to chrome: same error. stupid... i guess i have to google a bit 😕

**Comment by oliverschwendener** [comment]
Then I guess it has something to do with your chrome installation

**Comment by michabbb** [comment]
but: [this](https://stackoverflow.com/a/23039509/1092858) is working: `explorer "http://google.com"` without any problems 🤔

**Comment by michabbb** [comment]
don´t know if it has something todo with it: 

i am using a insider build of win10: `Version 1803 (Build 17692.1004)`

**Comment by oliverschwendener** [comment]
Can you downgrade?

**Comment by michabbb** [comment]
@oliverschwendener guess i can, but why should i change my OS because of _THIS_ ? 😏 the next WIN update will come, insider build or not. so at the end, i cannot stay the rest of my life at an older version only because i want a search working with ueli, hopefully u understand this 😏 maybe `explorer`  is working for you and all others, too - i don´t know - if yes, i might be worth a change - that´s up 2 you.
anyway, thank you very much taking time to debug this 🙏

**Comment by oliverschwendener** [comment]
Of course I don't expect you to stay on an old version of Windows only to be able to google with ueli:) Nevertheless I consider this issue as closed now because I suspect it only affects the insider build.

**Comment by michabbb** [comment]
@oliverschwendener do you see any problems changing 

`start "" "https://google.com/search?q=test"`

to 

`explorer "https://google.com/search?q=test"`

❓

**Comment by oliverschwendener** [comment]
What happens if you execute following command in cmd: 

```
start explorer "https://google.com/search?q=test"
```

?

**Comment by michabbb** [comment]
works 😏

**Comment by oliverschwendener** [comment]
Allright, then this is the way :)

**Comment by oliverschwendener** [comment]
@michabbb What happens if you execute this command from cmd:

```
powershell -Command "& {[Diagnostics.Process]::Start('https://google.com/search?q=test')}"
```

Do you still get this error?

**Comment by michabbb** [comment]
the issue is closed for me since a long time, I actually don't use ueli any longer for Google search, but I can try....

**Comment by michabbb** [comment]
@oliverschwendener your command is working. but anyway.. with your latest version i don´t have any problems (so far).
