### ISSUE TITLE
Dropdown menu looks odd with scaled display settings

### ISSUE THREAD

**Issue by LalaGhost** [oliverschwendener/ueli#422]
I have 2560 * 1440 screen and when I change the scale of the screen under Windows' "Display Settings" to 150% the dropdown in ueli are cutoff, the outer most line to display the end of the dropdown is not there(see screenshots).
It only works for one screenshot, the last one.

<img width="741" alt="Screenshot_1" src="https://user-images.githubusercontent.com/43962138/84006955-e8c65f00-a96f-11ea-98af-c54297698403.png">
<img width="751" alt="Screenshot_2" src="https://user-images.githubusercontent.com/43962138/84006956-e95ef580-a96f-11ea-933b-5cce6014fde6.png">
<img width="759" alt="Screenshot_3" src="https://user-images.githubusercontent.com/43962138/84006958-e9f78c00-a96f-11ea-9a4e-f70be4f4bb19.png">
<img width="754" alt="Screenshot_4" src="https://user-images.githubusercontent.com/43962138/84006959-e9f78c00-a96f-11ea-861b-0e796b6f14d6.png">
<img width="748" alt="Screenshot_5" src="https://user-images.githubusercontent.com/43962138/84006960-ea902280-a96f-11ea-82a1-0f70c49ddc24.png">
<img width="749" alt="dropdownMenuCorrect" src="https://user-images.githubusercontent.com/43962138/84006961-ea902280-a96f-11ea-82b4-cca2e1e6b220.png">

**Comment by oliverschwendener** [comment]
I assume that this will be fixed with ueli v9. You can try it out here: https://github.com/oliverschwendener/ueli/releases
