### ISSUE TITLE
[Feature Request] Show a new user the default hotkey

### ISSUE THREAD

**Issue by LalaGhost** [oliverschwendener/ueli#423]
I just installed the newest version of Ueli and noticed that if a new user does not how to open Ueli, he has to try several different hotkeys, since the installer does not say anything regarding opening it.
**I** know that it is Alt + Space for me, but a new user will having trouble opening it the first time, bad first experience.
Maybe add it to the last screen of the installer or something like this.

**Comment by oliverschwendener** [comment]
We have now a wiki where the first steps are described: https://github.com/oliverschwendener/ueli/wiki/Getting-Started#first-steps
