### ISSUE TITLE
latest update broke all application shortcuts on win10

### ISSUE THREAD

**Issue by eskoONE** [oliverschwendener/ueli#427]
im on win10 1909 and ueli 8.7.1. 

8.7.0 and the patch before that already broke shortcut icons to applications installed and now it doesnt show any installed application shortcuts at all.

doing a clean install didnt help.

edit:

refreshing index and clearing cache didnt help either.

**Comment by tkohlmeier** [comment]
Alright, now the error `Unexpected token C in JSON at position 2` makes sense. It's the `C` from `CommandType` that is not expected.

Don't be sorry, this was not your fault. Setting an alias should not break ueli's functionality...

>what i dont understand is, why was this working before and randomly stopped working in the later updates. funnily enough, it also fixed my issue with not seeing application icons.

The icon problem was not related to the problem of not finding any applications. The latest release includes a fix for application icons, so this explains why that works now, too.

One more thing: Did the output you got from the command [here](https://github.com/oliverschwendener/ueli/issues/427#issuecomment-642073030) really not contain that `CommandType` part?

**Comment by eskoONE** [comment]
no it didnt. 

it did after i removed the alias and ran the command through vs codes terminal like you suggested and it did ouput the first few likes like you expected.
