### ISSUE TITLE
Plugin support?

### ISSUE THREAD

**Issue by bantya** [oliverschwendener/ueli#43]
Are there any plans to add plugin support to the app? The utility is very handy and it will help to have even more flexibility (say plugin for dash documentation etc.).

**Comment by oliverschwendener** [comment]
I understand that it would be very helpful but there are no plans yet to support plugins. Mainly because I have no idea how to do it :) I would have to implement some kind of plugin manager which installs/uninstalls plugins and checks compatibility with the current ueli version and so on.

**Comment by oliverschwendener** [comment]
Closing this issue for now because I have no plans to implement a package/plugin manager.
