### ISSUE TITLE
Show again icon in taskbar

### ISSUE THREAD

**Issue by lucascrezende** [oliverschwendener/ueli#432]
I installed on Windows 10 and chose to not to show in taskbar, but now I want to change somethings and I cannot open the settings again. How can I show again the icon in taskbar so I can right-click and open configurations? Thanks.

**Comment by AmrBinBashir** [comment]
You can press `Alt+Space` to show the launcher then press `Ctrl + i` to open the settings. You should see the option to show tray icon.

**Comment by lucascrezende** [comment]
Perfect. Worked as expected. Thank you!
