### ISSUE TITLE
Shortcut to windows terminal hangs UELI

### ISSUE THREAD

**Issue by gabriel-peracio** [oliverschwendener/ueli#433]
After struggling with sometimes not being able to type anything in UELI, I've narrowed the problem to the new Windows Terminal.

## Steps to reproduce
1. Launch `windows terminal (Preview)` from UELI from a shortcut (type: "Commandline Tool", command: "wt")
2. Press the hotkey that invokes UELI
3. You cannot type anything
4. Close the `windows terminal (Preview)` window that you opened
5. Press the hotkey that invokes UELI
6. You can now type again

With a terminal window open, restarting UELI also fixes the problem, allowing you to use UELI freely.

Launching windows `windows terminal (Preview)` through another mechanism (without using UELI, or using ueli but choosing the UWP app instead of the shortcut) does not trigger the bug, and UELI remains usable.

I believe this is due to some weird interaction where launching a terminal window does not return control or does not inform UELI that the launch was successful. However, launching `wt` from `cmd` does not result in this bug, and `cmd` remains usable.

**Comment by AmrBinBashir** [comment]
This is similar to #395 , I will add a pr to fix this soon.

**Comment by gabriel-peracio** [comment]
By the way, this issue is still present in ueli `8.7.1`, even though it was marked as fixed in #395

**Comment by AmrBinBashir** [comment]
Yeah , the fix was for commandline plugin only, the issue in your case is with the shortcut plugin. The error is the same but in different plugins. I add a new PR to fix the error in both shortuctus and workflow plugins. 
Once oliver approves and merges the PR, it will be fixed. So I hope it will be in the next release.

**Comment by oliverschwendener** [comment]
Can someone check if this is still an issue with the latest v9 release? https://github.com/oliverschwendener/ueli/releases
If so, feel free to reopen.
