### ISSUE TITLE
[Discussion] A mix between execution and search plugin.

### ISSUE THREAD

**Issue by AmrBinBashir** [oliverschwendener/ueli#434]
I am trying to make a Process Killer plugin for ueli, and I have an idea that might be interesting. 
I want to getSearchResults only on the first invocation of the plugins then filter these results by the userInput. 

#### For example:
1. The user inputs `kill` which invokes the process killer plugin to get an array of processes.
2. The user goes on typing `kill spotify` and that would filter the array to only show results containing spotify.

Do you have any plans to add something like this ?

**Comment by tkohlmeier** [comment]
Wouldn't it be better to retrieve the currently running processes and filter them instead of all possible search results?

**Comment by AmrBinBashir** [comment]
I plan on getting all current running process with the cmdlet `Get-Process`, although I can pass userInput to this cmdlet and powershell will filter process but calling a powershell process takes some time so this approach won't be the best performance. Instead of that, I want to retrieve it once, then filter it inside ueli.

I think this mix can come in handy in the future.

**Comment by AmrBinBashir** [comment]
Closing this as it can be done with simple `if` check.
