### ISSUE TITLE
[Bug] opening apps as as admin does not work sometimes

### ISSUE THREAD

**Issue by maxiar** [oliverschwendener/ueli#436]
If I search the Visual Studio 2019 App into UELI, and then I open with Shift+Enter this opened as administrator correctly, like other apps.. BUT If I Open a every ***.sln (VS 2019 project file)** with Shift+Enter **Nothing happen**... 

In order to reproduce the error, first add a custom folder (with some *.sln) to Applications Menu and add the .sln files extension as valid program to ueli detect the apps. :)

Can I do some workaorund to open my *.sln as admin?

NOTE: I has the ueli latest version.

**Comment by oliverschwendener** [comment]
Can you try it again with the latest version? Feel free to reopen this issue if it doesn't.
