### ISSUE TITLE
Feature Request: Option to add "Win" key as hotkey

### ISSUE THREAD

**Issue by IronSuit** [oliverschwendener/ueli#438]
I would love the ability to run ueli instead of windows search when pressing the "win" button.

Ueli has effectively replace windows search for me, so i feel like i have two useless buttons on my keyboard, it would be much faster if we can launch ueli using only one button (in my case it's the win key)

**Comment by skjerns** [comment]
Plus one for this! 

I did this with Flow.Launcher, simply replace disable Win-Key by OpenShell and then use it as a hotkey for toggling the search. This is the only thing keeping me from switching to UELI which looks much better&faster overall

**Comment by oliverschwendener** [comment]
Ueli now supports all global shortcuts that are supported by electron, see here: https://www.electronjs.org/docs/latest/api/accelerator

Note that there are some limitations when using Super (Win key): https://github.com/oliverschwendener/ueli/issues/454#issuecomment-907609417
