### ISSUE TITLE
Custom theme support?

### ISSUE THREAD

**Issue by NeedsAdjustment** [oliverschwendener/ueli#44]
Same as title ^ would be cool to be able to make colour changes/deeper css tweaks akin to what u/khanhas has done with his fork

**Comment by oliverschwendener** [comment]
Thanks for your feedback! I will look into it.

**Comment by oliverschwendener** [comment]
I added the option to specify a custom user stylesheet (see: [documentation](https://github.com/oliverschwendener/ueli/tree/dev#custom-color-themes)). This will be released in the next release.
