### ISSUE TITLE
Chrome Bookmarks: Index additional roots

### ISSUE THREAD

**Issue by jondcoleman** [oliverschwendener/ueli#443]
Currently, only the bookmarks bar is indexed. You can also have bookmarks in Other Bookmarks (maybe also additional roots?)

![image](https://user-images.githubusercontent.com/11843663/85031852-2899fd00-b14d-11ea-8542-c625394259f1.png)

**Comment by oliverschwendener** [comment]
A fix for this is included in the latest release.
