### ISSUE TITLE
[Bug] Many Super hotkey combinations do not work under Windows 10

### ISSUE THREAD

**Issue by tvollstaedt** [oliverschwendener/ueli#454]
Didn't check other OS'es, but on Windows 10, ueli does not seem to recognize `Super+Space`, `Super+Plus`, and many more. That's probably because they are already taken by the OS. We should remove the ones that are not valid or show an conflict message to the user.

**Comment by docd27** [comment]
Getting this working will require using a [``WH_KEYBOARD_LL`` hook](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/ms644985(v=vs.85)) within some windows-specific native node module. Electron's ``globalShortcut`` ultimately calls [RegisterHotKey](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-registerhotkey) on Windows, which unfortunately fails for most ``Win + Key`` hotkeys already registered by the windows shell. See electron/electron#9206
Here's an example https://github.com/MarshallOfSound/node-lowlevel-keyboard-hook-win

This can be tricky to get right and it's a common issue in other launchers e.g. Wox-launcher/Wox#2445

Perhaps the best example of getting this to work well in practice is the [PowerToys Run launcher](https://github.com/microsoft/PowerToys) from Microsoft themselves - based on the Wox launcher but crucially does support ``Win + Key`` hotkeys unlike Wox proper.

Also unlike most other launchers it captures hotkeys when there's a privileged window in the foreground (by hooking the keystrokes in a subprocess running as Administrator and forwarding events to the non-privileged main UI process) and handles focus stealing well.

**Comment by oliverschwendener** [comment]
Thanks for the detailed answer @docd27

**Comment by oliverschwendener** [comment]
Closing this issue as I don't see a way to fix it.
