### ISSUE TITLE
Black list should be wildcard based.

### ISSUE THREAD

**Issue by amrbashir** [oliverschwendener/ueli#457]
I think it would be better to make the black list functionality depends on wildcard, for example `*uninstall*` should blacklist every searchResultItem that has `uninstall` in its name, on the other hand if it is just plain `rocketleague`  without `*`, it would block searchResultsItem if its name is exactly equal to `rocketleague`.

JS/TS has no support of wildcard so the solution would be to convert wildcard to regex. Unfortunately I am not good with regex, so the best I can do is to link this [package](https://github.com/sindresorhus/matcher).

**Comment by tkohlmeier** [comment]
You don't need to use regular expressions. I would rather suggest to use an npm package like this one: https://www.npmjs.com/package/wildcard

**Comment by AmrBinBashir** [comment]
They are quite the same, although the one you linked uses less regex than the one I linked. 
Anyway, I would be glad to help with a PR but making a manual implementation is beyond my capabilities.

**Comment by tkohlmeier** [comment]
The problem with regular expressions is that you would have to escape special characters of the user input. For example the `.` (dot) means *any character* in regular expressions. With the wildcard package you don't have to worry about that.

You can just add such a packge by running `yarn add <package name>`.

**Comment by AmrBinBashir** [comment]
The problem is I think oliver prefers if the solution is implemented manually. I tried to analyze these two packages source code so I might help but when I saw that both of them uses regex for some reason. I just gave up on trying to even think about the solution. It would be great If oliver agrees to use the wildcard package.
