### ISSUE TITLE
Find installed apps through Windows store?

### ISSUE THREAD

**Issue by TobiasDev** [oliverschwendener/ueli#46]
I know that Wox (a now looking dead launcher like this), was somehow able to also find Windows Store apps in the searches. Would this also be possible to add here?

**Comment by oliverschwendener** [comment]
This is related to (#38).

Wox is mainly C# code and thereby has better integration with Windows.

Ueli utilizes [node.js](https://nodejs.org) and to knowledge currently there is no way to get all UWP apps installed on a computer through node.js. If you know how to do it let me know ;)

I think [here](https://github.com/Wox-launcher/Wox/blob/master/Plugins/Wox.Plugin.Program/Programs/UWP.cs#L143) you can see how Wox gets all the UWP apps.

**Comment by oliverschwendener** [comment]
Closing all issues related to launching UWP apps on Windows for now because there is (to my knowledge) no way to get/launch UWP apps with node.js.

**Comment by Phibonacci** [comment]
[This article](https://answers.microsoft.com/en-us/windows/forum/windows_10-windows_store/starting-windows-10-store-app-from-the-command/836354c5-b5af-4d6c-b414-80e40ed14675) should help you.

Use the powershell command `Get-AppxPackage` to list the Installed Store Packages. Get only the desired columns with pipe `ft ColumnName1, ColumnName2 -AutoSize`.

i.e. : `Get-AppxPackage | ft Name, PackageFullName -AutoSize`

Then follow the article so find the command to start the app you found with the previous command.

**Comment by oliverschwendener** [comment]
Proper UWP support is now added in the latest release.
