### ISSUE TITLE
Ueli stops working after starting a workflow *Bug*

### ISSUE THREAD

**Issue by HangryDino** [oliverschwendener/ueli#462]
Hello,

I generated a workflow to open up different programs and documents. 
It contains the starting up of a Batch file and different cmd-lines.
The workflow works fine.
The problem occurs after that.
Ueli can be accessed by hotkey, but I cannot enter anything into the box.

**Comment by AmrBinBashir** [comment]
Until the bug is fixed, if Ueli hangs and you can't type anything, just hit `Ctrl + R`. This will reload the app window which is better than  closing the whole app.

**Comment by oliverschwendener** [comment]
See #433
