### ISSUE TITLE
[Bug] Built-in MacOS apps are not focused when launched

### ISSUE THREAD

**Issue by sashaweiss** [oliverschwendener/ueli#465]
First off, I love `ueli` and thank you for maintaining it!

I've noticed that the built-in MacOS apps - Messages, Contacts, Calendar, etc. - aren't focused when they're launched via `ueli`. This also seems to apply to stuff like preference panes. Weirdly, this also seems to affect Firefox.

I tried changing the `file-path-executor` to always use `osascript` to execute file paths, instead of using the Electron `shell.openItem`, which worked but made every file execution annoyingly slow. I also confirmed it's not an issue with the `shell.openItem` API itself, since I made a test Electron app that just launches Firefox and it focused it upon opening.

I suspect it has something to do with the `app.hide()` "return focus to the previously focussed app" workaround in `main.ts:hideMainWindow()`, since in my experiments disabling that seemed to fix the focus-on-launch issue (even though it reintroduced the issue that workaround fixed).

Any ideas on what might be happening? I'm able to repro this every time on MacOS X 10.15.5, as is @nathanshelly.

**Comment by oliverschwendener** [comment]
This is resolved with ueli v9, check it out here: https://github.com/oliverschwendener/ueli/releases
If this is still an issue feel free to reopen.

**Comment by sashaweiss** [comment]
Awesome, thanks so much for the note! Just tried it out, and really looking forward to it.
