### ISSUE TITLE
[Feature Request] Switch to another currency converter API.

### ISSUE THREAD

**Issue by Teraskull** [oliverschwendener/ueli#466]
The current one lacks a lot of currencies, as it includes only 32 out of 180.

https://rapidapi.com/natkapral/api/currency-converter5 would be a good alternative for free.

**Comment by GovindKrishnan** [comment]
+1

**Comment by oliverschwendener** [comment]
Ueli v9 supports more currencies:

![image](https://github.com/oliverschwendener/ueli/assets/15727229/63b30eff-1e47-4a1d-ab67-f9879be5cc75)

You can download the latest beta release here: https://github.com/oliverschwendener/ueli/releases
