### ISSUE TITLE
Show icons of programs

### ISSUE THREAD

**Issue by xXKeyleXx** [oliverschwendener/ueli#47]
It would be great if the icons for programs would be the ones you can seein the explorer too. For example the list entry of Steam should have the Steam icon, so I don't have to search for it in the list because an icon is way better to recognise than text.

**Comment by oliverschwendener** [comment]
Unfortunately this has to wait until i rewrite the current code base to async.

**Comment by oliverschwendener** [comment]
Finally! App icons are now shown by default! They are not perfect but it is better than nothing.

![native app icons](https://github.com/oliverschwendener/ueli/raw/master/img/doc/features/app-search.png)

Update is now available ;)
https://github.com/oliverschwendener/ueli/releases/tag/v7.0.0
