### ISSUE TITLE
Autostart

### ISSUE THREAD

**Issue by kumar007git** [oliverschwendener/ueli#471]
On General settings page, I enabled 'Autostart app on system startup' but, I don't see a shortcut in the startup folder or in the 'Run' registry keys in registry. When this setting is enabled how is Ueli autostarted, where is the shortcut or startup entry in the registry? Thanks.

**Comment by tkohlmeier** [comment]
On my system, it is in the registry, here:

`HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run\electron.app.ueli`
