### ISSUE TITLE
Indexes should refresh only when ueli is not in use.

### ISSUE THREAD

**Issue by aarjav24** [oliverschwendener/ueli#473]
Please consider modifying your code such that the app only refreshes indexes when the app is not in use. Currently, ueli updates the app every time I use it. Changing the period for rescan isn't that useful because when changes are made to folders and bookmarks and the indexes don't refresh automatically, it becomes an unwanted hassle.

**Comment by Queuecumbr** [comment]
I second this as well. There are many times I try searching for an app, but end up having to wait for the index to refresh. It would be nice if this was limited to refresh only in the background, and if a refresh is needed when visible, we can perform a manual refresh.

**Comment by oliverschwendener** [comment]
In the meanwhile as a workaround you can also just increase the "Rescan interval" in the general settings.

**Comment by oliverschwendener** [comment]
We've now moved the reindexing process to the background so you won't be interrupted. Make sure to update to the latest version to get this update.
