### ISSUE TITLE
[Feature Request] add actions/context menu to items

### ISSUE THREAD

**Issue by b-mq** [oliverschwendener/ueli#476]
Adding contextual actions (like right-clicking) on selected files/folder/apps would be a great addition.
Coming from Alred you can view actions via pressing the TAB key on the current selected item giving you even more possibilities to interact (like open with, reveal, delete, ...) rather than just launching/opening the selected file/application/folder

(Screenshot from Alfred)
<img width="605" alt="image" src="https://user-images.githubusercontent.com/3727554/87445525-7264ee80-c5f8-11ea-88fb-337344e680c6.png">

**Comment by MiCkSoftware** [comment]
Quicksilver does it too on tab press... A must have.
