### ISSUE TITLE
[Feature Request] Please, add this feature

### ISSUE THREAD

**Issue by ghost** [oliverschwendener/ueli#488]
HI! Ueli is cool, but this really annoys me, for example, I want to turn off a computer via Ueli and I write command "Выключить" (turn off) on Russian but my keyboard is English or German now and I get "Dsrk.xbnm" instead of "Выключить" and error "Nothing found"(((. Could you please add a feature, like in Google, when I write on Russian for example, but my keyboard is English or German and I get something like this: "Gj;fkeqcnf lj,fdmnt 'nj", Google understands, that I meant "Пожалуйста добавьте эту функцию". 

I hope, that You understood, what I meant, and You add this feature in the near future.

And maybe Ueli should understand when I write command with one or two typos)

**Comment by oliverschwendener** [comment]
Closing because original author was deleted.
