### ISSUE TITLE
Calculator Plugin to use with , instead of .

### ISSUE THREAD

**Issue by thebugfixnet** [oliverschwendener/ueli#49]
Maybe I am blind. But is there no option to switch from . to , in the calculator plugin? It is really annoying for a nearly perfect tool to  use the calculator plugin with the german keyboard layout and , as standard separator for digits.

102.4+102.2 works
102,2+102,2 do not work

**Comment by oliverschwendener** [comment]
Thank you for your feedback!

The problem here is that ueli is using [mathjs](https://github.com/josdejong/mathjs) to evaluate mathematical expressions. To my knowledge mathjs does not support any customization so that a `,` is recognized as a decimal separator. But I will look into this problem as soon as possible.

**Comment by khanhas** [comment]
mathjs also support array and `,` is used to separate array members. I don't think there is anything we can do about that except using another math evaluate package.

**Comment by oliverschwendener** [comment]
@khanhas Thank you for your research!

So apparently there is no way to get mathjs to work with `,` as a decimal separator and I am not willing to change the math library because of this issue. I am sorry but you have to stick with `.` as e decimal separator.

**Comment by tkohlmeier** [comment]
Maybe we could integrate another math parser that supports locales? After a quick search I found this:
https://www.npmjs.com/package/math-and-unit-parser
It supports setting delimiters based on locale or manually. We could add an option in the plugin settings to switch the parser and set delimiters.
What do you think?

**Comment by oliverschwendener** [comment]
Now available in the latest release: https://github.com/oliverschwendener/ueli/releases/tag/v8.10.0

**Comment by thebugfixnet** [comment]
Thank you so much! This is really helpful!!!

I'm really glad you build it in in this way!
