### ISSUE TITLE
[Bug] Search bar not opening in fullscreen in macOS Mojave

### ISSUE THREAD

**Issue by gaetgu** [oliverschwendener/ueli#493]
# FEATURE REQUEST:

Thanks so much for creating this!

I have been using this instead of Alfred for the past few days, and I like it much more so far - except for one thing - you can't use it in fullscreen. I think is because it acts as a window

![ueli_as_a_window](https://i.ibb.co/7KW2RhK/Screen-Shot-2020-08-15-at-4-11-37-PM.png)

instead of.... I don't really know, but whatever Alfred is. 

This isn't really all that bad, since it does switch to a new window where you can use it when opening it, but then you have to activate it again. 

I have no idea whether or not you are working on this right now, since I couldn't find any issues on this topic. If there is one, please point me to it and close this one!

## Example

![fullscreen_issue_example](https://i.ibb.co/gMWf9C8/ezgif-1-60c36fc9cef5.gif)

Thanks alot!
               \- gaetgu

**Comment by Semmu** [comment]
Having the exact same issue, disabling auto-hide on losing focus is a workaround, but it is not ideal.
Thanks for this app by the way!

**Comment by gaetgu** [comment]
> 
> 
> Having the exact same issue, disabling auto-hide on losing focus is a workaround, but it is not ideal.
> Thanks for this app by the way!

I actually had a magical fix, not sure what happened?

EDIT

It actually still happens occasionally, now kind of sporadically and not in any specific app.

**Comment by oliverschwendener** [comment]
Can someone confirm that this is still an issue with the latest version? If so feel free to reopen.
