### ISSUE TITLE
Search bar doesn't open when opening is bound to SUPER+SPACE [bug]

### ISSUE THREAD

**Issue by hucario** [oliverschwendener/ueli#494]
As written in title, I set the keybind to open ueli to `superkey` + `space`, as that's the keybind I had set for uLauncher on my Linux install. Unfortunately, as soon as I did that the launcher refuses to open. I can't find any way to access the settings without first opening the launcher.

**Comment by AmrBinBashir** [comment]
you can access settings by right clicking the tray icon and choose settings.

**Comment by hucario** [comment]
> You can access settings by right clicking the tray icon and choose settings.
> 
> If you're on windows (not sure about macOS) `super + space` is reserved for system so if you assign it to ueli it won't work for ueli.

I didn't even look for a tray icon, thanks!
