### ISSUE TITLE
Unsupported Mac OS version 20.0.0

### ISSUE THREAD

**Issue by haze** [oliverschwendener/ueli#501]
![image](https://user-images.githubusercontent.com/15584994/91125525-ec64aa80-e66f-11ea-9cdc-87eab5812576.png)

I'm running on Mac OS Big Sur 11.0 Beta (20A5354i)
(not sure if this an upstream problem of some library you are using, if so feel free to close)

**Comment by oliverschwendener** [comment]
Thanks for reporting! This is a bug 😅

**Comment by oliverschwendener** [comment]
Published a new release, which should support Big Sur.
