### ISSUE TITLE
Unable to use everything search

### ISSUE THREAD

**Issue by 11nonali23** [oliverschwendener/ueli#504]
When I use the command "es?" to search with everything, it does not work because it pops up a window that illustrates which command line options are available. 
I've checked the logs and the command run is: C:\Program Files\Everything\Everything.exe" -max-results 24 all.xlsx

**Comment by femto-code** [comment]
I also use Everything with ueli but in order for my setup to work I needed to download the command line tools additionally.
See [https://www.voidtools.com/downloads/](https://www.voidtools.com/downloads/) and scroll down to `Download Everything Command-line Interface`. Then just unzip the `es.exe` to a folder of your choice and give ueli the path.
I think this might help to solve your problem.

**Comment by 11nonali23** [comment]
This solved the issue. Thank you. Also and thumbs up to the Dev for the fantastic application.
