### ISSUE TITLE
Windows 10 - Everything default setup produces Command Line Options

### ISSUE THREAD

**Issue by meathrel** [oliverschwendener/ueli#505]
I'm having a problem (probably not a bug) with setting up Ueli and Everything on Windows 10. I've done the following:

1.  Install Everything x64 and Ueli on Windows 10 
2.  Settings is setup as follows:

![2020-08-27 11_15_40-New Issue · oliverschwendener_ueli](https://user-images.githubusercontent.com/2781934/91429813-b0d80500-e856-11ea-999a-d89f884cb88d.png)

3.  When I run a search using Ueli the following window appears:

![2020-08-27 11_16_21-New Issue · oliverschwendener_ueli](https://user-images.githubusercontent.com/2781934/91430190-c9e0b600-e856-11ea-856f-9b4e5f9b7a6f.png)

This also happens with the default prefix too.  I imagine that Everything is expecting something extra on the command line but I can't find online what to set this to.  Any advice?

thanks

**Comment by oliverschwendener** [comment]
See #504 or #317 or #233
