### ISSUE TITLE
Index / User Setting file name?

### ISSUE THREAD

**Issue by jensenyang922** [oliverschwendener/ueli#506]
Hey guys, I enjoyed the launcher a lot. 
I recently got a new laptop and wanted to copy my personal configuration to the new one.  Can anyone tell me the 
file name of the user configuration? thanks

**Comment by AmrBinBashir** [comment]
On old laptop: Open Settings > General, click the 3 dot icon from top right, choose export current settings and choose a folder to export the settings to.
On new laptop: Open Settings > General, click the 3 dot icon from top right, choose import settings and choose the file.

the file name is usually called, ueli.config.json

**Comment by oliverschwendener** [comment]
Thanks @AmrBinBashir for helping out!

**Comment by jensenyang922** [comment]
No problem, thank you for the reply!
