### ISSUE TITLE
F5 key to refresh indexes

### ISSUE THREAD

**Issue by crazy-max** [oliverschwendener/ueli#508]
Like Launchy it would be nice to be able to refresh indexes through `F5` key when keystroke launcher is displayed.

**Comment by GovindKrishnan** [comment]
> Like Launchy it would be nice to be able to refresh indexes through `F5` key when keystroke launcher is displayed.

Yea. That'll be intuitive

**Comment by oliverschwendener** [comment]
This is now solved with the latest update.

**Comment by crazy-max** [comment]
@oliverschwendener Thanks!
