### ISSUE TITLE
dict? not working

### ISSUE THREAD

**Issue by JaydevSR** [oliverschwendener/ueli#509]
It seems like the dictionary api that ueli uses no longer exists. I tried opening the url myself getting a 404 error. So, the dictionary api needs to be updated or fixed.

**Comment by oliverschwendener** [comment]
Works fine for me. Are you using the latest version?

**Comment by JaydevSR** [comment]
I checked it again and it was some problem with my firewall which was not allowing ueli internet access. I am really sorry for false issue. Thanks!
