### ISSUE TITLE
Does not find translated app name of system app

### ISSUE THREAD

**Issue by tliebig** [oliverschwendener/ueli#51]
Hi Oliver,

I'm happily using ueli on a german version of Win10. When trying to start the "Rechner" (Taschenrechner) however, Ueli doesn't find the application - it only finds "calculator" as "win:calculator".

Is there any way to make it find the translated app name as well?

**Comment by oliverschwendener** [comment]
Thank you for your feedback! I think this is related to #29 and #38.

The problem here is that there is no way to "search" for Windows' default UWP apps like Mail, Calendar, Calculator, etc. So these apps are hardcoded in [this](https://github.com/oliverschwendener/ueli/blob/master/src/ts/search-plugins/windows-10-settings-plugin.ts#L952) file. Maybe there is a way to add multi language support, but I still have to hardcode the names of the apps and os settings for every supported language. I will look into it!

**Comment by tliebig** [comment]
Hardcoding doesn't sound like the way to go.

The translated app names are available in the start menu, though. I've just googled "parse windows start menu", which came up with https://superuser.com/questions/171096/where-is-the-list-of-pinned-start-menu-and-taskbar-items-stored-in-windows-7 and https://docs.microsoft.com/en-us/windows/desktop/api/shldisp/ne-shldisp-shellspecialfolderconstants.

I don't know the inner workings of ueli, but maybe you can find the relevant data somewhere there. I suppose there must be some way to parse the start menu items, which would certainly help both with translated app names as well with UWP apps.

Crossing my fingers ;-)

**Comment by oliverschwendener** [comment]
Ueli already reads the files from the start menu folders: `C:\ProgramData\Microsoft\Windows\Start Menu\Programs` and `C:\Users\<User>\AppData\Roaming\Microsoft\Windows\Start Menu`. But in these folders are no shortcuts to UWP apps.

As I mentioned in #38 there is (to my knowledge) no proper way to get (and start) all installed UWP apps including Windows 10 system settings.

If you find a way to get and start UWP apps then let me know :)

**Comment by oliverschwendener** [comment]
With powershell you can get UWP apps with `Get-AppxPackage`.

Here is a snippet of the output: 

```
Name              : Microsoft.WindowsCalculator
Publisher         : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
Architecture      : X64
ResourceId        :
Version           : 10.1807.2121.0
PackageFullName   : Microsoft.WindowsCalculator_10.1807.2121.0_x64__8wekyb3d8bbwe
InstallLocation   : C:\Program Files\WindowsApps\Microsoft.WindowsCalculator_10.1807.2121.0_x64__8wekyb3d8bbwe
IsFramework       : False
PackageFamilyName : Microsoft.WindowsCalculator_8wekyb3d8bbwe
PublisherId       : 8wekyb3d8bbwe
IsResourcePackage : False
IsBundle          : False
IsDevelopmentMode : False
Dependencies      : {Microsoft.VCLibs.140.00_14.0.26706.0_x64__8wekyb3d8bbwe, Microsoft.WindowsCalculator_10.1807.2121.0_neutral_split.scale-150_8wekyb3d8bbwe, Microsoft.WindowsCalculator_10.1807.2121.0_neutral_split.scale-100_8wekyb3d8bbwe}
IsPartiallyStaged : False
SignatureKind     : Store
Status            : Ok
```

As you can see there is no translation and no information how to start the app.

**Comment by oliverschwendener** [comment]
Closing all issues related to launching UWP apps on Windows for now because there is (to my knowledge) no way to get/launch UWP apps with node.js.
