### ISSUE TITLE
[Feature Request] Allow input history for some plugin (eg. URL and command line commands)

### ISSUE THREAD

**Issue by MiCkSoftware** [oliverschwendener/ueli#512]
Hi!
There are some command I used several times in a day. I wish ueli could propose them as soon as I start to type. 
eg: cd /some/folder && git add . && git commit -a -m "partial commit" could be propose while just typing "partial"...

**Comment by oliverschwendener** [comment]
Why not using the shortcut feature? You could set up a shortcut to execute this command.

**Comment by MiCkSoftware** [comment]
This is what I did for the most common commands I run. But there a lot and sometimes it will just remain useful for a few days. 
On win I use Executor that has this feat. It's great.

**Comment by oliverschwendener** [comment]
Ueli v9 has now a general user input history, that you can enable:

<img width="704" alt="image" src="https://github.com/user-attachments/assets/f4eadbfc-1121-43d7-9155-f9a57710eb6f">
