### ISSUE TITLE
Please integrate Everything as search engine in Ueli

### ISSUE THREAD

**Issue by derei** [oliverschwendener/ueli#513]
I find it redundant and pointless to use different searching engines for windows when there is one that can do everything. And that one is Everything (from VoidTools)... and because it already has its own database, it would be just awesome to be able to use it as engine for Ueli.

..just a thought.

**Comment by AmrBinBashir** [comment]
There is already a plugin to use Everything with Ueli. Check this https://github.com/oliverschwendener/ueli#everything-windows-only

**Comment by derei** [comment]
Thank you, I don't know how I missed that!

**Comment by yashvardhan07** [comment]
Can anybody tell me how can I integrate everything search in Ueli. I have downloaded both everything and everything CLI but didn't what to do now. I have attached the pic that showing, the setting is disabled for me.

![ueli](https://user-images.githubusercontent.com/69007664/129087779-6f2008a1-96a5-4b53-ba88-9df2a7674f24.PNG)
