### ISSUE TITLE
I am not able to install Ueli

### ISSUE THREAD

**Issue by NotThareesh** [oliverschwendener/ueli#514]
It just says Installation Aborted. I use the ordinary Installer, not the portable one.

![image](https://user-images.githubusercontent.com/60844449/92438966-f253a300-f1ba-11ea-84ea-f5c166503afd.png)

Please help me @oliverschwendener

**Comment by AmrBinBashir** [comment]
Did you have the app installed before or Is it fresh install ? 
Also, posting your system info might help. 
I recommend deleting these folders if they exist before installation:
1. `C:\Program Files\Ueli`
2. `C:\Users\<your-username>\.ueli`
3. `C:\Users\<your-username>\AppData\Roaming\Ueli`
4. `C:\Users\<your-username>\AppData\Local\ueli-updater`

**Comment by NotThareesh** [comment]
I am installing it again, because I had some issues in customization. I will definitely try @Amr Bashir. Thanks From: Amr BashirSent: 09 September 2020 23:15To: oliverschwendener/ueliCc: Not_Thareesh; AuthorSubject: Re: [oliverschwendener/ueli] I am not able to install Ueli (#514) Did you have the app installed before or Is it fresh install ?Also, posting your system info might help.I recommend deleting these folders if they exist before installation:C:\Program Files\UeliC:\Users\<your-username>\.ueliC:\Users\<your-username>\AppData\Roaming\UeliC:\Users\<your-username>\AppData\Local\ueli-updater—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by NotThareesh** [comment]
@AmrBinBashir , I resolved it by clearing the file in AppData. Thanks bro

**Comment by AmrBinBashir** [comment]
You welcome, I think the issue can be closed now 👍.
