### ISSUE TITLE
ueli input window moves diagonally upwards with each keystroke

### ISSUE THREAD

**Issue by japchap** [oliverschwendener/ueli#515]
As the title says, when I use the keystroke to invoke the ueli input window and start typing, every new keystroke will cause the input window to move diagonally upwards and to the left by approximately 1 px, until it finally reaches the top of the window... 

I would expect the ueli input window to remain in place even when you are typing, but that is just me 😆

ueli version: 8.8.2
Electron: 8.5.0
Node: 12.13.0
V8: 8.0.426.27-electron.0
Windows 10 Home (10.0.18363), display size: 2560 x 1600 px

**Comment by oliverschwendener** [comment]
Do you have custom UI scaling activated in Windows? https://github.com/oliverschwendener/ueli/issues/37

**Comment by japchap** [comment]
Thanks for the reply. "Scale and layout" in "Display" is set to "150% (Recommended)", but custom UI scaling is not activated (no size has been inputted).

I just checked out #37  — thanks. Will you consolidate this bug there, or keep it separate?

**Comment by Net-zen** [comment]
Get this issue on 8.15. Didn't notice it before. I have custom UI scaling activated in Windows. And "Remember window position" don't fix it for me.

**Comment by voxain** [comment]
Hello, I've just experienced this same issue on my windows 11 machine, so it is apparently still a thing. Has an issue been filed over at the electron team already? If not, I'd go ahead and do so myself. It's a bit annoying not to be able to use custom scaling for a silly reason like windows moving around, so I'd like to get it out of the way sooner :)

**Comment by carlitorendon** [comment]
Hello @voxain thanks for offering to look onto this. I can confirm this is still happening on the latest version of everything as of today.

**Comment by oliverschwendener** [comment]
Can someone check if this is still an issue with the latest v9 release? https://github.com/oliverschwendener/ueli/releases
If so, feel free to reopen.
