### ISSUE TITLE
Unable to modify or update config in Powershell Constrained Language Mode

### ISSUE THREAD

**Issue by bloodsun** [oliverschwendener/ueli#519]
Currently the Powershell is running in "Constrained Language Mode" 
> PS C:\Users\someuser> $ExecutionContext.SessionState.LanguageMode
> ConstrainedLanguage

I notice that most if not all Powershell command which is executed by ueli will hit into following problem.

> 2020-09-19T13:25:24.064Z error: Cannot set property. Property setting is supported only on core types in this language mode.
> At line:1 char:5
> & { [Console]::OutputEncoding = [Text.UTF8Encoding]::UTF8; Get-ChildI ...
>     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      CategoryInfo          : InvalidOperation: (:) [], RuntimeException
>      FullyQualifiedErrorId : PropertySetterNotSupportedInConstrainedLanguage

Or 

> 2020-09-19T13:28:30.753Z error: Command failed: cmd /c chcp 65001>nul && powershell -NonInteractive -NoProfile -Command " $ErrorActionPreference = 'SilentlyContinue';....

Wondering if it is possible to run ueli in Powershell Constrained Language Mode?

**Comment by AmrBinBashir** [comment]
I don't think this is possible since Constrained Language Mode blocks a lot of cmdlets used by ueli.
I'd recommend you to disable this mode if you want to use ueli properly.

**Comment by bloodsun** [comment]
> I don't think this is possible since Constrained Language Mode blocks a lot of cmdlets used by ueli.
> I'd recommend you to disable this mode if you want to use ueli properly.

If that is the case, guess I wont be able to use ueli :( as I wont be able to disabled the Constrained Language Mode. Thanks for the info.

**Comment by AmrBinBashir** [comment]
I am not totally sure if ueli can bypass this mode or disable it temporarily or not. Wait for the response of the repo owner.

**Comment by AmrBinBashir** [comment]
I am guessing this is a workplace-pc you are trying to run windows on ? if so, I'd probably try no to mess around with the restrictions they made.

**Comment by bloodsun** [comment]
> I am guessing this is a workplace-pc you are trying to run windows on ? if so, I'd probably try no to mess around with the restrictions they made.

Yes, you have guessed it right. Thus I can't and won't mess around with the Constrained Language Mode. :)

**Comment by rGunti** [comment]
I am facing the same issue. Since this is a work PC, chances of changing this mode are next to none. Would it be possible to implement an alternative method of indexing installed applications without the use of PowerShell?
