### ISSUE TITLE
Does not show any applications

### ISSUE THREAD

**Issue by pcktm** [oliverschwendener/ueli#52]
Ueli does not show any user applications, for example: 
I search for Spotify and it's just not there even though it is installed. I tried changing paths in config file but it does nothing. 

I'm on Windows 10.

**Comment by oliverschwendener** [comment]
Did you install Spotify with the Microsoft Store?

**Comment by pcktm** [comment]
No I didn't. But ueli doesn't show any application not just spotify. It only searches for files and system settings.

**Comment by pcktm** [comment]
Alright, I don't have any idea what caused the issue but I reinstalled ueli two times and now it magically works! Thanks anyway.
