### ISSUE TITLE
Add clickable search results, right click functionality and drag & drop

### ISSUE THREAD

**Issue by walter6469** [oliverschwendener/ueli#523]
Is there a way to add an option so I can click the results?
Similarly an option to right click files like you do in file explorer, this might be very complicated to pull off, but with some work I think you guys can pull it off.
And this is an option that I really would love to have in ueli, and that is the option to drag and drop files, for example, if I have file explorer open in one place and by launching ueli, I would like to search for that file and drag and drop in the file explorer.

**Comment by oliverschwendener** [comment]
See #393, #476 and #500.

**Comment by Warden20** [comment]
+1
