### ISSUE TITLE
Can't access ueli after changing shortcut

### ISSUE THREAD

**Issue by thedaddy123** [oliverschwendener/ueli#525]
I have managed to change the shortcut to 'super' + space, however I can't now launch the launcher. How can I now access the launcher to change the settings back to alt space? I have a few custom shortcuts, so I dont want to uninstall if it removes these?

**Comment by thedaddy123** [comment]
Sorry not sure how to make this a help needed request, not issue.

**Comment by tkohlmeier** [comment]
Try this: Enter `%appdata%\ueli` in the address bar of file eplorer and open the file `config.json` with some text editor. Search for `hotKey` and change it back to the default like this:
```
"hotKey": {
    "key": "Space",
    "modifier": "Alt"
},
```

Then you need to restart ueli. You could either log out of Windows and sign in again or just kill ueli using task manager and then start it.

**Comment by oliverschwendener** [comment]
You can also open ueli by clicking on the system tray icon.

**Comment by thedaddy123** [comment]
tray forgot there was a system icon
