### ISSUE TITLE
I can't open any applications from Ueli

### ISSUE THREAD

**Issue by Th3G0dFather** [oliverschwendener/ueli#526]
I can't access the apps that I could access before and I get this when I try to select a file for browsing application:
Error: spawn C:\Windows\system32\config\systemprofile\adb-fastboot\platform-tools ENOENT
Help would be appreciated

**Comment by oliverschwendener** [comment]
Did you change the application search settings?

**Comment by Th3G0dFather** [comment]
I changed the path in to install adb that's it

**Comment by oliverschwendener** [comment]
Can you show me your application search settings

You can also reset all settings here:

![image](https://user-images.githubusercontent.com/15727229/94174511-ad578e00-fe95-11ea-8688-79c3e6ebc053.png)

**Comment by Th3G0dFather** [comment]
It's working again thanks ;)
