### ISSUE TITLE
Doesn´t search in my Home folder

### ISSUE THREAD

**Issue by Stooovie** [oliverschwendener/ueli#528]
Ueli doesn´t return any matches from my Home folder (Desktop, Music, Synology Drive...) 8.8.2 on fully updated Windows 10. I tried removing and re-adding the folder in Preferences but it didn´t fix the issue.

**Comment by AmrBinBashir** [comment]
can you add the folder and post the logs here.
![image](https://user-images.githubusercontent.com/48618675/94471139-f3c82800-01c8-11eb-8db3-431fac6dd6a8.png)

**Comment by Stooovie** [comment]
Here:

https://pastebin.com/emzMKF5E

Searching for files and folders in my Home folder only works through Everything. The home folder IS added in the Simple Folder Search settings.

**Comment by oliverschwendener** [comment]
Seems like some folders you added could not be found. Are you sure that all folders/drives are available?

**Comment by Stooovie** [comment]
Yes I'm totally sure, it's the C:/Users/myaccount folder with Desktop, Music, appdata and everything. I've tried removing it from Ueli and readding, to no avail.

**Comment by AmrBinBashir** [comment]
Can you post your application search settings and your shortcuts plugin settings ?

**Comment by Stooovie** [comment]
Sure, here´s the app search settings. There´s nothing in the shortcut plugin settings.

[https://imgur.com/a/58LSe6f](url)

**Comment by Stooovie** [comment]
Of course, it started working the second I sent the screenshot. I´m now able to search within my Home folder and subfolders, the issue is solved.
