### ISSUE TITLE
[Feature Request] Bin Trash

### ISSUE THREAD

**Issue by bastienvinh** [oliverschwendener/ueli#529]
Hi it will be nice if there is a feature to empty your trash bin. 😊

**Comment by AmrBinBashir** [comment]
On windows you can add a shortcut in the shortcut plugin and set it to commandlinetool and add this `start powershell -command "&Clear-RecycleBin";exit` in the command field.

**Comment by omerdduran** [comment]
@oliverschwendener I think we can close this issue now
