### ISSUE TITLE
Question:Periodic rescan

### ISSUE THREAD

**Issue by Mylo17** [oliverschwendener/ueli#531]
How many seconds would you recommend for the periodic rescan, I can't find a interval that I like and I would love to know what other people are using

**Comment by oliverschwendener** [comment]
I'm pretty fine with 300s which is the default value. Don't know about other people though. If you want to do a manual rescan you can run "Refresh indexes":

![image](https://user-images.githubusercontent.com/15727229/94559343-6258c480-0261-11eb-806c-9190ffeae070.png)

**Comment by dseptem** [comment]
@oliverschwendener It would be cool if the program didn't freeze completely while refreshing indexes. It is really annoying if you use ueli frequently. Is it possible to use the "old indexes" while the new ones are being created?
Refreshing manually is also a chore.

**Comment by oliverschwendener** [comment]
This is now solved with the latest update.
