### ISSUE TITLE
Decimal operator (comma instead of period)

### ISSUE THREAD

**Issue by dansroot** [oliverschwendener/ueli#538]
It would be nice if there would be a setting to change the decimal operator from a period ("2.5") to a comma ("2,5"). I use ueli quite a lot for quick calculations or currency conversions and fail so often because I separate decimals naturally by a comma, instead of the expected period. Not sure if there is a setting to accomplish that, but I haven't found it so far. Thanks.

**Comment by oliverschwendener** [comment]
See #49

**Comment by dansroot** [comment]
OK, so I understand there no solution for that for the time being because the math parser does not support localizations.

**Comment by oliverschwendener** [comment]
Yes, that's correct.

**Comment by oliverschwendener** [comment]
Thanks to @tkohlmeier this is not implemented in the latest release: https://github.com/oliverschwendener/ueli/releases/tag/v8.10.0
