### ISSUE TITLE
An enhancement request to the annoying "Refreshing Indexes..."

### ISSUE THREAD

**Issue by walter6469** [oliverschwendener/ueli#539]
![image](https://user-images.githubusercontent.com/70185618/96201298-de4d4f00-0f79-11eb-85fa-7ad880959509.png)
This is the most frustrating thing about UELI for me, the refresh timing is the default timing, but I think this could be made to be done in background and a refreshing text can pop up to the right side in the search bar like this 
![image](https://user-images.githubusercontent.com/70185618/96201422-27050800-0f7a-11eb-90e7-84ffde3552d3.png) But just replace the "Proceed?" with "Refreshing" and make that till the refreshing is done, we are still able to use the previously refreshed index and once the refreshing is done "Refreshing..." changes to "Refreshed!" (maybe in green color) and now we can search from the newly refreshed index. UELI is pretty much meant to simplify and increase workflows thus increasing productivity which it already does good but this is just an enhancement request so the most frustrating thing with UELI is resolved and I'd be really happy if something is done about this.
Thanks :)

**Comment by oliverschwendener** [comment]
Thanks for your feedback! There is already a ticket covering this issue: #473

I'll close this because it's a duplicate.
