### ISSUE TITLE
Searchbar is blinking when appear

### ISSUE THREAD

**Issue by cngz1903** [oliverschwendener/ueli#540]
When i push the alt + space for start ueli, searchbar comes with blinking 2 times and sometimes the bar comes half size.

**Comment by Memories4Life** [comment]
I had this problem and here is what i did to solve.
1. Settings>Plugins and switch off all active plugins
2. Quit ueli. Taskbar>Right click icon and Quit.
3. relaunch ueli.
4. Rebuild Cache
5. Alt-Space (with no active plugin) 

Now you should see the Search bar as normal.  Activate your used plugins.

Hope this helps!

**Comment by oliverschwendener** [comment]
This seems to be a bug in electron when having transparent windows on Windows, see [here](https://github.com/electron/electron/issues/22691).

A workaround would be to disable the transparency on the window in the appearance settings:

![image](https://user-images.githubusercontent.com/15727229/97079746-b8b5ea80-15f6-11eb-84b7-720ed11017ab.png)

**Comment by oliverschwendener** [comment]
This will be fixed in the next release.
