### ISSUE TITLE
Application Search doesn't work

### ISSUE THREAD

**Issue by uDEV2019** [oliverschwendener/ueli#543]
The Application Search doesn't work under Windows 7, even if i remove every default location and only add one folder path and one file extension (.exe). 

settings dialog stays forever in this state:
![image](https://user-images.githubusercontent.com/51911097/96376328-8df30e80-117e-11eb-9a81-46e15c39d48b.png)

**Comment by Dhyfer1** [comment]
> ![image](https://user-images.githubusercontent.com/51911097/96376328-8df30e80-117e-11eb-9a81-46e15c39d48b.png)

On the other hand, every time I make some adjustment in the Ueli settings dialog I also get the load spin spinning for a long time. 🙁

**Comment by oliverschwendener** [comment]
See #284

**Comment by uDEV2019** [comment]
Wow, complete different problem and closed

**debug.log**
`2020-10-18T20:35:40.273Z error: Can't read bookmarks file: Error: ENOENT: no such file or directory, open 'C:\Users\***\AppData\Local\Google\Chrome\User Data\Default\Bookmarks'
2020-10-18T20:35:49.232Z debug: Check for updates
2020-10-18T20:35:49.305Z error: Update check result: Error: net::ERR_NETWORK_ACCESS_DENIED
2020-10-18T20:36:12.940Z debug: Check for updates
2020-10-18T20:36:12.942Z error: Update check result: Error: net::ERR_NETWORK_ACCESS_DENIED
`

Nothing with "non-stop errors". App simply doesn't work under Windows 7 x64

**Comment by oliverschwendener** [comment]
I think it's the same problem as #284. I think this problem occurs because you added a top level folder to the application search settings. Now ueli searches to whole folder structure recursively for .exe files which is really slow and can result in errors due to permission problems. As I mentioned in the other issue: you shouldn't add top level folders like "L:\Programme". You should only add folders which contain the shorcut files (.lnk) for example the start menu folder. I suggest you remove "L:\Programme" from the application search list and add a folder which contains only shortcut files.

**Comment by uDEV2019** [comment]
@oliverschwendener I didn't add a top level folder. Screenshot above shows that i've added th folder "AIMP" under path "L:\Programme\" and in the folder "AIMP" are five executables (four more in subfolders of AIMP).
![image](https://user-images.githubusercontent.com/51911097/96505839-fca39b00-1256-11eb-941b-267b068b936d.png)

I've also tested it, with a directory where are only .lnk files. Added .lnk to searched file extension and same thing happens as above.
When i remove a folder or file extension, then the "index refresh overlay" (i name it this for now) in settings menu appears and stays as well on top. Only closing settings dialog and reopen helps to get settings dialog "working" again.
Finally, if i add or remove something under Application search, ueli does nothing.

**Comment by oliverschwendener** [comment]
Do you have the same issue when you reset the application search settings back to default? No search results when searching for applications?

**Comment by uDEV2019** [comment]
@oliverschwendener Yes to both. The default setting "Periodic rescan enabled" also has the effect too, that the settings dialog gets the "index refresh overlay". At this point the search dialog only shows "refreshing indexes..." till i close ueli and reopen it.
