### ISSUE TITLE
Option to disable ueli core functions/settings appearing in search results

### ISSUE THREAD

**Issue by CaptainProg** [oliverschwendener/ueli#549]
I use ueli exclusively for web searches. I've set a fallback option (DuckDuckGo), but sometimes this fallback is overridden to a core ueli function. For example, if I type "test" into the search box, ueli sends me to its own settings window, instead of searching DuckDuckGo for **test**.
<img width="606" alt="image" src="https://user-images.githubusercontent.com/73287647/96867263-5dec8980-1464-11eb-8409-3626fe25dc2e.png">

If I want to change ueli's settings, I would access these using the app's icon in the menu bar. I cannot see any way to disable ueli defaulting to fallback to its own internal functions – it seems it is possible to turn everything off except this.

As another example, typing "e" into the search box brings up multiple ueli functions, rather than defaulting to my chosen fallback:
<img width="605" alt="image" src="https://user-images.githubusercontent.com/73287647/96867552-c6d40180-1464-11eb-96ec-10c39ac771b9.png">

It would be great if we could somehow turn off this behaviour and _always_ fallback to the chosen web search.

**Comment by oliverschwendener** [comment]
This is solved in ueli v9.
