### ISSUE TITLE
iTunes cannot be found

### ISSUE THREAD

**Issue by pbuw** [oliverschwendener/ueli#55]
![image](https://user-images.githubusercontent.com/30902538/45342339-efa71e80-b59d-11e8-8686-981f9d0e77b1.png)
Its installed over the Microsoft app store, maybe that's the problem. Its also not listed in the Control Center. Is there a solution to fix this?

**Comment by cosimochellini** [comment]
this is a workaround:
1: search on windows (window key + itunes)
2. right click on the app icon> add to start
3: drag the app icon to the desktop
4 (optional): move the link to some folder if you prefer not to have such icons on your desktop

**Comment by pbuw** [comment]
Thanks for your help. 
It worked with a shortcut on the desktop, but I think it's not the most beautiful way to get it working.

**Comment by oliverschwendener** [comment]
This is related to #38. At the moment there is no way to get/start UWP apps (apps installed with Microsoft Store). Although there is a workaround from @cosimochellini.

**Comment by oliverschwendener** [comment]
Proper UWP support is now added in the latest release.
