### ISSUE TITLE
QUESTION: web suggestion 

### ISSUE THREAD

**Issue by mylo17** [oliverschwendener/ueli#550]
hi, could you provide a brief explanation of the new web suggestion feature implemented by @AmrBinBashir,i tried to use it but have not really grasped on its varius functionalities.
Thanks a lot for the great work you are carrying on with this amzing project

**Comment by AmrBinBashir** [comment]
Before the update, the web search plugin was used to search in your favorite search engine like this.

![image](https://user-images.githubusercontent.com/48618675/96911534-4089e080-14a1-11eb-83d8-a000dfbd5896.png)

You can see there is no suggestion.
In the latest update, ueli will provide suggestions like this.

![image](https://user-images.githubusercontent.com/48618675/96911623-5f887280-14a1-11eb-9342-491ddc2f6418.png)

Note: If the feature isn't working for you, you need to reset it to default first.

![image](https://user-images.githubusercontent.com/48618675/96911859-b4c48400-14a1-11eb-8ced-da3381d59d30.png)

**Comment by Mylo17** [comment]
thanks a lot, i needed to reset to default

**Comment by Mylo17** [comment]
another thing that came up with this update are the red lines under mispelled word that before was not there, and even if the words are correct are still present. is there a way to disable this?
![Cattura](https://user-images.githubusercontent.com/46066232/96971054-df035980-1514-11eb-9058-accbf58f3017.PNG)

**Comment by AmrBinBashir** [comment]
I don't think ueli has anything to do with that since there hasn't been any changes to the input box for 4 months, this is the OS spell checker.

**Comment by AmrBinBashir** [comment]
Something must be wrong on your machine. The correct words are not highlighted

**Comment by Mylo17** [comment]
ok i will try to find a solution, but what about the yt red line, before the update i am sure it did not appear

**Comment by AmrBinBashir** [comment]
It might be because Oliver update dependencies and I think the latest electron version has spell check on by default. 
If you want him to turn it off or provide an option to disable it, You'd better close this issue and start a new one for the spell check .

**Comment by Mylo17** [comment]
thaks a lot i will open a new issue then
