### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by walter6469** [oliverschwendener/ueli#551]
https://imgur.com/a/4NLtshD Have a look at this video...
The settings aren't working properly

**Comment by tkohlmeier** [comment]
The settings are from this [documentation](https://docs.microsoft.com/de-de/windows/uwp/launch-resume/launch-settings-app#mixed-reality).

`Uninstall` belongs to `Mixed reality`. The name should somehow make that clear...

**Comment by oliverschwendener** [comment]
See @tkohlmeier 's response.
