### ISSUE TITLE
[Bug] Commandline shortcuts not working for macOS Catalina with zsh as default shell

### ISSUE THREAD

**Issue by gspinoza** [oliverschwendener/ueli#556]
My default shell is "/bin/zsh" and when I try to execute a **commandline shortcut** nothing happens. 
**Note**: when I execute the command using the **commandline plugin** or my terminal it works.

**Logs:**
`"Error: Command failed: code /Users/gabriel/Desktop/text.txt`
`/bin/sh: code: command not found"`

Looking at the logs I see that it tries to execute the command using "/bin/sh:", but this does not work in my system maybe because my "sh" invocation still points to my "/bin/bash" instead of "/bin/zsh". I could change "sh" to point to "zsh", but I want to avoid unwanted problems, as I learned that changing the interpreter for sh "_may change the behavior of several crucial scripts in the system, management tools, and installers._"

Any suggestions?

**Comment by kristus123** [comment]
i have the same error. is there any quick fix?

**Comment by oliverschwendener** [comment]
Can someone confirm that this is still an issue with the latest version? If so feel free to reopen.
