### ISSUE TITLE
MacOS default apps are not shown

### ISSUE THREAD

**Issue by danieldisu** [oliverschwendener/ueli#557]
![image](https://user-images.githubusercontent.com/3216712/97777792-de9d3b00-1b72-11eb-9d68-18a19b8e18f9.png)

Using latest version of Ueli

When searching for any of the default MacOS applications, Ueli doesn't provide any suggestion for them, some of the apps that doesn't appear are:
- Calculator
- System Preferences
- Calendar
- Reminders

Safari for example does appear without issues.

**Comment by danieldisu** [comment]
This issue is fixed by adding `/System/Applications` to the ApplicationSearch plugin, but maybe should be there by default?

**Comment by GovindKrishnan** [comment]
It's better to keep this open issue for @oliverschwendener to take note.
