### ISSUE TITLE
[Feature request] Change Icon of "Open with web browser"

### ISSUE THREAD

**Issue by LalaGhost** [oliverschwendener/ueli#558]
![Screenshot_3](https://user-images.githubusercontent.com/43962138/98217027-2d1f5080-1f4a-11eb-92bc-ec2be5f19ed9.png)

See in the screenshot, the icon for the "Open with web browser" command looks like opening some folder. Maybe change the icon to the image on the left in the screenshot?

:)

**Comment by vishaluchil** [comment]
Changed the icon to this:

![image](https://user-images.githubusercontent.com/50170066/124633604-5697cf80-de7d-11eb-98d2-2a96923b0152.png)
