### ISSUE TITLE
[Bug/Feature request]

### ISSUE THREAD

**Issue by LalaGhost** [oliverschwendener/ueli#559]
After updating through the app I have to versions installed at the same time.

![Screenshot_4](https://user-images.githubusercontent.com/43962138/98217185-7374af80-1f4a-11eb-93d5-c15d54051175.png)

Is there a way that Ueli uninstalls the old version on its own?

**Comment by oliverschwendener** [comment]
No, ueli should only update itself. As the auto-update will be removed in the future due to distribution through the Microsoft Store, this shouldn't be a problem anymore.
