### ISSUE TITLE
Can't customise ueli ?

### ISSUE THREAD

**Issue by wedza** [oliverschwendener/ueli#56]
Hello !

I just installed UELI to try to replace Listary and Wox, and so far I'm really enjoying it!

But I have a small issue, even if I change some settings in the ueli.config.json in my User folder, nothing of my changes is taken into account.

I've tried to change the color theme, the hotkey etc... But even after reloading UELI (by the ueli command, or by restarting my computer), nothing happens and UELI keeps the original theme and hotkey.

I read multiple times the README.md and I think I followed correctly all the instructions, and I couldn't find where I made a mistake.

Thanks a lot for your patience.

**Comment by khanhas** [comment]
Uses ide like VSCode or Atom to check if your config file has any format error.
Because if it has error somewhere, UELI will fail to parse it and load default config instead.

**Comment by oliverschwendener** [comment]
Yep, first check if your syntax is correct.

**Comment by wedza** [comment]
Found it !

It was the folderPath, where I placed the directory like it was in Windows Explorer, without the double slash. Now working perfectly !

Thanks for your time.
