### ISSUE TITLE
The google search engine doesn't work under proxy

### ISSUE THREAD

**Issue by Lyn6969** [oliverschwendener/ueli#560]
I am a user of mainland China. I can only use Google under proxy. But even though I have turned on the proxy, I still can’t use Ueli for Google search, and so neither the wiki. What else do I need to set？

![image](https://user-images.githubusercontent.com/42564665/98255287-3515d980-1fb8-11eb-8389-c18c858eee7b.png)

**Comment by nightofmind** [comment]
Should use HTTP/HTTPS proxy if set. It needs development.

**Comment by AFlyingBird90** [comment]
Also a user in China. Uses proxy. Normally without proxy, bing.com will redirect to cn.bing.com. Whereas under proxy, "b?search something" will open bing.com. But duckduckgo, google, youtube don't work with the plugin. Don't know where the problem is.

**Comment by oliverschwendener** [comment]
This should be solved with v9.
