### ISSUE TITLE
Option to retain last command typed when Ueli reappears

### ISSUE THREAD

**Issue by GovindKrishnan** [oliverschwendener/ueli#563]
Hi,

I remember this 'feature' from the times of Launchy.

It allowed us to have the previous text we typed in launcher to remain there but as fully highlighted.

So if we wanted to ignore it, just type new line. No issues as highlighted text gets wiped out.

But in case we want to repeat the previous command (which we executed previously or just typed), it's extremely easy as just pressing Enter key is required.

I used to use this option in Launchy when I knew in advance I will need to execute something in future but can't leave it open before.

Eg: Opening a file (found with Everything) or application in between a work or a presentation.
You might want to open it only at the required moment though you know you will need it anyways.

Can be also helpful if Ueli window accidently lost focus while we had typed something but couldn't execute.

Don't know if this has any limitations but since I have seen it before... Thanks! @oliverschwendener  @AmrBinBashir 

(PS: I'm not a programmer yet)

**Comment by olivereisenhut** [comment]
@oliverschwendener

**Comment by GovindKrishnan** [comment]
> Hi,
> 
> I remember this 'feature' from the times of Launchy.
> 
> It allowed us to have the previous text we typed in launcher to remain there but as fully highlighted.
> 
> So if we wanted to ignore it, just type new line. No issues as highlighted text gets wiped out.
> 
> But in case we want to repeat the previous command (which we executed previously or just typed), it's extremely easy as just pressing Enter key is required.
> 
> I used to use this option in Launchy when I knew in advance I will need to execute something in future but can't leave it open before.
> 
> Eg: Opening a file (found with Everything) or application in between a work or a presentation.
> You might want to open it only at the required moment though you know you will need it anyways.
> 
> Can be also helpful if Ueli window accidently lost focus while we had typed something but couldn't execute.
> 
> Don't know if this has any limitations but since I have seen it before... Thanks! @oliverschwendener @AmrBinBashir
> 
> (PS: I'm not a programmer yet)

And I noticed that we have Shift+ ⬆️ to get the previously 'executed' commands. 👍

However if we've just typed something in advance to be only executed while doing something in immediate future (just moments away), we can't have it.

Also if Ueli window accidently lost focus while typing a query, retaining text will help.

It can be left to the user's preference whether to retain previous text or not.

Sorry if it sounds trivial but I will care for such minor helps 😅

Thanks! ☺️ @oliverschwendener

**Comment by GovindKrishnan** [comment]
Just found what I wanted with "Persistent User Input" 👍

Hence closed
