### ISSUE TITLE
File can't be opened if its whole path is typed (along with extension)

### ISSUE THREAD

**Issue by GovindKrishnan** [oliverschwendener/ueli#564]
Noticed that you can't open a file if we put its whole path in Ueli including file name & extension.

It'll only work if atleast the last letter (in extension part) is not typed.

It ain't a huge bug. But if at some point, we copy a path & paste it, it'll not execute unless we remove at least last character.

Here's examples to compare : 

![image](https://user-images.githubusercontent.com/74248475/98817944-e8ffe480-2450-11eb-8e57-9bff279bf42f.png)

![image](https://user-images.githubusercontent.com/74248475/98818132-219fbe00-2451-11eb-922c-2da60ccae759.png)

![image](https://user-images.githubusercontent.com/74248475/98818309-60ce0f00-2451-11eb-8661-7acfe500a49f.png)

![image](https://user-images.githubusercontent.com/74248475/98818376-780cfc80-2451-11eb-9c78-562bdf88c0fc.png)

Shouldn't it work though it ain't a big bug? @oliverschwendener 

Thanks! 😄

**Comment by GovindKrishnan** [comment]
Bumping this issue as it's been a while. @amrbashir as you implemented the autocomplete, will it be possible for you to fix it?

Having trouble presently when copy-pasting the “exact” file path to ueli.

Thanks!

**Comment by oliverschwendener** [comment]
Did you activate the "File Browser" plugin?

**Comment by GovindKrishnan** [comment]
> Did you activate the "File Browser" plugin?

Yes. I've all plugins enabled except Everything Search which I don't use.

**Comment by oliverschwendener** [comment]
Closing this as the File Browser plugin will be discontinued with ueli v9, unless someone takes their time to migrate it.
