### ISSUE TITLE
Reduce app size and follow Ui from microsoft LOBE app 

### ISSUE THREAD

**Issue by fisforfaheem** [oliverschwendener/ueli#565]
please downalod and isntall lobe app and see its ui

**Comment by mix3d** [comment]
link?

**Comment by fisforfaheem** [comment]
https://lobe.ai/ this the link

**Comment by mix3d** [comment]
So... rounded corners?

I'm not sure how the Lobe app UI applies here. You have control over the UI color scheme if you want it to match that.

How / why reduce the app size? It's an Electron based app, so unfortunately it bundles Chromium, and that's likely why it's so big. _/shrug_

**Comment by fisforfaheem** [comment]
Thanks for the tip! but i think you should use latest version of electron
then (bleeding edge) it has so many impromebnts

**Comment by oliverschwendener** [comment]
The app size is because ueli is using electron. I'm trying my best to keep the electron dependency up to date. And like @mix3d I don't see how the Lobe app UI applies here?

**Comment by fisforfaheem** [comment]
what i meant was you to get some inspirations for the lobe app ui and ux
for your project.
