### ISSUE TITLE
Question : Why Ueli has a huge file size?

### ISSUE THREAD

**Issue by GovindKrishnan** [oliverschwendener/ueli#568]
Just out of curiosity, wanna ask why Ueli installer is about 120 MB compared to small installers of similar keystroke launchers like Wox & Launchy?

Edit : I get it now that it's due to Electron. However, are there any plans to compress in future?

**Comment by oliverschwendener** [comment]
The current size of the installer and the app itself is really depending on electron and the number of source files. Currently there are not plans to compress it more that it is right now.
