### ISSUE TITLE
Calculator/Converter - Copy Product/Quotient/Sum/Difference/Etc.

### ISSUE THREAD

**Issue by moses-bowman** [oliverschwendener/ueli#57]
It would be handy if pressing **{enter}** will copy the result of a computation.
Same goes with conversion.

**Comment by oliverschwendener** [comment]
Good idea! I am working on this.

**Comment by oliverschwendener** [comment]
Implemented this feature in 5c894f0420b6da5622af396e2272b4474368110f (will be included in the next release).
