### ISSUE TITLE
What's the current indexing limit for Recursive Searching in Simple Folder Search?

### ISSUE THREAD

**Issue by GovindKrishnan** [oliverschwendener/ueli#570]
Is it ok to use Recursive Searching instead of going through the hassle of installing Everything? There are both big as well as small folders.

Will Recursive Searching replace the need for Everything in future?

Thanks

**Comment by oliverschwendener** [comment]
I'm not sure what the limit of the recursive file search is, I'm afraid you have to try it out yourself. I suggest that you use the simple file search plugin as long as possible. As soon as the reindexing takes too long I suggest that you install everything.

No the recursive searching will not replace everything.
