### ISSUE TITLE
[Feature Request] Clickable Search Results (mainly for Everything plugin)

### ISSUE THREAD

**Issue by IRlyLikeBac0n** [oliverschwendener/ueli#575]
Hey, really love this project and I'm glad it's still being actively maintained.

Is there any way to make the results displayed by ueli clickable? The main use case I want this for is the Everything plugin search. On Khanhas's deserted port, I was able to search for files, then right-click on a result to get the traditional Windows context menu. This feature would allow you to do things like view the file's properties, rename it, open its folder location, etc.

**Comment by ThinkSalat** [comment]
I would love this too. It's really weird that you can't click on the results to activate them

**Comment by juusan** [comment]
That would be awesome !
By the way, thank you so much for developing such a great tool ! <3

**Comment by arthurmarquesv** [comment]
As a concept designer, this is as must for me. In Wox, I can search for a keyword used in a reference image's name and open its respective folder to look at other references. In Ueli, I need to remember tha folder's name or search the reference, find its path and search for the folder after it. 

I'm still using Ueli cos' it easily finds every program I install in my computer, a feat Wox had difficulty replicating. Keep the good work!

**Comment by oliverschwendener** [comment]
This is solved in ueli v9.
