### ISSUE TITLE
[Feature Request] would search in webpages be possible

### ISSUE THREAD

**Issue by WorldTeacher** [oliverschwendener/ueli#579]
I tried adding Reddit to my web search engines with https://www.reddit.com/search/?q={{querry}} and the same for the suggestion URL. It gave me an error: "Invalid web search engine". Would it be possible to add such a feature, so that you can search in websites if configured?

**Comment by gabrielspinoza** [comment]
> I tried adding Reddit to my web search engines with [https://www.reddit.com/search/?q={{querry}}](https://www.reddit.com/search/?q=%7B%7Bquerry%7D%7D) and the same ...

ueli already has this feature and it's working for me. You have a typo in your search URL, hence it's not working for you. 
**it should be:**
https://www.reddit.com/search/?q={{query}}
**not** 
https://www.reddit.com/search/?q={{querry}}

**Comment by WorldTeacher** [comment]
Thsnks for the reply.
When I try using your link, it accepts the reddit link, but if I type in r?something
it tries to search for "" and does no autofill for the word I wrote and displays "an error occurred, check the logs for details"
I'm running ueli 8.10 btw, if the version matters.

**Comment by gabrielspinoza** [comment]
I have the same version and reddit search it's working perfectly. I don't really know what could be the problem in your case.

**Comment by WorldTeacher** [comment]
I checked with a different website, and it didn't work.
This is the error message I got from the log:
2020-11-22T08:16:25.429Z error: r[1].map is not a function
TypeError: r[1].map is not a function
    at C:\Program Files\ueli\resources\app.asar\bundle\main.js:25:151366
    at processTicksAndRejections (internal/process/task_queues.js:97:5
@oliverschwendener what can I do to fix this?

**Comment by tkohlmeier** [comment]
You have to leave the suggestion URL empty, then it should work. Suggestion URLs must return suggestions in a specific format for ueli to understand it. I'm not sure if there is a compatible reddit URL.
