### ISSUE TITLE
calculator functions

### ISSUE THREAD

**Issue by Khoding** [oliverschwendener/ueli#580]
Hello, I'd like to know what math functions are available, I know math.js has stuff like concat() and sqrt(), but it seems like I can only use sqrt (in those examples anyway)
would also be good to have help on them by typing them in Ueli (typing sqrt would show what variables can be entered, etc)

thanks :D

**Comment by oliverschwendener** [comment]
You can use all funtions that are available in math.js's `eval` function: https://mathjs.org/docs/expressions/parsing.html

**Comment by Worton1720** [comment]
Hello! Is there any help for all functions/plugins somewhere

**Comment by Worton1720** [comment]
Hi, is there any help on all the features/plugins somewhere?

**Comment by oliverschwendener** [comment]
https://github.com/oliverschwendener/ueli/wiki/Extensions

**Comment by Worton1720** [comment]
Does anyone know how the "Workflows" extension works?
