### ISSUE TITLE
[Bug] "Persistent user input" does not show results

### ISSUE THREAD

**Issue by mix3d** [oliverschwendener/ueli#584]
Coming from Launchy, I'm used to the persisted text persisting the search results as well. Is that an intended feature that's not working, could that be added in? Otherwise, I have to add then remove a character to get the search to re-show, making the feature worthless.

**Comment by cougarten** [comment]
FYI: I'm pretty sure search works, but the height calculation doesn't happen. With some settings I get a tiny scrollbar with which i can reach the results :)  

https://user-images.githubusercontent.com/7131556/103175842-651d8280-486d-11eb-86b6-eca1b2d6912d.mp4

**Comment by hanchenlu** [comment]
Not just for search, but I use the calculator all the time as a scratch pad for calculations, and not having the result persist after hiding the launcher really hampers its usefulness

**Comment by oliverschwendener** [comment]
This should be resolved with ueli v9: https://github.com/oliverschwendener/ueli/releases
