### ISSUE TITLE
Windows fluent folder icon in the windows app instead of mac folder icon

### ISSUE THREAD

**Issue by shahiljain** [oliverschwendener/ueli#586]
![icons8-folder-240](https://user-images.githubusercontent.com/75173792/100519263-da3d5f80-31bc-11eb-9966-ebdc94d8a085.png)
As seen above. (this png is from icons8)

**Comment by oliverschwendener** [comment]
This should be resolved with ueli v9: https://github.com/oliverschwendener/ueli/releases
