### ISSUE TITLE
Ueli crashes really easily

### ISSUE THREAD

**Issue by nekofurball** [oliverschwendener/ueli#59]
Ueli crashes regularly when opened.

I don't know the cause of the issue.

**Comment by oliverschwendener** [comment]
Operating system? Is there any crash message or does it just quit? Or does it freeze? Did you modify your config?

**Comment by khanhas** [comment]
Try open UELI from terminal. E.g in Windows, open cmd and run:
```bash
"C:\Program Files\ueli\ueli.exe"
```
It should throw error to cmd if it crashes

**Comment by nekofurball** [comment]
1. Windows
2. It freezes
3. Unmodified configuration

**Comment by longman391** [comment]
This seems to have gotten worse since the fall Windows 10 update. It now causes the file explorer to hang (with some weird refresh issues), which also causes the start menu to disappear completely. Restarting the file explorer solves the issues but only until UELI is invoked again.

**Comment by oliverschwendener** [comment]
Remove all entries in `applicationFolders` and `fileSearchOptions` in your config. Does it still freeze?

**Comment by oliverschwendener** [comment]
I have no problems with Windows 1809. Is there any difference when applying the steps I mentioned above?

**Comment by oliverschwendener** [comment]
@nekofurball @longman391 ?

**Comment by nekofurball** [comment]
Sorry for my lack of responses.
Since the latest update the issue has been resolved. I have no more issues with Ueli!

Thanks!
