### ISSUE TITLE
show ueli setting when typing "settings"

### ISSUE THREAD

**Issue by cathaysia** [oliverschwendener/ueli#591]
When I hidden my tray icon, if I want change it's settings, I must modify %Appdata%/ueli/perference.json and restart ueli.

Why we don't show ueli's settings when we typing "settings"? just like Wox

**Comment by oliverschwendener** [comment]
Like this?

![image](https://user-images.githubusercontent.com/15727229/101172155-15b6ae80-3641-11eb-94dd-04ef4a18846f.png)

**Comment by cathaysia** [comment]
Oh! Yes, but it doesn't shown in my ueli, which I rebuild just yesterday. Mybe it's because it' priority level is too low?

[cid:dbbbfe2d-a060-4e62-b329-fbf2ca1abe9a]
[cid:b486f492-35cf-48a0-9491-199ac63141f2]
________________________________
发件人: Oliver Schwendener <notifications@github.com>
发送时间: 2020年12月4日 13:58
收件人: oliverschwendener/ueli <ueli@noreply.github.com>
抄送: dragonWater <319513897@outlook.com>; Author <author@noreply.github.com>
主题: Re: [oliverschwendener/ueli] show ueli setting when typing "settings" (#591)


Like this?

[image]<https://user-images.githubusercontent.com/15727229/101172155-15b6ae80-3641-11eb-94dd-04ef4a18846f.png>

―

**Comment by oliverschwendener** [comment]
Are you building the app by yourself?

**Comment by cathaysia** [comment]
> 
> 
> Are you building the app by yourself?

Yes, I built it by myself.

**Comment by cathaysia** [comment]
The reason of this is beacuse 'settings' command's priority is too low, I guess this function brought by "operating system commands". Give it a highter priority may better.

**Comment by oliverschwendener** [comment]
It works fine for me

<img width="610" alt="image" src="https://user-images.githubusercontent.com/15727229/114818277-d56bf780-9dbb-11eb-8e2c-0a85a7eb6800.png">

**Comment by cathaysia** [comment]
Turn on more plugins may cause this problem? 

![图片](https://user-images.githubusercontent.com/42114817/114842235-3ec72700-9e0b-11eb-8d33-a53f10a16dee.png)
![图片](https://user-images.githubusercontent.com/42114817/114842286-4a1a5280-9e0b-11eb-81af-8543df2be6d8.png)
