### ISSUE TITLE
[Bug] unable to find files from Documents

### ISSUE THREAD

**Issue by VajraCool** [oliverschwendener/ueli#592]
Though I explicitly added documents folder on "Simple Folder Search" , still couldn't find files. This is on win 10.

**Comment by burt-ie** [comment]
I have this problem too, it finds some folders but not all. It also doesn't find files even if I type the exact name in.

**Comment by oliverschwendener** [comment]
Closing this issue because the simple folder search plugin will be discontinued with ueli v9, unless someone take their time to migrate it.
