### ISSUE TITLE
Ueli Continuously Refreshes Indexes

### ISSUE THREAD

**Issue by TrevorBushnell** [oliverschwendener/ueli#593]
I have just installed the Ueli app and not changed anything in settings (such as adding folders to application launch and the like). Ueli automatically refreshes indexes but when it does this, it never finishes the process (it always says refreshing indexes and I can't ever type anything into the textbox that appears). If I delete the program and reinstall I will eventually run into this same issue when it tries to automatically refresh indexes.

**Comment by leviqsupernova** [comment]
Got the same issue. Can it be because of the fact that I turned off indexing in Win 7?

**Comment by TrevorBushnell** [comment]
I should note that I needed to factory reset my laptop for different reasons and when I installed ueli this time it worked perfectly fine. I have no clue what was wrong before having to factory reset. Excellent application though, these types of programs really make my life easier, and this one is especially all-encompassing.

**Comment by oliverschwendener** [comment]
Can someone check if this is still an issue with the latest v9 release? https://github.com/oliverschwendener/ueli/releases
If so, feel free to reopen.
