### ISSUE TITLE
[Feature Request] Improve error messages when trying to add a shortcut

### ISSUE THREAD

**Issue by k2s09** [oliverschwendener/ueli#597]
I spend so long trying to make some shortcuts for websites but every time error message of invalid shortcut was popping up. I am not able to figure out what's the issue. Please let me know. Thanks.
![Settings 08_12_2020 19_02_28](https://user-images.githubusercontent.com/68739182/101490431-589dbc80-3988-11eb-80ab-4a5a48a40b00.png)
![Settings 08_12_2020 19_03_35](https://user-images.githubusercontent.com/68739182/101490447-5c314380-3988-11eb-98a8-31fbf27c21d5.png)

**Comment by oliverschwendener** [comment]
I think in your case you should just add `http://` or `https://` in front of your URL.

**Comment by oliverschwendener** [comment]
I agree that the error message here could be more accurate, telling the user what is wrong.

**Comment by k2s09** [comment]
With Https it worked. Thanks

**Comment by oliverschwendener** [comment]
This should be resolved with ueli v9. https://github.com/oliverschwendener/ueli/releases
