### ISSUE TITLE
Assigning "Super" as a hotkey

### ISSUE THREAD

**Issue by Nimerkuloff** [oliverschwendener/ueli#60]
Am I allowed to make a hotkey with only "windows" button? 
Adding `"hotKey": "Super"` to config leads to:
>Uncaught Exception:
>TypeError: Error processing argument at index 0, conversion failure from Super
>  at registerGlobalHotkey (C:\Program Files\ueli\resources app.asarbundlemain.js:102616:31)
>  at App.createMainWindow (C:\Program Files\ueli\resources app.asar\bundle\main.js:102597:5)
>  at emitTwo (events.js:131:20)
>  at App.emit (events.js:214:7)

**Comment by oliverschwendener** [comment]
Thank you for your feedback! I think electron does not allow only `Super` to be used as a global keyboard shortcut (see: [https://github.com/electron/electron/issues/1395](https://github.com/electron/electron/issues/1395)).

**Comment by airtonix** [comment]
meh
