### ISSUE TITLE
Learning searches

### ISSUE THREAD

**Issue by dietmar4711** [oliverschwendener/ueli#601]
Hi,

first, sorry if I missed some posting here regarding my issues - I read across but couldn't find anything.
First, I must say that ueli is a nice, good looking launcher, although I have to admit that 200MB "just for launching" is way too much (yes, I know, HDD space is not really an issue nowadays ;)).
In the past, I used Launchy (launchy.net) which is also very convenient, nice and has a very small footprint, but I now started testing ueli.

2 issues so far:
1) When I search for "uninstall" , I will only get results with "uninstall" in the beginning, but e.g. not "IOBit Uninstaller" - which I am searching for...
2) When I search "f", select "Firefox" from the list, Launchy (in the past) remembered this decision and showed my immediately "Firefox" as first hit when I again searched for "f". ueli doesn't do that. Am I missing something? I think this would be the greatest benefit of launchers like Launchy or ueli to remember search decisions and immediately priorizing the results, which results in a much more effective behaviour (which I expect from launchers, not just "looking good"!)

Dietmar

**Comment by oliverschwendener** [comment]
Thanks for your feedback!

1. You should get search results with "uninstaller" in the name when searching "uninstall". You can play around with the search engine settings here:

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/15727229/102182207-30441f80-3eac-11eb-9992-6bc79aacd3b6.png">

2. Ueli does something similar but apparently launching Firefox just once is not considered as "enough" to list it as a first result. Try to launch Firefox a few more times and it should get listed higher. The more you launch an app, the more important it is considered when showing the search result list.
