### ISSUE TITLE
Add support for Firefox bookmarks

### ISSUE THREAD

**Issue by Warden20** [oliverschwendener/ueli#604]
I want to make the searches with firefox and see the bookmarks

**Comment by oliverschwendener** [comment]
Currently not possible.

**Comment by al-lad** [comment]
I'm also interested. Is it not possible because of Firefox itself or just not included in ueli yet ?

**Comment by oliverschwendener** [comment]
Technically it's possible, but currently ueli does not support reading the firefox bookmarks.

**Comment by FunctionDJ** [comment]
I'll take a look at implementing this.

**Comment by tkohlmeier** [comment]
I already did. Just need to finalize it and create the pull request.

**Comment by FunctionDJ** [comment]
Awesome!

**Comment by Warden20** [comment]
Awesome!
