### ISSUE TITLE
Search web by default if there are no results

### ISSUE THREAD

**Issue by govindKAG** [oliverschwendener/ueli#61]
I have been enjoying this app so far but there is one feature I miss sorely from alfred on MacOs.
If you type something and there are no relevant results in ueli, it'd be a good idea to search some default search engine with that query (say google or duck duck go).
When you want to search something like "when is the winter solstice" you can just hit alt+space and mindlessly type it in. Having to type in g? just for that seems like a needless step since ueli doesn't do anything with that query anywhere.

**Comment by oliverschwendener** [comment]
There is a feature called 'fallback websearch'. If you are using the latest version you can open the settings with `ctrl+i` and then under 'Fallback web search' select a web search engine. If you are using an older version than 6.1.0 then you have to specify a `fallbackWebsearch` in your config file (see [here](https://github.com/oliverschwendener/ueli/tree/v6.0.0#fallback-web-search-engines)).
