### ISSUE TITLE
Half load

### ISSUE THREAD

**Issue by Prakrit-170807** [oliverschwendener/ueli#612]
I have assigned the key stroke of alt + space but each time I press it the search window opens only a half as in the photo ![image](https://user-images.githubusercontent.com/73429704/103256687-23e3ba80-49b4-11eb-926e-9300d484b307.jpeg)

**Comment by oliverschwendener** [comment]
Seems like you messed up the config file. Delete the following file and you should be good again:

Windows: `%APPDATA%\Roaming\ueli\config.json`
macOS: `~/Library/Application Support/ueli/config.json`
