### ISSUE TITLE
Show native icons not working on MacOS 11

### ISSUE THREAD

**Issue by krizajb** [oliverschwendener/ueli#613]
MacOs icons such as SystemPreferences, Bluetooth etc aren't displayed correctly. Native icons are turned on.

![image](https://user-images.githubusercontent.com/496094/103346802-6f21ca00-4a95-11eb-8940-4f3cbbb2f909.png)
![image](https://user-images.githubusercontent.com/496094/103346824-819c0380-4a95-11eb-930f-96be61511aff.png)

**Comment by oliverschwendener** [comment]
Can someone check if this is still an issue with the latest v9 release? https://github.com/oliverschwendener/ueli/releases
If so, feel free to reopen.
