### ISSUE TITLE
[Feature Request] Ueli instead of Windows Search by pressing Win+S

### ISSUE THREAD

**Issue by bradleythedeveloper** [oliverschwendener/ueli#614]
I got used to pressing Win+S to bring up Windows Search before finding Ueli, and I keep pressing Win+S instead of Alt+Space and triggering Windows Search instead of Ueli. This is really annoying me, so can the option to use Windows+S (or at least Windows+*something near the letter S*) to open Ueli instead of Windows Search.

**Comment by gabriel-peracio** [comment]
You may be able to use PowerToys to remap the shortcut.

I like binding it to win+enter, which normally brings up narrator and cannot be reassigned, but with PowerToys you can.

**Comment by oliverschwendener** [comment]
Unfortunately this is not possible, see here: #454
