### ISSUE TITLE
Ignore mouse until it is moved

### ISSUE THREAD

**Issue by govindKAG** [oliverschwendener/ueli#62]
When typing in a query most people will tend to leave the mouse in the middle of the screen, this often interferes with the search results. Often the top result is ignored in favor of the result the mouse pointer happens to be over. 

A possible solution could be to ignore the location of the mouse pointer until it is moved, or to not change the currently selected the search result based on the mouse pointer at all, (you could still allow clicking a specific result but it doesn't get highlighted/selected)

**Comment by oliverschwendener** [comment]
You can disable mouse interaction in the settings. If you are using v6.1.0 or later then open the settings with `ctrl+i`. If you are using v6.0.0 or older you have to modify your [config file](https://github.com/oliverschwendener/ueli/tree/v6.0.0#customization).
