### ISSUE TITLE
[Feature Request] [Help Wanted] French translation & quiet/silent install

### ISSUE THREAD

**Issue by topiga** [oliverschwendener/ueli#620]
## French translation & quiet/silent install
Hi everyone, I'd like to help you translate this app and to submit a feature.

### French translation
Okay so first I'd like to translate this app, I already use it, but I'd like to have it in my own language. Could someone explain me how to do that please ? Thank you.

### Quiet/Silent install
Okay so I was making a custom ISO for Windows, and I was getting rid of Windows Search and Cortana, So is there any hope for a silent install with like :
`"ueli-Setup-X.X.X.exe" /q` or `"ueli-Setup-X.X.X.exe" /S`, like VLC ?

Thank you for this great app.
Topiga

**Comment by tkohlmeier** [comment]
For the translation I suggest to look at this commit: https://github.com/oliverschwendener/ueli/pull/511/commits/9298e98d039387796b6328a182bac134b287882d
That's all that has to be done.

**Comment by tkohlmeier** [comment]
Silent install should work with `/S` (must be upper case).
