### ISSUE TITLE
Showing error when i search files

### ISSUE THREAD

**Issue by Jacob050** [oliverschwendener/ueli#621]
![image](https://user-images.githubusercontent.com/70995451/104080201-b3a72580-524c-11eb-8eba-feb1984b93dd.png)

I have installed everything and everything command line interfacece

**Comment by tkohlmeier** [comment]
Please post your debug log. You can open it here:

![grafik](https://user-images.githubusercontent.com/6824291/104090457-3644da80-5277-11eb-92fd-12890aebb24b.png)
