### ISSUE TITLE
Adding the ability to favourite/bookmark files so that they're promoted to the top of search results

### ISSUE THREAD

**Issue by kabirverman** [oliverschwendener/ueli#627]
As an example when I search for Notion I get the shortcut first followed by the application. Obviously this isn't a big deal as both will launch the program but personally I don't like seeing the shortcut icon when I have the actual application path linked in the Application Search settings.

![image](https://user-images.githubusercontent.com/33439194/104485381-6c949980-5598-11eb-86e6-ff348dd39050.png)

I also know there are work arounds like I can blanket remove the .lnk extension from search but that feels too broad, however having the ability to favourite the actual Notion application to have it promoted to the top would be great and more user-friendly

### Proposed Implementation:
_I understand that this isn't actually all too helpful as it's just words and not a tangible coded solution, but I don't want to just demand a feature wile contributing no thought to how it might actually work_

I can see this being implemented as another section within the Application Search settings where users can browse for files to add to their favourites, where I see this _primarily_ being used is with a keyboard shortcut within the ueli search itself to add the highlighted file to the favourites. `Ctrl + F` might not be intuitive because that's typically used to search on most programs so something like `Ctrl + B` might be more user friendly as most broswers use that for creating bookmarks (the implementation would be renamed to Application Bookmarks in this case)

Here's a little mock-up I made in Photoshop showing the possible Application Bookmarks section in the ueli settings and also what the search might look like to indicate that a file has been bookmarked/favourited

![image](https://user-images.githubusercontent.com/33439194/104493135-a10d5300-55a2-11eb-9980-7b7379931689.png)
![image](https://user-images.githubusercontent.com/33439194/104493147-a5d20700-55a2-11eb-807a-b79ff58f52cb.png)

**Comment by kabirverman** [comment]
When posting this issue I got a 404 error from github so I reposted. Both issues ended up being posted so I'm closing this one

**Comment by CouldBeThis** [comment]
> When posting this issue I got a 404 error from github so I reposted. Both issues ended up being posted so I'm closing this one

for anyone find this via search, the active issue is #626
