### ISSUE TITLE
[Bug] Browser Plugin reads wrong Browser Profile

### ISSUE THREAD

**Issue by OliverSchr** [oliverschwendener/ueli#628]
I had a Chrome User, and the plugin worked fine. Now i have a new Profile, and i'm logged into Chrome and the Google World with a new Account. What i miss is an option to make the Browser Bookmark Plugin to read the Bookmarks of my new Profile. It reads the old, not longer maintained Bookmarks.

**Comment by heyhoss** [comment]
did you find a fix for this/

**Comment by OliverSchr** [comment]
To be honest...
I can't remember :-)
Obviously i've found a solution, as it works now, but what i did... Don't
know.
but it had to do with "Try and error"..


#gernperdu

Gruß,

Oliver Schröder

Email: ***@***.***
Mobil: +49 176 62839978




Am Di., 6. Sept. 2022 um 02:01 Uhr schrieb heyhoss ***@***.***

**Comment by oliverschwendener** [comment]
Can you test this with the latest version and reopen the ticket if this is still an issue? Thanks
