### ISSUE TITLE
User input height value not registering beyond 60

### ISSUE THREAD

**Issue by irabronson** [oliverschwendener/ueli#633]
If a value is entered that is greater than 60, the input field itself does not increase in height. It seems there is a container that _does_ actually increase in height.

Screenshot attached; I have set the input height to 150. On the left you will see the extra space below the input field, and on the right, text has been entered

![ueli-input-height](https://user-images.githubusercontent.com/1404378/105612308-3968bc00-5d89-11eb-88d9-ff4bfaac521e.png)

**Comment by kr15uk** [comment]
Glitches on values below 60px - see attachment
Both with or without border radius aka rounded edge


<img width="726" alt="Screenshot 2021-02-16 at 00 07 04" src="https://user-images.githubusercontent.com/5671041/108003977-55f4be80-6fec-11eb-8af0-64a242731e97.png">

**Comment by oliverschwendener** [comment]
I'll close this issue as ueli v8 won't be maintained anymore and the ability to adjust the user input height will be removed in v9.
