### ISSUE TITLE
(Mac) Application search does not show results from Utilities folder

### ISSUE THREAD

**Issue by exinr** [oliverschwendener/ueli#634]
I have both /Applications and /Applications/Utilities as application folders for Application search, but application search is not able to load things in the utilities folder. If there is another folder I'm supposed to be enabling in application search to be able to open this applications, then please let me know.
![image](https://user-images.githubusercontent.com/62219187/105639328-4810ab00-5e3d-11eb-9624-337315d58d19.png)
![image](https://user-images.githubusercontent.com/62219187/105639421-e0a72b00-5e3d-11eb-95e9-8463f41b5068.png)
![image](https://user-images.githubusercontent.com/62219187/105639442-f3216480-5e3d-11eb-9137-866a3567bb4e.png)

**Comment by micnguyen** [comment]
I think there are issues searching in Application. `Calendar.app` is in `/Applications` and it doesn't show up either when I search `Calendar`

**Comment by oliverschwendener** [comment]
Try adding `/System/Applications`

**Comment by o1dnik** [comment]
Thanks @oliverschwendener , works just fine! I think, @exinr can close this issue.
