### ISSUE TITLE
Dictionary just doesn't work sometimes

### ISSUE THREAD

**Issue by siddarththiru** [oliverschwendener/ueli#636]
![image](https://user-images.githubusercontent.com/70185618/105996964-0d26a580-60d1-11eb-8bbd-ed38bd360d16.png)
![image](https://user-images.githubusercontent.com/70185618/105996989-144db380-60d1-11eb-84a5-bb34632bfa30.png)

Literally taken in a span of 30 seconds, and this isn't just the first time, I have had it happen SEVERAL times, and it quite honestly just may not exist cause if this can't be done properly I think we can just make **dict?x** just output **g?meaning of x**

**Comment by oliverschwendener** [comment]
Closing this as the Dictionary plugin will be discontinued with ueli v9, unless someone takes their time to migrate it.
