### ISSUE TITLE
Rectangle

### ISSUE THREAD

**Issue by prostogasha** [oliverschwendener/ueli#637]
A strange rectangle behind the search line which was not there but at some point appeared
![Screenshot_8](https://user-images.githubusercontent.com/73956556/106336254-92f84b80-629f-11eb-9a1d-dff18f37d269.png)
Reinstallation did't help

**Comment by oliverschwendener** [comment]
I guess this is on Windows. Did you activate the transparency option?

![image](https://user-images.githubusercontent.com/15727229/106357695-eb633380-6307-11eb-9ca7-f15f5a471890.png)
