### ISSUE TITLE
Photos app doesn't come up on Mac

### ISSUE THREAD

**Issue by tamaracks** [oliverschwendener/ueli#640]
For some reason, the 'Photos' app will not come up as a result when I type 'photos' in the search box. I'm on macOS 11.2.

**Comment by oliverschwendener** [comment]
Make sure to add the folder `/System/Applications` in the application search settings:

![image](https://user-images.githubusercontent.com/15727229/107743884-01aebd80-6d12-11eb-827f-7205b5c4b145.png)

**Comment by oliverschwendener** [comment]
Does it work with my suggestion?

**Comment by tamaracks** [comment]
I just tried it, and yes, it works. Thanks! Definitely a bit confusing since Finder also shows it in the regular Applications folder.

Thanks,
Tamara

**Comment by momomo** [comment]
I have these, and these applications still no showing up: 

![image](https://user-images.githubusercontent.com/9274346/183243511-738afa0a-fab8-4042-aeb2-b27501b4d5fb.png)


![image](https://user-images.githubusercontent.com/9274346/183243515-709beac8-4f6c-4544-b2c3-591c3e7bb624.png)


Tried to remove and re add the index. 

Currently, this application is unusable to me and will be going back to LaunchBar. 

Also, the settings prefeferences is not working. 

![image](https://user-images.githubusercontent.com/9274346/183243582-3b7157b6-b87a-427f-b1d6-a1a25f84a73a.png)

Refreshing and what not, not helping. 

What are the required Privacy settings?
