### ISSUE TITLE
[Feature Request] Allow Powershell in Workflow plugin

### ISSUE THREAD

**Issue by FunctionDJ** [oliverschwendener/ueli#644]
Right now the options for execution steps are Command line tool, File path and URL. It would be great to be able to run Powershell as well in order to use modern Powershell commands instead of the limited cmd.

**Comment by oliverschwendener** [comment]
In ueli v9 you are able to open Powershell with a given command:

![image](https://github.com/oliverschwendener/ueli/assets/15727229/5098f15e-6e0b-4b1b-96a4-fba391d6cf86)
