### ISSUE TITLE
Glitches with "user radius"

### ISSUE THREAD

**Issue by kr15uk** [oliverschwendener/ueli#645]
When "user radius" is defined and search result has scrollable content edges are not rounded on the side of the scroll bar.
Also if you keep typing so scroll bar disappears it creates weird white empty corners on all sides.
See attachments.

<img width="726" alt="Screenshot 2021-02-16 at 00 06 27" src="https://user-images.githubusercontent.com/5671041/108004497-f13a6380-6fed-11eb-879f-042b247d123b.png">
<img width="726" alt="Screenshot 2021-02-16 at 00 06 42" src="https://user-images.githubusercontent.com/5671041/108004495-f0093680-6fed-11eb-8a83-cd0b896f8bbe.png">

**Comment by aystic** [comment]
I am having this weird issue where I have set the border radius to 15px but I can see the background which should not be visible.
![image](https://user-images.githubusercontent.com/54324845/142980929-eec2e9aa-1edd-44fc-86c3-25fad724eaaa.png)

**Comment by oliverschwendener** [comment]
@aystic Did you enable transparent the transparent background?

**Comment by aystic** [comment]
> @aystic Did you enable transparent the transparent background?

Thanks for pointing out. I enabled the transparent background and restarted the system. This is how it looks like now.
I am not sure why this line is appearing below the search bar though.
![image](https://user-images.githubusercontent.com/54324845/142983374-774b5bf2-a3f2-437e-9936-5ae26956e3e2.png)

**Comment by polyjitter** [comment]
Is this ever going to be fixed? it makes rounded corners pointless and is one of the reasons i've been considering powertoys run instead

**Comment by oliverschwendener** [comment]
I'll close this issue as these customization options will be removed in ueli v9 and v8 is not maintained anymore.
