### ISSUE TITLE
Apps wont open

### ISSUE THREAD

**Issue by Radek792** [oliverschwendener/ueli#646]
When I try to search, I will get results but it wont open. Tried default settings and reinstall. Can someone help?
 Thanks!

**Comment by Gizmo-Ger** [comment]
I have the same issue. Can´t use enter key nor the mouse to open up the program.

**Comment by oliverschwendener** [comment]
Can you show us your debug log?

1. Open settings via the tray icon
2. Go to general settings
3. Click on the 3 dots and click Open debug log

![image](https://user-images.githubusercontent.com/15727229/108673477-0890b980-74e4-11eb-8685-628f7711c85f.png)

**Comment by oliverschwendener** [comment]
By the way: the enter key press only works when the cursor is set in the user input field.
![image](https://user-images.githubusercontent.com/15727229/108673917-c156f880-74e4-11eb-9bbc-09c87de2d417.png)

**Comment by Gizmo-Ger** [comment]
debug.log
https://pastebin.com/9iM1iNdE

While searching I can´t pick out of the drop down list with the mouse and double click the program to open.
I can do so with the cursor keys and open with enter. Just not with the mouse.

**Comment by oliverschwendener** [comment]
There is no support for mouse interaction yet.

**Comment by oliverschwendener** [comment]
You have to press enter to execute the selected item in the search result list.

**Comment by Gizmo-Ger** [comment]
OMG - shame on me. I´m feeling like a douchbag now. Mea culpa. So mouse support might be an upcoming feature?

**Comment by oliverschwendener** [comment]
Yes, see #393
