### ISSUE TITLE
(Mac) Native support for Apple Silicon / M1

### ISSUE THREAD

**Issue by davidschoefberger** [oliverschwendener/ueli#647]
There is support for Apple Silicon (arm64) in Electron 11. Is it planned to make ueli available as an universal app, so it's running on Intel and Apple Silicon natively?

**Comment by oliverschwendener** [comment]
Yes, as soon as GitHub Actions provides macOS hosts which run on arm64.

See here: https://github.com/actions/virtual-environments/issues/2187

**Comment by oliverschwendener** [comment]
This is solved with ueli v9.
