### ISSUE TITLE
Search result scoring issue

### ISSUE THREAD

**Issue by walter6469** [oliverschwendener/ueli#648]
![image](https://user-images.githubusercontent.com/70185618/108365588-62139280-721d-11eb-856f-b06e74869bb7.png)
![image](https://user-images.githubusercontent.com/70185618/108365788-9b4c0280-721d-11eb-9499-1eb6ad500164.png)
I have come across with several other weird issues and results
![image](https://user-images.githubusercontent.com/70185618/108366804-c7b44e80-721e-11eb-9963-5a7c8a959141.png)
Here there is no proper app icon, but windows has one, I am sure there is a fix for this, but wouldn't it be better if UELI can just do all this?

And there's this:
![image](https://user-images.githubusercontent.com/70185618/108367170-2da0d600-721f-11eb-9ee5-1238ede42681.png)
![image](https://user-images.githubusercontent.com/70185618/108367173-2ed20300-721f-11eb-9685-87c8c7dc40ad.png)

This one too: 
![image](https://user-images.githubusercontent.com/70185618/108367263-4610f080-721f-11eb-9d8d-2038b0d4d731.png)

Look where this is!
![image](https://user-images.githubusercontent.com/70185618/108367713-bcadee00-721f-11eb-97a0-609f6350bbf3.png)

Let me know if I have done something wrong and is there anyway I can fix this? Because Windows Search is pretty spot on on what I am looking for, few examples here:
![image](https://user-images.githubusercontent.com/70185618/108367886-e1a26100-721f-11eb-8edb-90be7c3cf7c5.png)
![image](https://user-images.githubusercontent.com/70185618/108367926-e9fa9c00-721f-11eb-84f8-b95c379784ec.png)

**Comment by oliverschwendener** [comment]
Hmm this looks weird...

Did you change the fuzzyness in the search engine settings?

![image](https://user-images.githubusercontent.com/15727229/108371400-008ffb80-71fe-11eb-893a-3ea62938f503.png)

**Comment by walter6469** [comment]
Changing fuzziness to 0.5 (it was at 1, idk when I changed it but I do remember messing with some settings a while ago)) indeed fixes a few issues, but the dictionary and icon issues still persist

**Comment by oliverschwendener** [comment]
Then I see this as resolved. For the dictionary and icon issues please open up separate github issues, so it's easier to track the progress. Thanks for reporting!
