### ISSUE TITLE
[Feature Request] Add Google Translate API

### ISSUE THREAD

**Issue by ghost** [oliverschwendener/ueli#650]
First of all, thank you for this great app. Actually, I don't understand why we can't select with mouse cursor besides enter button. It would be very useful to have this feature. Also, can you please try to add Google Translate API? I am Turkish and I need Turkish translation which I can't do in "linguee" API.

**Comment by oliverschwendener** [comment]
Thanks for your feedback!

As there is already a ticket for the mouse support feature request (#393) I will change this issue's title to "Add Google Translate API".

**Comment by ataberkcemunal** [comment]
Other requests:
- In the web search engine suggestions, "ç", "ö" and "ü" (Turkish characters) appear as a question mark. I would be happy if you fix that problem.
- IMDb API to search movies and see their year and rating.

**Comment by oliverschwendener** [comment]
For other issues please open separate issues so it's easier to track the progress, thanks!

**Comment by oliverschwendener** [comment]
I consider this to be resolved with the integration of the DeepL Translator in ueli v9.
