### ISSUE TITLE
Persist window position after app restart when "remember window position" is turned on

### ISSUE THREAD

**Issue by paperfairy** [oliverschwendener/ueli#652]
https://user-images.githubusercontent.com/3393711/108607123-54702100-7373-11eb-8fd8-ec972857986f.mp4
Windows 10.0.19043 Build 19043
ueli 8.10.0

Whenever I start Ueli, the app is near the top of the screen. At larger resolutions, it is completely out of touch and reach.

I have tried the following steps:

1) Move the application window.
2) make sure "remember position" is turned on
3) close the app
4) re-open the app

When I re-open the app, I expect the window to be in the position I dragged it to, but instead, it goes back to the original, off screen position. I have attached a video of me attempt to fix the issue.

What am I doing wrong?

**Comment by oliverschwendener** [comment]
Thanks for your feedback!

You're doing nothing wrong. The "remember position" option is currently only designed to work within the same session. When the app is restarted the window will show up in the center of the screen.

I'll rename this issue to "Persist window position after app restart" and turn it into a feature request.

**Comment by paperfairy** [comment]
@oliverschwendener 

In the meantime, does that mean I can't use ueli? The bar and first few results are invisible when I'm at my normal resolution - I have to scale down to 1024x768 just to be able to see it. Is there a config file where I can manually edit where the bar is placed on cold start?

**Comment by oliverschwendener** [comment]
The window should now appear in the same position, even after a app restart. Make sure to update to the latest version.
