### ISSUE TITLE
forgot hotkey and app icon hiden ,how to reset ueli(reinstall not work)

### ISSUE THREAD

**Issue by ltu00** [oliverschwendener/ueli#655]

**Comment by oliverschwendener** [comment]
1. Click on the tray icon => Click on settings
    ![image](https://user-images.githubusercontent.com/15727229/108673629-4ab9fb00-74e4-11eb-99b4-aace7fd925db.png)
2. Go to general settings
3. Change your hot key
    ![image](https://user-images.githubusercontent.com/15727229/108673663-586f8080-74e4-11eb-95e8-100e782f103a.png)

**Comment by ltu00** [comment]
> 1. Click on the tray icon => Click on settings
>    ![image](https://user-images.githubusercontent.com/15727229/108673629-4ab9fb00-74e4-11eb-99b4-aace7fd925db.png)
> 2. Go to general settings
> 3. Change your hot key
>    ![image](https://user-images.githubusercontent.com/15727229/108673663-586f8080-74e4-11eb-95e8-100e782f103a.png)

emmm,i turned off tray icon ,so i can't find the way  to reset ueli hotkey

**Comment by oliverschwendener** [comment]
Try this:

1. Quit the app
2. Delete the following file:
    Windows: `%APPDATA%\Roaming\ueli\config.json`
    macOS: `~/Library/Application\ Support/ueli/config.json`
3. Start the app again. Default hotkey is `Alt+Space`

**Comment by ltu00** [comment]
> Try this:
> 
> 1. Quit the app
> 2. Delete the following file:
>    Windows: `%APPDATA%\Roaming\ueli\config.json`
>    macOS: `~/Library/Application\ Support/ueli/config.json`
> 3. Start the app again. Default hotkey is `Alt+Space`

it works .thx 
i have a suggestion ,it is possible to set double ctrl as hotkey ? (yeah i'm listary user too)

**Comment by oliverschwendener** [comment]
As this issue is resolved I'll close this issue.

For any other feature requests please open a separate issue.
