### ISSUE TITLE
Currency Converter: Support PKR currency

### ISSUE THREAD

**Issue by ayoubkhan558-zz** [oliverschwendener/ueli#657]
Not showing any result for USD to PKR.
![image](https://user-images.githubusercontent.com/20210961/108988954-e87b0a80-7649-11eb-8ad3-d9c8ce40c33a.png)

**Comment by oliverschwendener** [comment]
Ueli uses this API to convert currencies: https://exchangeratesapi.io
Apparently PKR is not supported yet.

**Comment by ayoubkhan558** [comment]
I have created issue on their repo [exchangeratesapi Currency Converter: Support PKR currency #115](https://github.com/exchangeratesapi/exchangeratesapi/issues/115)

**Comment by oliverschwendener** [comment]
This is solved with ueli v9:

![image](https://github.com/oliverschwendener/ueli/assets/15727229/87c35366-9be0-48a0-bb28-1f1eac68672a)

You can try out the beta version here: https://github.com/oliverschwendener/ueli/releases
