### ISSUE TITLE
Update chocolatey packages

### ISSUE THREAD

**Issue by aarjav24** [oliverschwendener/ueli#658]
Version 8.11.0 was released 5 days ago. Suggesting @oliverschwendener to update the choco repo himself which would consequently lead to consistency in updates.

**Comment by oliverschwendener** [comment]
@TimB87 Is this something you can do?

**Comment by TimB87** [comment]
@oliverschwendener Yes, sure, but once I get to my windows workstation that has the git repository/tools installed. I am sorry but other commitments don't let me prioritize this any higher. 

I think that in the long run I will step down from maintaining ueli for chocolatey for a number of reasons, but mainly a) I am not a windows user in my private time and b) I don't even use ueli anymore. 

So in case @aarjav24 or anyone else wants to take over the package I would be glad to hand it over.

**Comment by aarjav24** [comment]
Totally understandable @TimB87. Apologies since I have other commitments to make as well and am not too familiar with such procedures. In fact, I'd request @oliverschwendener to take over the repo since it's his project and regular updates by the dev himself will encourage more people to use ueli. Chocolatey is a great platform for developers like him since it's considered the best package manager for windows and extremely useful. Please do consider it @oliverschwendener.
Thanks.

**Comment by TimB87** [comment]
@oliverschwendener The package is updated, but I'd be okay with the issue staying open so a new maintainer can be found in the long run. I don't mind carrying it along for a while, but I won't break a leg over updating it.

**Comment by oliverschwendener** [comment]
Thanks alot @TimB87! No worries I totally understand this! :) Can you show me how to update the package and give me all the access that is needed, so I can take over the ownership of the package?

**Comment by TimB87** [comment]
@oliverschwendener Sure thing! I'll have a look into it over the weekend, you could prepare yourself a chocolatey account in the meantime.

A short summary is just adjust numbers and sha sum in choco files, create a package out of it (basically just zip format), then upload that to chocolatey through their cli tool which will need an API key locked to your account.

It might work with giving you access to my repo, or you want to split off to your own repo. Whichever suits you best and works.

**Comment by oliverschwendener** [comment]
I wouldn't mind working on your repo, might be the simplest solution?

**Comment by TimB87** [comment]
Ok, I just invited you to be a collaborator over there.

With chocolatey around, after updating the chocolatey distfiles, you just need to issue the following commands (at least that's how I did it):

- `choco pack`
   - creates the zip package
- `choco update ueli -y -s .` 
   - update ueli on the system from your current working directory,  just to see if it works at all
- `choco push` 
   - sends the package for automatic review by chocolatey
- then just update the git repo

Just an ftr: i tried setting that up in a mono container in docker but it didn't work for me. If it would we probably wouldn't talk about it now :)

If you want, you can try out with creating some test branch just to see if it works, I really have no idea yet. If that works, we only need to get the chocolatey maintainership sorted, but that shouldn't be too much of a problem.

**Comment by aarjav24** [comment]
@oliverschwendener Have you gained authorized access to the repo?

**Comment by TimB87** [comment]
@aarjav24 it's ok to chill 🌞

**Comment by oliverschwendener** [comment]
Yeah no worries, you don't have to do it ;)

**Comment by TimB87** [comment]
So whats the future of the chocolatey package? Shall I try and delete it?

**Comment by TimB87** [comment]
Happy new year everybody.

@digitalcardboard stepped up and will keep the ueli package updated from here on on. Thanks for taking over Jason!

**Comment by digitalcardboard** [comment]
At this point this issue can be closed. Chocolatey package has been updated. @oliverschwendener
