### ISSUE TITLE
Web Search Engines

### ISSUE THREAD

**Issue by moses-bowman** [oliverschwendener/ueli#66]
1. **Spaces**
- search engines such as Google use **+** for spaces:
https://google.com/search?q=random+search+term
- some use _hyphens_, _%20_, and whatnot
- is there a way to instruct ueli to use which spacing for queries?

2. **Suffixes**
- some search engines suffix search terms which return 404 error when omitted
- suffixes on ueli's custom search engine might be useful

**Comment by LalaGhost** [comment]
As far as I know, your first point, moses-bowman, is already fixed. At least it works for me.
Ueli is not adding '+' signs in between the words but nonetheless it works

Link to video in my dropbox:
https://www.dropbox.com/s/a5jdauvwh9bk3kr/ueliGoogleSearch.mp4?dl=0

**Comment by oliverschwendener** [comment]
I added the possibility to specify a special "whitespace character" for web search engines:

![image](https://user-images.githubusercontent.com/15727229/50385248-de0fff80-06d2-11e9-8478-af7c4867b910.png)

If you have set a `Whitesapce Character` all whitespace from your query will be replaced with that character/string.

![image](https://user-images.githubusercontent.com/15727229/50385290-b5d4d080-06d3-11e9-9bce-7a9bc01bcf97.png)

If you don't specify a whitespace character ueli lets the browser decide how to encode the whitespace.

Additionally I added the possibilty to set up the URLs like this:

```
https://my-search-engine.com/?q={{query}}&suffix=whatever
```

`{{query}}` will be replaced by your input and therefore you should be able to preserve the suffix of the web search engine.

Here an example:

![image](https://user-images.githubusercontent.com/15727229/50385381-0c8eda00-06d5-11e9-967c-914353547f40.png)

I hope this solves your problems. These fixes will be included in the next release.
