### ISSUE TITLE
[Feature Request] the "reset" icon looks like a "refresh" icon

### ISSUE THREAD

**Issue by CouldBeThis** [oliverschwendener/ueli#664]
Hello, this is such a great tool! 

One thing: this icon 
![image](https://user-images.githubusercontent.com/53547181/110204671-4ece0d00-7e42-11eb-988e-2ccacb50e9ff.png)

To me the function looks like it could be "refresh" as in, once you have changed a setting, refresh the index. But as you know, what it *actually* does is reset to default. 

I've made the mistake a couple of times. I remember now what it does, but in a few months I'll have forgotten.

Suggestions

- change the icon (no specific suggestion for this)
- Add text
- Add a tooltip

**Comment by oliverschwendener** [comment]
Ueli v9 will use a "dismiss" icon and add a tooltip. Thanks for reporting!

![image](https://github.com/oliverschwendener/ueli/assets/15727229/b75d9705-10cb-4065-a67f-4b6d1112c83b)
