### ISSUE TITLE
Firefox bookmarks doesn't work

### ISSUE THREAD

**Issue by eliyabar** [oliverschwendener/ueli#667]
Using macOS Catalina (10.15.7) and Firefox 86, After selecting the Firefox option under Browser History Tab, a spinner will appear and stuck like that doing nothing until I will close the setting window.
![Screen Shot 2021-03-16 at 11 32 58](https://user-images.githubusercontent.com/13337543/111286994-75165880-864b-11eb-954f-6dacb45c8581.png)

**Comment by oliverschwendener** [comment]
@tkohlmeier

**Comment by tkohlmeier** [comment]
Are there any errors in the debug log?

![grafik](https://user-images.githubusercontent.com/6824291/111368333-0a3e3f00-8696-11eb-855f-dec7d5cfc0d3.png)

**Comment by eliyabar** [comment]
`2021-03-17T21:30:27.284Z debug: Update check result: update not available
2021-03-17T21:30:32.494Z error: Can't read bookmarks file: Error: ENOENT: no such file or directory, open '/Users/ebaron/Library/Application Support/Google/Chrome/Default/Bookmarks'
2021-03-17T21:30:36.402Z error: Can't read bookmarks file: Error: ENOENT: no such file or directory, open '/Users/ebaron/Library/Application Support/Google/Chrome/Default/Bookmarks'
2021-03-17T21:30:40.435Z error: SQLITE_BUSY: database is locked
Error: SQLITE_BUSY: database is locked`

It seems like the last two lines are triggered when I click on Firefox
since the app gets stuck after I click on Firefox, I'm restarting the app and the state of the Browser stays Firefox but immediately changes to Chrome for some reason.
In any case, I get errors, even though I have both browsers installed.

**Comment by tkohlmeier** [comment]
Does it work when Firefox is not running?

**Comment by eliyabar** [comment]
@tkohlmeier yes.

**Comment by tkohlmeier** [comment]
Firefox obviously locks the database ueli tries to access. I have no idea why this is different under Windows. The problem is, I don't have a Mac so I'm unable to find a solution, if there is any.

**Comment by oliverschwendener** [comment]
Closing this as it has been stale for a while now. Try out the latest beta release here to check if this is still an issue: https://github.com/oliverschwendener/ueli/releases. If so, feel free to reopen.
