### ISSUE TITLE
Border radius not working on search results when scrollbar is active

### ISSUE THREAD

**Issue by nodomw** [oliverschwendener/ueli#671]
![winter 2021-03-24 9287db19-031c-40e4-923a-275ba46f8690](https://user-images.githubusercontent.com/47635446/112277864-7ca8b380-8c82-11eb-8b97-25a64d3ed5b3.png)
![winter 2021-03-24 2904f983-10a3-43ff-b00d-597e445024e3](https://user-images.githubusercontent.com/47635446/112277867-7fa3a400-8c82-11eb-91b1-292de2d3f719.png)
![winter 2021-03-24 7d706d38-6491-4c6d-a087-a5559586c787](https://user-images.githubusercontent.com/47635446/112277873-80d4d100-8c82-11eb-9c4a-64740cc15dbc.png)

![winter 2021-03-24 f0a1faf0-4687-42b3-9ff4-3dbcf31a9613](https://user-images.githubusercontent.com/47635446/112277545-29cefc00-8c82-11eb-811c-5c75da165081.png)
![winter 2021-03-24 a7801edb-6f71-42ac-933a-d1b3c0c17bb5](https://user-images.githubusercontent.com/47635446/112277552-2b98bf80-8c82-11eb-80bb-352ab379f7b6.png)
![winter 2021-03-24 ddf39478-7a15-428c-91e8-fd8385fd7875](https://user-images.githubusercontent.com/47635446/112277683-48cd8e00-8c82-11eb-8b69-1442d543d9c4.png)
![winter 2021-03-24 da4646b9-4246-4233-b85c-ef0d3dc5cbf1](https://user-images.githubusercontent.com/47635446/112277691-4a975180-8c82-11eb-8c3d-8e04f37eb742.png)

**Comment by oliverschwendener** [comment]
Border radius customization will be removed in v9 and v8 is not maintained anymore. Therefore I'll close this issue.
