### ISSUE TITLE
[Feature Request] Option to Use Locally Saved Web Search Icon

### ISSUE THREAD

**Issue by natkey** [oliverschwendener/ueli#674]
For the web search icon, I think it would be nice to have the option to use files stored locally on the device. I'm wondering if Ueli often retrieves the icon files remotely because there is a noticeable delay in the search icon appearing. I think it would be better to have the option to use icon files stored on the pc, or alternatively, on first retrieval of url icon, store them locally and maybe have the option to refresh the icons periodically, if desired.

**Comment by oliverschwendener** [comment]
By default the icon is loaded from your computer but you can choose where the icon should be loaded from:

![image](https://user-images.githubusercontent.com/15727229/113502382-57426200-952c-11eb-841a-df462f4753e7.png)

SVG: icon is loaded from your computer.
URL: icon is loaded from the URL that you specify, it can be external but also a local file path

If you want to load an icon from your computer just type in this URL: `file://<FILE PATH>`

**Comment by oliverschwendener** [comment]
I guess your problem is related to #665

**Comment by oliverschwendener** [comment]
I consider this issue as resolved as Ueli v9 will use the favicons for URL search result items in a non-blocking way.
