### ISSUE TITLE
everything search not working

### ISSUE THREAD

**Issue by ahsanfarooq210** [oliverschwendener/ueli#675]
i have installed everything and everything command line interface but when i set up the path to the es.exe and search using the "es?" key word, it gives an error i 
[debug.log](https://github.com/oliverschwendener/ueli/files/6237405/debug.log)
am attaching the log files below so that you can solve the problem

**Comment by tkohlmeier** [comment]
Please open a cmd window, run the command `echo %pathext%` and post the result.

**Comment by tkohlmeier** [comment]
Please open a cmd window and post the result of this this command:

    echo %pathext%

**Comment by ahsanfarooq210** [comment]
C:\Users\ahsan>echo %pathext%
.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW

**Comment by ahsanfarooq210** [comment]
please help me

**Comment by balaji-ch** [comment]
**I too face the same issue**

```
Error: Command failed: cmd /c chcp 65001>nul && "C:\Program Files\Everything\es.exe" -max-results 24 hell
Error 7: Unable to send IPC message.

    at ChildProcess.exithandler (child_process.js:312:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
```

**Comment by tkohlmeier** [comment]
@ahsanfarooq210: I was asking for the pathext environment variable because in #561 this was the reason for a similar issue. But it seems to be ok on your system.

Does the cmd.exe exist in C:\Windows\System32? And is C:\Windows\System32 in the path variable? You can print the path varaible with this command:

    echo %path:;=&echo %

**Comment by ahsanfarooq210** [comment]
following are the results of the  `echo %path:;=&echo %` command. I think that **C:\Windows\System32** is not a path variable. I am going to add it in the path variable and try again.
 
**C:\Users\ahsan>echo %path:;=&echo %
C:\Users\ahsan\AppData\Local\Programs\Python\Python37\Scripts\
C:\Users\ahsan\AppData\Local\Programs\Python\Python37\
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL
C:\Program Files\Intel\Intel(R) Management Engine Components\DAL
C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\
C:\Users\ahsan\AppData\Local\Programs\Python\Python37-32\Scripts\
C:\Users\ahsan\AppData\Local\Programs\Python\Python37-32\
C:\Users\ahsan\AppData\Local\Programs\Python\Python37\Scripts\
C:\Users\ahsan\AppData\Local\Programs\Python\Python37\
C:\Python37.7\Scripts\
C:\Python37.7\
C:\Users\ahsan\AppData\Local\Microsoft\WindowsApps
ECHO is on.**

**Comment by ahsanfarooq210** [comment]
it solved my problem thanks @tkohlmeier, you are awesome.

### FOR THOSE OF YOU HAVING SIMILAR ISSUE:

**PROBLEM: ** Every thing search not working

**CAUSE OF THE PROBLEM;**  (C:\Windows\System32) was not a path variable.

**FIX:** Go to the environment variable and add (C:\Windows\System32) in path

**Comment by paraselen** [comment]
> **I too face the same issue**
> 
> ```
> Error: Command failed: cmd /c chcp 65001>nul && "C:\Program Files\Everything\es.exe" -max-results 24 hell
> Error 7: Unable to send IPC message.
> 
>     at ChildProcess.exithandler (child_process.js:312:12)
>     at ChildProcess.emit (events.js:315:20)
>     at maybeClose (internal/child_process.js:1021:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
> ```

Hey, did you fix this error (Error 7: Unable to send IPC message") somehow? I am facing the same problem.
