### ISSUE TITLE
Ulei, it doesn't let me select what I searched for, or the search results with the mouse pointer, ESPAÑOL = Ulei, no me deja seleccionar lo que busqué o los resultados de la búsqueda con el puntero del mouse

### ISSUE THREAD

**Issue by freedsny** [oliverschwendener/ueli#676]
Ulei, it doesn't let me select what I searched for, or the search results with the mouse pointer, it only lets me select them with the keyboard keys or arrows. windows 10

**Comment by oliverschwendener** [comment]
Currently there is no support for mouse interaction. See here: #393
