### ISSUE TITLE
Ueli tray icon missing

### ISSUE THREAD

**Issue by kumar007git** [oliverschwendener/ueli#677]
9 out of 10 times, Ueli icon in system tray is missing. I'm using windows 10, 64 bit and latest version of Ueli. This is problematic when I need to close the app. Of course, I'm still able to call up Ueli search bar. So, in Ueli search bar is there a way I can close Ueli app or force the Ueli icon to show up? Also, first of all why is Ueli not showing (most of the time) in system tray on taskbar and how can I fix it or can you fix it if it is an app issue? Thanks.

**Comment by oliverschwendener** [comment]
First of all, have you activated the option "Show tray icon" in the general settings?

**Comment by kumar007git** [comment]
Yes, 'Show Tray Icon' setting is enabled.

On a side note, the launch box shows correctly upon calling it up however, as soon as I start typing two things happen.
1. The launch box starts moving from its original position as I'm typing in it. After I finish typing and hit enter, of course the launch box disappears and the target search result (for example an app) is launched.
2. There is some lag from when I type to the time when characters show up in the launch box. There is a lag in typing in launch box.

**Comment by tkohlmeier** [comment]
The moving window thing is a known electron bug: #515

**Comment by oliverschwendener** [comment]
Maybe it's just hidden?

![image](https://user-images.githubusercontent.com/15727229/113819324-708c1e00-9779-11eb-9e20-e082b003e20b.png)

**Comment by kumar007git** [comment]
Trust me, it's not showing in the system tray. I checked the extend tray (clicking the up arrow) and it's not there either. However, the process is running in the task manager.

**Comment by scorpioraj** [comment]
I too have this query 

The UELI icon is there where the arrow is marked, but it is not visible at all. Unless and until we move the mouse, we will never know that the application is active. Once we move the move there, we realise that the application has been open all the time. 

I think you should make the icon more visible and maybe in dark color or 2 tone color to immediately confirm that the application is active



![pp](https://user-images.githubusercontent.com/83529373/121391031-90071900-c96b-11eb-87f6-566ede67fbd1.jpg)

**Comment by oliverschwendener** [comment]
Can someone check if this is still an issue with the latest v9 release? https://github.com/oliverschwendener/ueli/releases
If so, feel free to reopen.
