### ISSUE TITLE
Currency Converter does not work

### ISSUE THREAD

**Issue by quqech** [oliverschwendener/ueli#680]
ueli
8.12.0
Electron
11.2.3
Node
12.18.3
V8
8.7.220.31-electron.0
Windows

**Comment by oliverschwendener** [comment]
Thanks for the report! Apparently https://exchangeratesapi.io/ does not allow free unlimited usage anymore. I have to find another API that can provide the current exchange rates for free.

**Comment by notsuhas** [comment]
> Thanks for the report! Apparently https://exchangeratesapi.io/ does not allow free unlimited usage anymore. I have to find another API that can provide the current exchange rates for free.

Is it possible for us to add our own apiKey for exchangerates?

**Comment by hmnd** [comment]
@oliverschwendener I found exchangerate.host which uses the European Central Bank to source its exchange rates. What would your thoughts be on either switching to exchangerate.host or adding local, daily caching of rates from ECB?
