### ISSUE TITLE
[Feature Request] Solicitud de caracteristicas

### ISSUE THREAD

**Issue by freedsny** [oliverschwendener/ueli#682]
It would be very useful if they could add options that Alfred or Wox has, such as being able to navigate between folders from there, that is, from the same results without leaving,  **and also the right click function: (copy, paste, cut, execute as an administrator, open location, open selected search with one click),** as it is a bit ugly to have to use the arrow keys or arrow keys on the keyboard.

**Thank you very much for listening, I appreciate your effort.**

----------------------ESPAÑOL-----------
Sería muy útil que pudiesen agregar opciones que tiene Alfred o Wox, tal como poder navegar entre carpetas desde ahi mismo, es decir desde los mismos resultado sin salirse , y también la función de clic derecho: (copiar, pegar, cortar, ejecutar como administrador, abrir ubicación, abrir búsqueda seleccionada con un clic), pues es un poco feo tener que usar las teclas de dirección o flecas del teclado.

Muchas gracias por escuchar, les agradezco su esfuerzo.

**Comment by oliverschwendener** [comment]
As the title is not English I'm going to close this issue. See the language section of [the contribution guideline](https://github.com/oliverschwendener/ueli/blob/main/CONTRIBUTING.md#languages):
