### ISSUE TITLE
[Feature Request] Create an official youtube channel, for the Ueli app, suo tutorials and updates

### ISSUE THREAD

**Issue by freedsny** [oliverschwendener/ueli#684]
Create an official youtube channel, for the Ueli app, to tutorials, updates an Tips, if possible also in Spanish.
because there aren't many videos on youtube about ueli.

Thank you...

Thank You

**Comment by freedsny** [comment]
Create an official youtube channel, for the Ueli app, suo tutorials and updates, because there aren't many videos on youtube about ueli, if possible also in Spanish.

**Comment by oliverschwendener** [comment]
Thanks for the idea, I'll consider it.
