### ISSUE TITLE
Currency Change

### ISSUE THREAD

**Issue by alejandrorojasg** [oliverschwendener/ueli#686]
I just downloaded it and it's too powerful, it's wonderful. Thanks for that.
But the only thing I found not working , it was the currency, so could you help me plz ?
Thanks

**Comment by hmnd** [comment]
Search for existing issues prior to opening a new one. #680 already exists.

**Comment by oliverschwendener** [comment]
Closing this issue because it's a duplicate.

**Comment by oliverschwendener** [comment]
Thanks @hmnd
