### ISSUE TITLE
add Windows 10-like acrylic effect to the launcher

### ISSUE THREAD

**Issue by firinael** [oliverschwendener/ueli#689]
Hi, pretty simple request, I just wanted the app to have an acrylic effect along with the transparency.

**Comment by freedsny** [comment]
If, in fact, the idea is quite good, a transparent Blur effect, or acrylic would be perfect together with the possibility of a shadow or border to give it a little volume.granial, I support it

**### Add this feature for Milestone version 9.0 ... Please**

**Comment by ahmuro** [comment]
Given that visually the launcher is just an small horizontal bar, having visual elements for volume and separation is a must I think. Is really easy to get lost when there is other windows or elements with similar colors or geometry. Both acrylic and shadow would help to improve comfort and usability, beyond just the aesthetic aspect.

**Comment by oliverschwendener** [comment]
Unfortunately this is not so easy to implement, please check out this feature request for more details: https://github.com/oliverschwendener/ueli/issues/116

**Comment by oliverschwendener** [comment]
I'll close this as it is included in v9.0.0-alpha.1
