### ISSUE TITLE
Ueli settings/ ctrl+i  not working

### ISSUE THREAD

**Issue by govindKAG** [oliverschwendener/ueli#69]
Following the readme I tried pressing ctrl + i to open the ueli settings which did not do anything. I also tried searching for "ueli settings". There was only one result named "local settings" , pressing enter gives me an error message saying permission denied. I ran Ueli as administrator just to be sure, but the same thing happened again. Am I missing something obvious?
running on windows 10 pro

**Comment by oliverschwendener** [comment]
What is your version of ueli?

**Comment by govindKAG** [comment]
Yes, this was the issue. Working now that i got the latest version.
