### ISSUE TITLE
Ability to make Google search as default without the need to press g?

### ISSUE THREAD

**Issue by TheCoinAxe** [oliverschwendener/ueli#691]
It would be great if I just type and press enter and "by default" have it search in google. That is without the need for pressing g? . 

I would see a good opportunity for an option in the Web Search plugin, as a switch to override it to make it the default,

**Comment by oliverschwendener** [comment]
How about using the "fallback" option?

![image](https://user-images.githubusercontent.com/15727229/114773593-88623400-9d6f-11eb-8137-630861c763fe.png)

**Comment by TheCoinAxe** [comment]
I'm not sure how that works, I checked it and typed something , still I'm not able to search google with that. Am I missing something ?

**Comment by oliverschwendener** [comment]
The fallback option enables the websearch as soon as there are no other search results found. You could also just remove the `g?` prefix completly, then the google search will appear everytime you type something but there won't be any other search results. What is the exact behavior that you're looking for? What about other search results like programs or files? Where would they be placed? Before or after?

**Comment by TheCoinAxe** [comment]
Yes this worked perfectly, thanks !

As of now it works only for Google which is nice, and as you said its not searching for anything else. I can also suggest making a prefix option searching files in the computer, like a? for apps and f? for files or something like that. Because for my use scenario I would say im using google search 90% of the time, and occasionally I would be searching my files and some apps I have to launch. Is adding a prefix currently supported for apps and files ?

**Comment by oliverschwendener** [comment]
Searching files & apps with a prefix is currently not possible.

**Comment by TheCoinAxe** [comment]
Would be a great feature to have. can I close this comment and add a new ticket with that other topic

**Comment by oliverschwendener** [comment]
Yes that would be great, thanks!
