### ISSUE TITLE
Visual Issue, Bug

### ISSUE THREAD

**Issue by x84yr41** [oliverschwendener/ueli#693]
Visual issue with the appearance of the launcher. Restarted my computer and the way it looked changed, it became tiny (refer to attached image). Tried resetting all settings and reinstalling the application but it's still the same. 

![Screenshot (44)](https://user-images.githubusercontent.com/82630193/115027856-ce95cf80-9ef6-11eb-90fb-75125b5a1db1.png)

**Comment by oliverschwendener** [comment]
Keep in mind that the "reset" button (the on with the icon) just resets the currently visible settings. For example when you're on "Appearance" and you click on the reset button, it just resets the appearance settings. To reset **all** settings you have to go to "General" and then click on the 3 dots and click "Reset all settings to default". Did you do that?

![image](https://user-images.githubusercontent.com/15727229/115160443-6b43a300-a098-11eb-8a94-ff64a893cb70.png)

**Comment by x84yr41** [comment]
> Keep in mind that the "reset" button (the on with the icon) just resets the currently visible settings. For example when you're on "Appearance" and you click on the reset button, it just resets the appearance settings. To reset **all** settings you have to go to "General" and then click on the 3 dots and click "Reset all settings to default". Did you do that?
> 
> ![image](https://user-images.githubusercontent.com/15727229/115160443-6b43a300-a098-11eb-8a94-ff64a893cb70.png)

Yes, also did that. Did a full reset to all settings from the General tab, also tried uninstalling and then reinstalling but issue still persisted.

**Comment by oliverschwendener** [comment]
Try the following:
- Quit the app
- Delete the following folder with it's content: `C:\Users\<YourUserName>\AppData\Roaming\ueli`
- Start the app again and check if it works

**Comment by x84yr41** [comment]
> Try the following:
> 
> * Quit the app
> * Delete the following folder with it's content: `C:\Users\<YourUserName>\AppData\Roaming\ueli`
> * Start the app again and check if it works

This solved the problem. Thank you. 👍

**Comment by oliverschwendener** [comment]
Then the "reset all settings to default" option does not work properly. Thanks for reporting this!
