### ISSUE TITLE
Visual error

### ISSUE THREAD

**Issue by developmaxcode** [oliverschwendener/ueli#694]
When you start typing in the search bar, the input field starts to move to the corners or upwards.

**Comment by oliverschwendener** [comment]
Are you using Windows and do you have set the set the UI scaling to a custom value?

![image](https://user-images.githubusercontent.com/15727229/115137603-53800680-a027-11eb-839a-aefd3ef28f05.png)

**Comment by developmaxcode** [comment]
Sorry for answering so late, but I am in the same situation, today I reinstalled the program and I still have the same problem, I use Windows, the search bar starts to scroll when typing things inside.

**Comment by oliverschwendener** [comment]
Are you using a custom scaling option?

**Comment by developmaxcode** [comment]
No, I do not use it

![Captura de pantalla 2021-06-27 085434](https://user-images.githubusercontent.com/71987916/123547184-66007580-d725-11eb-8754-66a0b6a8e2f5.png)

**Comment by developmaxcode** [comment]
I found out what is causing this behavior, I have the text magnification in settings, I checked to set it to 100%, and it doesn't have this problem anymore but with only 1% magnification the program starts to scroll up when typing things in.
