### ISSUE TITLE
[Feature Request] Mac: File Browser should support home director `~`

### ISSUE THREAD

**Issue by micnguyen** [oliverschwendener/ueli#696]
Hi,

The file browser plugin should be able to support `~` for the user home director. I can go to the location by typing `/Users/myusername/Downloads` but I can't go to it using `~/Downloads`. `~` is a common shorthand to your user directory (ie: in bash).

**Comment by oliverschwendener** [comment]
I'm going to close this issue as the File Browser extension will be discontinued with ueli v9 unless someone takes their time to migrate it.
