### ISSUE TITLE
[bug]DuckDuckGo web search cut off search query

### ISSUE THREAD

**Issue by LalaGhost** [oliverschwendener/ueli#699]
As you can see in the screenshot, ueli is suggesting different DuckDuckGo search queries than I have typed in. It does not happen with Google or Youtube.
![Screenshot_1](https://user-images.githubusercontent.com/43962138/115198918-e76ad480-a0f2-11eb-883d-8ac38a044eac.jpg)

**Comment by oliverschwendener** [comment]
I guess this is related to #665

**Comment by oliverschwendener** [comment]
I am going to close this issue because it's most likely a duplicate of #665
