### ISSUE TITLE
 cannot type  ueli bar after autostart with system

### ISSUE THREAD

**Issue by vvambo** [oliverschwendener/ueli#703]
For a few days now, when ueli started with the system I can call the ueli bar,  but I cannot type in it. 

The focus gets taken from the previous window, but there is no cursor blinking and inputs don't seem to arrive on the ueli bar. I can "unsummon" it again, I can open the settings from the taskbar icon, it seems ueli is working correctly just the keyboard inputs do not arrive.

Once I close ueli and start it up again its working as it used to.

ueli 8.12.0
Electron 11.2.3
Node 12.18.3
V8 8.7.220.31-electron.0

I can not recall whether I updated UELI or Windows since it happened, but it is definitely possible (especially for windows)

**Comment by vvambo** [comment]
I just noticed that it is not on every start.
Today I managed to start a workflow with ueli (short after or during system startup) worked for a few hrs, and then the described behaviour happened. 

I can imagine that one of the programs I usually start could be the culprit:
Browser (Vivaldi, Chrome, Firefox), Zoo, RocketChat, Outlook, OneNote

It could be something on autostart as well:
Voicemeeter, Eartrumpet, Cisco Anyconnect, Synology CloudStation Drive, Parsec, Pushbullet, Razer Synapse, Realtek Audio Driver Tool

**Comment by vvambo** [comment]
I notice that I haven't added this, but even when starting ueli manually it happens.

On a few rare occasions UELI I got still type in ueli even hrs after starting it.  I cannot make out a pattern sadly.

**Comment by oliverschwendener** [comment]
Can someone check if this is still an issue with the latest v9 release? https://github.com/oliverschwendener/ueli/releases
If so, feel free to reopen.

**Comment by lxxorz** [comment]
`autostart` option is not working 

![image](https://github.com/user-attachments/assets/76bf2694-d3be-4f84-b301-f917734fef2a)

![image](https://github.com/user-attachments/assets/2cb875be-66b2-4405-b6c3-f7e1f477e501)

**Comment by oliverschwendener** [comment]
@lxxorz That's another issue, see here: #1137
