### ISSUE TITLE
[Feature Request] Using Tab and Shift Tab to scroll through the result list

### ISSUE THREAD

**Issue by NoahELE** [oliverschwendener/ueli#704]
Please consider to add this keyboard shortcut, as it is sometimes incovenient to use up and down arrows.
Thank you.

**Comment by oliverschwendener** [comment]
Tab and Shift-Tab are used to focus the next or previous element. I think we need another shortcut for scrolling pages. I'll close this issue as there is another one already for this topic already: #820.
