### ISSUE TITLE
[Query]How do I access Ueli settings?

### ISSUE THREAD

**Issue by onlytanmoy** [oliverschwendener/ueli#708]
Hiya, I disabled Ueli from showing up in system tray via the option in its settings. How do I access the Ueli interface/settings window again? I tried windows start menu > Ueli but nothing happens, is there a default windows hot key combination to access the settings window?

**Comment by oliverschwendener** [comment]
Did you try typing in "settings"?

<img width="631" alt="image" src="https://user-images.githubusercontent.com/15727229/115970376-27dab000-a542-11eb-9b2c-e63de5cf0df9.png">

**Comment by onlytanmoy** [comment]
Thanks mate, I wasn't aware of that until now 😊 working like a charm now.
