### ISSUE TITLE
ueli 7 on windows starts many powershell processes

### ISSUE THREAD

**Issue by maku** [oliverschwendener/ueli#71]
When I run ueli 7 on win 10, many **powershell** processes are started (starts with 1 and then over time processes are added).

This seems very strange....

**Comment by oliverschwendener** [comment]
Ueli uses powershell to generate the app icons which are stored in `~/.ueli/app-icon-store`. Maybe this could be optimized, so that only one powershell process is invoked and more. If you don't want ueli to execute powershell commands uncheck "Use native icons" in the settings.

**Comment by oliverschwendener** [comment]
Here you can see which powershell commands are executed: https://github.com/oliverschwendener/ueli/blob/933543d5f67a3a5566e9e7b5e57d299e3f33c85c/src/ts/icon-service/windows-app-icon-store.ts#L33-L54

**Comment by maku** [comment]
I had ca. 100 running processes... The I killed ueli... (and reverted back to 6.1.4)

**Comment by oliverschwendener** [comment]
I'll look into this. There should be a way to only use one powershell process. Thanks for your feedback!

**Comment by cosimochellini** [comment]
Yes, I also noticed this strange thing, but I had not connected the thing to the last update of ueli

**Comment by oliverschwendener** [comment]
I think I already found a solution... there should be a way to only use one powershell process for generating the icons. Thanks for your feedback! As I said, you don't have to revert back, just disable the feature "use native icons" in the settings.

**Comment by GitBiker** [comment]
I tried "use native icons" but then ueli does not show any results. Windows 10, ueli 7.0.0

**Comment by oliverschwendener** [comment]
> I tried "use native icons" but then ueli does not show any results. Windows 10, ueli 7.0.0

Created a separate issue for this.

**Comment by oliverschwendener** [comment]
Sorry for the hassle. Very stupid mistake. I forgot to kill the powershell process after generating the native app icons. This is fixed now and I released a new version: https://github.com/oliverschwendener/ueli/releases/v7.0.1

Thank you for feedback guys! 🙌

**Comment by maku** [comment]
Thank you for your fast responding and keep up the great work...
