### ISSUE TITLE
No se agregan iconos con URL, ni con los archivos dentro del computador

### ISSUE THREAD

**Issue by Johan-Palacios** [oliverschwendener/ueli#710]
Hay un error en el cual UELI no agrega el icono correspondiente a una URL

![image](https://user-images.githubusercontent.com/77251405/116168066-d9065500-a6be-11eb-9f3a-80ee7585c755.png)

![image](https://user-images.githubusercontent.com/77251405/116168097-ed4a5200-a6be-11eb-9c90-601da46a3b21.png)

Esto también pasa para los iconos que tengo guardados en mi computador

**Comment by oliverschwendener** [comment]
English please?

**Comment by oliverschwendener** [comment]
Try removing the `<img>` tag and just add the value of the `srf` attribute:

```
data:image/svg+xml;base64,PHN2....
```

**Comment by Johan-Palacios** [comment]
> Try removing the `<img>` tag and just add the value of the `srf` attribute:
> 
> ```
> data:image/svg+xml;base64,PHN2....
> ```

Can you give me an example ?

**Comment by oliverschwendener** [comment]
> 
> ```
> data:image/svg+xml;base64,PHN2....
> ```

This is the example. Just remove the whole img tag and add the value of the `src` attribute.

**Comment by Johan-Palacios** [comment]
> > ```
> > data:image/svg+xml;base64,PHN2....
> > ```
> 
> Este es el ejemplo. Simplemente elimine toda la etiqueta img y agregue el valor del atributo.`src`

That's not works, i have the same issue, i tried with other image but i have the same issue :(

Sorry, i'am a Noob xd

![image](https://user-images.githubusercontent.com/77251405/116346556-c3b92580-a7a7-11eb-9ef8-681a0ac04415.png)
![image](https://user-images.githubusercontent.com/77251405/116346563-c582e900-a7a7-11eb-8b02-3e2abaac9d45.png)

**Comment by oliverschwendener** [comment]
Can you send me a link to the image that you're trying to add?

**Comment by oliverschwendener** [comment]
You have 3 options:

# URL

Just add the link which points to the image:

<img width="614" alt="image" src="https://user-images.githubusercontent.com/15727229/116355098-a57c1580-a7f9-11eb-8135-a954aeed5192.png">

Or you can add a base64 encoded image:

<img width="612" alt="image" src="https://user-images.githubusercontent.com/15727229/116355193-cc3a4c00-a7f9-11eb-9911-7ff86a0c2245.png">

# SVG

Add an SVG:

<img width="598" alt="image" src="https://user-images.githubusercontent.com/15727229/116355512-410d8600-a7fa-11eb-909f-686c40f74100.png">

# Color

Or just choose a color (hex, rgb, rgba, hsl):

<img width="601" alt="image" src="https://user-images.githubusercontent.com/15727229/116355630-68645300-a7fa-11eb-9e03-ea44d9bb6269.png">

**Comment by Johan-Palacios** [comment]
> You have 3 options:
> 
> # URL
> Just add the link which points to the image:
> 
> <img alt="image" width="614" src="https://user-images.githubusercontent.com/15727229/116355098-a57c1580-a7f9-11eb-8135-a954aeed5192.png">
> 
> Or you can add a base64 encoded image:
> 
> <img alt="image" width="612" src="https://user-images.githubusercontent.com/15727229/116355193-cc3a4c00-a7f9-11eb-9911-7ff86a0c2245.png">
> 
> # SVG
> Add an SVG:
> 
> <img alt="image" width="598" src="https://user-images.githubusercontent.com/15727229/116355512-410d8600-a7fa-11eb-909f-686c40f74100.png">
> 
> # Color
> Or just choose a color (hex, rgb, rgba, hsl):
> 
> <img alt="image" width="601" src="https://user-images.githubusercontent.com/15727229/116355630-68645300-a7fa-11eb-9e03-ea44d9bb6269.png">

oh thanks bro, now it works !!
