### ISSUE TITLE
Question: How does powershell commands execute without a console opening?

### ISSUE THREAD

**Issue by HermasciousLevander** [oliverschwendener/ueli#711]
This is perhaps a strange question to ask, but while I am in no way proficient at looking through code, I can't figure out how you're getting commands from the Shortcuts plugin (for example) to execute commands without a window popping up at all.

Getting Powershell to not open a shell window is rather hard without work arounds, as I've come to understand, so I'm quite curious if you don't mind me asking :)

**Comment by oliverschwendener** [comment]
Maybe I don't really understand your question, but I think it's very easy. For example you can execute inline scripts like this from cmd:

![image](https://user-images.githubusercontent.com/15727229/116932583-be098700-ac62-11eb-8afd-7d6ba7ed9545.png)
