### ISSUE TITLE
Different config file names and content

### ISSUE THREAD

**Issue by LalaGhost** [oliverschwendener/ueli#714]
I find two config files on my computer.
Under C:\Users\_username_\AppData\Roaming\ueli I find a **config.json** that looks like this:
![config](https://user-images.githubusercontent.com/43962138/116847575-18670100-abeb-11eb-901d-1dbe2ee61a12.jpg)

but when open the ueli settings and hit export current settings it is named **ueli.config.json** and looks like this:
![ueli config json](https://user-images.githubusercontent.com/43962138/116847652-3e8ca100-abeb-11eb-88c7-99ab323d5ab0.jpg)

Why is their content and format a bit different and have different names? Which is one "more correct"?

**Comment by oliverschwendener** [comment]
`config.json` must be from an older version. In ueli v9 the config file will change to `ueli9.settings.json`.
