### ISSUE TITLE
Wrong grammar in settings

### ISSUE THREAD

**Issue by LalaGhost** [oliverschwendener/ueli#715]
There is wrong grammar in the settings in the Application Search.
It says _Use native icons (turned off might result to better performance)_ but it should say _Use native icons (turned off might result **in** better performance_.
![Screenshot_1](https://user-images.githubusercontent.com/43962138/117121085-7125cd80-ad94-11eb-9348-31017bacf3cf.jpg)

**Comment by oliverschwendener** [comment]
Thanks for pointing out!

**Comment by oliverschwendener** [comment]
This should be resolved.
