### ISSUE TITLE
How do I make Ueli open web searches and URLs in an incognito tab?

### ISSUE THREAD

**Issue by helloWorld2187** [oliverschwendener/ueli#720]
I want to be able to open web searches and URLs in a new incognito tab. From what I have searched, there is no setting dedicated to that. If there was an option to customize our browser's location, then I can try adding `--incognito` to the Chrome URL. But I don't see any setting for that. It would be really helpful if you could implement this feature. Thanks for the awesome launcher!

**Comment by oliverschwendener** [comment]
Is this a duplicate of #310 ?

**Comment by helloWorld2187** [comment]
Yes, it is a duplicate. I didn't see it before though.

**Comment by oliverschwendener** [comment]
Alright no problem. Then I'm going to close this issue.

**Comment by helloWorld2187** [comment]
Thanks.
