### ISSUE TITLE
Unable to "pin" to top of screen + Suggestions

### ISSUE THREAD

**Issue by drewauff** [oliverschwendener/ueli#721]
Ueli keeps defaulting to `"y": 442`

even if the value is modified it resets the "y" value and resets all settings to default. not good.

Also a couple of suggested additions:

1) Adustable font sizes
2) Adjustable border, nothing I do works.
3) Dark mode for the preferences ui.
4) Adustable "X" and "Y" Values in preferences
5) Add border thickness and color in themes
6) Add option to change placement of the "search result numbers" ie. on the left or right

**Comment by oliverschwendener** [comment]
Did you enable to option "Remember window position" in the general settings?

**Comment by drewauff** [comment]
yeah I did.

Thats way I decided look in for a config file. Change settings in config.json only work temporarily and by that I mean maybe a minute if Im lucky.

**Comment by drewauff** [comment]
until an update comes along I have taken to modding the app.asar file to change the font size, only font size that I couldn't change is the list font but adding descriptions shrunk them a little.

**Comment by oliverschwendener** [comment]
If you want to pin the window to a certain position try the following:

1. Enable the option "Allow window move".
2. Enable the option "Remember window position".
3. Drag the window to the desired position.
4. Next time you activate ueli it shows up at the position where you left it.

This works fine for me, doesn't this work for you?

For the other feature requests please open up separate issues, so it's easier to track the progress.

**Comment by drewauff** [comment]
As I said previously, for whatever reason, the version on brew, which has the same version number works just fine.

With regards to the other issues/suggestions, will do.

**Comment by drewauff** [comment]
@oliverschwendener the problem is back again, just randomly "pins" it self back to center of the screen regardless of where I move it to.

**Comment by oliverschwendener** [comment]
Can someone check if this is still an issue with the latest v9 release? https://github.com/oliverschwendener/ueli/releases
If so, feel free to reopen.
