### ISSUE TITLE
How to add "Suggestion url" to custom websites in "Web search" ? 

### ISSUE THREAD

**Issue by rahulbhatia101** [oliverschwendener/ueli#722]
I have added multiple websites like Amazon , youtube music and some regional website, and I have configured their "search url", but I cant get to know how to add the "suggestion url" for those websites. I would really appreciate your effort in explaining that.
Please take amazon as an example if possible.
Thanks!

**Comment by svensto190** [comment]
Hey, I'm a little late, but nonetheless.

You can find the suggestion URL out pretty well with the **Developer Tools** in your **Chrome** browser. 

Visit the page with the search bar, e.g. https://www.amazon.com.

Then open the Developer Tools via the **Three Dots Menu** and **More Tools**. Switch to the **Network** tab and filter the results by the type **Fetch/XHR**.

Now start typing a word **without** confirming the search with enter. The answers of your search suggestion requests will show up.  If you inspect one of the answers by clicking on it, you will see the matching URL under the **Headers** tab, at **General** → **Request URL**. Copy this, locate your previous search term, replace it with **{{query}}** and paste it into the **Suggestion URL** in ueli.
