### ISSUE TITLE
File and Folder search not working

### ISSUE THREAD

**Issue by sHrEyAsJaIn06** [oliverschwendener/ueli#727]
Not able to search for any files or folders, but application search is working 
this is the error I'm getting:
![Screenshot 2021-05-29 102654](https://user-images.githubusercontent.com/64124426/120058427-6a733900-c068-11eb-9a39-1ce1478755eb.png)

**Comment by oliverschwendener** [comment]
The file path that you specified seems to include folders which you don't have access to.

**Comment by sHrEyAsJaIn06** [comment]
But I am the only user on that PC and the Administrator and I have been using Ueli from the last year or so and the file and folder search was working fine until yesterday only so...
How to I regain access on those folders?
Thank you.
