### ISSUE TITLE
System freezes while reindexing.

### ISSUE THREAD

**Issue by drewauff** [oliverschwendener/ueli#728]
I have set the index interval to 1min.

Every time Ueli indexes it freezes the system for around 2-5 seconds.

Extremely irritating.

**Comment by oliverschwendener** [comment]
Can you show us the list of enabled plugins?

**Comment by drewauff** [comment]
all except: Calculator, Currenc Converter, Mdfind, Shortcuts, Translation and Work flow.

**Comment by oliverschwendener** [comment]
So I guess you're on macOS?

**Comment by drewauff** [comment]
You guess correctly.

Should note, after a reboot, its still there, though "freeze" is not as protracted.

**Comment by oliverschwendener** [comment]
I suggest you disable all plugins and start enabling them one by one. Then we should find out which plugin is causing the issue.

**Comment by drewauff** [comment]
Did as you suggested, no change.

I am wondering if there would be an entry in the syslog that would show the "freeze"

**Comment by oliverschwendener** [comment]
Did you disable **all** plugins and then it still happens?

**Comment by drewauff** [comment]
still happens..its a very sudden freeze, I notice it mostly when typing or moving app windows around.

Also could find a value for the App. Title text in the dropdown in the app.asar. I've found the other font sizes I can change no problems. 

You see I find the font sizes to large so I chnage the values to 15px, 13px and 12px. That covers everything except the application title names in the dropdown list. So that font is huge and look very much out of place.

**Comment by drewauff** [comment]
any luck on finding a fix? maybe have an option where the user can decide on whether to have it reindex whenever they choose or make it "live" like spotlight does.

**Comment by drewauff** [comment]
Has there been any progress on this?

Is there a way I can reindex from the command line? then I can add it to my cron and it will index in the background with no harm to performance, well thats the hope.

**Comment by oliverschwendener** [comment]
No, no idea what is causing the issue 🤔 . You could increase the reindex interval in the general settings.

**Comment by oliverschwendener** [comment]
Can someone check if this is still an issue with the latest v9 release? https://github.com/oliverschwendener/ueli/releases
If so, feel free to reopen.
