### ISSUE TITLE
Add a modal confirmation for actions possibly harmful to the user

### ISSUE THREAD

**Issue by cosimochellini** [oliverschwendener/ueli#73]
[feature request]
![image](https://user-images.githubusercontent.com/24718181/49437903-0932bd80-f7bd-11e8-889f-7e07b04ee238.png)

I think it would be really useful to give the user (perhaps in the settings of ueli) to provide an array of commands which start and preceded by a prompt that says "you are sure you want to run {{action}}", because as in example above turning off the PC unintentionally is not nice.
said this congratulations for the application I find it really good

**Comment by oliverschwendener** [comment]
Good idea! Will look into this!

**Comment by oliverschwendener** [comment]
What do you think about this?

![image](https://user-images.githubusercontent.com/15727229/49463075-dc4fcc00-f7f7-11e8-8c9d-efec853d88bf.png)

**Comment by oliverschwendener** [comment]
Of course. If you press enter on a "dangerous" item this dialog pops up and you can either proceed with `Enter` or cancel with `Escape`.

![image](https://user-images.githubusercontent.com/15727229/49472120-e6c99000-f80e-11e8-950f-ae1520b36670.png)

**Comment by oliverschwendener** [comment]
Plus there will be a user option to disable this feature.

**Comment by oliverschwendener** [comment]
This will be included in the next release.
