### ISSUE TITLE
Not able to click on the results?

### ISSUE THREAD

**Issue by arjunguliya** [oliverschwendener/ueli#730]
I don't know if it's intended or not, but after searching for something, I cannot click on the results, only scroll through them using arrow keys and select by pressing enter. 
If there is a solution, can someone help me out?
EDIT: ahhhhh I just read through some issues and realized there is no mouse support, man I feel stupid for trying to fix it for half an hour.

**Comment by oliverschwendener** [comment]
No worries ;) Support for mouse interaction will come with the next version
