### ISSUE TITLE
How to insert icon for a shortcut I created?

### ISSUE THREAD

**Issue by arjunguliya** [oliverschwendener/ueli#731]
I made a shortcut for opening PowerPoint by typing 'ppt', but I was wondering if there was an option to insert a logo and if there is, how do I do it? I saw that there was an option for URL, SVG, and Colour, but I'm confused about how to use them

**Comment by zen-quo** [comment]
you can download [this svg file ](https://upload.wikimedia.org/wikipedia/commons/0/0d/Microsoft_Office_PowerPoint_%282019%E2%80%93present%29.svg)by hitting ctrl+s in your browser. then open this with a text editor, like notepad. then select all text and copy and paste the text to the shortcut's svg box in ueli. (i just googled "powerpoint logo svg" to get this by the way, you can use another logo if you like)

or just pasting the above url should work too. webpages can change or vanish so i think svg is a better option.

the third option, color, just shows up the color you specified as an icon. you need the hex code of the color i think.
