### ISSUE TITLE
Google Chrome bookmark issue

### ISSUE THREAD

**Issue by ahrooran-r** [oliverschwendener/ueli#737]
In settings, bookmark option is not working. When I reload bookmarks option, it says
![image](https://user-images.githubusercontent.com/46846338/121146297-6a8be980-c85d-11eb-9828-a56e20c24a9b.png)

The underlying problem is with the different user profiles set in chrome: For example, in my PC, the path of bookmarks file is in: `C:\Users\msi user\AppData\Local\Google\Chrome\User Data\Profile 1`
which is not  in Default folder. In fact, there is no default folder.

When I manually created a Default folder in there and placed the Bookmarks file in there, it worked.

So as a workaround I suggest add a feature to letting us specify the path manually. 

Or is there any other solutions?

Please fix this as it is an important but small issue. Thanks in advance

**Comment by FunctionDJ** [comment]
Thanks for the workaround! Looking forward to the fix ❤️

**Comment by polyankaglade** [comment]
In case anybody else is in need of Chrome bookmarks being updated from Profile N to Default on a regular basis, here is a command line prompt you can use in the Shortcuts:

`copy "C:\Users\User\AppData\Local\Google\Chrome\User Data\Profile 1\Bookmarks" "C:\Users\User\AppData\Local\Google\Chrome\User Data\Default\Bookmarks"`

<img width="731" alt="image" src="https://github.com/oliverschwendener/ueli/assets/31651460/5a530db2-f207-4913-8ad2-94ced1596741">

Also here is a random svg I used for this icon: 
<img width="120" alt="image" src="https://github.com/oliverschwendener/ueli/assets/31651460/e5ffcf14-f007-498d-9928-d98d21b37476">

**Comment by oliverschwendener** [comment]
Can someone check if this is still an issue with the latest v9 release? https://github.com/oliverschwendener/ueli/releases
If so, feel free to reopen.
