### ISSUE TITLE
macOS 12 beta

### ISSUE THREAD

**Issue by alexriabtsev** [oliverschwendener/ueli#738]
Ueli doesn't recognise the latest beta version of macOS and throws an error.

**Comment by alexriabtsev** [comment]
any updates?
I've tried to look into the problem myself but looks like version checking isn't an easy task...

**Comment by oliverschwendener** [comment]
Can someone check if this is still an issue with the latest v9 release? https://github.com/oliverschwendener/ueli/releases
If so, feel free to reopen.
