### ISSUE TITLE
ueli 7 - popup error window on icon resolving...

### ISSUE THREAD

**Issue by maku** [oliverschwendener/ueli#74]
Since version 7.0.1 I get from time to time an error popup window (on windows 10)

![image](https://user-images.githubusercontent.com/64805/49506198-c8e74400-f87d-11e8-9ece-9ec9070514d1.png)

It seems this a background operation and the error occurs on resolving icons for URL's (Files wird extension "url")

**Comment by oliverschwendener** [comment]
Unfortunately the message does not show the file which can't be found. Try to launch ueli from command prompt or powershell (there the error output should not be cropped) and tell me for which file the icon conversion fails.

**Comment by maku** [comment]
```
Error while generating app icon: Ausnahme beim Aufrufen von "ExtractAssociatedIcon" mit 1 Argument(en):  "C:\ProgramData\Microsoft\Windows\Start
Menu\Programs\IBM Anwendungen\Unterst├╝tzung\IBM Notes-Diagnosedaten erfassen und Notes beenden.lnk"
In Zeile:1 Zeichen:22269
+ ... at]::Png);; $icon = [System.Drawing.Icon]::ExtractAssociatedIcon("C:\ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FileNotFoundException

```

usw.

**Comment by oliverschwendener** [comment]
This should be fixed now. The fix will be included in the next release.
