### ISSUE TITLE
[Feature Request] Browser Bookmarks: support multiple browsers at the same time

### ISSUE THREAD

**Issue by scorpioraj** [oliverschwendener/ueli#743]
Hi 

I would like to know why you have used dropdown menu for Browser bookmark settings

I am using Firefox, Librewolf, Ungoogled chromium, Vivaldi, Slimjet,Opera, Slimbrowser for browsing and I have added bookmarks onto them.

Wouldn't it be better for the user to add additional browsers rather than selecting any of the browsers from the drop down menu.

I am curious to know how you are going to sort this situation out

Thanks

![Capturet654tyjhy679](https://user-images.githubusercontent.com/83529373/121389830-6ac5db00-c96a-11eb-953c-520c0f9626f2.JPG)

**Comment by oliverschwendener** [comment]
This will be included in ueli v9.
