### ISSUE TITLE
why is the icon not visible at all ?

### ISSUE THREAD

**Issue by scorpioraj** [oliverschwendener/ueli#744]
The UELI icon is there where the arrow is marked, but it is not visible at all. Unless and until we move the mouse, we will never know that the application is active. Once we move the move there, we realise that the application has been open all the time.

I think you should make the icon more visible and maybe in dark color or 2 tone color to immediately confirm that the application is active

![pp](https://user-images.githubusercontent.com/83529373/121393951-7b785000-c96e-11eb-8661-27b40d07cec4.jpg)

**Comment by oliverschwendener** [comment]
It's not visible because it's a white icon on a white background.

**Comment by scorpioraj** [comment]
I would request you to make it more colorful, vibrant easily recognizable color. See how these icons are rich and colorful.. something like this..posh colors




![Capture4335t](https://user-images.githubusercontent.com/83529373/121556752-c73ffd80-ca31-11eb-9183-f7caa8649dc6.JPG)

**Comment by krisu5** [comment]
Or easiest fix is to add black stroke around the icon.

**Comment by oliverschwendener** [comment]
This should be fixed with the latest beta version of ueli v9. https://github.com/oliverschwendener/ueli/releases
