### ISSUE TITLE
Converter works or not?

### ISSUE THREAD

**Issue by Waleedov** [oliverschwendener/ueli#745]
![2021-06-10_11-53-40](https://user-images.githubusercontent.com/48418015/121504888-a43a2d00-c9e2-11eb-8f44-ce65ee9abaae.png)

![2021-06-10_11-53-20](https://user-images.githubusercontent.com/48418015/121504903-a7351d80-c9e2-11eb-9266-2f7b43f6915a.png)

I get errors!

**Comment by krisu5** [comment]
It works again with latest update: https://github.com/oliverschwendener/ueli/releases/tag/v8.13.0

**Comment by Waleedov** [comment]
![image](https://user-images.githubusercontent.com/48418015/121778880-53b90000-cb99-11eb-9c2f-5d9d8bd4ae80.png)

Latest update!

**Comment by krisu5** [comment]
False positive: https://www.virustotal.com/gui/file/74c903f4ccba36f9cd4df2b03eb770352855c728da06f58a878d88ef0e2fae4e/detection

**Comment by oliverschwendener** [comment]
The currency converter is working again, please update to the latest version.
