### ISSUE TITLE
Search windows settings bug?

### ISSUE THREAD

**Issue by thewaliii** [oliverschwendener/ueli#746]
how does the search works?

I enable it
![2021-06-10_11-47-55](https://user-images.githubusercontent.com/48418015/121505142-dd729d00-c9e2-11eb-9296-f527e4c1630b.png)

Not found
![2021-06-10_11-48-16](https://user-images.githubusercontent.com/48418015/121505161-e2375100-c9e2-11eb-8bcf-2e0a398aadfc.png)

But in start menu I find it
![2021-06-10_11-47-46](https://user-images.githubusercontent.com/48418015/121505177-e5cad800-c9e2-11eb-85ad-fc34d50863cd.png)

**Comment by oliverschwendener** [comment]
This should be fixed with latest beta version of ueli v9. https://github.com/oliverschwendener/ueli/releases
