### ISSUE TITLE
doubts on Everything file finder

### ISSUE THREAD

**Issue by scorpioraj** [oliverschwendener/ueli#748]
I have specified the path to es.exe in the option - Path to "es.exe" 

I tried typing es?.mp3 in the search box. At this point of time Everything was not running . I got error message.
Error: Command failed: cmd /c chcp 65001>nul && "I:\FILE SEARCHING SOFTWARES\EVERYTHING COMMAND LINE INTERFACE\es.exe" -max-results 24 .mp
Error 8: Everything IPC window not found. Please make sure Everything is running.

    at ChildProcess.exithandler (child_process.js:312:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

After this, I opened the Everything program  and I got the results. So, every time if I have to use the es? option and search for something, the everything program has to be opened?. I am bit confused here. Without opening the Everything program can EULI not execute the command? I am lost here.

Please update.

![Untitled34gtry56756](https://user-images.githubusercontent.com/83529373/121563598-328cce00-ca38-11eb-8de9-3ec2db88f92f.png)

![Untitled34gtry56756](https://user-images.githubusercontent.com/83529373/121563303-ea6dab80-ca37-11eb-87c6-55bde25994c1.png)

**Comment by oliverschwendener** [comment]
Yes, you have to run everything when using the everything plugin. You can also run the program in the background.

**Comment by scorpioraj** [comment]
oka..got it
