### ISSUE TITLE
Application fails to launch 

### ISSUE THREAD

**Issue by abhijeetd073** [oliverschwendener/ueli#749]
After installing the software, the setting page of application freezes and it has to be forcefully shutdown through task manager. If the setting page is working fine, after few minutes the application wont lunch even after pressing Alt + spacebar multiple time. I had this issue in version 8.12 as well. Version 8.11 works fine. So please can you look into it

**Comment by oliverschwendener** [comment]
Can someone check if this is still an issue with the latest v9 release? https://github.com/oliverschwendener/ueli/releases
If so, feel free to reopen.
