### ISSUE TITLE
Preferred selection from the browser bookmarks extension not prioritized

### ISSUE THREAD

**Issue by SchalkCloete** [oliverschwendener/ueli#751]
It seems like the browser bookmarks are not prioritized after a previous selection. For example, I regularly go to the Rescuetime online dashboard (third option in the image below). However, when I have selected it once using by just typing "res" and navigating down with the arrow key, it should be at the top the next time. Unfortunately, this does not happen, so I need to navigate down every time. 
![image](https://user-images.githubusercontent.com/69623855/121765188-71f70f80-cb49-11eb-9703-0b2152aa1924.png)
It seems like the applications are prioritized regardless of previous preferences. Please change it so that any previous preference is remembered as the top selection for the next use.

**Comment by oliverschwendener** [comment]
In ueli v9 you can set items as "favorites", so they will show up first:

![image](https://github.com/oliverschwendener/ueli/assets/15727229/c0b952d1-fab1-4b25-920b-e93a4e7c7e17)

You try out the latest beta release of v9 here: https://github.com/oliverschwendener/ueli/releases
