### ISSUE TITLE
UELI taking too much memory?

### ISSUE THREAD

**Issue by scorpioraj** [oliverschwendener/ueli#752]
Ueli seems to be taking lot of memory. Anyways of sorting this issue out. I am using Windows 8.1 x64 with 8MB Ram and 2 GB Graphics card too. I can see 5 processes running. 

Any solutions?

![Capture43g453453](https://user-images.githubusercontent.com/83529373/121799742-67bd3a00-cc4b-11eb-9acb-fc95c57a765b.JPG)
![Capture3453534t3](https://user-images.githubusercontent.com/83529373/121799743-6986fd80-cc4b-11eb-982a-5f092a08e063.JPG)

**Comment by oliverschwendener** [comment]
This is really normal for an [electron](https://electronjs.org) app

**Comment by scorpioraj** [comment]
oh okay got it
