### ISSUE TITLE
Rounded?

### ISSUE THREAD

**Issue by ItxWeird** [oliverschwendener/ueli#753]
Can we make the UI more rounded somehow?

**Comment by oliverschwendener** [comment]
No, unfortunately not

**Comment by vicky-nike** [comment]
In the setting you can change the radius and make it round.

![Screenshot (139)](https://user-images.githubusercontent.com/40816229/123534770-12018b00-d73d-11eb-9531-6347f2a12543.png)

**Comment by vishaluchil** [comment]
@TheDingOfTheHud wait for windows 11 or join the insiders channel. Your ueli will automatically have rounded corners

![image](https://user-images.githubusercontent.com/50170066/124408340-f1899000-dd3d-11eb-85a2-c6bd54f793e9.png)

**Comment by vishaluchil** [comment]
Wait for Windows 11 or just join the insider channel. Your ueli will automatically have rounded corners.

![image](https://user-images.githubusercontent.com/50170066/124408451-30b7e100-dd3e-11eb-8705-1f82b4b9e075.png)

![image](https://user-images.githubusercontent.com/50170066/124408604-770d4000-dd3e-11eb-8086-d979549bb2d7.png)

I know this isn't a solution but just to let you know

**Comment by paraselen** [comment]
> insider cha

Sorry, how to join the insider channel? I am on Windows 11 and do not have rounded corners.
