### ISSUE TITLE
Black Border around window opened through ueli

### ISSUE THREAD

**Issue by rahulbhatia101** [oliverschwendener/ueli#754]
Whenever I open a software through ueli search, there is a black border around the window opened ( screenshot 1 ). If I open the same software using windows search or using pinned icon on Taskbar, there is no border ( screenshot 2 ). PFA screenshots of my browser. 

This happens in both windowed mode and fullcreen mode windows. Would like to hear from you.

Thanks in advanced 

![Screenshot (44)](https://user-images.githubusercontent.com/84509359/122196555-f54f9280-ceb4-11eb-8cea-c4f55c37f1b2.png)
![Screenshot (43)](https://user-images.githubusercontent.com/84509359/122196561-f7195600-ceb4-11eb-8af2-cbaa56cbdeaa.png)

**Comment by oliverschwendener** [comment]
I see that you're on Windows, what version are you using?

**Comment by rahulbhatia101** [comment]
Yes, I am using Windows 10 64bit. 

This happens peculiarly only on browsers' windows. not on other software or file explorer windows. Strange. 
And to verify that this is not a windows issue, I tried a different web search service " power toy run " by windows, and there is no borders around if I open through that

![image](https://user-images.githubusercontent.com/84509359/123501949-27f04c80-d666-11eb-9e1a-de1052610648.png)

**Comment by rahulbhatia101** [comment]
Hey Oliver, thanks for your time, but I uninstalled it and clean installed 8.13 ( i was earlier on 8.12 ). The issue has been fixed. Sorry to have not done that earlier.
Thanks
