### ISSUE TITLE
`Screenshot` is not found

### ISSUE THREAD

**Issue by gervaisb** [oliverschwendener/ueli#755]
While all of the applications folders are given, the `Screenshot` app cannot be started by UELI. Entering "screenshot" show the `/System/Library/CoreServices/screencaptureui.app` but this one does not open the MacOS Screenshot tool.

Here are the configured application folders:
 - `/Applications`
 - `/System/Library/CoreServices`
 - `/Users/{me}/Applications`
 - `/Applications/Utilities`

**Comment by oliverschwendener** [comment]
Try adding `/System/Applications`

**Comment by gervaisb** [comment]
Indeed. Thanks for the quick answer. This issue is **resolved**.
