### ISSUE TITLE
[feature request] Command to run as administrator

### ISSUE THREAD

**Issue by cosimochellini** [oliverschwendener/ueli#76]
Hi, I understand that it is a difficult function to implement, but as a developer, I often have to start applications as an administrator, it would be possible, maybe when you're preemptive on the shift, run the app selected as an administrator?
Thanks for your patience

**Comment by oliverschwendener** [comment]
Ueli is build with electron and uses node.js to interact with the operating system and execute os specific commands such as opening files and programs. As far as I know it is not possible to start an application as admin/bring up the UAC dialog. If you always want to open specific programs as admin you can do the this:

1. Search for the app

![image](https://user-images.githubusercontent.com/15727229/49753366-71990780-fcb3-11e8-9d24-0335d600ad7e.png)

2. Press `Ctrl+o` to open the file explorer at the specified file location
3. Right click the program you want to run as admin
4. Under `Compatibility` check `Run this program as an administrator`

![image](https://user-images.githubusercontent.com/15727229/49753433-af962b80-fcb3-11e8-9bab-e5853735c509.png)

5. Lauch the program again
6. The UAC dialog should now show up and you should be able to run the program as admin

I know it does not solve your problem if you want don't always want to launch the program as admin but only "on command". But at least something. I will close this issue and mark it as 'Won't fix'. If you or anyone else has a solution to this, reopen it and let me know ;)

**Comment by khanhas** [comment]
In release binaries, Electron put `elevate.exe` in `resources` folder, I don't know why but it's there:
![image](https://user-images.githubusercontent.com/26436809/49850919-fc901400-fe11-11e8-93be-1675e2b6861a.png)

You can use it to open shortcut as Administrator, just execute it with shortcut path as parameter
```
.\resources\elevate.exe "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Sublime.lnk"
```

**Comment by oliverschwendener** [comment]
@khanhas Thank you for your research, I will look into this!

**Comment by oliverschwendener** [comment]
For me it doesn't always work. For example the Windows command prompt or Notepad won't work as expected. When I execute

```.\resources\elevate.exe C:\Users\Oliver\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Accessories\Notepad.lnk"```

Notepad does start (I checked in the Windows Task Manager) but there is no Window. Any idea?

**Comment by khanhas** [comment]
Yeah, it doesn't open CMD and Notepad in my side too, weird.

**Comment by khanhas** [comment]
How about powershell command?
```powershell
Start-Process "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Accessories\Notepad.lnk" -Verb Runas
```

**Comment by oliverschwendener** [comment]
Does this bring up the UAC dialog? Or do you have to enter the user's password on the command line?

**Comment by khanhas** [comment]
Yes, it does bring up UAC dialog as expected in all elevated programs.   
And no, users don't need to enter password.

**Comment by oliverschwendener** [comment]
Oh nice! @khanhas Thank you for your research!

**Comment by oliverschwendener** [comment]
@cosimochellini Added the possibility to launch programs as admin. Will be included in the next release.

@khanhas Thank you for your research!
