### ISSUE TITLE
[Feature Request] Add ueli to the Microsoft Store on Windows

### ISSUE THREAD

**Issue by vishaluchil** [oliverschwendener/ueli#768]
Since the new Windows 11 update, Microsoft store is going to get a huge boost.

I've seen that ueli is accessible through the new Windows Package Manager and that's great.
So, can it also be added to the Microsoft store to make it easier to find for more casual users?

[Link](https://developer.microsoft.com/en-us/microsoft-store/) regarding the steps:

**Comment by Light-Lens** [comment]
> Since the new Windows 11 update, Microsoft store is going to get a huge boost.
> 
> I've seen that ueli is accessible through the new Windows Package Manager and that's great.
> So, can it also be added to the Microsoft store to make it easier to find for more casual users?
> 
> [Link](https://developer.microsoft.com/en-us/microsoft-store/) regarding the steps:

Yes, please make it available on Microsoft Store. It would be great!

**Comment by firinael** [comment]
Adding my bump to this, ueli being on the Microsoft Store could be a step towards making it more available/usable for laypeople. Could also garner some funding and project collaborators, who knows!

**Comment by vishaluchil** [comment]
Any update on this? The store policy now allows listing of free and open source projects as long as it is listed by the creator. @oliverschwendener

**Comment by oliverschwendener** [comment]
I'm on this. The goal is to get version 9 into the Microsoft Store. I also hope to get the app signed, so that Windows doesn't complain about an "unverified developer". I'll keep you posted.

**Comment by zerenxyz** [comment]
> I'm on this. The goal is to get version 9 into the Microsoft Store. I also hope to get the app signed, so that Windows doesn't complain about an "unverified developer". I'll keep you posted.

I would also like to use UELI but I can not install unsigned apps on my device as it is managed. Any updates on this or when it might come by?

**Comment by oliverschwendener** [comment]
Traditional EV code signing certificates are very expensive, and their cost exceed the amount of money I want to spend on this project. Please note that I work on this project solely in my free time and I don't get paid for it. Microsoft just launched the "Trusted Signing" service on azure and I will look into this in the next weeks, maybe it's cheaper. I keep you updated.

**Comment by Enubia** [comment]
@oliverschwendener not sure if it's applicable here but SignPath provide free code signing for open source projects if you apply

https://about.signpath.io/product/open-source

**Comment by oliverschwendener** [comment]
Finally! Ueli is now available in the Microsoft Store: https://apps.microsoft.com/detail/9pk44n42b2g7

Thanks for the patience.
