### ISSUE TITLE
/Applications/Utilities folder not working 

### ISSUE THREAD

**Issue by pauLee** [oliverschwendener/ueli#769]
All utilities in the /Applications/Utilities directory are not found.

I tried adding this folder to the configuration - but no luck.

<img width="609" alt="Bildschirmfoto 2021-07-11 um 14 05 30" src="https://user-images.githubusercontent.com/592889/125194328-19eb2000-e251-11eb-8a5f-202753c008a8.png">

<img width="616" alt="Bildschirmfoto 2021-07-11 um 14 07 58" src="https://user-images.githubusercontent.com/592889/125194390-6c2c4100-e251-11eb-9bff-a953df155680.png">

I'am running Mac OS 10.15.7 with Ueli 8.13.0

**Comment by oliverschwendener** [comment]
I think this solution might solve your problem: https://github.com/oliverschwendener/ueli/issues/640

**Comment by pauLee** [comment]
Yes, this solves my problem. Thank you!
