### ISSUE TITLE
Support for importing / exporting config via script

### ISSUE THREAD

**Issue by carlitorendon** [oliverschwendener/ueli#774]
Hello @oliverschwendener / team, love ueli. Quick question, is there a way to import / export the configuration in a more automated way (i.e. without having to use the UI)? 

If not, I'd like to throw my 2 cents proposing this as a great way to allow syncing when one uses Ueli across multiple machines. 

Thanks again! 🙏

**Comment by NotWearingPants** [comment]
The config is managed by [`electron-store`](https://www.npmjs.com/package/electron-store) so it's a JSON file in:
- Windows: `%APPDATA%\ueli\config.json`
- Linux: `$XDG_CONFIG_HOME/ueli/config.json` or `~/.config/ueli/config.json`
- macOS: `~/Library/Application Support/ueli/config.json`

As a shortcut, there's an `edit settings file` command in ueli which opens the file.

So your scripts can just read/write this file (I'd symlink it into a dotfiles repo).
Sadly there is no way to make ueli reload settings from the file when you change it yourself, but you can kill it and reopen and viola.

The best solution for this issue IMO is be to add a command-line parameter to ueli such as `--reload-settings` which tells the currently opened ueli to reload.

**Comment by carlitorendon** [comment]
I think this is basically what I need. Thanks a lot @NotWearingPants 🙏

**Comment by carlitorendon** [comment]
One more thing I wanted to add in case it helps anyone. By using the approach proposed here, the procedure works and Ueli comes back with the new configuration. However, on Windows it leaves a "zombie" tray icon from the instance just killed. This goes away by you just hovering the mouse over it. This can become annoying if you're relaunching often. I found this AutoHotKey utility that takes care of it. Just call it after you have killed and relaunched Ueli: 

https://github.com/sphr2k/RefreshSystray
