### ISSUE TITLE
Simple folder search

### ISSUE THREAD

**Issue by Or-Fadlon** [oliverschwendener/ueli#775]
The "simple folder search" plugin doesn't index all the folders in the selected main folder
("Recursive file scan" selected)

**Comment by Wever1985** [comment]
What's even stranger, the index seems to arbitrarily include _some_ subfolders but not others... I really like the app but since I can never be sure all files are found reliably, I unfortunately have to switch to another app.

**Comment by oliverschwendener** [comment]
Closing this issue as the Simple folder search plugin will be discontinued with v9, unless someone takes their time to migrate it.
