### ISSUE TITLE
Tempature conversion

### ISSUE THREAD

**Issue by bonn2** [oliverschwendener/ueli#784]
Allow the quick calculation of temperature conversions

I think this could be an addition to the calculator plugin as it already does queries like `13ft to in`.

The query would look something like `70f to c`

**Comment by oliverschwendener** [comment]
Try `70 degF in degC`

**Comment by oliverschwendener** [comment]
Or `13 ft in in`

**Comment by bonn2** [comment]
That works, but seems to be case sensative (which just seems a bit clunky to me)
My example of `13ft to in` actually works, so I guess this is a case of the commands being a bit inconsistent?

**Comment by oliverschwendener** [comment]
ueli is using [math.js](https://mathjs.org) to do the unit conversion. You can see the full list of all units [here](https://mathjs.org/docs/datatypes/units.html#reference).

**Comment by bonn2** [comment]
Gotcha, really strange they would do this imo:
![image](https://user-images.githubusercontent.com/42011672/129972056-15b570ab-34dd-4600-b9d3-0927f3917be3.png)
But I guess this means it isn't really ueli's job to fix it.

Thanks for the explanation!

**Comment by firinael** [comment]
@bonn2 Google also returns the answer in the form of a suggestion.

Use `g? (or your equivalent) 12 celcius` or something like that.
