### ISSUE TITLE
Everything not working. Error 7: Unable to send IPC message.

### ISSUE THREAD

**Issue by ghost** [oliverschwendener/ueli#785]
UELI is working fine. Everything is working fine. But UELI + Everything isn't working fine. What should I do about this error? 

![image](https://user-images.githubusercontent.com/67146868/130996367-9611f691-1604-4eee-9c10-f7381c67a4dd.png)

**Comment by paraselen** [comment]
Is there an update on this error? Same issue, cannot use Everything search in Ueli :(

**Comment by oliverschwendener** [comment]
Can someone check if this is still an issue with the latest v9 release? https://github.com/oliverschwendener/ueli/releases
If so, feel free to reopen.
