### ISSUE TITLE
[REQUEST] Switch to app if already open (as a toggleable setting)

### ISSUE THREAD

**Issue by firinael** [oliverschwendener/ueli#786]
I have Zotero open on my PC, but minimized. Launching ueli and looking up Zotero then pressing Enter/Return switches to Zotero as the focused window instead of opening another instance of Zotero.

This is the exact behaviour I need/am requesting. It'd be a _MASSIVE_ quality of life improvement for people that, like me, need to keep several apps running at the same time.

Thank you for the wonderful app!

**Comment by oliverschwendener** [comment]
See #86

**Comment by firinael** [comment]
I am so very sorry, I searched for "open window" and it didn't show up!
