### ISSUE TITLE
Failure to show installed application

### ISSUE THREAD

**Issue by ZoroNasr** [oliverschwendener/ueli#791]
Hi, the app is great, and I love it. But at the moment, it fails to detect any application that I installed. It shows windows applications (applications from the store) without a problem. 

this is the message that i receive. 

![Untitled](https://user-images.githubusercontent.com/67539686/132357140-3be913f7-b7f7-4304-bd09-5b220f270979.png)

Thanks !!

**Comment by oliverschwendener** [comment]
Can you show us your application search settings? Which folders and what extensions did you add?

**Comment by tkohlmeier** [comment]
Might be the same issue as here: https://github.com/oliverschwendener/ueli/issues/561#issuecomment-733237191

**Comment by ZoroNasr** [comment]
Sorry for the late reply

![whole](https://user-images.githubusercontent.com/67539686/132525358-46f4ae47-a9aa-4537-aae4-c8401ff28d3c.png)

and when i try to add a folder like program file or so, i get this error.

![error](https://user-images.githubusercontent.com/67539686/132525414-d30eddf5-a98e-4ab0-87b2-b258e712330c.png)

**Comment by oliverschwendener** [comment]
Remove `C:\Program Files` and you should be good

**Comment by ZoroNasr** [comment]
I did, but it still give me the same error whenever i try to add to remove any folder, even restarting and using only default folders, gave me the same error !!. I'm sorry for making such a fuss !!, but i use the app every single day, and not working like this is a real bummer !!

**Comment by oliverschwendener** [comment]
Ah sorry, I didn't look at the error message good enough.

It seems like `powershell` can't be found. Can you please check if you find a solution in #561 as @tkohlmeier suggested?

**Comment by ZoroNasr** [comment]
I did change my PathEXT to only .exe, and .Ink, but the problem is still the same !!

**Comment by tkohlmeier** [comment]
Can you run `powershell` in a command window?
If not, does `powershell.exe` work?

**Comment by ZoroNasr** [comment]
No, I can't 

yes, it works

**Comment by ZoroNasr** [comment]
sorry, when i run it in adminstrator mode, it works in command window

**Comment by ZoroNasr** [comment]
ok, now i figured out what was the problem, the app needed to run in administrator mode !!, is there a way to make sure it always works in admin mode ?

**Comment by ZoroNasr** [comment]
Everything works good now, thanks for the help :)

**Comment by tkohlmeier** [comment]
Administrator mode should not be necessary. Could you please run the command `echo %PATHEXT%` in a command window, once with administrator privileges and once without, and post the results?
