### ISSUE TITLE
Web search uses wrong browser

### ISSUE THREAD

**Issue by LalaGhost** [oliverschwendener/ueli#792]
I switched from Firefox to Edge and under Browser Bookmarks I switched to Microsoft Edge, too but every Web search function I use opens in Firefox.
Is there any way to change that?

**Comment by oliverschwendener** [comment]
What browser do you have set as default in the operating system settings?

**Comment by LalaGhost** [comment]
Oh... that is kinda embarrassing...
Yeah in the OS setting there was a different default set.
