### ISSUE TITLE
Add reverse translate

### ISSUE THREAD

**Issue by RomanKornev** [oliverschwendener/ueli#793]
There needs to be an easy way to translate back from target language to source language.
Perhaps using a different prefix? Or maybe auto-detect input language?

**Comment by RomanKornev** [comment]
Nevermind, Russian translate API seems to be broken #238

**Comment by firinael** [comment]
It's not just a Russian translate API issue, though. I use both PT-BR and EN-GB as day-to-day languages and can confirm that we do not have both-ways translation.

I think I've already requested this as a feature, though.

**Comment by oliverschwendener** [comment]
In v9 there will be a DeepL Translator extension that can auto detect the language and should fix a lot of translation issues. Here is a screenshot from v9.0.0-alpha.3:

<img width="862" alt="image" src="https://github.com/oliverschwendener/ueli/assets/15727229/63cf429e-6002-4891-87d1-612b56498a1c">
