### ISSUE TITLE
How can I search bookmarks and web (e.g. Google) at the same time like the address bar of Chrome 

### ISSUE THREAD

**Issue by UndefinedVoidNull** [oliverschwendener/ueli#794]
How can I search bookmarks and web (e.g. Google) at the same time like the address bar of Chrome.
1. You can sort the result like Chrome 
2. Or give an option like showing the result of web search over the search bar and showing the result of bookmarks search under the search bar, which will be really clear and easy to choose the entry that user want.
Plus: Maybe we can use the "tab" key to switch between local search and web&bookmarks search.

**Comment by YouMoeYi** [comment]
I can make contributions to implement this function, cuz it's really important to me.

**Comment by oliverschwendener** [comment]
Unfortunately this is currently not possible.
