### ISSUE TITLE
[Feature Request] Display full hotkeys/shortcuts and allow changing

### ISSUE THREAD

**Issue by firinael** [oliverschwendener/ueli#799]
Hi, ueli is very hostile to new users. 

One of the major reasons is the fact that the hotkeys are simply not listed in the app. How would someone know that `Ctrl+I` (never seen this as an "options" hotkey, btw) without reading the full README? (Please mind that most people won't read something that's not pushed on their face)

Suggested fix: add a "Shortcuts" tab in the options with text boxes for switching said shortcuts, and a prompt on first launch showing the default shortcuts for launching and opening the settings.

**Comment by oliverschwendener** [comment]
Keyboard shortcuts are now shown in the UI. This should solve this issue.

![image](https://github.com/user-attachments/assets/e3079e19-a904-44d7-9409-a780320e2e7d)
