### ISSUE TITLE
[SUGGESTION] Add `alt+spacebar` in the list of hotkeys

### ISSUE THREAD

**Issue by Arpit-Babbar** [oliverschwendener/ueli#800]
I had to Google to even learn that `ueli` search can be done without using the mouse, which is a great feature. I really think it should be the first hotkey, while it isn't even in the list; as I can see.

EDIT - I meant `alt+spacebar`, sorry for the confusion. To be more clear, I am suggesting that `alt+spacebar` be included in the list of hotkeys!

**Comment by oliverschwendener** [comment]
Like this?

![image](https://user-images.githubusercontent.com/15727229/133002010-7f251255-c6d9-4c13-b535-19a0cafb7103.png)

**Comment by oliverschwendener** [comment]
It's already there.

**Comment by Arpit-Babbar** [comment]
Merged in https://github.com/oliverschwendener/ueli/pull/803
