### ISSUE TITLE
[feature request] Add workflows feature

### ISSUE THREAD

**Issue by cosimochellini** [oliverschwendener/ueli#81]
As a user, I like the option to build my own workflow, for example, every working morning i open the same programs (["vs code", "visual studio", "git-fork" .... ]) , a nice feature could be to add the ability to config in the **ueli.config.json** a list of workflows that run a list of command callable via ueli

maybe something like this 😄  in the .json
` "workfolows": [
    {
      "name": "work",
      "actions": [
        {
          "url": "path\\to\\vs code",
          "type": "program"
        },
        {
          "url": "path\\to\\git-fork",
          "type": "program"
        },
        {
          "url": "path\\to\\insomnia",
          "type": "program"
        },
        {
          "url": "https://www.reddit.com/r/webdev",
          "type": "link"
        }
      ]
    },
    {
      "name": "home",
      "actions": [
        {
          "url": "https://www.youtube.com/",
          "type": "link"
        },
        {
          "url": "https://www.netflix.com/",
          "type": "link"
        }
      ]
    }
  ]`

**Comment by oliverschwendener** [comment]
Will look into it as soon as possible!

**Comment by cosimochellini** [comment]
take your time, it's nothing urgent :D

**Comment by alanaasmaa** [comment]
On windows you could do something like this
`>cmd.exe /k "start https://google.com & start https://www.reddit.com/r/webdev & code"`

but currently there is an issue here https://github.com/oliverschwendener/ueli/blob/d3ecfb429de4d70c0613e2271b32dca742991b6c/src/ts/helpers/string-helpers.ts#L6 thats splits everything to seperate command. When you would replace `.split(/\s/g);` to `.match(/"(?:\\"|\\\\|[^"])*"|\S+/g);` it would work.

**Comment by oliverschwendener** [comment]
Good idea! Because I am working on a total rewrite you have to wait for this until I release the major version.

**Comment by oliverschwendener** [comment]
This is included in the newest [v8.0.0](https://github.com/oliverschwendener/ueli/releases/v8.0.0) release.
