### ISSUE TITLE
Cant activate Ueli after running fullscreen app

### ISSUE THREAD

**Issue by drewauff** [oliverschwendener/ueli#819]
If I switch my browser to fullscreen mode to watch youtube then switch to another space I cannot activate Ueli. I have to kill Ueli and re-launch Ueli.

Also, I have to switch to another space because Ueli wont activate while using fullscreen apps ie. web browsers.

Keep up the awesome work!

-
Andy

**Comment by weiw11** [comment]
Is this on macOS? Also what do you mean by another "space"?

I fullscreened youtube on Firefox, switched to another virtual desktop and it was working fine for me. This is on windows.

**Comment by drewauff** [comment]
Yes, MacOS Catalina.

Space = Desktop.

Either way after watching youtube on fullscreen then switching back to "normal" mode Ueli wont activate, literally have to go and launch from finder to 
activate.

Very annoying.

**Comment by oliverschwendener** [comment]
Not sure if this is still an issue, but I think it should be fixed with v9 where I couldn't reproduce the issue.
