### ISSUE TITLE
[Feature Request] Scrolling shortcut keys.

### ISSUE THREAD

**Issue by musaAmir** [oliverschwendener/ueli#820]
Would really appreciate it if you could add a hotkey or some way of scrolling through the search list aside from the arrow keys. For the inconvenience of using arrow keys, or for users without arrow keys on their keyboard.

Something like tab, ctrl/shift + tab. You could add a toggle for the autocomplete file path.

**Comment by oliverschwendener** [comment]
You can use <kbd>Ctrl</kbd><kbd>n</kbd> and <kbd>Ctrl</kbd><kbd>p</kbd>
