### ISSUE TITLE
Error: Command failed

### ISSUE THREAD

**Issue by Chameleon-789** [oliverschwendener/ueli#826]
Whenever I add a folder to the application folder list, or just do anything else I get this Error:
```Error: Command failed: powershell -NonInteractive -NoProfile -Command "& { [Console]::OutputEncoding = [Text.UTF8Encoding]::UTF8; $ErrorActionPreference = 'SilentlyContinue'; $applications = New-Object Collections.Generic.List[String]; 'C:\ProgramData\Microsoft\Windows\Start Menu\Programs','C:\Users\xxx\AppData\Roaming\Microsoft\Windows\Start Menu','C:\Users\xxx\Desktop' | %{ Get-ChildItem -Path $_ -include *.lnk, *.appref-ms, *.url, *.exe -Recurse -File | % { $applications.Add($_.FullName) } }; $result = (@{ errors = @($error | ForEach-Object { $_.Exception.Message }); applications = $applications } | ConvertTo-Json); Write-Host $result; }" Internal Windows PowerShell error.  Loading managed Windows PowerShell failed with error 80070002.  ```

Assume xxx is my user account.

**Comment by oliverschwendener** [comment]
Can someone check if this is still an issue with the latest v9 release? https://github.com/oliverschwendener/ueli/releases
If so, feel free to reopen.
