### ISSUE TITLE
[Bug] Workflows open a cmd window where shortcuts do not

### ISSUE THREAD

**Issue by HermasciousLevander** [oliverschwendener/ueli#830]
ueli: 8.18.0
Electron: 11.4.8
Node: 12.18.3
V8: 8.7.220.31-electron.0

---

I updated to 8.18.0 around an hour ago and since I've been having problems where a cmd console opens and does not close when using workflow command line. If I use a shortcut command line with an identical command, it does not do this.

I have downgraded all the way to 8.15.0, testing each version manually after resetting all settings. Shortcuts still work fine, but workflows open a visible cmd window that is not closed afterwards. I uninstalled the application and removed all directories for ueli under AppData and reinstalled, but no bueno. Same problem. Checked the debug but there is [nothing important](https://pastebin.com/8TUCE8hr) there after executing the workflow.

**Comment by mahoromax** [comment]
This is still happening.
Workaround is to add "&& exit" to automatically close the CMD window.  
But this is only viable for commands that finish, not for programs started with a command, that keep running.

**Comment by oliverschwendener** [comment]
Can someone check if this is still an issue with ueli v9? You can try out the latest beta release here: https://github.com/oliverschwendener/ueli/releases

Feel free to reopen if this is still an issue.
