### ISSUE TITLE
Can't run on macOS Monterey.

### ISSUE THREAD

**Issue by ivan-leschinsky** [oliverschwendener/ueli#832]
Can't run on macOS Monterey.
Applicatoin vesion 8.18.0
<img width="416" alt="screen" src="https://user-images.githubusercontent.com/4127186/139597939-43822275-d653-4c87-9cbf-5da6aa4608e6.png">
.0

**Comment by oliverschwendener** [comment]
Fix is on the way!

**Comment by Berrserker** [comment]
8.18 ping. not work on monterey

**Comment by fabiompneves** [comment]
For when the 8.18.1 or 8.19 with IOs Monterey fix?

**Comment by o1dnik** [comment]
@oliverschwendener  can I support you somehow in implementing this fix?

**Comment by oliverschwendener** [comment]
Thanks for the support but it's already implemented thanks to @danitt ;) I just need to publish a new release.

**Comment by oliverschwendener** [comment]
This should work now with the latest release.
