### ISSUE TITLE
Allow extension *.rdp for application search

### ISSUE THREAD

**Issue by mundus08** [oliverschwendener/ueli#836]
It would be great if application search would allow to add extension *.rdp

**Comment by oliverschwendener** [comment]
You can add the `.rdp` extension in the application search settings.

**Comment by mundus08** [comment]
I tried - but got the message "*.rdp  ist keine gültige Dateierweiterung / *.rdp is not a valid extension"

**Comment by tkohlmeier** [comment]
Try `.rdp` instead of `*.rdp`.

**Comment by mundus08** [comment]
It works - thanks for your great support!
I shouldn't start my PC before the first coffee ;-)
