### ISSUE TITLE
Calculation is slightly off

### ISSUE THREAD

**Issue by LalaGhost** [oliverschwendener/ueli#84]
When you type '1.1625 - 0.2' its result is '0.9625000000000001'. It the only issue I had with calculations so far.

Screenshot:
![screenshot_3](https://user-images.githubusercontent.com/43962138/50727962-30b1d880-1123-11e9-9656-38611e3df3e6.png)

**Comment by oliverschwendener** [comment]
Actually this has to do with JavaScript having serious issues when doing math with decimals.

For example see here:
- http://adripofjavascript.com/blog/drips/avoiding-problems-with-decimal-math-in-javascript.html
- https://hackernoon.com/understanding-the-problem-javascript-maths-2119d85dad2a

I have to look into this to find a solution. Thank you for your feedback!

**Comment by oliverschwendener** [comment]
Fixed this issue with the help of @khanhas, thank you for your help! The fix will be shipped with the next release.

**Comment by khanhas** [comment]
Mathjs instance we using in both CalculatorInputValidator and Searcher are the same one so you only need to set config once.
You also might want to change precision field in config since default value is really long, 64.

**Comment by oliverschwendener** [comment]
New version released: https://github.com/oliverschwendener/ueli/releases/v7.2.2
