### ISSUE TITLE
Improper Searching for Files

### ISSUE THREAD

**Issue by amangalampalli** [oliverschwendener/ueli#842]
Ueli is not able to search for files properly within the local folder. When searching by the name of the file, no results come up although manually entering the whole path of the specific document makes it show up. Furthermore, excluding the `/System` directory does not work as I do not want to index the files of the system.

**Comment by oliverschwendener** [comment]
Which plugin are you referring to? I'll close this issue as I assume that this is not relevant anymore. Feel free to reopen it.
