### ISSUE TITLE
Searching for "made" using Everything Search closes the app and prevents it to open again

### ISSUE THREAD

**Issue by arthurmarquesv** [oliverschwendener/ueli#847]
Hey guys! I'm having a strange bug (I think) with ueli: everytime i try to search for the word _made_  using everything search (regardless of the chosen shortcut), ueli closes in a way I can't open it again. If I click on the ueli.exe, windows prompts a "this app can't run on your pc" message. The only way I know to get ueli again is to reinstall it.

The bug doesn't happen is defaut search or when I using other keywords. It doesn't happen on Everything directly either.
I tried to clean unistalls and installing older versions to (before 8.18.1). The problem persists.

This my OS version:
![image](https://user-images.githubusercontent.com/78812600/144614605-b2e4abbc-9fe8-45aa-a468-d1a445dd52af.png)

Love the app! I hope there is a answer to this problem.

**Comment by arthurmarquesv** [comment]
Update: the problem don't occur when starting ueli as a admin.

**Comment by oliverschwendener** [comment]
I have no clue what the issue could be here. I suggest trying the latest beta release of ueli v9. I'll close this issue assuming that this is not relevant anymore. Feel free to reopen it.
