### ISSUE TITLE
[BUG] - Color Themes Broken

### ISSUE THREAD

**Issue by ondrovic** [oliverschwendener/ueli#848]
None of the color themes seem to be working, tried importing, tried manually changing. Tried Rebooting, Restarting. Seems like it's just he default colors that work

[config_and_theme.zip](https://github.com/oliverschwendener/ueli/files/7653232/config_and_theme.zip)

Also tried downloading [Dracula Theme](https://draculatheme.com/ueli) and using this one as an alternate test.

![image](https://user-images.githubusercontent.com/3682042/144694885-a749f522-112d-487a-bfe9-f5328a9a42c8.png)
![image](https://user-images.githubusercontent.com/3682042/144694841-961c469c-fdca-4679-ba89-7d2a57576f3f.png)
![image](https://user-images.githubusercontent.com/3682042/144694827-8eed58dd-ad93-484e-be24-f07ce817199a.png)

**Comment by oliverschwendener** [comment]
The screenshot that you shared doesn't seem to be ueli.

**Comment by tkohlmeier** [comment]
Right, looks like [PowerToys Run](https://docs.microsoft.com/en-us/windows/powertoys/run).

**Comment by oliverschwendener** [comment]
@ondrovic I guess you have both running but only PowerToys reacts to the keyboard shortcut. If you click on ueli's tray icon and then click "Show" you can see ueli and there the color themes should work.

**Comment by ondrovic** [comment]
Yeah confirmed working forgot PowerToys Run was enabled by default sorry about that
