### ISSUE TITLE
Xbox gamebar pinned "apps" makes the search bar dissapear. Search still works. 100% proven.

### ISSUE THREAD

**Issue by mario-haslan** [oliverschwendener/ueli#851]
The issue happens with all pinned xbox gamebar "apps". It's 100% the reason of the issue.

When you keep searching, lets say you have typped config and the bar is not showing, it still works, you press enter and the ueli config pops.

**Comment by nihilitycollapse** [comment]
@haslanz I had the same issue with Xbox Gamebar pinned apps, I could find a way around it by enabling click-through in Gamebar settings.
I don't know how this causes the problem because the launcher from powertoys I used worked fine even with click-through disabled.

**Comment by oliverschwendener** [comment]
Can you try if this still occurs with the latest beta release of ueli v9? https://github.com/oliverschwendener/ueli/releases
