### ISSUE TITLE
Не находит

### ISSUE THREAD

**Issue by wita74** [oliverschwendener/ueli#852]
Hello. When you type " log " the native search engine finds the system stability log. UELI doesn't find that. I wish it could be found. Thank you
![скрин 1](https://user-images.githubusercontent.com/6236532/145537407-ff2a6c44-b03f-4682-96d6-654bf0fe22ed.png)
![скрин 2](https://user-images.githubusercontent.com/6236532/145537414-e5c078a0-b195-487c-a8c8-57d0a9a3c9bc.png)
о

**Comment by oliverschwendener** [comment]
Unfortunately there is no way currently that ueli will find these things.
