### ISSUE TITLE
Copy Path and Open Folder

### ISSUE THREAD

**Issue by elamhut** [oliverschwendener/ueli#859]
Please let us Ctrl+C over a result to copy it's Path. This is the only feature from Wox that is driving me crazy to not have, seriously. 
(Also Open Folder would be amazing)

I would do this myself if Ueli could be extended with Python or something :P

**Comment by GovindKrishnan** [comment]
Open Containing Folder can be down with Ctrl + O [Windows] or Cmd + O [macOS]

To copy the path of a file, press Tab to get full file path & then Ctrl + C to copy.

Hope I got your question right.

**Comment by oliverschwendener** [comment]
This will be supported in ueli v9. You can download the latest beta release here: https://github.com/oliverschwendener/ueli/releases

![image](https://github.com/oliverschwendener/ueli/assets/15727229/910abb6c-ead5-4be2-a1bb-e83822736e72)
