### ISSUE TITLE
[Bug] Application search does not allow directory symbolic link

### ISSUE THREAD

**Issue by raveren** [oliverschwendener/ueli#860]
When I try to add my portable app folder it complains that it is "not a folder"

![image](https://user-images.githubusercontent.com/364220/147872175-5f43c8d6-f9ed-4807-952b-856b202ba26c.png)

I create it on every windows machine I use by:

```
mklink /d c:\Apps c:\gdrive\Apps
```

**Comment by Atemu** [comment]
On macOS, you can add another directory separator to dereference the symlink. Try `C:\Apps\`.

**Comment by oliverschwendener** [comment]
Can you check if this is still an issue with the latest version? Feel free to reopen.
