### ISSUE TITLE
[Feature Request] Dark mode for the Settings UI.

### ISSUE THREAD

**Issue by arcticpinecone** [oliverschwendener/ueli#863]
Hello Oliver! This app is amazing frankly. I've tried _many_ different programs similar to yours over the last decade or so. Yours is by far the best. 

However, I find that when going into the settings interface, the subsequent white screen of the settings UI feels like this:

![Indiana Jones Face Melting GIF](https://c.tenor.com/ZMlYoFXVCLgAAAAd/indiana-jones-face-melting.gif)

Would you please consider a section under Color Theme for the Settings UI? 

I think it could ultimately use:
1. UI background color selection
2. Input box color
3. Input text color
4. UI font
5. Font selection
6. Font color

Thanks for the consideration.

**Comment by raptormama** [comment]
At the very least, a basic dark theme would be a good idea. The settings window could get the theme state (light/dark) and apply it as appropriate when the window opens.

**Comment by arcticpinecone** [comment]
It's been 9 months! I was hoping a baby would get cooking by this time. For my poor eyes, and for the love of all that is holy, Dark.. Mode UI...

**Comment by oliverschwendener** [comment]
This will be fixed in v9. Here is an example screenshot:

![image](https://github.com/oliverschwendener/ueli/assets/15727229/b5c87ed0-c5be-4446-acbe-cbcfaf97d78c)
