### ISSUE TITLE
The project is missing localization management

### ISSUE THREAD

**Issue by shateq** [oliverschwendener/ueli#869]
Here: Crowdin as an example of Localization Management Tool
Crowdin Integration would be an opportunity to translate ueli into more languages making it accessible etc.
There are Crowdin alternatives if you don't like it.

I've tried adding translation, but it's pain to do inside a text editor - so I gave up finishing it.

**Comment by andrii-bodnar** [comment]
Hi everyone!

it's Andrii from Crowdin. Crowdin is free for open-source projects. 

I can do a pull request with the integration setup. I would only need a green light from you and the minimal setup of this repo (create a Crowdin project and add some Actions secrets). Please let me know where is localizable content located in the project.

The integration can be completely automatic and can be done via [Crowdin GH Action](https://github.com/crowdin/github-action).

Also, I'd like to participate in the Ukrainian language translations if you'll add this language.

**Comment by oliverschwendener** [comment]
I don't consider adding translations in the text editor as a pain.
