### ISSUE TITLE
Doesn't see System Preference

### ISSUE THREAD

**Issue by alabotski** [oliverschwendener/ueli#870]
ueli 8.19
macos monterey 12.1 (21C52

Doesn't see System Preference 

Spotlight
![image](https://user-images.githubusercontent.com/439337/151147526-7bd688bc-9e12-4706-9292-e037a7628a4f.png)
ueli
![image](https://user-images.githubusercontent.com/439337/151147481-63e7fa1f-fa1e-4359-b41c-fef1f96e0ac6.png)

**Comment by oliverschwendener** [comment]
What happens if you add `/System/Applications` to the application folders in the settings?

![image](https://user-images.githubusercontent.com/15727229/151186830-32e66218-362d-4952-baf1-d02a55cf9e25.png)

**Comment by Obverser** [comment]
> What happens if you add `/System/Applications` to the application folders in the settings?
> 
> ![image](https://user-images.githubusercontent.com/15727229/151186830-32e66218-362d-4952-baf1-d02a55cf9e25.png)

I was having the same issue yesterday, this should fix it.

They show up in the same Applications folder, but they are in different directories. You can check this with "Get Info."

![image](https://user-images.githubusercontent.com/57118333/151240274-2c247068-6135-4774-b708-ee0529d153d2.png)

**Comment by Obverser** [comment]
This is something that Ueli currently can't do, I think. A lot of the system apps don't have an .icns file (as far as I can see). Instead, they store the app icon in the Assets.car file.

App Store (Has .icns file and an Assets.car file in the Resources folder)
<img width="762" alt="image" src="https://user-images.githubusercontent.com/57118333/151469229-589b4e59-d6d7-45c4-bef7-953c8f101d48.png">
As you can see, there is the AppIcon.icns file. This is what Ueli looks for using the function in [src/main/plugins/application-search-plugin/application-icon-helpers.ts](https://github.com/oliverschwendener/ueli/blob/dev/src/main/plugins/application-search-plugin/application-icon-helpers.ts), here's the function if you're interested:
```ts
export function getApplicationIconFilePath(applicationFilePath: string): string {
    const hash = createHash("md5").update(`${applicationFilePath}`).digest("hex");
    const fileName = `${replaceWhitespace(
        basename(applicationFilePath).replace(extname(applicationFilePath), "").toLowerCase(),
        "-",
    )}-${hash}`;
    return `${join(applicationIconLocation, fileName)}.png`;
}
```

System Preferences (Does not have .icns file and only an Assests.car file in the Resources folder)
<img width="767" alt="image" src="https://user-images.githubusercontent.com/57118333/151469890-651ec3d9-eb55-41cc-841f-85bce1ffbbdf.png">
The .icns file is missing and thus Ueli can't display an image for it. If we inspect the Assets.car file, we can see the icons in there (you can get this information with an app like Asset Catalog Tinkerer).
<img width="807" alt="image" src="https://user-images.githubusercontent.com/57118333/151470105-672055b0-f0b7-48f0-9766-be2f720f39f4.png">

My guess is that there needs to be an update to Ueli for these icons to appear. I'm not exactly sure how to implement this, so it might be worthwhile to open a Feature Request for this.

**Comment by oliverschwendener** [comment]
@Obverser Thanks for jumping in, you're 100% correct. Currently ueli can only read icons from the .icns file.
