### ISSUE TITLE
Index other drives

### ISSUE THREAD

**Issue by otaviokamel** [oliverschwendener/ueli#876]
Is there any way to make UELI search files in other drives other than C:/?

**Comment by oliverschwendener** [comment]
Did you try adding more folders to the application search settings?

![image](https://user-images.githubusercontent.com/15727229/156066704-5535778e-87ee-4ba1-87b8-d87a7129343e.png)

**Comment by otaviokamel** [comment]
Hi, thanks for the reply.
I haven't tried it before, but I tried now, and it didn't change a thing.
What I want is to search for FILES, not only applications, on my other drive :x

**Comment by oliverschwendener** [comment]
Then I suggest that you try this:

![image](https://user-images.githubusercontent.com/15727229/156514743-75981498-d363-4e43-abcb-64b90d373ee1.png)

**Comment by otaviokamel** [comment]
Hey Oliver, thanks again for you help.
Unfortunately, I tried but it's still not working as intended. What a bummer :(

**Comment by oliverschwendener** [comment]
Is there a error message or anything?

**Comment by otaviokamel** [comment]
No, nothing. It takes some time to load the indexes, and that's it.
I even tried refreshing the indexes, but it didn't change anything.

**Comment by weiw11** [comment]
Did you enable `recursive file scan`? Without it, it won't index child folders.

What's your operating system?

I tested this on Windows 10 64-Bit Version 21H1 and it works properly. It was able to detect the files of the current folder, and it's child folders if I enabled `recursive file scan`.

**Comment by otaviokamel** [comment]
The recursive file scan wasn't enabled, but I've tried with it now and didn't change a thing.

By operating system is Windows 11 Home 64-Bit - Version 10.0.22000 Build 22000

**Comment by oliverschwendener** [comment]
If you want to search files across whole drives I suggest to use the everything plugin as the simple folder search plugin is only intended to search smaller amounts of files.

**Comment by otaviokamel** [comment]
Okay, I will stick to it. Thank you both very much for your help!
