### ISSUE TITLE
[Bug] Search Suggestions Don't Show up when Calculator is Active, hiding Numerical Filenames.

### ISSUE THREAD

**Issue by GovindKrishnan** [oliverschwendener/ueli#880]
Consider a hypothetical situation where we have an image named "123456.png" which is to be opened.

Currently, it seems we can't do that as the calculator plugin takes over for number inputs, hiding any further suggestions.

**Can be a problem, especially for people having files named based on something like numerical Consumer ID, etc. as they have to type full filename along with file extension every time.**

Also applies in the case of #872 

A probable solution could be to still show the other search suggestions below the calculator result.

![image](https://user-images.githubusercontent.com/74248475/157156148-89869df3-2348-4af8-98c0-ac68bfa2b5d4.png)

**Comment by Otiel** [comment]
Why not add a simple prefix like `=` mandatory to trigger the Calculator plugin?

**Comment by oliverschwendener** [comment]
This should be fixed in the latest beta version of ueli v9. https://github.com/oliverschwendener/ueli/releases
