### ISSUE TITLE
How about Changing Translator API for more Global Languages?

### ISSUE THREAD

**Issue by GovindKrishnan** [oliverschwendener/ueli#886]
**https://github.com/soimort/translate-shell**

This CLI tool seems more feature rich having multiple translators including Google Translate

Also has dictionary it seems.

Might want to have a look at its working yourself as I ain't sure.

Have added available languages in Linguee for the time being #885

**Comment by oliverschwendener** [comment]
This should be resolved with the addition of the DeepL Translator extension in v9.
