### ISSUE TITLE
Add GitHub Sponsor Button 

### ISSUE THREAD

**Issue by GovindKrishnan** [oliverschwendener/ueli#887]
You might consider adding a GitHub Sponsor Button :heart_decoration: to this repo.

**[GitHub Sponsor Button - Docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository)**

You definitely deserve a coffee :coffee: for your active development. :blush:

**Comment by GovindKrishnan** [comment]
Maybe a cool **cover image** in [Social Preview](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/customizing-your-repositorys-social-media-preview) settings too! 😉

**Comment by GovindKrishnan** [comment]
@oliverschwendener 

![sponsorships-checkbox.png](https://user-images.githubusercontent.com/74248475/158504483-99d34268-b81c-4922-b32f-59de62c51680.png)

**Comment by oliverschwendener** [comment]
Thanks for the hint. I just applied for GitHub sponsors now :)

**Comment by oliverschwendener** [comment]
You can now sponsor me: https://github.com/sponsors/oliverschwendener
