### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by 0ANIMEFREAK0** [oliverschwendener/ueli#89]
Is there anyway i can make the window transparent?

**Comment by LalaGhost** [comment]
I guess you are somewhat familiar with Alfred?
Maybe you want to download macintosh to you use Apples OS and look into Alfred for some functions you can integrate it into Ueli.
Oh and thanks for developing Ueli, very handy because it's so basic but holds so many functions to speed up your work at the PC! :)

**Comment by oliverschwendener** [comment]
@0ANIMEFREAK0 I added the option `Transparent window` in user settings:

![image](https://user-images.githubusercontent.com/15727229/51072424-ca681100-1660-11e9-9c98-6bbb3a2edd61.png)

**Note: Changing this option needs a restart of ueli.**

Then you can add a transparent background color in a [custom stylesheet](https://github.com/oliverschwendener/ueli#custom-color-themes).

Example: 

```css
:root {
    --background-color: rgba(0,0,0,0.5);
}
```

Then it should look like this:

![image](https://user-images.githubusercontent.com/15727229/51072417-a60c3480-1660-11e9-8f3a-de24c28bc300.png)

This will be included in the next release.

**Comment by 0ANIMEFREAK0** [comment]
sorry for the late reply thanks

**Comment by jcklpe** [comment]
@oliverschwendener This is excellent. Would you be able to add the blur effect that was added in this fork of your project? https://github.com/khanhas/ueli#features

**Comment by oliverschwendener** [comment]
@jcklpe Please open a separate issue for this so I can keep track of opened feature requests. Thanks!

**Comment by LonWake** [comment]
Does this option appear with the macOS version?  I don't see it in the settings menu.

<img width="1000" alt="Screen Shot 2020-04-02 at 12 28 37 PM" src="https://user-images.githubusercontent.com/63072349/78293567-98e59a80-74dd-11ea-80c7-785f86714e9b.png">

**Comment by oliverschwendener** [comment]
@LonWake On macOS the transparent background option is always enabled. You can directly add a transparent color value in the color theme settings.

**Comment by LalaGhost** [comment]
Do you still need to use the custom style sheet to make the window transparent or can you just change the 'alpha' in the 'Color Theme' settings(Ueli: 8.6.2)?

**Comment by oliverschwendener** [comment]
Since ueli 8.x you don't need to create a custom stylesheet.

**Comment by LalaGhost** [comment]
And how do you change the transparency? In the Color Theme settings?

**Comment by oliverschwendener** [comment]
![image](https://user-images.githubusercontent.com/15727229/78357004-ef6fd900-75b0-11ea-9edc-dbd73b767481.png)

**Comment by CosmicdusT-03** [comment]
> @LonWake On macOS the transparent background option is always enabled. You can directly add a transparent color value in the color theme settings.

is there any way to reduce the font size of the text , which we type in the search window.???

**Comment by CosmicdusT-03** [comment]
is there any way to reduce the font size of the text , which we type in the search window.???
