### ISSUE TITLE
Still running after uninstall

### ISSUE THREAD

**Issue by tkwonbeatcha** [oliverschwendener/ueli#892]
I uninstalled Ueli using Control Panel, but the program is still running when I alt + space. What should I do to completely delete?

**Comment by squirrelboot** [comment]
@tkwonbeatcha it probably was running in memory when you uninstalled it? If you rebooted for example, it probably doesn't appear. Though, that then begs the question.. does UELI close all running instances on uninstall? That could be checked..

**Comment by harahetaman** [comment]
I have the exact same problem. I uninstalled Ueli from Control Panel, reboot the OS, but the search bar still runs when I Alt + Space.

**Comment by harahetaman** [comment]
I'm sorry  it was my mistake. It was PowerToys Run provided by Windows. My problem has been resolved. Thank you
