### ISSUE TITLE
[feature request]Blacklisting special items

### ISSUE THREAD

**Issue by LalaGhost** [oliverschwendener/ueli#90]
Just a suggestion.
Maybe it would be nice to blacklist specific folder and or files.
For example when I am looking for 'C:\Program Files\Autodesk\Maya2018\bin\Maya' he is suggesting me 'mayabatch.exe' as the first result, but I know that I am always looking for 'maya.exe' in the same folder. It would be a nice feature to blacklist items so they do not pop up in the search.
Under uelis settings there could be a area for blacklisted folders and files that look like this:
![ueli](https://user-images.githubusercontent.com/43962138/50983809-9aa1f780-1500-11e9-9573-4c0342c4d861.jpg)

The same goes with favouriting stuff, but it's harder to determine when to display your favourited items and when not.

**Comment by oliverschwendener** [comment]
It's already there:

![image](https://user-images.githubusercontent.com/15727229/50985028-988d6800-1503-11e9-8dd1-970878e5ae2e.png)

**Comment by LalaGhost** [comment]
Sorry did not know that.
I tried it out, but I was not able to make it work...
Can I past there a folder path and/or path to files?

**Comment by oliverschwendener** [comment]
Folder or file names it will ignore
