### ISSUE TITLE
UELI - search window does not overlay some apps

### ISSUE THREAD

**Issue by mmfs37** [oliverschwendener/ueli#900]
The essential app that it cannot overwrite right now is obsidian. It is built on electron; maybe that is the problem, but I can use ueli by knowing how to do everything, but it is hard. I can press my hotkeys to type something and hope I am on the correct search query when I press enter. But it is not fantastic. Earlier, it worked. After I updated ueli to the newest version, it did not.

**Comment by jachymsol** [comment]
This is happening to me with iTerm2. When I try to bring up ueli, the search window appears on the screen, but it is in the background (behind the iTerm2 window) and doesn't switch into focus, so I am typing still into the iTerm2 app.

**Comment by etlandis1** [comment]
Same here - if I enter the shortcut to show ueli multiple times in quick succession it "blinks" in front of the background for a few frames but then goes behind the desktop background again.

Seems to randomly no longer overlay even the desktop (I've tried it with no apps in the foreground). 

Am on Windows 10.

**Comment by oliverschwendener** [comment]
Can someone check if this is still an issue with the latest v9 release? https://github.com/oliverschwendener/ueli/releases
If so, feel free to reopen.
