### ISSUE TITLE
[Bug] Design now has edges and isn't rounded anymore

### ISSUE THREAD

**Issue by Fischchen** [oliverschwendener/ueli#907]
So for some reason the searchbar now has edges:
<img width="494" alt="image" src="https://user-images.githubusercontent.com/61012902/166216184-003fc2b6-f352-43c2-8761-59cf304e523d.png">
and isnt rounded anymore, like it has been before:
<img width="638" alt="Screenshot 2022-05-02 111143" src="https://user-images.githubusercontent.com/61012902/166216234-2dfb94e8-f3d2-4136-abee-4fcddc93d47b.png">

Is this a bug or is this intentional?
If this is intentional, how do I revert it?

**Comment by oliverschwendener** [comment]
This will be fixed in v9.
