### ISSUE TITLE
[Feature Request] ueli app feature suggestions

### ISSUE THREAD

**Issue by BabcB** [oliverschwendener/ueli#908]
Ueli is an Awesome app. It would be even better if it had these options.
1) Recycle Bin in suggestion.
2) simple notes taking feature for faster notes.
3) search web and bookmarks in specific chrome profile
4) Option to Open folder in windows terminal or cmd with and winthout admin.
5) is there a way to use the windows search index for ueli. It would be very useful.
6) A way to mark recent searches.

This app have some bugs.
1) sometimes the search bar does not appear after pressing the shortcut
2) Refreshing index slows down the app search or just freezes.

Thank you for creating this app. This is a very useftul app. I have been using this app for a month and it makes using my pc very fast with just few keys rather than using the mouse everytime.
Thank you for reading my review.

**Comment by oliverschwendener** [comment]
Please open a separate issue for each bug and for each feature request, so it's easier to track progress, thanks.
