### ISSUE TITLE
Javascript errors on opening latest versions

### ISSUE THREAD

**Issue by HavermansStef** [oliverschwendener/ueli#92]
![image](https://user-images.githubusercontent.com/36959568/51378424-87e57f00-1b0d-11e9-8035-4b8cb8384d93.png)

I get this every time. Any quick fixes or packages I miss ?

**Comment by oliverschwendener** [comment]
What version of Windows are you running?

**Comment by HavermansStef** [comment]
1809 build 17763.253

**Comment by oliverschwendener** [comment]
Seems like powershell is not installed or it is not in the PATH environment variable. What happens when enter this command in Command Prompt: `powershell` ?

**Comment by HavermansStef** [comment]
Ok I fixed this. The problem was the path variable not being set.
Maybe you can add this to the FAQ and close the issue after it. You can resolve the problem by 
* going to system environments, 
* selecting system vars instead of user
* find the path variable
* add this to your path C:\Windows\System32\WindowsPowerShell\v1.0

This will fix the bug. 
Thanks for your help @oliverschwendener.

**Comment by PaoneGit** [comment]
![image](https://user-images.githubusercontent.com/31804968/58928777-8beb0400-8771-11e9-9c09-fbc44b242ef6.png)

**Comment by PaoneGit** [comment]
i am facing this error on every startup if my system. what could be the error
