### ISSUE TITLE
Installed windows 11 and nothing works anymore. Even when complete reinstalling

### ISSUE THREAD

**Issue by mmfs37** [oliverschwendener/ueli#923]
I always get errors.  I can't open any applications anymore. they don't show up.
"Error: Command failed: powershell.exe -NonInteractive -NoProfile -Command "& { [Console]::OutputEncoding = [Text.UTF8Encoding]::UTF8; $ErrorActionPreference = 'SilentlyContinue'; $applications = New-Object Collections.Generic.List[String]; $extensions = New-Object System.Collections.Generic.HashSet[string] ([string[]]@('.lnk','.appref-ms','.url','.exe'), [System.StringComparer]::OrdinalIgnoreCase); 'C:\ProgramData\Microsoft\Windows\Start Menu\Programs','C:\Users\Malte\AppData\Roaming\Microsoft\Windows\Start Menu','C:\Users\Malte\Desktop' | %{ Get-ChildItem -LiteralPath $_ -Recurse -File | Where-Object { $extensions.Contains($_.Extension) } | ForEach-Object { $applications.Add($_.FullName) } }; $result = (@{ errors = @($error | ForEach-Object { $_.Exception.Message }); applications = $applications } | ConvertTo-Json); Write-Host $result; }" Windows PowerShell terminated with the following error:    The type initializer for 'System.Management.Automation.Runspaces.InitialSessionState' threw an exception.  "

**Comment by pybash1** [comment]
I am on windows 11 and it works flawlessly for me @mmfs37

**Comment by AlanD20** [comment]
I'm also on Windows 11 and it works perfectly fine. But I noticed when you run the application's uninstaller, it doesn't uninstall the config files entirely. As all the configurations and caches are stored at `AppData\Roaming\ueli`.

Enter the following address in your explorer and try to remove all the files & folders inside it:
`C:\Users\%USERPROFILE%\AppData\Roaming\ueli`

After removing all the files & folders inside `AppData\Roaming\ueli`. Make sure you have [Powershell 7.x](https://github.com/PowerShell/PowerShell) installed before re-installing ueli app.

**Comment by oliverschwendener** [comment]
Uninstall Ueli and as @AlanD20 mentioned remove the folder `C:\Users\%USERPROFILE%\AppData\Roaming\ueli`. Then install Ueli again and check if it works.
