### ISSUE TITLE
CleanMyMac X identifies backdoor 'NukeSped' used by Ueli and uninstalls app every time I do a manual scan & clean of my PC. Please advise. 

### ISSUE THREAD

**Issue by MagiDruid** [oliverschwendener/ueli#924]
Hello, 

I downloaded the latest .dmg of ueli from the releases page several times. CleanMyMac X, a multi-function cleanup tool and malware remover I have running on my computer, keeps uninstalling the latest release of ueli after every system scan & cleanup because it identified a backdoor, called 'NukeSped', being used by the app to access some of my computer's data & functionality. 

Quick search online reveals NukeSped is a malware Trojan designed specifically to infect Macs. 

Please advise. Thank you.

**Comment by melis-m** [comment]
Bump

**Comment by carlitorendon** [comment]
In the same topic: #933

**Comment by MagiDruid** [comment]
![1323 - CleanMyMac X@2x](https://user-images.githubusercontent.com/100071592/178103602-3765eca3-2133-46e2-b092-18a9463d6149.jpg)

I am still seeing the NukeSped backdoor warning in CleanMyMac X. Has anyone else come across NukeSped or similar malware when using ueli? 

The developer hasn't commented yet on this issue. I don't know if its safe to use this app. Any ideas/suggestions are welcome. Thank you.

**Comment by carlitorendon** [comment]
Hey @MagiDruid my issue #933 ended up being more like a question. After Oliver explained it made total sense; went ahead and closed it. 

My two cents on this is, malware detection tools are very fallible. As an example, look below:

![image](https://user-images.githubusercontent.com/14046845/179282319-08a255c9-61ce-41f3-8067-61d5cc281606.png)

Here we have very respectable providers, like SysInternals for windows and Lenovo among others being flagged for legitimate software. 

If you go to virus total, you will see that out of 70 providers only one is the one reporting the flag on a piece of software that is basically provided by Microsoft: 

https://www.virustotal.com/gui/file/77358157efbf4572c2d7f17a1a264990843307f802d20bad4fb2442245d65f0b/detection
 
Just my two cents.

**Comment by MagiDruid** [comment]
@carlitorendon , Thank you for providing a more detailed explanation of your issue. I installed Bitdefender on my Mac a few days ago and it did not flag ueli at all. CleanMyMacX, on the other hand, got me worried because I use it frequently. Given that its an all-purpose tool, its virus detection capabilities are probably questionable. Anyhow, I thought that drawing attention to the NukeSped backdoor could help other ueli users. Apologies for any inconvenience caused. Kind Regards.

**Comment by oliverschwendener** [comment]
Thanks for raising awareness regarding this. I'll close this issue as it seems to be resolved.

**Comment by yosamsimiti** [comment]
Um...I don't think it's resolved.  I mean, I get this flag when I installed ueli.  Do I have the malware or not?  I really want to be able to use ueli cause spotlight stopped working for some reason.
