### ISSUE TITLE
Slowly moves to top left with every key typed on Win 11

### ISSUE THREAD

**Issue by ph33nx** [oliverschwendener/ueli#928]
Preview : [https://imgur.com/a/hequTFt](https://imgur.com/a/hequTFt)

Details : Ueli slowly moves to top left with every key typed on Win 11
OS : Windows 11 (21H2) (OS Build 22000.739)
Display: 2560x1440 (144hz) : Scaled at 150% from System > Display
GPU : AMD Radeon RX 6600XT

**Comment by ph33nx** [comment]
i think this issue could be caused by [display scaling on Windows](https://imgur.com/a/2Alelqy).
Scaled from **System Settings > System > Display**

**Comment by oliverschwendener** [comment]
See the known bugs: https://github.com/oliverschwendener/ueli#known-bugs
