### ISSUE TITLE
[Feature Request] Use an alternate to default browser

### ISSUE THREAD

**Issue by toolman11** [oliverschwendener/ueli#930]
My Windows default browser is Microsoft Edge (for work) but I use Ueli mainly for personal (Chrome). Is there a way to have Ueli use a browser other than the default one configured by the OS? I couldn't find a way to do this. Thanks.

**Comment by cobaltbeau** [comment]
I'd love this - even more so if you configure different types of commands to open in different browsers (though that's probably a pipe dream)

**Comment by SpamsAlex** [comment]
Hi, same issue here, would be great

**Comment by leowilkin** [comment]
Has this been iterated/developed on more?

**Comment by oliverschwendener** [comment]
I started implementing this in `feat-custom-web-browser`

**Comment by oliverschwendener** [comment]
The next release will include an option to define a custom web browser.
