### ISSUE TITLE
Spellcheck red underline in input fields

### ISSUE THREAD

**Issue by luopa** [oliverschwendener/ueli#931]
First of all - thank you so much for the efforts invested into developping ueli - I just started using it and I'm very intruiged!

However, I came across a bug - I assume:

Current behavior: 
- Whenever I input a text string into a field, an autocorrect spellcheck is being applied to the input and certain words underlined with a red line. (Screenshot 1)
- this happens both to the main ueli input field aswell as settings fields (Screenshot 2)
- It seems as if this spellcheck follows system language (my system is set to german)  (Screenshot 3)
- In settings I couldnt find an option to enable/disable spellcheck behavior.

Exepected behavior

- Don't perform spellcheck

Since I couldnt find any other issues on this, I assume this is a unknown behavior? 
Are there any hints on this?

Kind regards, lu

------

ueli 8.22.0
Electron 18.2.3
Node 16.13.2
V8 10.0.139.17-electron.0

------

Screen 1
![image](https://user-images.githubusercontent.com/5087420/175809713-b62251a7-9573-4368-9d92-9d265b437d12.png)
Screen 2
![image](https://user-images.githubusercontent.com/5087420/175809736-48a5c905-f578-4495-b921-f4c83d10c789.png)
Screen 3
![image](https://user-images.githubusercontent.com/5087420/175809767-fa563ead-9499-41f4-9395-d02a57933fa0.png)

**Comment by oliverschwendener** [comment]
Thanks for your feedback, this will be fixed with the next release.
