### ISSUE TITLE
Question on Network Activity

### ISSUE THREAD

**Issue by carlitorendon** [oliverschwendener/ueli#933]
Hello, really like the program but have a couple of questions around network activity. As you can see, the program (at least for me) is pretty chatty (Process Explorer is sorting by sending network traffic): 

![image](https://user-images.githubusercontent.com/14046845/176883680-3ca9b76d-59e9-4871-ba2c-1f4b8e40c774.png)

So this is a computer that was left on all night running a separate process. 

Here's a list of the permanent connections the program seems to maintain (this fluctuates over time): 
![image](https://user-images.githubusercontent.com/14046845/176883937-e4902710-b86a-41c9-abf4-1f8129279b21.png)

I haven't dived into the code. Could someone kindly drop a couple of lines of why these permanent connections and why the amount of data sent and received? (I get that some of the icons of my items are downloaded frequently but I would imagine that does not merit so much traffic?)

Thank you,

**Comment by oliverschwendener** [comment]
The following plugins need to fetch data from the www:
- websearch
- currency converter
- dictionary
- translation
- weather

Additionally the app checks for available updates on startup.

Does this help?

**Comment by carlitorendon** [comment]
Thank you @oliverschwendener for clarifying this. It does help. Really like the app. So useful.

**Comment by oliverschwendener** [comment]
Glad I could help. If you want to have more details then search for `axios` in the code base (that's the library we use to make HTTP calls).
