### ISSUE TITLE
Browser not getting focused when using web search

### ISSUE THREAD

**Issue by piike** [oliverschwendener/ueli#941]
Hi, when using web search (i.e. google, youtube), usually when the search is executed, the browser gets focused. But more often than not, it doesn't, so key shortcuts like ctrl+w can't be executed until clicking on the browser.

**Comment by kristus123** [comment]
i have noticed the same on mac. the browser won't be "pushed to the front focus"

**Comment by oliverschwendener** [comment]
Can someone check if this is still an issue with the latest v9 release? https://github.com/oliverschwendener/ueli/releases
If so, feel free to reopen.
