### ISSUE TITLE
Ueli not finding chrome bookmarks in "work" user profile

### ISSUE THREAD

**Issue by heyhoss** [oliverschwendener/ueli#945]
ueli is only picking up bookmarks from my "personal" chrome profile, if I try to search for stuff that is in my work profile, it doesn't come up in ueli. 

Is there a fix or workaround for this?

**Comment by polyankaglade** [comment]
I think the only workaround, for now, is to make a script that would merge all bookmark files you want into a single one and put it at `C:\Users\User\AppData\Local\Google\Chrome\User Data\Default\Bookmarks` (Windows)

**Comment by oliverschwendener** [comment]
I think this is a duplicate of #628
