### ISSUE TITLE
command not being executed when i have an app (Intellij) in fullscreen mode

### ISSUE THREAD

**Issue by kristus123** [oliverschwendener/ueli#949]
i use a mac

https://gyazo.com/6032e867863bdd3f9dd65e5f01f12499

Also, would it be hard to have Ueli not open the terminal in order to execute a command. ?

**Comment by oliverschwendener** [comment]
Can someone check if this is still an issue with the latest v9 release? https://github.com/oliverschwendener/ueli/releases
If so, feel free to reopen.
