### ISSUE TITLE
How can i refresh settings ?

### ISSUE THREAD

**Issue by kristus123** [oliverschwendener/ueli#950]
I have written a script to generate the config for me since then i can programatically add my wanted shortcuts.

Currently i have been doing this in order to 'refresh the settings'

```
pkill ueli && sleep 0.5 && open -a ueli
``` 

Is there another way i could do this ? It takes some time to refresh the settings and that ain't fun

**Comment by kristus123** [comment]
i'm on mac

**Comment by oliverschwendener** [comment]
No, currently there is no possibility to "refresh" the settings.
