### ISSUE TITLE
Doesn't work with macOS ventura

### ISSUE THREAD

**Issue by mw-mcw** [oliverschwendener/ueli#955]
Hey there,

first of: thanks for a fantastic app! Unfortunately it throws an error running on macOS Ventura (13.0). 
Is there anything I can do about it on my end?

![Bildschirm­foto 2022-10-25 um 14 58 54](https://user-images.githubusercontent.com/14879953/197779784-759ed785-5245-4240-b0db-a256343e0876.png)

**Comment by oliverschwendener** [comment]
Fixed with the [latest release](https://github.com/oliverschwendener/ueli/releases/tag/v8.23.2).
