### ISSUE TITLE
Application Search - Show native icons (ON) breaks searching for applications

### ISSUE THREAD

**Issue by varatiki** [oliverschwendener/ueli#958]
When toggled ON, an error is returned and the application search no longer functions:

![image](https://user-images.githubusercontent.com/32350922/199544786-62d64ba0-3cb2-4620-957c-64125c4090f2.png)

![image](https://user-images.githubusercontent.com/32350922/199545686-a9b80be0-3a0c-444a-aad2-efff1736755d.png)

**Comment by oliverschwendener** [comment]
Can you show the full application search options?

**Comment by varatiki** [comment]
The username is all lowercase alphabet.  No weird characters.

![image](https://user-images.githubusercontent.com/32350922/199550925-27d9c7c5-84a9-4d52-960e-5aa3221369f4.png)

**Comment by oliverschwendener** [comment]
What happens if you reset all settings to default?

**Comment by varatiki** [comment]
Immediately after reset:

![image](https://user-images.githubusercontent.com/32350922/199563498-fbeab2e1-c2ae-4227-bee2-211f90b0fb30.png)

![image](https://user-images.githubusercontent.com/32350922/199563598-a0e34f26-106e-47fd-a604-954f3c9f6255.png)

**Comment by varatiki** [comment]
Also, I quit the application, and reloaded it after applying the default settings.  Search results still missing:

![image](https://user-images.githubusercontent.com/32350922/199563930-bde8f727-c11f-4d95-9974-cddd430b811f.png)

**Comment by oliverschwendener** [comment]
Is this still occuring in the latest v9 beta release? https://github.com/oliverschwendener/ueli/releases
If so, feel free to reopen.
