### ISSUE TITLE
How to change the default shell?

### ISSUE THREAD

**Issue by Chameleon-789** [oliverschwendener/ueli#960]
When I try to change anything in the "Application Search" plugin. It runs some command starting with "powershell", what defines the directory where powershell is located? I want to change the default powershell to Powershell 7, how do I do that? I am on Windows 8.1 btw.

**Comment by oliverschwendener** [comment]
Does this still occur with the latest v9 beta release? https://github.com/oliverschwendener/ueli/releases
If so, feel free to reopen.
