### ISSUE TITLE
Support for more windows URI

### ISSUE THREAD

**Issue by chantisnake** [oliverschwendener/ueli#97]
Here is a list of windows URI:
1. Default App Uri: https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-default-app
2. Setting Uri: https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-settings-app
3. Store Uri: https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-store-app (including search in store)
4. Map Uri: https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-maps-app (including search in map)
5. Contact Uri: https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-people-apps (including search in contact, open contact app by phone number or name).

**Comment by oliverschwendener** [comment]
Did you see this feature: https://github.com/oliverschwendener/ueli#operating-system-settings?

**Comment by chantisnake** [comment]
Yes, but I think there are some URI missing.
