### ISSUE TITLE
Everything Integration doesn't run properly 🆘 

### ISSUE THREAD

**Issue by INELPORT** [oliverschwendener/ueli#971]
Hello!

Today I found this launcher and that's incredible but I can't integrate everything properly.

When I search something with the prefix "es?" the app doesn't find nothing...

For example, I have the file prueba.py in C:\....\Desktop\Programas\prueba.py

When I run the launcher...
![image](https://user-images.githubusercontent.com/119863137/206710774-6e25ba96-2341-4e37-a1b0-27a4d8b1f338.png)

I have reinstalled everything (cause I have been using before) and put the es.exe in C:\Program Files\ES\es.exe

Tell me if I'm doing something wrong

**Comment by oliverschwendener** [comment]
Can someone check if this is still an issue with the latest v9 release? https://github.com/oliverschwendener/ueli/releases
If so, feel free to reopen.
