### ISSUE TITLE
Please sign the app with a certificate

### ISSUE THREAD

**Issue by masumshaikh** [oliverschwendener/ueli#974]
My workplace will not let me install the app without a valid certificate. After signing, when right-clicking on the exe and viewing properties, there will be a Digital Signatures tab as illustrated. Currently there isn't.

![image](https://user-images.githubusercontent.com/6390012/208483811-b323338a-5bca-4fa6-873c-ba292a5fcddd.png)

**Comment by oliverschwendener** [comment]
As I already stated [here](https://github.com/oliverschwendener/ueli/issues/193#issuecomment-532104540), code signing certificates are very expensive, and because this is a project I work on only in my free time and I don't get any money for it I'm totally fine with an unsigned app.

**Comment by oliverschwendener** [comment]
You can now get the app from the Microsoft Store here: https://apps.microsoft.com/detail/9pk44n42b2g7
