### ISSUE TITLE
[Bug] Web search is too slow.

### ISSUE THREAD

**Issue by Bradzu** [oliverschwendener/ueli#977]
When I type g?somethingsomething and quickly press enter, it usually misses last 2 - 3 letters and only googles "somethingsometh". I can avoid this by waiting a second before pressing enter but that kind of defeats the purpose of the app.

**Comment by Eshanatnight** [comment]
Hey, I tried to do the quick web seach but I simply cannot recreate this issue. It is possible I am not typing fast enough. But I don't think there is a bug?(or I'm typing slow). Can anyone try to recreate this issue?

**Comment by kristus123** [comment]
what i did for this was to make my own googlr search.
that way i don't have to wait 2-3 seconds before being able to press enter

**Comment by oliverschwendener** [comment]
This is a duplicate of #665
