### ISSUE TITLE
Settings make the program stuck for various seconds

### ISSUE THREAD

**Issue by shmykelsa** [oliverschwendener/ueli#98]
Whenever I wanna change a settings within Ueli, the program hangs for 20 to 30 seconds. No matter what setting I wanna change. Resulting in Windows obfuscating the window and telling me that Ueli is not responding.

Ueli version: 7.2.2

PC Specs

I7 6700HQ @ 2.59 GHZ
16 GB RAM
Windows 10 17763.253

**Comment by oliverschwendener** [comment]
That's why it is so slow. Can you disable the file search feature and then check if the index size was reduced?

![image](https://user-images.githubusercontent.com/15727229/51734350-8aebec80-2084-11e9-9ac1-98d3b91efb75.png)

**Comment by shmykelsa** [comment]
Yeah, it's now reduced to 712. I'll give it a go and see if it runs any better!

**Comment by oliverschwendener** [comment]
If you want to enable file search again, then check the file search options:

![image](https://user-images.githubusercontent.com/15727229/51735000-790b4900-2086-11e9-9358-2b1c7af3e81b.png)

Most likely one of the folders contains a lot of files and this causes ueli to slow down.

**Comment by shmykelsa** [comment]
It is indeed better, I must say. But it still gets somewhere around 5 to 10 seconds, even with an index of 244. Again, the window gets greyed out by Windows and it's completely stuck. Then it un-freezes.

**Comment by oliverschwendener** [comment]
Hmm, shouldn't be that slow... Just to test: uncheck the "Programs" feature and then check if it is still slow?

**Comment by shmykelsa** [comment]
Okay, I made a clean install, resetting all my preferences. It seems to be working regardless of "Programs" feature, with all my personal settings. Adding folders with the + sign was a pain. Now it doesn't get stuck anymore.

**Comment by oliverschwendener** [comment]
Can you explain more why "Adding folders with the + sign" was a pain?

**Comment by shmykelsa** [comment]
With that sentence I mean that adding folders (like the ones to specify programms or files paths) was particularly slow. Also removing them, to be fair.

**Comment by oliverschwendener** [comment]
If adding the application folders was slowing down the app then your application folders might be huge and have a ton of subfolders which take so long to scan. It's recommended only to specify folders with shortcuts files. You shouldn't add "top-level" folders because they will be scanned for apps **recursively**. Can you show me a screenshot of your application folder settings?

**Comment by shmykelsa** [comment]
It does. Though the freeze situation got better in my third to last comment
