### ISSUE TITLE
trigonometric functions wont give right answer. sin() cos() log etc...

### ISSUE THREAD

**Issue by alexthekukac** [oliverschwendener/ueli#980]
I have attached my results with cos and sin.
![Untitled](https://user-images.githubusercontent.com/12429553/212542222-32193e27-c737-48f8-8d6d-a5d8d84caf1b.png)
![Untitletd](https://user-images.githubusercontent.com/12429553/212542224-58228e06-067e-4030-a815-6d812f591685.png)
![trewt](https://user-images.githubusercontent.com/12429553/212542225-06f02d9e-4a77-4145-81bf-5fffffccdb2e.png)
![trjhrtfj](https://user-images.githubusercontent.com/12429553/212542226-9cc02f02-c3dd-4342-94d2-5c416cb116f0.png)
![fgjgk](https://user-images.githubusercontent.com/12429553/212542227-45d3d2fb-d626-474c-8b58-3680fce23a82.png)
![jtzk](https://user-images.githubusercontent.com/12429553/212542228-834490f1-c95f-4d90-bdbd-309e02abda22.png)

**Comment by TheophileMot** [comment]
These values are correct. In mathematics, the default is to calculate in radians: instead of breaking the circle into 180 degrees, we think of the full angle as `2*pi`, corresponding to the circumference. Try the following:

Degrees:
```
cos(180 deg)
= -1
```

Radians:
```
cos(pi)
= -1
```

**Comment by TheophileMot** [comment]
As for logarithms, the default is base `e = 2.71828...`. You can get other bases using `log2` and `log10`. Thus:

```
log(e^4)
= 4
```

```
log10(1000)
= 3
```

```
log2(32)
= 5
```

**Comment by alexthekukac** [comment]
thanks, quite inconvenient, you would think base 10 would be default.
as for the cos and sin, they work now, thanks.

**Comment by oliverschwendener** [comment]
Ueli is using [math.js](https://mathjs.org/) for the calculator. If there is an issue I suggest reporting it on their side.
