### ISSUE TITLE
Changing font family to custom ones

### ISSUE THREAD

**Issue by Aaryan-N** [oliverschwendener/ueli#981]
Hi Oliver, 

I just wanted to ask if it is possible for Ueli to accept fonts that you have downloaded onto your laptop. I tried it but it doesn't seem to work. 

Thanks,
Aaryan

**Comment by oliverschwendener** [comment]
Did you try changing the font here?

<img width="754" alt="image" src="https://user-images.githubusercontent.com/15727229/213941177-ad001e78-67b0-4ac8-8e67-93cc5222edad.png">

**Comment by Aaryan-N** [comment]
Yes I did. Turns out I needed to restart my laptop for it to work, which is strange. You should put a notice on the font family that says Restart Required.
