### ISSUE TITLE
When searching for file content via everythinh i get error "an error occured" check log for more details

### ISSUE THREAD

**Issue by NolanNolan** [oliverschwendener/ueli#982]
i followed instructions to install exevything (version 1.5a to be able to search content) and inserted location of commandline es.exe file

any idea how to solve ?

thanks

Nolan

**Comment by oliverschwendener** [comment]
Can someone check if this is still an issue with the latest v9 release? https://github.com/oliverschwendener/ueli/releases
If so, feel free to reopen.
