### ISSUE TITLE
Ueli starts multiple windows power shell, and overload CPU to 100% 

### ISSUE THREAD

**Issue by zocidj** [oliverschwendener/ueli#986]
Ueli starts multiple windows power shell, and overload CPU to 100%

**Comment by zocidj** [comment]
![Ueli - Powershell](https://user-images.githubusercontent.com/114068063/219367245-7edc6fc4-8636-4ed7-b356-12fa896413d4.jpg)

**Comment by oliverschwendener** [comment]
Did you change the rescan interval in the general settings?

![image](https://user-images.githubusercontent.com/15727229/219372219-6a20aa6b-dc12-44c4-ace0-3127b09c89bb.png)

**Comment by zocidj** [comment]
No it is 300, as default

**Comment by oliverschwendener** [comment]
What version of ueli are you running?

**Comment by velimirl** [comment]
I had the same issue, UELI version: 8.21.1 randomly started using 100% of CPU every 5 minutes yesterday. (Didn't tweak anything in settings).

Disabling Periodic rescan of course solved it.

**Comment by zocidj** [comment]
> What version of ueli are you running?

I used lastest version. I have install ueli on my laptop, and no issue with CPU overload

**Comment by zocidj** [comment]
When I start refresh indexes I got this, and never finish.
![Ueli - Refreshl](https://user-images.githubusercontent.com/114068063/219570635-26041d7a-25f5-4a42-925c-83af8c3554bb.jpg)

**Comment by velimirl** [comment]
https://user-images.githubusercontent.com/51071241/219757191-562c51ce-d0eb-4519-ab9b-17313c65493e.mp4

My POV if it might help.

**Comment by oliverschwendener** [comment]
Do you have the "simple folder search" plugin enabled? If yes, can you show us the settings?

**Comment by velimirl** [comment]
Yep,

Settings under 'Simple folder search' are:"
C:\Users\Vel			
D:\Steam rear			
C:\Users\Vel\Desktop			
D:\			
C:\Program Files\Git	
"

Under 'Application search': "
C:\ProgramData\Microsoft\Windows\Start Menu\Programs	
C:\Users\Vel\AppData\Roaming\Microsoft\Windows\Start Menu	
C:\Users\Vel\Desktop

.lnk	
.appref-ms	
.url	
.exe
"

**Comment by oliverschwendener** [comment]
What happens if you turn off the Simple Folder search plugin?

**Comment by velimirl** [comment]
If off when I refresh indexes nothing happens, but now after I turned it on again, refreshing indexes only uses like 26% of my CPU (while previously it used 90-100%)

![image](https://user-images.githubusercontent.com/51071241/220072719-3bf4dc47-b563-4dcd-aa9a-f2e44dd35126.png)

So the bug definitely occurred there

**Comment by zocidj** [comment]
Me to, when I turn off simple folder search, everything is ok

**Comment by oliverschwendener** [comment]
Can someone check if this is still an issue with the latest v9 release? https://github.com/oliverschwendener/ueli/releases
If so, feel free to reopen.
