### ISSUE TITLE
mdfind on MAC version not working MAC OS Ventura 13.2

### ISSUE THREAD

**Issue by artcrime** [oliverschwendener/ueli#987]
Hi,

I have problems using mdfind on my MacBook Pro M2 with Mac OS Ventura 13.2. Mdfind does not find anything. Sometimes I get an error message with  a reference to the log file.  The only thing I find inside the log are this two rows:

2023-02-08T08:23:05.485Z error: 2023-02-08 09:23:04.427 mdfind[3956:195237] [UserQueryParser] Loading keywords and predicates for locale "de_DE"
2023-02-08 09:23:04.427 mdfind[3956:195237] [UserQueryParser] Loading keywords and predicates for locale "de"

Perhaps this is an problem with the rights of ueli? My collegue has the same problem with his MacBook Air 2022 M1

This is my running ueli version:

ueli
8.23.2
Electron
20.1.1
Node
16.15.0
V8
10.4.132.22-electron.0 

Regards

**Comment by nimatrueway** [comment]
In my case I have disabled Spotlight, because `mds_store` was crushing my CPU. As a result this command that **ueli** leverages to collect applications won't work.

```
mdfind kMDItemContentTypeTree=com.apple.application-bundle | egrep "^\/Applications|^\/System/Library/CoreServices|^\/System/Applications|^\/Users/nima.taheri/Applications"
```

This may be a better alternative that works independent of spotlight.

```
find '/System/Library/CoreServices' '/System/Applications' '/Users/nima.taheri/Applications' '/Applications' -maxdepth 2 -type d -iname '*.app' -a \( -prune  \)
```

**Comment by oliverschwendener** [comment]
Can someone check if this is still an issue with the latest v9 release? https://github.com/oliverschwendener/ueli/releases
If so, feel free to reopen.
