### ISSUE TITLE
Shortcuts Commandline doesn't seem to execute

### ISSUE THREAD

**Issue by mburnett8** [oliverschwendener/ueli#993]
I'm running a command to changes a directory and run vscode in MacOS: `cd ~/code/notes && code .`. When I try to run the command the interface flashes and does nothing else. If I run the same command in a terminal, vscode opens to my notes folder as expected.

I couldn't find any documentation, in case I'm doing something wrong.

![image](https://user-images.githubusercontent.com/49873044/221606010-a62fb12f-84a3-48d5-ac8f-87e32c6eee9b.png)

![image](https://user-images.githubusercontent.com/49873044/221606508-c93058ab-0e01-4974-9070-d003368ae1e1.png)

**Comment by oliverschwendener** [comment]
`cd` wont work here as it requires the full path to the binary. Use the absolute path to `code` and it should work. If not try the latest beta release of ueli v9 here: https://github.com/oliverschwendener/ueli/releases
