### ISSUE TITLE
Everything search not working, "Error 7: Unable to send IPC message"

### ISSUE THREAD

**Issue by camayl** [oliverschwendener/ueli#997]
Can someone help me with this error? I have Everything and Everything Command Line installed.

**Comment by paraselen** [comment]
Am I right that the logs are in C:\Users\user\AppData\Roaming\ueli\Session Storage\? The problem is that all those file contain illegible text. Any help?

**Comment by oliverschwendener** [comment]
Does this still occur with the latest v9 beta release? https://github.com/oliverschwendener/ueli/releases
If so, feel free to reopen.
