### ISSUE TITLE
404 error when trying to use translation

### ISSUE THREAD

**Issue by maku** [oliverschwendener/ueli#999]
Translation seems to be broken. I get an 404 error when I try to use it...

**Comment by SCLiao47** [comment]
I presume the link in this [file](https://github.com/oliverschwendener/ueli/blob/main/src/main/plugins/translation-plugin/translation-plugin.ts#L30) is broken. The URL from [Linguee API](https://github.com/imankulov/linguee-api#sample-installation) seems to be changed. 

Maybe it can be fix by replacing `const url = `https://linguee-api.herokuapp.com/api?q=${textToTranslate}&src=${source}&dst=${target}`;` as `const url = `https://linguee-api.fly.dev/api/v2/translations?query=${textToTranslate}&src=${source}&dst=${target}`;` in [translation-plugin.ts](https://github.com/oliverschwendener/ueli/blob/main/src/main/plugins/translation-plugin/translation-plugin.ts#L30). 

However, I don't have enough experience and time to set up the development environment yet. Maybe someone can give this a quick try?

**Comment by maku** [comment]
@SCLiao47 I forked the project, made the change and tried to package the app. But I get an error:

**Comment by maku** [comment]
Ok I got it working with "npm" (instead of using "pnpm")

However, the structure of the JSON result has also changed significantly and not just the URL. And technically we're in promise/callback hell when it comes to implementation here. 

Well, unfortunately not that easy...

**Comment by turkeyphant** [comment]
Any update on this?

**Comment by oliverschwendener** [comment]
This should be fixed in the next version.
